USE [DIVA_US00_FY23]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[AM_IRGR_MATERIAL_GROUP_HIERARCHY](
	[T023T_MATKL] [nvarchar](50) NULL,
	[T023T_WGBEZ] [nvarchar](50) NULL,
	[IRGR_SPEND_CAT_LEVEL_1] [nvarchar](50) NULL,
	[IRGR_SPEND_CAT_LEVEL_2] [nvarchar](50) NULL,
	[IRGR_SPEND_CAT_LEVEL_3] [nvarchar](50) NULL,
	[IRGR_SPEND_CAT_LEVEL_4] [nvarchar](50) NULL
) ON [PRIMARY]
GO
