USE [DIVA_US00_FY23]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[AM_AP_CLEARING](
	[ZF_ACCOUNTS] [nvarchar](100) NULL,
	[SKAT_TXT50] [nvarchar](1000) NULL,
	[SKAT_TXT20] [nvarchar](1000) NULL,
	[ZF_AP_CLEARING] [nvarchar](100) NULL
) ON [PRIMARY]
GO
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A012001', N'Cash on hand- SEL', N'Cash on hand- SEL', N'N/A')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A012106', N'JP Morgan CAD SEL LB', N'Cash in Bank- JP Morgan CAD SEL Lockbox', N'N/A')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A012109', N'CIB- JPM Receipts', N'Cash in Bank- JPM Receipts', N'N/A')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A012115', N'DEUTSCHE BK-ACH A/C', N'Cash in Bank- DEUTSCHE BANK-ACH A/C', N'N/A')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A012221', N'Interim/On Account', N'Cash in Bank ? Interim/On Account', N'N/A')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A012300', N'RAS cash-RAS SEK', N'RAS cash- RAS ACCOUNT SEK', N'N/A')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A012302', N'RAS cash-RAS EUR', N'RAS cash- RAS ACCOUNT EUR', N'N/A')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A012306', N'RAS cash-RAS GBP', N'RAS cash- RAS ACCOUNT GBP', N'N/A')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A012307', N'RAS cash-RAS USD', N'RAS cash- RAS ACCOUNT USD', N'N/A')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A012308', N'RAS cash-RAS DKK', N'RAS cash- RAS ACCOUNT DKK', N'N/A')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A012309', N'RAS cash-RAS JPY', N'RAS cash- RAS ACCOUNT JPY', N'N/A')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A012311', N'RAS cash-RAS NOK', N'RAS cash- RAS ACCOUNT NOK', N'N/A')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A012315', N'RAS cash-RAS CAD', N'RAS cash- RAS ACCOUNT CAD', N'N/A')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A012316', N'RAS cash-RAS AUD', N'RAS cash- RAS ACCOUNT AUD', N'N/A')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A012318', N'RAS cash-RAS NZD', N'RAS cash- RAS ACCOUNT NZD', N'N/A')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A012319', N'RAS cash-RAS MXN', N'RAS cash- RAS ACCOUNT MXN', N'N/A')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A012320', N'RAS cash-RAS SGD', N'RAS cash- RAS ACCOUNT SGD', N'N/A')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A012392', N'RAS cash-RAS EUR', N'RAS cash- RAS ACCOUNT EUR SOCAN', N'N/A')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A012395', N'RAS cash-CAD SOCAN', N'RAS cash- RAS ACCOUNT CAD SOCAN', N'N/A')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A012396', N'RAS cash-RAS GBP', N'RAS cash- RAS ACCOUNT GBP SOCAN', N'N/A')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A012397', N'RAS cash-USD SOCAN', N'RAS cash- RAS ACCOUNT USD SOCAN', N'N/A')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A012399', N'RAS cash-JPY SOCAN', N'RAS cash- RAS ACCOUNT JPY SOCAN', N'N/A')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A012990', N'Cash OH-FX Trans', N'Cash on hand- FX Translation', N'N/A')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A014020', N'T AR-Clearing', N'Trade account receivable- Clearing', N'N/A')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A014105', N'JP MORGAN C CONCENT', N'Incoming Clearing- JP MORGAN CHASE CONCENTRATION', N'N/A')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A014117', N'Icl- JPMC-SARF ACH', N'Incoming Clearing- JPMC Bank-SARF ACH', N'N/A')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A014850', N'T AR-D GL entry-OIM', N'Trade account receivable- direct GL entry- OIM', N'N/A')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A014851', N'T AR-D GL entry-NOI', N'Trade account receivable- direct GL entry- NOIM', N'N/A')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A014990', N'T AR-FX Trans', N'Trade account receivable- FX Translation', N'N/A')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A021010', N'M&FG-SAP main acct', N'Products- Merchandise & Finished goods- SAP main', N'N/A')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A021015', N'M&FG-D GL-OIM', N'Products- Merchandise & FG- direct GL entry OIM', N'N/A')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A021020', N'M&FG-D GL-balance', N'Products- Merchandise & FG- direct GL- balance', N'N/A')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A021050', N'M&FG-Devaluation', N'Products- Merchandise & FG- Devaluation', N'N/A')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A021060', N'M&FG-SAB104', N'Products- Merchandise & Finished goods- SAB104', N'N/A')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A021100', N'SFG-Gen', N'Products- SFG- General', N'N/A')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A021110', N'SFG-D GL entry', N'Products- SFG- direct GL entry', N'N/A')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A024010', N'WIP-Gen', N'WIP- General', N'N/A')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A025100', N'SP-SAP-MM', N'Other inventory- Spare parts- SAP-MM', N'N/A')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A025110', N'SP-In transit', N'Other inventory- Spare parts- In transit', N'N/A')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A025120', N'SP-Devaluation', N'Other inventory- Spare parts- Devaluation', N'N/A')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A025130', N'SP- Direct GL', N'Other inventory- Spare parts- Direct GL', N'N/A')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A025200', N'Supplies-Gen', N'Other inventory- Supplies- General', N'N/A')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A031080', N'PE-Payroll/Welf/Pen', N'Prepaid exps- Payroll/Welfare/Pension', N'N/A')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A032001', N'ACL - Other Cur AR', N'Allowance for credit loss (other AR - current)', N'N/A')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A032050', N'Other AR-tax refund', N'Other AR-current- income tax refund', N'N/A')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A032072', N'OthAR-St in tax rec', N'Other AR- current - State income tax receivable', N'N/A')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A032850', N'OtherAR-D GL ent-OIM', N'Other AR-current- direct GL entry- OIM', N'N/A')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A032851', N'OtherAR-D GL ent-NOI', N'Other AR-current- direct GL entry- NOIM', N'N/A')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A032990', N'Other AR-FX Trans', N'Other AR-current- FX Translation', N'N/A')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A033990', N'ST loan-FX Trans', N'Short term loan- FX Translation', N'N/A')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A035901', N'Exp to be rec-Other2', N'Expense to be recharged- Other2', N'N/A')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A038010', N'VAT-R on purch-gen', N'VAT-receivable on purchase- general', N'N/A')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A038360', N'VAT-R clr CA', N'VAT-receivable (clearing) CA', N'N/A')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A038361', N'VAT-R clr CA RITC', N'VAT-receivable (clearing) CA - RITC', N'N/A')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A038362', N'VAT-R clr CA ITC', N'VAT-receivable (clearing) CA - ITC', N'N/A')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A038990', N'VAT-R-FX Trans', N'VAT-receivable- FX Translation', N'N/A')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A039010', N'ADA-Gen', N'Allowance for doubtful debts- General', N'N/A')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A039020', N'ADA-Specific', N'Allowance for doubtful debts- Specific', N'N/A')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A056990', N'DTA-FX Trans', N'Def tax assets-current- FX Translation', N'N/A')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A089070', N'OCA - Fed in tax rec', N'Other Current Assets - Fed income tax receivables.', N'N/A')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A089080', N'OCA State in tax rec', N'Other Current Assets - State income tax receivable', N'N/A')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A110011', N'ROU, Building', N'Right of use assets- Buildings - Direct GL', N'N/A')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A110071', N'ROU, Vehicle', N'Right of use assets-Vehicles-Direct GL', N'N/A')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A110201', N'ROU, A.Amort Bldg', N'Right of use assets- Acc/Amort- buildings - Dir GL', N'N/A')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A110202', N'ROU, A.Amort Bldg', N'ROU assets- Acc/Amort- buildings - Dir GL NOIM', N'N/A')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A110231', N'ROU, A.Amort M&E', N'Right of use assets- Acc/Amort- M&E - Direct GL', N'N/A')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A110261', N'ROU, A.Amort Veh', N'Right of use assets- Acc/Amort- Veh-Direct GL', N'N/A')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A110262', N'ROU, A.Amort Veh', N'Right of use assets- Acc/Amort- Veh-Direct-NOIM', N'N/A')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A110282', N'ROU, A.Amort Land', N'Right of use assets- Acc/Amort-Land-Direct GL-NOIM', N'N/A')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A111020', N'Build-cost-D GL', N'Buildings- at cost- direct GL entry', N'N/A')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A111210', N'Build-Acc/D-D GL', N'Buildings- Acc/Dep- direct GL entry', N'N/A')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A112020', N'LI-cost-D GL', N'Leasehold imp- at cost- direct GL entry', N'N/A')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A112210', N'LI-Acc/D-Manual', N'Leasehold imp- Acc/Dep- Manual', N'N/A')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A114020', N'M&E-cost-D GL', N'M&E- at cost- direct GL entry', N'N/A')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A114210', N'M&E-Acc/D-D GL entry', N'M&E- Acc/Dep- direct GL entry', N'N/A')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A114401', N'M&E-Acc/Impair- Dir', N'M&E- Acc/Impair- Direct GL', N'N/A')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A116020', N'F&F-cost-D GL', N'Furniture & fixtures- at cost- direct GL entry', N'N/A')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A116210', N'F&F-Acc/D-D GL entry', N'Furniture & fixtures- Acc/Dep- direct GL entry', N'N/A')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A119200', N'Assets interim acct', N'Construction in Progress- Assets interim account', N'N/A')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A122070', N'TM-Ext. TM - D GL', N'TM-Externally acquired Trademarks-Direct Input', N'N/A')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A122260', N'PR-Acc/A (Ext) D GL', N'PR- Acc/Amort. (Externally acquired) Direct Input', N'N/A')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A122270', N'TM-Acc/A (Ext) D GL', N'TM- Acc/Amort. (Externally acquired) Direct Input', N'N/A')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A122280', N'CR-Acc/A (Ext) D GL', N'CR- Acc/Amort. (Externally acquired) Direct Input', N'N/A')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A123041', N'SW-Int.dev SWOU-D GL', N'Software- Int. dev SW for own use- direct GL entry', N'N/A')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A132010', N'Sec Inv-Subsidiaries', N'Security investment- Subsidiaries', N'N/A')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A141010', N'ADA-Gen', N'Allowance for doubtful debts-non-curr- General', N'N/A')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A142200', N'DTA-Foreign tax', N'Def tax assets-non-curr- Foreign tax', N'N/A')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A144100', N'VA-Local tax', N'Valuation allowance-non-curr- Local tax', N'N/A')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A159010', N'ONCA-Gen', N'Other non-curr assets- General', N'N/A')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A212100', N'T AP- GRIR 1', N'Trade AP- invoice to be received- GRIR 1', N'N/A')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A212110', N'T AP-Invo to be rec', N'Trade AP- invoice to be received- direct GL entry', N'N/A')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A212850', N'T AP-D GL entry- OIM', N'Trade AP- direct GL entry- OIM', N'N/A')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A212851', N'T AP-D GL NOI', N'Trade AP- direct GL entry- NOIM', N'N/A')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A212990', N'T AP-FX Trans', N'Trade AP- FX Translation', N'N/A')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A213010', N'ST Borrowing-Gen', N'Short Term Borrowing- General', N'N/A')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A213100', N'ST Borrowing-SGTS', N'Short Term Borrowing- SGTS', N'N/A')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A213990', N'ST Borrow-FX Trans', N'Short Term Borrowing- FX Translation', N'N/A')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A215020', N'AP-NT-S&W to be paid', N'AP-non trade- Salaries and wages to be paid', N'N/A')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A215070', N'DTC Ext Warranty', N'DTC Extended Warranty', N'N/A')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A215071', N'AP-NT- GRIR SRM', N'AP-non trade- invoice to be received- GRIR SRM', N'N/A')
GO
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A215080', N'AP-NT-Invo to be rec', N'AP-non trade-invoice to be received-direct GLentry', N'N/A')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A215090', N'AP-NT-cons tax-Natio', N'AP-non trade- consolidated taxation-National', N'N/A')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A215091', N'AP-NT-cons tax-Local', N'AP-non trade- consolidated taxation-Local', N'N/A')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A215100', N'CTBNK DISBURSEMENTS', N'Outgo Clr- CTBNK DISBURSEMENTS', N'x')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A215102', N'CITI-ADP PAYROLL-SEL', N'Outgoing Clearing- CASH CITIBANK-ADP PAYROLL- SEL', N'x')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A215103', N'CITIBK-AP CHECK DISB', N'Outgoing Clearing- CITIBANK-AP CHECK DISB', N'x')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A215105', N'JP MORGAN C CONCENT', N'Outgoing Clearing- JP MORGAN CHASE CONCENTRATION', N'x')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A215106', N'JP Morgan CAD SEL LB', N'Outgoing Clearing- JP Morgan CAD SEL Lockbox', N'x')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A215108', N'CITIBANK CORP A/P', N'Outgoing Clearing- CITIBANK CORP A/P', N'x')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A215112', N'O Clr 255', N'Outgoing Clearing 255', N'x')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A215117', N'Ocl- JPMC-SARF ACH', N'Outgoing Clearing- JPMC Bank-SARF ACH', N'x')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A215133', N'JP MORGAN C CONCENT', N'Outgoing Clearing- JP MORGAN CHASE CONCENTRATION', N'x')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A215246', N'OCl- SEL CONCUR', N'Outgoing Clearing- SEL CONCUR ACCOUNT', N'x')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A215302', N'RAS cash-RAS EUR', N'Outgoing Clearing- RAS ACCOUNT EUR', N'x')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A215306', N'RAS cash-RAS GBP', N'Outgoing Clearing- RAS ACCOUNT GBP', N'x')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A215307', N'O Clr-RAS USD', N'Outgoing Clearing- RAS ACCOUNT USD', N'x')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A215309', N'RAS cash-RAS JPY', N'Outgoing Clearing- RAS ACCOUNT JPY', N'x')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A215315', N'RAS cash-RAS CAD', N'Outgoing Clearing- RAS ACCOUNT CAD', N'x')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A215392', N'RAS cash-RAS EUR', N'Outgoing Clearing- RAS ACCOUNT EUR SOCAN', N'x')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A215395', N'O Clr 395', N'Outgoing Clearing RAS CAD SOCAN', N'x')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A215397', N'O Clr 397', N'Outgoing Clearing RAS USD SOCAN', N'x')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A215399', N'O Clr 399', N'Outgoing Clearing RAS JPY SOCAN', N'x')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A215850', N'Other AP-NT-D GL-OIM', N'Other AP-non trade- direct GL entry- OIM', N'x')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A215851', N'Other AP-NT-Tech', N'Other AP-non trade- Technical Purposes only', N'N/A')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A215870', N'Other AP-RSU', N'Other AP-current- RSU', N'N/A')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A215990', N'O.AP-NT-FX Tra othe', N'Other AP-non trade- FX Translation for others', N'x')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A216020', N'AE-Packaging levies', N'Accrd exps- Packaging levies', N'N/A')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A216100', N'Accrd Co-op AD(MDF)1', N'Accrd exps- SR- Co-op AD(MDF) 1', N'N/A')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A216101', N'Accrd Co-op AD(MDF)2', N'Accrd exps- SR- Co-op AD(MDF) 2', N'N/A')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A216120', N'Accrd Fin support PG', N'Accrd exps- SR- Financial support programs', N'N/A')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A216130', N'Accrd SR-Spiff1', N'Accrd exps- SR- Spiff(Floor salesman incentive) 1', N'N/A')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A216136', N'Accrd SR-Spiff7', N'Accrd exps- SR- Spiff(Floor salesman incentive) 7', N'N/A')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A216137', N'Accrd SR-Spiff8', N'Accrd exps- SR- Spiff(Floor salesman incentive) 8', N'N/A')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A216139', N'Accrd SR-Spiff10', N'Accrd exps- SR- Spiff(Floor salesman incentive) 10', N'N/A')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A216141', N'Accrd Stock Comp2', N'Accrd exps- SR- Stock Compensation 2', N'N/A')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A216150', N'Accrd SR-VR1', N'Accrd exps- SR- Volume Rebate 1', N'N/A')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A216151', N'Accrd SR-VR2', N'Accrd exps- SR- Volume Rebate 2', N'N/A')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A216160', N'Accrd SR,CB Act', N'Accrd exps, SR, Cashback (Activity)', N'N/A')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A216180', N'Accrd SR-SIA1', N'Accrd exps- SR- Sell-in allowance 1', N'N/A')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A216181', N'Accrd SR-SIA2', N'Accrd exps- SR- Sell-in allowance 2', N'N/A')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A216184', N'Accrd SR-SIA5', N'Accrd exps- SR- Sell-in allowance 5', N'N/A')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A216186', N'Accrd SR-SIA7', N'Accrd exps- SR- Sell-in allowance 7', N'N/A')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A216200', N'ASR-Instant rebate', N'Accrd exps- SR- Instant rebate', N'N/A')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A216210', N'Accrd SR-Bundle', N'Accrd exps- SR- Bundle', NULL)
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A216220', N'ASR-AR early payment', N'Accrd exps- SR- AR early payment related', N'N/A')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A216230', N'ASR-O.man price adj', N'Accrd exps- SR- Other manual price adj', N'N/A')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A216240', N'ASR-Other', N'Accrd exps- SR- Other(WEEE- recycle- etc)', N'N/A')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A216310', N'AE-Salaries & Wages', N'Accrd exps- Salaries & Wages', N'N/A')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A216320', N'AE-Bonuses-Gen', N'Accrd exps- Bonuses- General', N'N/A')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A216330', N'AE-DC', N'Accrd exps- Defined Contribution', N'N/A')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A216340', N'AE-Compens absence', N'Accrd exps- Compensated absence', N'N/A')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A216345', N'AE-SS Exp', N'Accrd exps- Social security expense', N'N/A')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A216350', N'AE-Welfare Exp', N'Accrd exps- Welfare expense', N'N/A')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A216360', N'AE-O.personal cost', N'Accrd exps- Other personal cost', N'N/A')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A216410', N'AE-Reserve royalty', N'Accrd exps- Reserve for royalty', N'N/A')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A216440', N'AE-freight', N'Accrd exps- SGA freight', N'N/A')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A216450', N'AE-storage', N'Accrd exps- SGA storage', N'N/A')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A216460', N'AE-S.commission-Gen', N'Accrd exps- SGA sales commission- General', N'N/A')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A216461', N'AE-S.commiss-Int.SF', N'Accrd exps- SGA sales commission- Int. sales force', N'N/A')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A216480', N'AE-legal Exp', N'Accrd exps- SGA legal expense', N'N/A')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A216500', N'AE-Consultant fee', N'Accrd exps- SGA Consultant fee', N'N/A')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A216510', N'AE-Ad&Pro', N'Accrd exps- SGA Advertising & promotion', N'N/A')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A216610', N'Liabilities for sale', N'Liabilities for sales returns', N'N/A')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A216800', N'AE freight', N'Accrd exps- COGS freight', N'N/A')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A216810', N'AE-COGS duty', N'Accrd exps- COGS duty', N'N/A')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A216820', N'AE COGS', N'Accrd exps- COGS', N'N/A')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A216900', N'AE-Other1', N'Accrd exps- Other1', N'N/A')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A216901', N'AE - Other2', N'Acccrued Expense- Other2', N'N/A')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A216902', N'AE- Other3', N'Accrd exps- Other3', N'N/A')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A216903', N'Accrd Exps SGA Other', N'Accrued Expenses- SGA Other', N'N/A')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A216905', N'Acc Exps SGA Lease', N'Accrued SGA - Lease liability accrued', N'N/A')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A216910', N'Bulk Invo control', N'Accrd exps- Other- Bulk Invoice control account', N'N/A')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A216911', N'Bulk Invo Accrual', N'Accrd exps- Other- Bulk Invoice accrual account', N'N/A')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A216990', N'AE-FX Trans', N'Accrd exps- FX Translation', N'N/A')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A220010', N'Tax-P on sales-Gen', N'Tax payable on sales- General', N'N/A')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A220020', N'Tax-P on sales-D GL', N'Tax payable on sales- direct GL entry', N'N/A')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A220022', N'Sales Tax Clearing', N'Sales/Use Tax Clearing Canada', N'N/A')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A220030', N'Tax-P on sales-Gen2', N'Tax payable on sales- General2', N'N/A')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A220100', N'Sales Tax Clearing', N'Sales/Use Tax Clearing US', N'N/A')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A220990', N'Tax-P on sales-FX Tr', N'Tax payable on sales- FX Translation', N'N/A')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A226010', N'Def rev-Gen', N'Deferred revenue-current- General', N'N/A')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A226040', N'Def rev-Prepaid card', N'Deferred revenue-current- Prepaid card', N'N/A')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A226080', N'Def rev-Ext warranty', N'Deferred revenue-current- Extended warranty', N'N/A')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A226090', N'Def Rev Cur LTC  IO', N'Deferred revenue-current, LT Contract (IO req''ed)', N'N/A')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A229010', N'Reserve for warranty', N'Reserve for warranty- General', N'N/A')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A231010', N'ITP-National tax', N'Income tax payable- National tax', N'N/A')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A231100', N'ITP-Local tax', N'Income tax payable- Local tax', N'N/A')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A232020', N'AOT-Property tax', N'Accrued other taxes- Property tax', N'N/A')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A232030', N'AOT-Tax hold/Welfare', N'Accrued other taxes- Tax Withhholding/Welfare', N'N/A')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A232031', N'AOT-Local Tax', N'Accrued other taxes - Local Tax', N'N/A')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A232032', N'AOT-Soc Sec and Wel', N'Accrued other taxes - Social Security and Welfare', N'N/A')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A232110', N'AOT-use tax(US only)', N'Accrued other taxes- use tax (US only)', N'N/A')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A232111', N'AOT-use tax(US)- DGL', N'Accrued other taxes- use tax (US only)- Direct GL', N'N/A')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A232902', N'AOT-Other3', N'Accrued other taxes- Other3', N'N/A')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A237010', N'Deriv liab-FXforward', N'Derivative liabilities-current- FX forward', N'N/A')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A247010', N'Current portion of L', N'Current portion of LT Debt, Operating', N'N/A')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A247030', N'LL-current-Interest', N'Lease liability - current - Interest', N'N/A')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A273010', N'Other misc. CL-Gen', N'Other misc. CL- General', N'N/A')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A273020', N'O.misc. CL-Deposits1', N'Other misc. CL- Deposits1', N'N/A')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A273060', N'O.misc. CL-Welfare', N'Other misc. CL- Welfare', N'N/A')
GO
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A306010', N'LT Debts, Operating', N'LT Debts, Operating', N'N/A')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A307010', N'LT debts-Op Lease', N'Long Term Debts (Op Lease)', N'N/A')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A310061', N'Other AP-RSU-NC', N'Other AP-non-current- RSU', N'N/A')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A311010', N'LT debts-Gen', N'LT debts- General', N'N/A')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A312020', N'Guaranteed depo rec1', N'Guaranteed deposits received 1', N'N/A')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A313020', N'Liab for DB', N'Liability for DB&DC- Corporate pension fund(DB)', N'N/A')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A313100', N'Liab for O.PRP', N'Liability for DB&DC- other post-retirement plans', N'N/A')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A316200', N'Acc Lab non-current', N'Accrued Labor expenses - non-current', N'N/A')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A320010', N'ARO-Gen', N'Asset retirement obligation-non-curr- General', N'N/A')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A330010', N'Def rev Gen', N'Def rev General', N'N/A')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A340010', N'ONCL-Gen', N'Other non-curr liabilities- General', N'N/A')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A411010', N'Common stock-Gen', N'Common stock- General', N'N/A')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A421020', N'APIC-Other', N'Additional paid-in capital- Other', N'N/A')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A421030', N'APIC-Stock option', N'Additional paid-in capital- Stock option', N'N/A')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A443900', N'R/E other1', N'R/E other than legal reserve- other1', N'N/A')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A471070', N'NCI-Other', N'NCI- Other', N'N/A')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A505010', N'COGS-Products', N'COGS- Products', N'N/A')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A505030', N'COGS-Other', N'COGS- Other', N'N/A')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A505077', N'Inb Freight-Other', N'COGS- Inbound Freight- Other', N'N/A')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A505080', N'Inb Insurance', N'COGS- Inbound Insurance', N'N/A')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A505171', N'Out Freight-FG(Air)', N'COGS - Outbound Freight- Finished goods (Air)', N'N/A')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A531400', N'NOE-FX Trans losses', N'NOE- FX Translation losses', N'N/A')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A622240', N'SR-Spiff1', N'Sales reduction- Spiff(Floor salesman incentive)1', N'N/A')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A631300', N'NOR-FX Trans gain', N'NOR- FX Translation gain', N'N/A')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A631900', N'NOR-Other1', N'NOR- Other1', N'N/A')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A705010', N'Unemploy act contri', N'Social security- Unemployment act contribution', NULL)
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A705050', N'SS-Insurance1', N'Social security- Insurance1', NULL)
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A706020', N'Welfare exps-Meals', N'Welfare exps- Meals', N'N/A')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A706900', N'Welfare-Misc Benefit', N'Welfare - Misc Employee Benefits Welfare', N'N/A')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A706901', N'Welfare - Misc Other', N'Welfare - Misc Employee Benefits Other', N'N/A')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A711030', N'Freight-FG (Land)', N'Freight- Finished goods freightage(Land)', N'N/A')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A711900', N'Freight-Other1', N'Freight- Other1', N'N/A')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A712010', N'E&T expensed', N'Equipment- tools & software expensed- E&T', N'N/A')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A712100', N'SW expensed', N'Equipment- tools & software expensed- Soft', N'N/A')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A714020', N'Water charges', N'Utilities exps- Water charges', N'N/A')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A714030', N'Gas charges', N'Utilities exps- Gas charges', N'N/A')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A714900', N'Utilities other1', N'Utilities exps- Other1', N'N/A')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A722010', N'Recruiting exp', N'R&T exps- Recruiting expense', N'N/A')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A723020', N'Accommodation', N'Travelling & commutation- Accommodation', N'N/A')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A725020', N'NW & Land phone', N'Commu exps- Network and Land phone', N'N/A')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A725030', N'Cell phone', N'Commu exps- Cell phone', N'N/A')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A731900', N'Insurance Other1', N'Insurance exps- Other1', N'N/A')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A731910', N'Insurance stock', N'Insurance exps- Stock in transit/transport', N'N/A')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A732020', N'R&M-Bld/LI/struc', N'Repair&maintenance exps- Bld/LI/struc', N'N/A')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A732160', N'R&M-IS S/W Maintenan', N'Repair&maintenance exps- IS S/W Maintenance', N'N/A')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A742010', N'Consumption tax', N'misc. tax- Consumption tax', N'N/A')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A742200', N'D regional tax', N'misc. tax- Deductible regional tax', N'N/A')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A743010', N'FG storage fee', N'Storage- Finished goods storage fee', N'N/A')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A743900', N'Storage-Other1', N'Storage- Other1', N'N/A')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A744010', N'membership fee', N'misc. exps- membership fee', N'N/A')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A744090', N'Engineering expense', N'misc. exps- Engineering expense', NULL)
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A744800', N'Outgo recharge', N'misc. exps- Outgoing recharge', N'N/A')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A744900', N'misc. exps-Other1', N'misc. exps- Other1', N'N/A')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A745080', N'Vehicles exps', N'Rent exps- Vehicles exps', N'N/A')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A745095', N'Rent Exps, Office re', N'Rent Exps, Office rent (SysInt)', N'N/A')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A745900', N'Rent exps-Other1', N'Rent exps- Other1', N'N/A')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A748020', N'Temp staff agency fe', N'Prof service fee- Temp staff service fee (agency)', N'N/A')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A748030', N'Legal Services', N'Prof service fee- Legal Services', N'N/A')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A748040', N'IS consultant fees', N'Prof service fee- IS consultant fees', N'N/A')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A748050', N'O.consultant fees', N'Prof service fee- Other consultant fees', N'N/A')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A748090', N'BPO', N'Prof service fee- Business Process Outsourcing', N'N/A')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A748900', N'Prof serv Other1', N'Prof service fee- Other1', N'N/A')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A771090', N'Internet others', N'AD&Pro exps- Media expenses- Internet others', N'N/A')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A771210', N'Event&Exhibition', N'AD&Pro exps- Event&Exhibition', N'N/A')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A771230', N'Give Away', N'AD&Pro exps- Others- Give Away', N'N/A')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A771240', N'AD&Pro-Training', N'AD&Pro exps- Others- Dealer/Customer- Training', N'N/A')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A771900', N'AD&Pro exps-Other1', N'AD&Pro exps- Other1', N'N/A')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A775020', N'Service-IW-other', N'Service- Inwarranty- other', N'N/A')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A775900', N'Service-Other1', N'Service- Other1', N'N/A')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A778030', N'Battery levies', N'Battery levies', NULL)
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A901000', N'Purchase merchandise', N'Purchase merchandise', N'N/A')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A910000', N'Inventory end mercha', N'Inventory end merchandise', N'N/A')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A920120', N'AP Invos to be rece', N'Intracompany- AP Invoices to be received', N'N/A')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A999900', N'RTR Int Control Acc', N'RTR Interface Control Account', N'N/A')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A999930', N'Journal splitting Co', N'Journal splitting Control Account', N'N/A')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A999990', N'CO-FI RECON.', N'CO-FI RECONCILIATION POSTINGS', N'N/A')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A999994', N'Clr - FA migration', N'Clearing account, FIXED ASSET Migration', N'N/A')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A999995', N'GL CONVERSION', N'Clearing account- GL CONVERSION', N'N/A')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A999996', N'AR OPEN ITEM CONVERS', N'Clearing account- AR OPEN ITEM CONVERSION', N'N/A')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A999997', N'AP OPEN ITEM CONVERS', N'Clearing account- AP OPEN ITEM CONVERSION', N'N/A')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A999998', N'STOCK CONVERSION', N'Clearing account- STOCK CONVERSION', N'N/A')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A999999', N'FIXED ASSET CONVERS', N'Clearing account- FIXED ASSET CONVERSION', N'N/A')
GO
