USE [DIVA_US00_FY23]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[AM_COPA_MAPPING](
	[COPA_MANDT] [nvarchar](100) NULL,
	[COPA_BUKRS] [nvarchar](100) NULL,
	[COPA_KOKRS] [nvarchar](100) NULL,
	[COPA_RACCT] [nvarchar](100) NULL,
	[COPA_RACCT_TXT50] [nvarchar](100) NULL,
	[COPA_RACCT_Hierarchy_L1] [nvarchar](100) NULL,
	[COPA_RACCT_Hierarchy_L2] [nvarchar](100) NULL,
	[COPA_RACCT_Hierarchy_L3] [nvarchar](100) NULL,
	[COPA_Contractual_Condition] [nvarchar](100) NULL,
	[COPA_Settlement_method] [nvarchar](100) NULL,
	[COPA_Rebate_basis] [nvarchar](100) NULL,
	[COPA_CI_or_non_CI] [nvarchar](100) NULL,
	[COPA_Value] [nvarchar](100) NULL
) ON [PRIMARY]
GO
INSERT [dbo].[AM_COPA_MAPPING] ([COPA_MANDT], [COPA_BUKRS], [COPA_KOKRS], [COPA_RACCT], [COPA_RACCT_TXT50], [COPA_RACCT_Hierarchy_L1], [COPA_RACCT_Hierarchy_L2], [COPA_RACCT_Hierarchy_L3], [COPA_Contractual_Condition], [COPA_Settlement_method], [COPA_Rebate_basis], [COPA_CI_or_non_CI], [COPA_Value]) VALUES (N'888', N'US00', N'E004', N'A505010', N'COGS- Products', N'Sales Reductions', NULL, NULL, NULL, NULL, NULL, NULL, NULL)
INSERT [dbo].[AM_COPA_MAPPING] ([COPA_MANDT], [COPA_BUKRS], [COPA_KOKRS], [COPA_RACCT], [COPA_RACCT_TXT50], [COPA_RACCT_Hierarchy_L1], [COPA_RACCT_Hierarchy_L2], [COPA_RACCT_Hierarchy_L3], [COPA_Contractual_Condition], [COPA_Settlement_method], [COPA_Rebate_basis], [COPA_CI_or_non_CI], [COPA_Value]) VALUES (N'888', N'US00', N'E004', N'A505020', N'COGS- Material sales', N'Sales Reductions', NULL, NULL, NULL, NULL, NULL, NULL, NULL)
INSERT [dbo].[AM_COPA_MAPPING] ([COPA_MANDT], [COPA_BUKRS], [COPA_KOKRS], [COPA_RACCT], [COPA_RACCT_TXT50], [COPA_RACCT_Hierarchy_L1], [COPA_RACCT_Hierarchy_L2], [COPA_RACCT_Hierarchy_L3], [COPA_Contractual_Condition], [COPA_Settlement_method], [COPA_Rebate_basis], [COPA_CI_or_non_CI], [COPA_Value]) VALUES (N'888', N'US00', N'E004', N'A505030', N'COGS- Other', N'Sales Reductions', NULL, NULL, NULL, NULL, NULL, NULL, NULL)
INSERT [dbo].[AM_COPA_MAPPING] ([COPA_MANDT], [COPA_BUKRS], [COPA_KOKRS], [COPA_RACCT], [COPA_RACCT_TXT50], [COPA_RACCT_Hierarchy_L1], [COPA_RACCT_Hierarchy_L2], [COPA_RACCT_Hierarchy_L3], [COPA_Contractual_Condition], [COPA_Settlement_method], [COPA_Rebate_basis], [COPA_CI_or_non_CI], [COPA_Value]) VALUES (N'888', N'US00', N'E004', N'A505040', N'COGS- Service & Repair', N'Sales Reductions', NULL, NULL, NULL, NULL, NULL, NULL, NULL)
INSERT [dbo].[AM_COPA_MAPPING] ([COPA_MANDT], [COPA_BUKRS], [COPA_KOKRS], [COPA_RACCT], [COPA_RACCT_TXT50], [COPA_RACCT_Hierarchy_L1], [COPA_RACCT_Hierarchy_L2], [COPA_RACCT_Hierarchy_L3], [COPA_Contractual_Condition], [COPA_Settlement_method], [COPA_Rebate_basis], [COPA_CI_or_non_CI], [COPA_Value]) VALUES (N'888', N'US00', N'E004', N'A505050', N'COGS- Warranty - Extended', N'Sales Reductions', NULL, NULL, NULL, NULL, NULL, NULL, NULL)
INSERT [dbo].[AM_COPA_MAPPING] ([COPA_MANDT], [COPA_BUKRS], [COPA_KOKRS], [COPA_RACCT], [COPA_RACCT_TXT50], [COPA_RACCT_Hierarchy_L1], [COPA_RACCT_Hierarchy_L2], [COPA_RACCT_Hierarchy_L3], [COPA_Contractual_Condition], [COPA_Settlement_method], [COPA_Rebate_basis], [COPA_CI_or_non_CI], [COPA_Value]) VALUES (N'888', N'US00', N'E004', N'A505060', N'COGS- Inbound Duties and other fees', N'Sales Reductions', NULL, NULL, NULL, NULL, NULL, NULL, NULL)
INSERT [dbo].[AM_COPA_MAPPING] ([COPA_MANDT], [COPA_BUKRS], [COPA_KOKRS], [COPA_RACCT], [COPA_RACCT_TXT50], [COPA_RACCT_Hierarchy_L1], [COPA_RACCT_Hierarchy_L2], [COPA_RACCT_Hierarchy_L3], [COPA_Contractual_Condition], [COPA_Settlement_method], [COPA_Rebate_basis], [COPA_CI_or_non_CI], [COPA_Value]) VALUES (N'888', N'US00', N'E004', N'A505072', N'COGS- Inbound Freight- Finished goods (Land)', N'Sales Reductions', NULL, NULL, NULL, NULL, NULL, NULL, NULL)
INSERT [dbo].[AM_COPA_MAPPING] ([COPA_MANDT], [COPA_BUKRS], [COPA_KOKRS], [COPA_RACCT], [COPA_RACCT_TXT50], [COPA_RACCT_Hierarchy_L1], [COPA_RACCT_Hierarchy_L2], [COPA_RACCT_Hierarchy_L3], [COPA_Contractual_Condition], [COPA_Settlement_method], [COPA_Rebate_basis], [COPA_CI_or_non_CI], [COPA_Value]) VALUES (N'888', N'US00', N'E004', N'A505077', N'COGS- Inbound Freight- Other', N'Sales Reductions', NULL, NULL, NULL, NULL, NULL, NULL, NULL)
INSERT [dbo].[AM_COPA_MAPPING] ([COPA_MANDT], [COPA_BUKRS], [COPA_KOKRS], [COPA_RACCT], [COPA_RACCT_TXT50], [COPA_RACCT_Hierarchy_L1], [COPA_RACCT_Hierarchy_L2], [COPA_RACCT_Hierarchy_L3], [COPA_Contractual_Condition], [COPA_Settlement_method], [COPA_Rebate_basis], [COPA_CI_or_non_CI], [COPA_Value]) VALUES (N'888', N'US00', N'E004', N'A505080', N'COGS- Inbound Insurance', N'Sales Reductions', NULL, NULL, NULL, NULL, NULL, NULL, NULL)
INSERT [dbo].[AM_COPA_MAPPING] ([COPA_MANDT], [COPA_BUKRS], [COPA_KOKRS], [COPA_RACCT], [COPA_RACCT_TXT50], [COPA_RACCT_Hierarchy_L1], [COPA_RACCT_Hierarchy_L2], [COPA_RACCT_Hierarchy_L3], [COPA_Contractual_Condition], [COPA_Settlement_method], [COPA_Rebate_basis], [COPA_CI_or_non_CI], [COPA_Value]) VALUES (N'888', N'US00', N'E004', N'A505110', N'COGS- Adjustment of sales return', N'Sales Reductions', NULL, NULL, NULL, NULL, NULL, NULL, NULL)
INSERT [dbo].[AM_COPA_MAPPING] ([COPA_MANDT], [COPA_BUKRS], [COPA_KOKRS], [COPA_RACCT], [COPA_RACCT_TXT50], [COPA_RACCT_Hierarchy_L1], [COPA_RACCT_Hierarchy_L2], [COPA_RACCT_Hierarchy_L3], [COPA_Contractual_Condition], [COPA_Settlement_method], [COPA_Rebate_basis], [COPA_CI_or_non_CI], [COPA_Value]) VALUES (N'888', N'US00', N'E004', N'A505171', N'COGS - Outbound Freight- Finished goods (Air)', N'Sales Reductions', NULL, NULL, NULL, NULL, NULL, NULL, NULL)
INSERT [dbo].[AM_COPA_MAPPING] ([COPA_MANDT], [COPA_BUKRS], [COPA_KOKRS], [COPA_RACCT], [COPA_RACCT_TXT50], [COPA_RACCT_Hierarchy_L1], [COPA_RACCT_Hierarchy_L2], [COPA_RACCT_Hierarchy_L3], [COPA_Contractual_Condition], [COPA_Settlement_method], [COPA_Rebate_basis], [COPA_CI_or_non_CI], [COPA_Value]) VALUES (N'888', N'US00', N'E004', N'A505177', N'COGS - Outbound Freight- Other', N'Sales Reductions', NULL, NULL, NULL, NULL, NULL, NULL, NULL)
INSERT [dbo].[AM_COPA_MAPPING] ([COPA_MANDT], [COPA_BUKRS], [COPA_KOKRS], [COPA_RACCT], [COPA_RACCT_TXT50], [COPA_RACCT_Hierarchy_L1], [COPA_RACCT_Hierarchy_L2], [COPA_RACCT_Hierarchy_L3], [COPA_Contractual_Condition], [COPA_Settlement_method], [COPA_Rebate_basis], [COPA_CI_or_non_CI], [COPA_Value]) VALUES (N'888', N'US00', N'E004', N'A505300', N'COGS- Devaluation', N'Sales Reductions', NULL, NULL, NULL, NULL, NULL, NULL, NULL)
INSERT [dbo].[AM_COPA_MAPPING] ([COPA_MANDT], [COPA_BUKRS], [COPA_KOKRS], [COPA_RACCT], [COPA_RACCT_TXT50], [COPA_RACCT_Hierarchy_L1], [COPA_RACCT_Hierarchy_L2], [COPA_RACCT_Hierarchy_L3], [COPA_Contractual_Condition], [COPA_Settlement_method], [COPA_Rebate_basis], [COPA_CI_or_non_CI], [COPA_Value]) VALUES (N'888', N'US00', N'E004', N'A505400', N'COGS- Shortage & shrinkage', N'Sales Reductions', NULL, NULL, NULL, NULL, NULL, NULL, NULL)
INSERT [dbo].[AM_COPA_MAPPING] ([COPA_MANDT], [COPA_BUKRS], [COPA_KOKRS], [COPA_RACCT], [COPA_RACCT_TXT50], [COPA_RACCT_Hierarchy_L1], [COPA_RACCT_Hierarchy_L2], [COPA_RACCT_Hierarchy_L3], [COPA_Contractual_Condition], [COPA_Settlement_method], [COPA_Rebate_basis], [COPA_CI_or_non_CI], [COPA_Value]) VALUES (N'888', N'US00', N'E004', N'A505410', N'COGS- Special loss on disposal of inventories', N'Sales Reductions', NULL, NULL, NULL, NULL, NULL, NULL, NULL)
INSERT [dbo].[AM_COPA_MAPPING] ([COPA_MANDT], [COPA_BUKRS], [COPA_KOKRS], [COPA_RACCT], [COPA_RACCT_TXT50], [COPA_RACCT_Hierarchy_L1], [COPA_RACCT_Hierarchy_L2], [COPA_RACCT_Hierarchy_L3], [COPA_Contractual_Condition], [COPA_Settlement_method], [COPA_Rebate_basis], [COPA_CI_or_non_CI], [COPA_Value]) VALUES (N'888', N'US00', N'E004', N'A542300', N'Current income tax expense- WH (foreign tax)1', N'COGS', NULL, NULL, NULL, NULL, NULL, NULL, NULL)
INSERT [dbo].[AM_COPA_MAPPING] ([COPA_MANDT], [COPA_BUKRS], [COPA_KOKRS], [COPA_RACCT], [COPA_RACCT_TXT50], [COPA_RACCT_Hierarchy_L1], [COPA_RACCT_Hierarchy_L2], [COPA_RACCT_Hierarchy_L3], [COPA_Contractual_Condition], [COPA_Settlement_method], [COPA_Rebate_basis], [COPA_CI_or_non_CI], [COPA_Value]) VALUES (N'888', N'US00', N'E004', N'A621010', N'Gross Sales- Products', N'Gross Sales', NULL, NULL, NULL, NULL, NULL, NULL, NULL)
INSERT [dbo].[AM_COPA_MAPPING] ([COPA_MANDT], [COPA_BUKRS], [COPA_KOKRS], [COPA_RACCT], [COPA_RACCT_TXT50], [COPA_RACCT_Hierarchy_L1], [COPA_RACCT_Hierarchy_L2], [COPA_RACCT_Hierarchy_L3], [COPA_Contractual_Condition], [COPA_Settlement_method], [COPA_Rebate_basis], [COPA_CI_or_non_CI], [COPA_Value]) VALUES (N'888', N'US00', N'E004', N'A621020', N'Gross Sales- Insurance & freight', N'Gross Sales', NULL, NULL, NULL, NULL, NULL, NULL, NULL)
INSERT [dbo].[AM_COPA_MAPPING] ([COPA_MANDT], [COPA_BUKRS], [COPA_KOKRS], [COPA_RACCT], [COPA_RACCT_TXT50], [COPA_RACCT_Hierarchy_L1], [COPA_RACCT_Hierarchy_L2], [COPA_RACCT_Hierarchy_L3], [COPA_Contractual_Condition], [COPA_Settlement_method], [COPA_Rebate_basis], [COPA_CI_or_non_CI], [COPA_Value]) VALUES (N'888', N'US00', N'E004', N'A621050', N'Gross Sales- Service & Repair', N'Gross Sales', NULL, NULL, NULL, NULL, NULL, NULL, NULL)
INSERT [dbo].[AM_COPA_MAPPING] ([COPA_MANDT], [COPA_BUKRS], [COPA_KOKRS], [COPA_RACCT], [COPA_RACCT_TXT50], [COPA_RACCT_Hierarchy_L1], [COPA_RACCT_Hierarchy_L2], [COPA_RACCT_Hierarchy_L3], [COPA_Contractual_Condition], [COPA_Settlement_method], [COPA_Rebate_basis], [COPA_CI_or_non_CI], [COPA_Value]) VALUES (N'888', N'US00', N'E004', N'A621060', N'Gross Sales- Extended Warranty', N'Gross Sales', NULL, NULL, NULL, NULL, NULL, NULL, NULL)
INSERT [dbo].[AM_COPA_MAPPING] ([COPA_MANDT], [COPA_BUKRS], [COPA_KOKRS], [COPA_RACCT], [COPA_RACCT_TXT50], [COPA_RACCT_Hierarchy_L1], [COPA_RACCT_Hierarchy_L2], [COPA_RACCT_Hierarchy_L3], [COPA_Contractual_Condition], [COPA_Settlement_method], [COPA_Rebate_basis], [COPA_CI_or_non_CI], [COPA_Value]) VALUES (N'888', N'US00', N'E004', N'A621070', N'Gross Sales- Subscription revenue', N'Gross Sales', NULL, NULL, NULL, NULL, NULL, NULL, NULL)
INSERT [dbo].[AM_COPA_MAPPING] ([COPA_MANDT], [COPA_BUKRS], [COPA_KOKRS], [COPA_RACCT], [COPA_RACCT_TXT50], [COPA_RACCT_Hierarchy_L1], [COPA_RACCT_Hierarchy_L2], [COPA_RACCT_Hierarchy_L3], [COPA_Contractual_Condition], [COPA_Settlement_method], [COPA_Rebate_basis], [COPA_CI_or_non_CI], [COPA_Value]) VALUES (N'888', N'US00', N'E004', N'A621900', N'Gross Sales- Other1', N'Gross Sales', NULL, NULL, NULL, NULL, NULL, NULL, NULL)
INSERT [dbo].[AM_COPA_MAPPING] ([COPA_MANDT], [COPA_BUKRS], [COPA_KOKRS], [COPA_RACCT], [COPA_RACCT_TXT50], [COPA_RACCT_Hierarchy_L1], [COPA_RACCT_Hierarchy_L2], [COPA_RACCT_Hierarchy_L3], [COPA_Contractual_Condition], [COPA_Settlement_method], [COPA_Rebate_basis], [COPA_CI_or_non_CI], [COPA_Value]) VALUES (N'888', N'US00', N'E004', N'A622110', N'Sales Reduction- On-invoice Disc- Coupon Discount', N'Sales Reductions', NULL, NULL, NULL, NULL, NULL, NULL, NULL)
INSERT [dbo].[AM_COPA_MAPPING] ([COPA_MANDT], [COPA_BUKRS], [COPA_KOKRS], [COPA_RACCT], [COPA_RACCT_TXT50], [COPA_RACCT_Hierarchy_L1], [COPA_RACCT_Hierarchy_L2], [COPA_RACCT_Hierarchy_L3], [COPA_Contractual_Condition], [COPA_Settlement_method], [COPA_Rebate_basis], [COPA_CI_or_non_CI], [COPA_Value]) VALUES (N'888', N'US00', N'E004', N'A622111', N'Sales Reduction- On-invoice Disc- Sales Discount', N'Sales Reductions', NULL, NULL, NULL, NULL, NULL, NULL, NULL)
INSERT [dbo].[AM_COPA_MAPPING] ([COPA_MANDT], [COPA_BUKRS], [COPA_KOKRS], [COPA_RACCT], [COPA_RACCT_TXT50], [COPA_RACCT_Hierarchy_L1], [COPA_RACCT_Hierarchy_L2], [COPA_RACCT_Hierarchy_L3], [COPA_Contractual_Condition], [COPA_Settlement_method], [COPA_Rebate_basis], [COPA_CI_or_non_CI], [COPA_Value]) VALUES (N'888', N'US00', N'E004', N'A622112', N'Sales Reduction- On-invoice Disc- SIP Base Disc', N'Sales Reductions', NULL, NULL, NULL, NULL, NULL, NULL, NULL)
INSERT [dbo].[AM_COPA_MAPPING] ([COPA_MANDT], [COPA_BUKRS], [COPA_KOKRS], [COPA_RACCT], [COPA_RACCT_TXT50], [COPA_RACCT_Hierarchy_L1], [COPA_RACCT_Hierarchy_L2], [COPA_RACCT_Hierarchy_L3], [COPA_Contractual_Condition], [COPA_Settlement_method], [COPA_Rebate_basis], [COPA_CI_or_non_CI], [COPA_Value]) VALUES (N'888', N'US00', N'E004', N'A622113', N'Sales Red- On-invoice Disc- Disc in lieu of return', N'Sales Reductions', NULL, NULL, NULL, NULL, NULL, NULL, NULL)
INSERT [dbo].[AM_COPA_MAPPING] ([COPA_MANDT], [COPA_BUKRS], [COPA_KOKRS], [COPA_RACCT], [COPA_RACCT_TXT50], [COPA_RACCT_Hierarchy_L1], [COPA_RACCT_Hierarchy_L2], [COPA_RACCT_Hierarchy_L3], [COPA_Contractual_Condition], [COPA_Settlement_method], [COPA_Rebate_basis], [COPA_CI_or_non_CI], [COPA_Value]) VALUES (N'888', N'US00', N'E004', N'A622114', N'Sales Reduct- On-invoice Disc- Payment Efficiency', N'Sales Reductions', NULL, NULL, NULL, NULL, NULL, NULL, NULL)
INSERT [dbo].[AM_COPA_MAPPING] ([COPA_MANDT], [COPA_BUKRS], [COPA_KOKRS], [COPA_RACCT], [COPA_RACCT_TXT50], [COPA_RACCT_Hierarchy_L1], [COPA_RACCT_Hierarchy_L2], [COPA_RACCT_Hierarchy_L3], [COPA_Contractual_Condition], [COPA_Settlement_method], [COPA_Rebate_basis], [COPA_CI_or_non_CI], [COPA_Value]) VALUES (N'888', N'US00', N'E004', N'A622115', N'Sales Reduction- On-invoice Disc- RFA Allowance', N'Sales Reductions', NULL, NULL, NULL, NULL, NULL, NULL, NULL)
INSERT [dbo].[AM_COPA_MAPPING] ([COPA_MANDT], [COPA_BUKRS], [COPA_KOKRS], [COPA_RACCT], [COPA_RACCT_TXT50], [COPA_RACCT_Hierarchy_L1], [COPA_RACCT_Hierarchy_L2], [COPA_RACCT_Hierarchy_L3], [COPA_Contractual_Condition], [COPA_Settlement_method], [COPA_Rebate_basis], [COPA_CI_or_non_CI], [COPA_Value]) VALUES (N'888', N'US00', N'E004', N'A622121', N'Sales Reduct- On-invoice Disc- Retail Store Disc', N'Sales Reductions', NULL, NULL, NULL, NULL, NULL, NULL, NULL)
INSERT [dbo].[AM_COPA_MAPPING] ([COPA_MANDT], [COPA_BUKRS], [COPA_KOKRS], [COPA_RACCT], [COPA_RACCT_TXT50], [COPA_RACCT_Hierarchy_L1], [COPA_RACCT_Hierarchy_L2], [COPA_RACCT_Hierarchy_L3], [COPA_Contractual_Condition], [COPA_Settlement_method], [COPA_Rebate_basis], [COPA_CI_or_non_CI], [COPA_Value]) VALUES (N'888', N'US00', N'E004', N'A622210', N'Variable MDF', N'Sales Reductions', NULL, NULL, NULL, NULL, NULL, NULL, NULL)
INSERT [dbo].[AM_COPA_MAPPING] ([COPA_MANDT], [COPA_BUKRS], [COPA_KOKRS], [COPA_RACCT], [COPA_RACCT_TXT50], [COPA_RACCT_Hierarchy_L1], [COPA_RACCT_Hierarchy_L2], [COPA_RACCT_Hierarchy_L3], [COPA_Contractual_Condition], [COPA_Settlement_method], [COPA_Rebate_basis], [COPA_CI_or_non_CI], [COPA_Value]) VALUES (N'888', N'US00', N'E004', N'A622211', N'Fixed MDF', N'Sales Reductions', NULL, NULL, NULL, NULL, NULL, NULL, NULL)
INSERT [dbo].[AM_COPA_MAPPING] ([COPA_MANDT], [COPA_BUKRS], [COPA_KOKRS], [COPA_RACCT], [COPA_RACCT_TXT50], [COPA_RACCT_Hierarchy_L1], [COPA_RACCT_Hierarchy_L2], [COPA_RACCT_Hierarchy_L3], [COPA_Contractual_Condition], [COPA_Settlement_method], [COPA_Rebate_basis], [COPA_CI_or_non_CI], [COPA_Value]) VALUES (N'888', N'US00', N'E004', N'A622220', N'Sales reduction- Display allowance', N'Sales Reductions', NULL, NULL, NULL, NULL, NULL, NULL, NULL)
INSERT [dbo].[AM_COPA_MAPPING] ([COPA_MANDT], [COPA_BUKRS], [COPA_KOKRS], [COPA_RACCT], [COPA_RACCT_TXT50], [COPA_RACCT_Hierarchy_L1], [COPA_RACCT_Hierarchy_L2], [COPA_RACCT_Hierarchy_L3], [COPA_Contractual_Condition], [COPA_Settlement_method], [COPA_Rebate_basis], [COPA_CI_or_non_CI], [COPA_Value]) VALUES (N'888', N'US00', N'E004', N'A622230', N'Sales reduction- Financial support programs', N'Sales Reductions', NULL, NULL, NULL, NULL, NULL, NULL, NULL)
INSERT [dbo].[AM_COPA_MAPPING] ([COPA_MANDT], [COPA_BUKRS], [COPA_KOKRS], [COPA_RACCT], [COPA_RACCT_TXT50], [COPA_RACCT_Hierarchy_L1], [COPA_RACCT_Hierarchy_L2], [COPA_RACCT_Hierarchy_L3], [COPA_Contractual_Condition], [COPA_Settlement_method], [COPA_Rebate_basis], [COPA_CI_or_non_CI], [COPA_Value]) VALUES (N'888', N'US00', N'E004', N'A622240', N'Sales reduction- Spiff(Floor salesman incentive)1', N'Sales Reductions', NULL, NULL, NULL, NULL, NULL, NULL, NULL)
INSERT [dbo].[AM_COPA_MAPPING] ([COPA_MANDT], [COPA_BUKRS], [COPA_KOKRS], [COPA_RACCT], [COPA_RACCT_TXT50], [COPA_RACCT_Hierarchy_L1], [COPA_RACCT_Hierarchy_L2], [COPA_RACCT_Hierarchy_L3], [COPA_Contractual_Condition], [COPA_Settlement_method], [COPA_Rebate_basis], [COPA_CI_or_non_CI], [COPA_Value]) VALUES (N'888', N'US00', N'E004', N'A622310', N'Sales Reduction- Stock Compensation 1- PP', N'Sales Reductions', NULL, NULL, NULL, NULL, NULL, NULL, NULL)
INSERT [dbo].[AM_COPA_MAPPING] ([COPA_MANDT], [COPA_BUKRS], [COPA_KOKRS], [COPA_RACCT], [COPA_RACCT_TXT50], [COPA_RACCT_Hierarchy_L1], [COPA_RACCT_Hierarchy_L2], [COPA_RACCT_Hierarchy_L3], [COPA_Contractual_Condition], [COPA_Settlement_method], [COPA_Rebate_basis], [COPA_CI_or_non_CI], [COPA_Value]) VALUES (N'888', N'US00', N'E004', N'A622311', N'Sales Reduction- Stock Compensation 2- SMAF/MAF', N'Sales Reductions', NULL, NULL, NULL, NULL, NULL, NULL, NULL)
INSERT [dbo].[AM_COPA_MAPPING] ([COPA_MANDT], [COPA_BUKRS], [COPA_KOKRS], [COPA_RACCT], [COPA_RACCT_TXT50], [COPA_RACCT_Hierarchy_L1], [COPA_RACCT_Hierarchy_L2], [COPA_RACCT_Hierarchy_L3], [COPA_Contractual_Condition], [COPA_Settlement_method], [COPA_Rebate_basis], [COPA_CI_or_non_CI], [COPA_Value]) VALUES (N'888', N'US00', N'E004', N'A622410', N'Sales reduction- Volume Rebate 1', N'Sales Reductions', NULL, NULL, NULL, NULL, NULL, NULL, NULL)
INSERT [dbo].[AM_COPA_MAPPING] ([COPA_MANDT], [COPA_BUKRS], [COPA_KOKRS], [COPA_RACCT], [COPA_RACCT_TXT50], [COPA_RACCT_Hierarchy_L1], [COPA_RACCT_Hierarchy_L2], [COPA_RACCT_Hierarchy_L3], [COPA_Contractual_Condition], [COPA_Settlement_method], [COPA_Rebate_basis], [COPA_CI_or_non_CI], [COPA_Value]) VALUES (N'888', N'US00', N'E004', N'A622430', N'Sales Reduction- Sell-in allowance- Sales Discount', N'Sales Reductions', NULL, NULL, NULL, NULL, NULL, NULL, NULL)
INSERT [dbo].[AM_COPA_MAPPING] ([COPA_MANDT], [COPA_BUKRS], [COPA_KOKRS], [COPA_RACCT], [COPA_RACCT_TXT50], [COPA_RACCT_Hierarchy_L1], [COPA_RACCT_Hierarchy_L2], [COPA_RACCT_Hierarchy_L3], [COPA_Contractual_Condition], [COPA_Settlement_method], [COPA_Rebate_basis], [COPA_CI_or_non_CI], [COPA_Value]) VALUES (N'888', N'US00', N'E004', N'A622431', N'Sales Red- Sell-in Allow- Disc in lieu of returns', N'Sales Reductions', NULL, NULL, NULL, NULL, NULL, NULL, NULL)
INSERT [dbo].[AM_COPA_MAPPING] ([COPA_MANDT], [COPA_BUKRS], [COPA_KOKRS], [COPA_RACCT], [COPA_RACCT_TXT50], [COPA_RACCT_Hierarchy_L1], [COPA_RACCT_Hierarchy_L2], [COPA_RACCT_Hierarchy_L3], [COPA_Contractual_Condition], [COPA_Settlement_method], [COPA_Rebate_basis], [COPA_CI_or_non_CI], [COPA_Value]) VALUES (N'888', N'US00', N'E004', N'A622432', N'Sales Reduction- Sell-in Allowance- RFA Allowance', N'Sales Reductions', NULL, NULL, NULL, NULL, NULL, NULL, NULL)
INSERT [dbo].[AM_COPA_MAPPING] ([COPA_MANDT], [COPA_BUKRS], [COPA_KOKRS], [COPA_RACCT], [COPA_RACCT_TXT50], [COPA_RACCT_Hierarchy_L1], [COPA_RACCT_Hierarchy_L2], [COPA_RACCT_Hierarchy_L3], [COPA_Contractual_Condition], [COPA_Settlement_method], [COPA_Rebate_basis], [COPA_CI_or_non_CI], [COPA_Value]) VALUES (N'888', N'US00', N'E004', N'A622433', N'Sales Reduction – End Customer Rebates', N'Sales Reductions', NULL, NULL, NULL, NULL, NULL, NULL, NULL)
INSERT [dbo].[AM_COPA_MAPPING] ([COPA_MANDT], [COPA_BUKRS], [COPA_KOKRS], [COPA_RACCT], [COPA_RACCT_TXT50], [COPA_RACCT_Hierarchy_L1], [COPA_RACCT_Hierarchy_L2], [COPA_RACCT_Hierarchy_L3], [COPA_Contractual_Condition], [COPA_Settlement_method], [COPA_Rebate_basis], [COPA_CI_or_non_CI], [COPA_Value]) VALUES (N'888', N'US00', N'E004', N'A622434', N'Sales Reduction – SIA - Sony Rewards', N'Sales Reductions', NULL, NULL, NULL, NULL, NULL, NULL, NULL)
INSERT [dbo].[AM_COPA_MAPPING] ([COPA_MANDT], [COPA_BUKRS], [COPA_KOKRS], [COPA_RACCT], [COPA_RACCT_TXT50], [COPA_RACCT_Hierarchy_L1], [COPA_RACCT_Hierarchy_L2], [COPA_RACCT_Hierarchy_L3], [COPA_Contractual_Condition], [COPA_Settlement_method], [COPA_Rebate_basis], [COPA_CI_or_non_CI], [COPA_Value]) VALUES (N'888', N'US00', N'E004', N'A622435', N'Sales Reduction- Sell-in Allow- SIP Ship & Debit', N'Sales Reductions', NULL, NULL, NULL, NULL, NULL, NULL, NULL)
INSERT [dbo].[AM_COPA_MAPPING] ([COPA_MANDT], [COPA_BUKRS], [COPA_KOKRS], [COPA_RACCT], [COPA_RACCT_TXT50], [COPA_RACCT_Hierarchy_L1], [COPA_RACCT_Hierarchy_L2], [COPA_RACCT_Hierarchy_L3], [COPA_Contractual_Condition], [COPA_Settlement_method], [COPA_Rebate_basis], [COPA_CI_or_non_CI], [COPA_Value]) VALUES (N'888', N'US00', N'E004', N'A622436', N'Sales Reduction- Sell-in Allow- Sell-in Allow Disc', N'Sales Reductions', NULL, NULL, NULL, NULL, NULL, NULL, NULL)
INSERT [dbo].[AM_COPA_MAPPING] ([COPA_MANDT], [COPA_BUKRS], [COPA_KOKRS], [COPA_RACCT], [COPA_RACCT_TXT50], [COPA_RACCT_Hierarchy_L1], [COPA_RACCT_Hierarchy_L2], [COPA_RACCT_Hierarchy_L3], [COPA_Contractual_Condition], [COPA_Settlement_method], [COPA_Rebate_basis], [COPA_CI_or_non_CI], [COPA_Value]) VALUES (N'888', N'US00', N'E004', N'A622450', N'Sales reduction- Instant rebate', N'Sales Reductions', NULL, NULL, NULL, NULL, NULL, NULL, NULL)
INSERT [dbo].[AM_COPA_MAPPING] ([COPA_MANDT], [COPA_BUKRS], [COPA_KOKRS], [COPA_RACCT], [COPA_RACCT_TXT50], [COPA_RACCT_Hierarchy_L1], [COPA_RACCT_Hierarchy_L2], [COPA_RACCT_Hierarchy_L3], [COPA_Contractual_Condition], [COPA_Settlement_method], [COPA_Rebate_basis], [COPA_CI_or_non_CI], [COPA_Value]) VALUES (N'888', N'US00', N'E004', N'A622480', N'Sales reduction- Bundle', N'Sales Reductions', NULL, NULL, NULL, NULL, NULL, NULL, NULL)
INSERT [dbo].[AM_COPA_MAPPING] ([COPA_MANDT], [COPA_BUKRS], [COPA_KOKRS], [COPA_RACCT], [COPA_RACCT_TXT50], [COPA_RACCT_Hierarchy_L1], [COPA_RACCT_Hierarchy_L2], [COPA_RACCT_Hierarchy_L3], [COPA_Contractual_Condition], [COPA_Settlement_method], [COPA_Rebate_basis], [COPA_CI_or_non_CI], [COPA_Value]) VALUES (N'888', N'US00', N'E004', N'A622510', N'Sales reduction- Sales return allowance', N'Sales Reductions', NULL, NULL, NULL, NULL, NULL, NULL, NULL)
INSERT [dbo].[AM_COPA_MAPPING] ([COPA_MANDT], [COPA_BUKRS], [COPA_KOKRS], [COPA_RACCT], [COPA_RACCT_TXT50], [COPA_RACCT_Hierarchy_L1], [COPA_RACCT_Hierarchy_L2], [COPA_RACCT_Hierarchy_L3], [COPA_Contractual_Condition], [COPA_Settlement_method], [COPA_Rebate_basis], [COPA_CI_or_non_CI], [COPA_Value]) VALUES (N'888', N'US00', N'E004', N'A622610', N'Sales reduction- AR early payment related 1', N'Sales Reductions', NULL, NULL, NULL, NULL, NULL, NULL, NULL)
INSERT [dbo].[AM_COPA_MAPPING] ([COPA_MANDT], [COPA_BUKRS], [COPA_KOKRS], [COPA_RACCT], [COPA_RACCT_TXT50], [COPA_RACCT_Hierarchy_L1], [COPA_RACCT_Hierarchy_L2], [COPA_RACCT_Hierarchy_L3], [COPA_Contractual_Condition], [COPA_Settlement_method], [COPA_Rebate_basis], [COPA_CI_or_non_CI], [COPA_Value]) VALUES (N'888', N'US00', N'E004', N'A622620', N'Sales reduction- Other manual price adj', N'Sales Reductions', NULL, NULL, NULL, NULL, NULL, NULL, NULL)
INSERT [dbo].[AM_COPA_MAPPING] ([COPA_MANDT], [COPA_BUKRS], [COPA_KOKRS], [COPA_RACCT], [COPA_RACCT_TXT50], [COPA_RACCT_Hierarchy_L1], [COPA_RACCT_Hierarchy_L2], [COPA_RACCT_Hierarchy_L3], [COPA_Contractual_Condition], [COPA_Settlement_method], [COPA_Rebate_basis], [COPA_CI_or_non_CI], [COPA_Value]) VALUES (N'888', N'US00', N'E004', N'A622630', N'Sales reduction- Other(WEEE- recycle- etc)', N'Sales Reductions', NULL, NULL, NULL, NULL, NULL, NULL, NULL)
INSERT [dbo].[AM_COPA_MAPPING] ([COPA_MANDT], [COPA_BUKRS], [COPA_KOKRS], [COPA_RACCT], [COPA_RACCT_TXT50], [COPA_RACCT_Hierarchy_L1], [COPA_RACCT_Hierarchy_L2], [COPA_RACCT_Hierarchy_L3], [COPA_Contractual_Condition], [COPA_Settlement_method], [COPA_Rebate_basis], [COPA_CI_or_non_CI], [COPA_Value]) VALUES (N'888', N'US00', N'E004', N'A625041', N'OPR- Rent - Operating Lease', N'Gross Sales', NULL, NULL, NULL, NULL, NULL, NULL, NULL)
INSERT [dbo].[AM_COPA_MAPPING] ([COPA_MANDT], [COPA_BUKRS], [COPA_KOKRS], [COPA_RACCT], [COPA_RACCT_TXT50], [COPA_RACCT_Hierarchy_L1], [COPA_RACCT_Hierarchy_L2], [COPA_RACCT_Hierarchy_L3], [COPA_Contractual_Condition], [COPA_Settlement_method], [COPA_Rebate_basis], [COPA_CI_or_non_CI], [COPA_Value]) VALUES (N'888', N'US00', N'E004', N'A625900', N'OPR- Other1', N'Gross Sales', NULL, NULL, NULL, NULL, NULL, NULL, NULL)
GO
