USE [DIVA_US00_FY23]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[AM_IRGR_GINI_ARDR_MAPPING](
	[IRGR_GL_ACCT] [nvarchar](100) NULL,
	[IRGR_GL_TXT] [nvarchar](100) NULL,
	[IRGR_OR_GINI_OR_ARDR] [nvarchar](100) NULL
) ON [PRIMARY]
GO
