USE [DIVA_US00_FY23]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[AM_VAT_CLF](
	[ACCOUNT] [nvarchar](100) NULL,
	[GL TEXT] [nvarchar](1000) NULL,
	[CLASSIFICATION] [nvarchar](100) NULL
) ON [PRIMARY]
GO
INSERT [dbo].[AM_VAT_CLF] ([ACCOUNT], [GL TEXT], [CLASSIFICATION]) VALUES (N'A038010', N'VAT-R on purch-gen', N'VAT on purchases')
INSERT [dbo].[AM_VAT_CLF] ([ACCOUNT], [GL TEXT], [CLASSIFICATION]) VALUES (N'A215851', N'Other AP-NT-Tech', N'VAT on purchases')
INSERT [dbo].[AM_VAT_CLF] ([ACCOUNT], [GL TEXT], [CLASSIFICATION]) VALUES (N'A220010', N'Tax-P on sales-Gen', N'VAT on sales')
INSERT [dbo].[AM_VAT_CLF] ([ACCOUNT], [GL TEXT], [CLASSIFICATION]) VALUES (N'A220020', N'Tax-P on sales-D GL', N'VAT on sales')
INSERT [dbo].[AM_VAT_CLF] ([ACCOUNT], [GL TEXT], [CLASSIFICATION]) VALUES (N'A220100', N'Sales Tax Clearing', N'VAT on sales')
INSERT [dbo].[AM_VAT_CLF] ([ACCOUNT], [GL TEXT], [CLASSIFICATION]) VALUES (N'A232110', N'AOT-use tax(US only)', N'VAT on sales')
GO
