USE [DIVA_US00_FY21_22_23]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[AM_CALENDAR_MAPPING](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[ZF_YEAR_MONTH] [nvarchar](20) NULL
) ON [PRIMARY]
GO
SET IDENTITY_INSERT [dbo].[AM_CALENDAR_MAPPING] ON 

INSERT [dbo].[AM_CALENDAR_MAPPING] ([ID], [ZF_YEAR_MONTH]) VALUES (1, N'2021-10')
INSERT [dbo].[AM_CALENDAR_MAPPING] ([ID], [ZF_YEAR_MONTH]) VALUES (2, N'2021-11')
INSERT [dbo].[AM_CALENDAR_MAPPING] ([ID], [ZF_YEAR_MONTH]) VALUES (3, N'2021-12')
INSERT [dbo].[AM_CALENDAR_MAPPING] ([ID], [ZF_YEAR_MONTH]) VALUES (4, N'2022-01')
INSERT [dbo].[AM_CALENDAR_MAPPING] ([ID], [ZF_YEAR_MONTH]) VALUES (5, N'2022-02')
INSERT [dbo].[AM_CALENDAR_MAPPING] ([ID], [ZF_YEAR_MONTH]) VALUES (6, N'2022-03')
INSERT [dbo].[AM_CALENDAR_MAPPING] ([ID], [ZF_YEAR_MONTH]) VALUES (7, N'2022-04')
INSERT [dbo].[AM_CALENDAR_MAPPING] ([ID], [ZF_YEAR_MONTH]) VALUES (8, N'2022-05')
INSERT [dbo].[AM_CALENDAR_MAPPING] ([ID], [ZF_YEAR_MONTH]) VALUES (9, N'2022-06')
INSERT [dbo].[AM_CALENDAR_MAPPING] ([ID], [ZF_YEAR_MONTH]) VALUES (10, N'2022-07')
INSERT [dbo].[AM_CALENDAR_MAPPING] ([ID], [ZF_YEAR_MONTH]) VALUES (11, N'2022-08')
INSERT [dbo].[AM_CALENDAR_MAPPING] ([ID], [ZF_YEAR_MONTH]) VALUES (12, N'2022-09')
INSERT [dbo].[AM_CALENDAR_MAPPING] ([ID], [ZF_YEAR_MONTH]) VALUES (13, N'2022-10')
INSERT [dbo].[AM_CALENDAR_MAPPING] ([ID], [ZF_YEAR_MONTH]) VALUES (14, N'2022-11')
INSERT [dbo].[AM_CALENDAR_MAPPING] ([ID], [ZF_YEAR_MONTH]) VALUES (15, N'2022-12')
INSERT [dbo].[AM_CALENDAR_MAPPING] ([ID], [ZF_YEAR_MONTH]) VALUES (16, N'2023-01')
INSERT [dbo].[AM_CALENDAR_MAPPING] ([ID], [ZF_YEAR_MONTH]) VALUES (17, N'2023-02')
INSERT [dbo].[AM_CALENDAR_MAPPING] ([ID], [ZF_YEAR_MONTH]) VALUES (18, N'2023-03')
SET IDENTITY_INSERT [dbo].[AM_CALENDAR_MAPPING] OFF
GO
