USE [DIVA_US00_FY21_22_23]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[AM_DEBIT_BANK_CREDIT](
	[ZF_FIRST_DEBIT_ACCOUNT] [varchar](max) NULL,
	[ZF_FIRST_CREDIT_ACCOUNT] [varchar](max) NULL,
	[ZF_FIRST_DEBIT_ACCOUNT_TEXT] [varchar](max) NULL,
	[ZF_FIRST_CREDIT_ACCOUNT_TEXT] [varchar](max) NULL,
	[ZF_CREDIT_AR_CLEARING_FLAG] [varchar](1) NOT NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
INSERT [dbo].[AM_DEBIT_BANK_CREDIT] ([ZF_FIRST_DEBIT_ACCOUNT], [ZF_FIRST_CREDIT_ACCOUNT], [ZF_FIRST_DEBIT_ACCOUNT_TEXT], [ZF_FIRST_CREDIT_ACCOUNT_TEXT], [ZF_CREDIT_AR_CLEARING_FLAG]) VALUES (N'A012197', N'A014010', N'Barclays Bank - USD', N'Oth AP-NT Doc Split', N'')
INSERT [dbo].[AM_DEBIT_BANK_CREDIT] ([ZF_FIRST_DEBIT_ACCOUNT], [ZF_FIRST_CREDIT_ACCOUNT], [ZF_FIRST_DEBIT_ACCOUNT_TEXT], [ZF_FIRST_CREDIT_ACCOUNT_TEXT], [ZF_CREDIT_AR_CLEARING_FLAG]) VALUES (N'A012182', N'A014010', N'Oth AP-NT Doc Split', N'Oth AP-NT Doc Split', N'')
INSERT [dbo].[AM_DEBIT_BANK_CREDIT] ([ZF_FIRST_DEBIT_ACCOUNT], [ZF_FIRST_CREDIT_ACCOUNT], [ZF_FIRST_DEBIT_ACCOUNT_TEXT], [ZF_FIRST_CREDIT_ACCOUNT_TEXT], [ZF_CREDIT_AR_CLEARING_FLAG]) VALUES (N'A012105', N'A014010', N'HSBC - NC', N'Oth AP-NT Doc Split', N'')
INSERT [dbo].[AM_DEBIT_BANK_CREDIT] ([ZF_FIRST_DEBIT_ACCOUNT], [ZF_FIRST_CREDIT_ACCOUNT], [ZF_FIRST_DEBIT_ACCOUNT_TEXT], [ZF_FIRST_CREDIT_ACCOUNT_TEXT], [ZF_CREDIT_AR_CLEARING_FLAG]) VALUES (N'A012163', N'A014010', N'Oth AP-NT Doc Split', N'Oth AP-NT Doc Split', N'')
INSERT [dbo].[AM_DEBIT_BANK_CREDIT] ([ZF_FIRST_DEBIT_ACCOUNT], [ZF_FIRST_CREDIT_ACCOUNT], [ZF_FIRST_DEBIT_ACCOUNT_TEXT], [ZF_FIRST_CREDIT_ACCOUNT_TEXT], [ZF_CREDIT_AR_CLEARING_FLAG]) VALUES (N'A012142', N'A014010', N'BCA - NC 2', N'T AR,Gen', N'')
INSERT [dbo].[AM_DEBIT_BANK_CREDIT] ([ZF_FIRST_DEBIT_ACCOUNT], [ZF_FIRST_CREDIT_ACCOUNT], [ZF_FIRST_DEBIT_ACCOUNT_TEXT], [ZF_FIRST_CREDIT_ACCOUNT_TEXT], [ZF_CREDIT_AR_CLEARING_FLAG]) VALUES (N'A012166', N'A014010', N'Krungthai Bank - NC', N'T AR,Gen', N'')
INSERT [dbo].[AM_DEBIT_BANK_CREDIT] ([ZF_FIRST_DEBIT_ACCOUNT], [ZF_FIRST_CREDIT_ACCOUNT], [ZF_FIRST_DEBIT_ACCOUNT_TEXT], [ZF_FIRST_CREDIT_ACCOUNT_TEXT], [ZF_CREDIT_AR_CLEARING_FLAG]) VALUES (N'A012138', N'A014010', N'BDO - PH NC2', N'T AR,Gen', N'')
INSERT [dbo].[AM_DEBIT_BANK_CREDIT] ([ZF_FIRST_DEBIT_ACCOUNT], [ZF_FIRST_CREDIT_ACCOUNT], [ZF_FIRST_DEBIT_ACCOUNT_TEXT], [ZF_FIRST_CREDIT_ACCOUNT_TEXT], [ZF_CREDIT_AR_CLEARING_FLAG]) VALUES (N'A012166', N'A014010', N'Krungthai Bank - NC', N'Oth AP-NT Doc Split', N'')
INSERT [dbo].[AM_DEBIT_BANK_CREDIT] ([ZF_FIRST_DEBIT_ACCOUNT], [ZF_FIRST_CREDIT_ACCOUNT], [ZF_FIRST_DEBIT_ACCOUNT_TEXT], [ZF_FIRST_CREDIT_ACCOUNT_TEXT], [ZF_CREDIT_AR_CLEARING_FLAG]) VALUES (N'A012138', N'A014010', N'BDO - PH NC2', N'Oth AP-NT Doc Split', N'')
INSERT [dbo].[AM_DEBIT_BANK_CREDIT] ([ZF_FIRST_DEBIT_ACCOUNT], [ZF_FIRST_CREDIT_ACCOUNT], [ZF_FIRST_DEBIT_ACCOUNT_TEXT], [ZF_FIRST_CREDIT_ACCOUNT_TEXT], [ZF_CREDIT_AR_CLEARING_FLAG]) VALUES (N'A012138', N'A032010', N'BDO - PH NC2', N'Oth AP-NT Doc Split', N'')
INSERT [dbo].[AM_DEBIT_BANK_CREDIT] ([ZF_FIRST_DEBIT_ACCOUNT], [ZF_FIRST_CREDIT_ACCOUNT], [ZF_FIRST_DEBIT_ACCOUNT_TEXT], [ZF_FIRST_CREDIT_ACCOUNT_TEXT], [ZF_CREDIT_AR_CLEARING_FLAG]) VALUES (N'A012142', N'A014010', N'BCA - NC 2', N'Oth AP-NT Doc Split', N'')
INSERT [dbo].[AM_DEBIT_BANK_CREDIT] ([ZF_FIRST_DEBIT_ACCOUNT], [ZF_FIRST_CREDIT_ACCOUNT], [ZF_FIRST_DEBIT_ACCOUNT_TEXT], [ZF_FIRST_CREDIT_ACCOUNT_TEXT], [ZF_CREDIT_AR_CLEARING_FLAG]) VALUES (N'A012182', N'A014010', N'Robinson Bank - NC', N'T AR,Gen', N'')
INSERT [dbo].[AM_DEBIT_BANK_CREDIT] ([ZF_FIRST_DEBIT_ACCOUNT], [ZF_FIRST_CREDIT_ACCOUNT], [ZF_FIRST_DEBIT_ACCOUNT_TEXT], [ZF_FIRST_CREDIT_ACCOUNT_TEXT], [ZF_CREDIT_AR_CLEARING_FLAG]) VALUES (N'A012197', N'A226015', N'Barclays Bank - USD', N'Def rev,Adv Recpt', N'')
INSERT [dbo].[AM_DEBIT_BANK_CREDIT] ([ZF_FIRST_DEBIT_ACCOUNT], [ZF_FIRST_CREDIT_ACCOUNT], [ZF_FIRST_DEBIT_ACCOUNT_TEXT], [ZF_FIRST_CREDIT_ACCOUNT_TEXT], [ZF_CREDIT_AR_CLEARING_FLAG]) VALUES (N'A012135', N'A014010', N'BPI - PH NC2', N'Oth AP-NT Doc Split', N'')
INSERT [dbo].[AM_DEBIT_BANK_CREDIT] ([ZF_FIRST_DEBIT_ACCOUNT], [ZF_FIRST_CREDIT_ACCOUNT], [ZF_FIRST_DEBIT_ACCOUNT_TEXT], [ZF_FIRST_CREDIT_ACCOUNT_TEXT], [ZF_CREDIT_AR_CLEARING_FLAG]) VALUES (N'A012163', N'A014010', N'Oth AP-NT Doc Split', N'T AR,Gen', N'')
INSERT [dbo].[AM_DEBIT_BANK_CREDIT] ([ZF_FIRST_DEBIT_ACCOUNT], [ZF_FIRST_CREDIT_ACCOUNT], [ZF_FIRST_DEBIT_ACCOUNT_TEXT], [ZF_FIRST_CREDIT_ACCOUNT_TEXT], [ZF_CREDIT_AR_CLEARING_FLAG]) VALUES (N'A012163', N'A014010', N'Siam CB - NC1', N'T AR,Gen', N'')
INSERT [dbo].[AM_DEBIT_BANK_CREDIT] ([ZF_FIRST_DEBIT_ACCOUNT], [ZF_FIRST_CREDIT_ACCOUNT], [ZF_FIRST_DEBIT_ACCOUNT_TEXT], [ZF_FIRST_CREDIT_ACCOUNT_TEXT], [ZF_CREDIT_AR_CLEARING_FLAG]) VALUES (N'A012109', N'A014010', N'HSBC - National curr', N'Oth AP-NT Doc Split', N'')
GO
