USE [DIVA_US00_FY21_22_23]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[AM_COMPANY_CODE](
	[COMPANY_CODE] [varchar](20) NOT NULL
) ON [PRIMARY]
GO
INSERT [dbo].[AM_COMPANY_CODE] ([COMPANY_CODE]) VALUES (N'US00')
GO
