USE [DIVA_US00_FY21_22_23]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[AM_AR_ACCOUNT](
	[ACDOCA_RACCT] [nvarchar](255) NULL,
	[SKAT_TXT50] [nvarchar](255) NULL,
	[SKAT_TXT20] [nvarchar](255) NULL,
	[ZF_AR_ACCOUNT] [nvarchar](255) NULL
) ON [PRIMARY]
GO
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A012001', N'Cash on Hand - National Currency', N'Cash on Hand - NC', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A012007', N'Cash on Hand - National Currency 2', N'Cash on Hand - NC 2', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A012009', N'Cash on Hand - SAR', N'Cash on Hand - SAR', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A012100', N'Citibank - National Currency', N'Citibank - NC', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A012101', N'Citibank - USD', N'Citibank - USD', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A012103', N'Citibank - EUR', N'Citibank - EUR', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A012105', N'HSBC - National Currency', N'HSBC - NC', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A012106', N'HSBC - USD', N'HSBC - USD', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A012109', N'HSBC - National curr 2', N'HSBC - National curr', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A012110', N'HSBC - ANZ National curr 3', N'HSBC - NC3', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A012114', N'SMBC - National Currency', N'SMBC - NC', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A012115', N'SMBC - USD', N'SMBC - USD', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A012123', N'JPMG - National Currency', N'JPMG - NC', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A012135', N'BPI - PH National Curr 2', N'BPI - PH NC2', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A012136', N'Union Bank - National Currency', N'Union Bank - NC', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A012138', N'BDO - PH National Curr 2', N'BDO - PH NC2', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A012139', N'BDO - USD', N'BDO - USD', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A012140', N'BCA - National currency', N'BCA - NC', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A012141', N'BCA - National currency 1', N'BCA - NC 1', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A012142', N'BCA - National currency 2', N'BCA - NC 2', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A012156', N'BBL - National Currency', N'BBL - NC', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A012159', N'Kasikorn Bank - National Currency', N'Kbank - NC', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A012162', N'SIAM COMMERCIAL BANK - NC', N'Siam CB - NC', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A012163', N'SIAM COMMERCIAL BANK - NC1', N'Siam CB - NC1', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A012166', N'Krungthai Bank - National Currency', N'Krungthai Bank - NC', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A012182', N'Robinson Bank - National currency', N'Robinson Bank - NC', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A012193', N'Emirates NBD - NC', N'Emirates NBD - NC', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A012194', N'Emirates NBD - NC1', N'Emirates NBD - NC1', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A012195', N'Emirates NBD - USD', N'Emirates NBD - USD', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A012196', N'Barclays Bank - NC', N'Barclays Bank - NC', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A012197', N'Barclays Bank - USD', N'Barclays Bank - USD', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A012198', N'Barclay Bank - EUR', N'Barclay Bank - EUR', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A012199', N'Others - National Currency', N'Others - NC', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A012200', N'Citibank – National Currency 2', N'Citibank – NC2', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A012209', N'Citibank – ZAR', N'Citibank – ZAR', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A012250', N'Asia United Bank - National Currency', N'AUB - NC', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A012302', N'RAS cash, RAS ACCOUNT EUR', N'RAS cash,RAS EUR', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A012306', N'RAS cash, RAS ACCOUNT GBP', N'RAS cash,RAS GBP', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A012307', N'RAS cash, RAS ACCOUNT USD', N'RAS cash,RAS USD', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A012309', N'RAS cash, RAS ACCOUNT JPY', N'RAS cash,RAS JPY', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A012316', N'RAS cash, RAS ACCOUNT AUD', N'RAS cash,RAS AUD', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A012318', N'RAS cash, RAS ACCOUNT NZD', N'RAS cash,RAS NZD', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A012320', N'RAS cash, RAS ACCOUNT SGD', N'RAS cash,RAS SGD', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A012321', N'RAS cash, RAS ACCOUNT THB', N'RAS cash,RAS THB', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A012990', N'Cash on hand- FX Translation', N'Cash OH-FX Trans', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A014100', N'Citibank - National Currency (incoming)', N'I Clr Citibank - NC', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A014101', N'Citibank - USD (incoming)', N'I Clr Citibank - USD', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A014103', N'Citibank - EUR (incoming)', N'I Clr Citibank - EUR', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A014105', N'HSBC - National Currency (incoming)', N'I Clr HSBC - NC', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A014106', N'HSBC - USD (incoming)', N'I Clr HSBC - USD', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A014109', N'HSBC - National curr 2 (incoming)', N'HSBC - National curr', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A014110', N'HSBC - ANZ National curr 3 (incoming)', N'I Clr HSBC - NC3', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A014123', N'JPMG - National Currency (incoming)', N'I Clr JPMG - NC', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A014135', N'BPI - PH NC2 (incoming)', N'I Clr, BPI - PH NC2', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A014138', N'BDO - PH National Curr 2 (incoming)', N'I Clr BDO - PH NC2', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A014140', N'BCA - National currency (incoming)', N'I Clr BCA - NC', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A014141', N'BCA - National currency 1 (incoming)', N'I Clr BCA - NC 1', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A014156', N'BBL - National Currency incoming', N'I Clr BBL - NC', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A014159', N'Kasikorn Bank - National Currency incoming', N'I Clr Kbank - NC', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A014162', N'SIAM COMMERCIAL BANK - NC incoming', N'I Clr Siam CB - NC', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A014163', N'SIAM COMMERCIAL BANK - NC1 incoming', N'I Clr Siam CB - NC1', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A014166', N'Krungthai Bank - National Currency incoming', N'I Clr Krungthai Bank', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A014182', N'Robinson Bank - NC (incoming)', N'I Clr, Robinson - NC', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A014193', N'Emirates NBD - NC (incoming)', N'I Clr Emirates - NC', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A014195', N'Emirates NBD - USD (incoming)', N'I Clr Emirates - USD', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A014200', N'Citibank - National Currency2 (incoming)', N'I Clr Citibank - NC2', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A014209', N'Citibank - ZAR (Incoming)', N'I Clr Citibank - ZAR', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A014250', N'Asia United Bank - National Currency (incoming)', N'I Clr AUB - NC', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A014302', N'Incoming Clearing- RAS ACCOUNT EUR', N'I Clr, RAS EUR', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A014307', N'Incoming Clearing- RAS ACCOUNT USD', N'I Clr, RAS USD', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A014309', N'Incoming Clearing- RAS ACCOUNT JPY', N'I Clr, RAS JPY', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A014316', N'Incoming Clearing- RAS ACCOUNT AUD', N'I Clr, RAS AUD', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A014318', N'Incoming Clearing- RAS ACCOUNT NZD', N'I Clr, RAS NZD', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A014321', N'Incoming Clearing- RAS ACCOUNT THB', N'I Clr, RAS THB', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A014850', N'Trade account receivable, direct GL entry, OIM', N'T AR,D GL entry,OIM', N'x')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A014851', N'Trade account receivable- direct GL entry- NOIM', N'T AR-D GL entry-NOI', N'x')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A014990', N'Trade account receivable, FX Translation', N'T AR,FX Trans', N'x')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A021010', N'Products, Merchandise & Finished goods, SAP main', N'M&FG,SAP main acct', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A021015', N'Products- Merchandise & FG- direct GL entry OIM', N'M&FG,D GL,OIM', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A021020', N'Products, Merchandise & FG, direct GL, balance', N'M&FG,D GL,balance', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A021030', N'Products, Merchandise & FG, In transit', N'M&FG,In transit', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A021050', N'Products, Merchandise & FG, Devaluation', N'M&FG,Devaluation', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A024020', N'WIP, direct GL entry – System service', N'WIP-D GL-sys ser', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A024021', N'WIP- direct GL entry- LT contract', N'WIP-D GL-LT contract', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A031010', N'Prepaid exps, Advertizing & promotion', N'PE,Ad&pro', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A031030', N'Prepaid exps, Rental/Leasing', N'PE,Rental/Leasing', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A031050', N'Prepaid exps- Non income tax', N'PE, Non income tax', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A031060', N'Prepaid exps, Insurance', N'PE,Insurance', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A031900', N'Prepaid exps, Other1', N'PE,Other1', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A032850', N'Other AR-current- direct GL entry- OIM', N'OtherAR-D GL ent-OIM', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A032851', N'Other AR-current- direct GL entry- NOIM', N'OtherAR-D GL ent-NOI', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A032990', N'Other AR-current, FX Translation', N'Other AR,FX Trans', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A033010', N'Short term loan, General', N'Short term loan,Gen', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A033100', N'Short term loan, Deposit paid, RAS account', N'ST Loan-Deposit-RAS', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A033990', N'Short term loan- FX Translation', N'ST loan-FX Trans', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A034040', N'Adv paymts- Sales Reductions- Tactical Cash Back', N'Adv-Tact Cash Back', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A034990', N'Adv paymts- FX Translation', N'Adv-FX Trans', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A035900', N'Expense to be recharged, Other1', N'Exp to be rec,Other1', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A035990', N'Expense to be recharged- FX Translation', N'Exp to be rec-FX Tra', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A037010', N'Accrd income, General', N'Accrd income,Gen', N'N/A')
GO
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A037990', N'Accrd income- FX Translation', N'AI-FX Trans', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A038010', N'VAT-receivable on purchase, general', N'VAT-R on purch,gen', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A038340', N'VAT-receivable (clearing) AU', N'VAT-R clr AU', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A038440', N'VAT-receivable (clearing) PH', N'VAT-R clr PH', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A038460', N'Vat-Receivable (Clearing)TH', N'Vat-Recl TH', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A038480', N'VAT-receivable (clearing) VN', N'VAT-R clr VN', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A038510', N'VAT-receivable (clearing) UAE', N'VAT-R clr UAE', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A039010', N'Allowance for doubtful debts, General', N'ADA,Gen', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A040010', N'Derivative Assets-current, Frgn exchange forward', N'Deriv FX forward', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A062010', N'Contract assets- rights to recover goods', N'Rights to recover go', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A089010', N'Other misc. current assets, General', N'OCA,Gen', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A089090', N'Other Current Asset - Cannibalization', N'OCA, Cannibalization', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A089091', N'Other Current Asset - Interim Service', N'OCA, Interim Service', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A089100', N'OCA - Withholding tax – receivable', N'OCA,WHT-receivable', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A089990', N'Other misc. current assets- FX Translation', N'OCA-FX Trans', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A110012', N'ROU- Buildings - Direct GL-NOIM', N'ROU- Buildings', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A110072', N'ROU- Vehicles-Direct-NOIM', N'ROU- Vehicles', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A110202', N'Right of use assets- Acc/Amort- buildings - NOIM', N'ROU, A.Amort Bldg', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A110262', N'ROU- Acc/Amort- Veh-Direct-NOIM', N'ROU- Acc/Amort- Veh', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A110282', N'ROU- Acc/Amort- Land - Direct GL-NOIM', N'ROU- Acc/Amort- Land', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A114210', N'M&E- Acc/Dep- direct GL entry', N'M&E,Acc/D,D GL entry', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A119200', N'Construction in Progress, Assets interim account', N'Assets interim acct', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A119205', N'CIP, Assets interim account (SysInt)', N'CIP, AInterim SysInt', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A138900', N'Incremental costs of obtaining a contract', N'Inc Cost Cont Obtain', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A142010', N'Def tax assets-non-curr, National tax', N'DTA,National tax', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A158010', N'Security Deposit - Non Current', N'Sec.Dep-NC', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A176010', N'Prepaid Income Tax - Non current', N'Prepaid I.T - NC', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A212100', N'Trade AP- invoice to be received- GRIR 1', N'T AP, GRIR 1', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A212101', N'Trade AP- invoice to be received- GRIR 2', N'T AP, GRIR 2', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A212851', N'Trade AP- direct GL entry- NOIM', N'T AP-D GL NOI', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A212990', N'Trade AP, FX Translation', N'T AP,FX Trans', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A213010', N'Short Term Borrowing, General', N'ST Borrowing,Gen', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A213021', N'Short Term Borrowing- Bank', N'ST Borrowing - Bank', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A213100', N'Short Term Borrowing, SGTS', N'ST Borrowing,SGTS', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A213990', N'Short Term Borrowing- FX Translation', N'ST Borrow-FX Trans', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A215070', N'AP-non trade, invoice to be received, GRIR', N'AP-NT,GRIR', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A215100', N'Citibank - National Currency (outgoing)', N'O Clr Citibank - NC', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A215101', N'Citibank - USD (outgoing)', N'O Clr Citibank - USD', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A215103', N'Citibank - EUR (outgoing)', N'O Clr Citibank - EUR', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A215105', N'HSBC - National Currency (outgoing)', N'O Clr HSBC - NC', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A215106', N'HSBC - USD (outgoing)', N'O Clr HSBC - USD', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A215109', N'HSBC - National curr 2 (outgoing)', N'HSBC - National curr', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A215110', N'HSBC - ANZ National curr 3 (outgoing)', N'O Clr HSBC - NC3', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A215123', N'JPMG - National Currency (outgoing)', N'O Clr JPMG - NC', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A215135', N'BPI - PH NC2 (outgoing)', N'O Clr, BPI - PH NC2', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A215136', N'Union Bank - NC (outgoing)', N'O Clr, Union Bank-NC', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A215138', N'BDO - PH National Curr 2 (outgoing)', N'O Clr BDO - PH NC2', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A215139', N'BDO - USD (outgoing)', N'O Clr BDO - USD', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A215140', N'BCA - National currency (outgoing)', N'O Clr BCA - NC', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A215141', N'BCA - National currency 1 (outgoing)', N'O Clr BCA - NC 1', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A215142', N'BCA - National currency 2 (outgoing)', N'O Clr BCA - NC 2', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A215156', N'BBL - National Currency outgoing', N'O Clr BBL - NC', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A215159', N'Kasikorn Bank - National Currency outgoing', N'O Clr Kbank - NC', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A215162', N'SIAM COMMERCIAL BANK - NC outgoing', N'O Clr Siam CB - NC', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A215163', N'SIAM COMMERCIAL BANK - NC1 outgoing', N'O Clr Siam CB - NC1', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A215166', N'Krungthai Bank - National Currency outgoing', N'O Clr Krungthai Bank', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A215182', N'Robinson Bank - NC (outgoing)', N'O Clr, Robinson - NC', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A215193', N'Emirates NBD - NC (outgoing)', N'O Clr Emirates - NC', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A215195', N'Emirates NBD - USD (outgoing)', N'O Clr Emirates - USD', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A215200', N'Citibank - National Currency2 (outgoing)', N'O Clr Citibank - NC2', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A215209', N'Citibank - ZAR (Outgoing)', N'O Clrg Citi - ZAR', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A215250', N'Asia United Bank - National Currency (outgoing)', N'O Clr AUB - NC', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A215302', N'Outgoing Clearing- RAS ACCOUNT EUR', N'O Clr, RAS EUR', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A215307', N'Outgoing Clearing- RAS ACCOUNT USD', N'O Clr, RAS USD', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A215309', N'Outgoing Clearing- RAS ACCOUNT JPY', N'O Clr, RAS JPY', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A215316', N'Outgoing Clearing- RAS ACCOUNT AUD', N'O Clr, RAS AUD', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A215318', N'Outgoing Clearing- RAS ACCOUNT NZD', N'O Clr, RAS NZD', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A215321', N'Outgoing Clearing- RAS ACCOUNT THB', N'O Clr, RAS THB', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A215850', N'Other AP-non trade- direct GL entry- OIM', N'Other AP-NT-D GL-OIM', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A215851', N'Other AP-non trade-Doc Splitting Account', N'Oth AP-NT Doc Split', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A215852', N'Other AP-non trade- direct GL entry- NOIM', N'Other AP-NT,D GL,NOI', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A215870', N'Other AP-current- RSU', N'Other AP-RSU', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A215990', N'Other AP-non trade- FX Translation for others', N'O.AP-NT,FX Tra othe', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A216100', N'Provision for Activity Based Co-Op A&P', N'Accrd Co-op AD(MDF)1', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A216101', N'Provision for Co Op A&P - General', N'Accrd Co-op AD(MDF)2', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A216140', N'Accrd exps, SR, Stock Compensation (Activity)', N'Accrd Stock Comp1', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A216141', N'Accrd exps, SR, Stock Compensation (General)', N'Accrd Stock Comp2', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A216160', N'Accrd exps, SR, Cashback (Activity)', N'Accrd SR,CB Act', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A216161', N'Accrd exps, SR, Cashback (General)', N'Accrd SR,CB Gen', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A216164', N'Accrd exps, SR, Sell Thru/Promo Rebate (Activity)', N'Accrd SR, STR PR Act', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A216165', N'Accrd exps, SR, Sell Thru/Promo Rebate (General)', N'Accrd SR, STR PR Gen', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A216180', N'Accrd exps, SR, Sell-in allowance(Activity)', N'Accrd SR, SIA Act', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A216181', N'Accrd exps, SR, Sell-in allowance(General)', N'Accrd SR, SIA Gen', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A216230', N'Accrd exps, SR, Other manual price adj', N'ASR,O.man price adj', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A216260', N'Accrd Exp, Sales Discount', N'Accrd SR, Sales Disc', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A216261', N'Accrd Exp, Sales Discount (General)', N'Accrd SR,Sales D Gen', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A216310', N'Accrd exps, Salaries & Wages', N'AE,Salaries & Wages', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A216320', N'Accrd exps, Bonuses, General', N'AE,Bonuses,Gen', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A216322', N'Accrd exps- Bonuses- Managements', N'AE,Bonuses,Mgt', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A216340', N'Accrd exps, Compensated absence', N'AE,Compens absence', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A216345', N'Accrd exps, Social security expense', N'AE,SS Exp', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A216350', N'Accrd exps, Welfare expense', N'AE,Welfare Exp', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A216440', N'Accrd exps, SGA freight', N'AE,freight', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A216460', N'Accrd exps, SGA sales commission, General', N'AE,S.commission,Gen', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A216490', N'Accrd exps, SGA audit fee', N'AE,audit fee', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A216500', N'Accrd exps, SGA Consultant fee', N'AE,Consultant fee', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A216510', N'Accrd exps, SGA Advertising & promotion', N'AE,Ad&Pro', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A216854', N'Accrd exps, COGS contents delivery & encoding fees', N'AE delivery & encodi', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A216900', N'Accrd exps, Other1', N'AE,Other1', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A216902', N'Accrued exps - SGA Other', N'AE,Other3', N'N/A')
GO
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A216903', N'Accrd exps, Customer Svc', N'AE, Customer Svc', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A216904', N'Accrued Exp, COGS Others', N'AE, Other 4', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A216990', N'Accrd exps- FX Translation', N'AE-FX Trans', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A218010', N'Accrd exps- Accrued interest', N'Acrd exp - Acrd Int', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A220010', N'Tax payable on sales, General', N'Tax-P on sales,Gen', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A220020', N'Tax payable on sales- direct GL entry', N'Tax-P on sales-D GL', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A220100', N'Tax Payable-VAT Output Tax', N'Tax-P,VAT O.tax', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A226010', N'Deferred revenue-current, General', N'Def rev,Gen', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A226060', N'Deferred revenue-current, Voucher', N'Def rev,Voucher', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A226080', N'Deferred revenue-current, Extended warranty', N'Def rev,Ext warranty', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A226990', N'Deferred Revenue- FX translation', N'Deferred Revenue- FX', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A229010', N'Reserve for warranty, General', N'Reserve for warranty', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A231010', N'Income tax payable- current- General', N'ITP, Curr Gen', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A232030', N'Accrued other taxes, payroll1', N'AOT,payroll1', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A232031', N'Accrued other taxes- payroll - FBT', N'AOT-Payroll-FBT', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A232032', N'Accrued other taxes- payroll - PAYE', N'AOT-Payroll-PAYE', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A232900', N'Accrued other taxes, Other1', N'AOT,Other1', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A232901', N'Accrued other taxes- International', N'AOT-Int tax', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A232990', N'Accrued other taxes- FX Translation', N'AOT-FX Trans', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A237010', N'Derivative liabilities-current- FX forward', N'Deriv liab-FXforward', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A247010', N'Lease liability- Current portion of LTD', N'L.L - curr LTD', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A247030', N'Lease liability- Current Interest Accrual', N'L.L -curr Interest A', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A273010', N'Other misc. CL, General', N'Other misc. CL,Gen', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A273020', N'Other misc. CL-Deposits1', N'O.misc.CL.Deposits1', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A307010', N'Long Term Debts (Op Lease)', N'LT debts-Op Lease', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A310061', N'Other AP-non-current- RSU', N'Other AP-RSU-NC', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A313010', N'Liability for DB&DC, severance(DB)', N'Liab for severance', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A313020', N'Liability for DB&DC- Corporate pension fund(DB)', N'Liab for DB', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A313990', N'Liability for DB&DC- FX Translation', N'Liab for DBDC-FX', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A320010', N'Asset retirement obligation-non-curr, General', N'ARO,Gen', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A330010', N'Def. Revenue- non curr- General (Customer)', N'Def rev Gen', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A340040', N'Other non-curr liabilities- Severance', N'ONCL-Severance', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A340050', N'Other non-curr liabilities, Deferred compensation', N'ONCL,Def compens', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A443010', N'R/E other than legal reserve, R/E brought forward', N'R/E brought forward', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A467010', N'OCI 4-pension liability adjustment, Gross amount', N'Pension liab adj,Gro', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A505010', N'COGS- Products', N'COGS,Products', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A505030', N'COGS- Other', N'COGS,Other', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A505040', N'COGS- Service & Repair', N'COGS,Service&Repair', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A505055', N'COGS - Spare Parts', N'COGS - SP', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A505300', N'COGS- Devaluation', N'COGS,Devaluation', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A505410', N'COGS- Special loss on disposal of inventories', N'COGS,Special LOD inv', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A505410N', N'COGS- Special loss on disposal of inventories (N)', N'COGS- Sp.Loss (N)', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A531010', N'NOE- Interest on borrowing', N'Inter on borrowing', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A531040', N'Interest on Defined Benefit', N'Interest on DB', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A531080', N'NOE- tax deductible inter for overdue(national)', N'D.inter OD(national)', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A531110', N'NOE/ Intr exps on liability to make lease payments', N'NOE/Int exp in lease', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A531400', N'NOE- FX Translation losses', N'NOE,FX Trans losses', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A531510', N'NOE- ARO accretion expense', N'NOE- ARO accre.exp', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A531900', N'NOE- Other1', N'NOE,Other1', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A542010', N'Current income tax expense- National tax', N'CIT,National', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A542500', N'Current income tax expense- Correction for past YR', N'Current income tax e', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A543010', N'Deferred income tax expense- National tax', N'DIT,National', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A621010', N'Gross Sales- Products', N'Gross Sales,Products', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A621050', N'Gross Sales- Service & Repair', N'G sales,Service&Repa', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A621055', N'Gross Sales - Spare Parts', N'Gross Sales - SP', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A621060', N'Gross Sales- Extended Warranty', N'G sales,Ext.Warranty', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A621900', N'Gross Sales- Other1', N'Gross Sales,Other1', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A622110', N'Sales reduction, On-invoice discount Merchandise', N'SR,OID Merchandise', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A622111', N'Sales reduction, On-invoice discount Spare Parts', N'SR,OID Spare Parts', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A622112', N'Sales reduction, On-invoice discount Round diff', N'SR,OID Round diff', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A622113', N'Sales reduction, On-invoice discount General', N'SR,OID General', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A622210', N'Sales reduction, Co-op AD(Activity)', N'SR,Co-op AD (Act)', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A622211', N'Sales reduction, Co-op AD(General)', N'SR,Co-op AD (Gen)', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A622310', N'Sales reduction, Stock Compensation(Activity)', N'SR,Stock Comp (Act)', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A622311', N'Sales reduction, Stock Compensation (General)', N'SR,Stock Comp (Gen)', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A622421', N'Sales Reduction - Cashback (Activity)', N'SR, Cashback (Act)', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A622422', N'Sales Reduction - Cashback (General)', N'SR, Cashback (Gen)', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A622424', N'Sales reduction, Sell Thru/Promo Rebate (Activity)', N'SR, STR (Act)', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A622425', N'Sales reduction, Sell Thru/Promo Rebate (General)', N'SR, STR (Gen)', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A622430', N'Sales reduction, Sell-in allowance (Activity)', N'SR,SIA (Act)', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A622431', N'Sales reduction, Sell-in allowance (General)', N'SR,SIA (Gen)', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A622620', N'Sales reduction, Other manual price adj', N'SR,O.manual adj', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A625900', N'OPR- Other1', N'OPR,Other1', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A631010', N'NOR- Interest income', N'NOR,Inter income', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A631020', N'NOR- Loan interest income', N'NOR,Loan inter inc', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A631030', N'NOR- Other interest income', N'NOR- Other interest', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A631300', N'NOR- FX Translation gain', N'NOR,FX Trans gain', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A631900', N'NOR- Other1', N'NOR,Other1', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A702010', N'S&W- Base salaries', N'S&W,Base salaries', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A702011', N'S&W- Base salaries(Management)', N'S&W,Base salary Mgt', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A702020', N'S&W- Overtime pay for employees', N'S&W,OT pay for empl', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A702100', N'S&W- Temporary employees', N'S&W,Temp employees', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A702200', N'S&W- Compensated absence', N'S&W,Compensated abse', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A702900', N'S&W- Other1', N'S&W,Other1', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A702910', N'S&W- Taxation remuneration in kind VAT full rate', N'S&W,VAT full rate', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A703010', N'Bonuses & allowance- General', N'Bonuses,Gen', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A703020', N'Bonuses & allowance- Management', N'Bonuses, Mgt', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A704010', N'Retirement bnf exps- Prov for retirement bnfs?DB?', N'Prov for DB', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A704300', N'Retirement benefit exps- Termination benefits', N'Termination benefits', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A705010', N'Social security- Unemployment act contribution', N'Unemploy act contri', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A705050', N'Social security- Insurance1', N'SS,Insurance1', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A705900', N'Social security- Other1', N'SS,Other1', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A706010', N'Welfare exps- Private Healthcare Insurance', N'PrivateHealthcareIns', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A706900', N'Welfare exps- Other1', N'Welfare exps,Other1', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A706901', N'Welfare exps- Other2', N'Welfare exps,Other2', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A706902', N'Welfare exps,General Expat', N'Welfare exps,Expat', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A709030', N'Stock-based compensation- RSU', N'Stock-based-compensa', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A711010', N'Freight- Finished goods freightage(Ship)', N'Freight,FG (Ship)', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A711020', N'Freight- Finished goods freightage(Air)', N'Freight,FG (Air)', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A711030', N'Freight- Finished goods freightage(Land)', N'Freight,FG (Land)', N'N/A')
GO
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A711100', N'Freight- Office cost on export', N'Freight,Office Expor', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A711900', N'Freight- Other1', N'Freight,Other1', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A712010', N'Equipment- tools & software expensed- E&T', N'E&T expensed', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A712100', N'Equipment- tools & software expensed- Soft', N'SW expensed', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A714010', N'Utilities exps- Electrical power', N'Electrical power', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A714020', N'Utilities exps- Water charges', N'Water charges', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A722010', N'R&T exps- Recruiting expense', N'Recruiting exp', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A722020', N'R&T exps- Training exps', N'Training exps', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A723010', N'Travelling & commutation- Fare', N'Fare', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A723020', N'Travelling & commutation- Accommodation', N'Accommodation', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A723030', N'Travelling & commutation- vehicle running exp', N'Vehicle running exp', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A723900', N'Travelling & commutation- Other1', N'Trav&commut,Other1', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A725010', N'Commu exps- Postal exps', N'Postal exps', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A725020', N'Commu exps- Network', N'Network', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A725030', N'Commu exps- Cell phone & Land phone', N'Cellphone & Landline', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A725060', N'Commu exps, Global Infra Comm', N'Global Infra Comm', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A725100', N'Commu exps, H/W maintenance', N'H/W maintenance', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A725110', N'Commu exps, S/W maintenance', N'S/W maintenance', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A725900', N'Commu exps, Other1', N'Commu exps,Other1', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A726010', N'Meals and Entmt exps, Meal', N'Meal', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A726010N', N'Meals and Entmt exps, Meal', N'Meal (N)', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A726200', N'Meals and Entmt exps, Gift', N'Gift', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A726200N', N'Meals and Entmt exps- Gift (Non deductible)', N'Gift (ND)', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A726300', N'Meals and Entmt exps, Entmt', N'Entmt', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A731010', N'Insurance exps, Fire premiums on tangible FA', N'Fire prem tangibleFA', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A731900', N'Insurance exps, Other1', N'Insurance Other1', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A731920', N'Insurance exps, Credit insurance', N'Credit insurance', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A732010', N'Repair&maintenance exps, M&Es', N'R&M,M&Es', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A732020', N'Repair&maintenance exps, Bld/LI/struc', N'R&M,Bld/LI/struc', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A732030', N'Repair&maintenance exps- Vehicles', N'R&M-Vehicles', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A732100', N'Repair&maintenance exps- In-company cleaning fee', N'R&M-company cleaning', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A732130', N'Repair&maintenance exps- Security consignment fee', N'R&M-Sec consignment', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A733020', N'Dep, Leasehold impr', N'Dep,Leasehold impr', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A733040', N'Dep, M&Es', N'Dep,M&Es', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A733060', N'Dep, Furniture & fixtures', N'Dep,F&F', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A733070', N'Dep, Vehicles', N'Dep,Vehicles', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A733220', N'Dep- Ext. Software for own use(Amort)', N'Dep,Ext. SWOU(Amort)', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A733300', N'Dep, Lease assets-buildings(Operating)', N'Dep, LA Bldg (Op)', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A733360', N'Dep- Lease assets-vehicles(Amort)', N'Dep, Leased Vehicle', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A733370', N'Dep, Lease assets-Land(Operating)', N'Dep, LA Land (Op)', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A734010', N'Allowance for doubtful debts, General', N'ADA,Gen', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A741010', N'Donation, General', N'Donation,Gen', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A741010N', N'Donation, General (Non deductible)', N'Donation,Gen (ND)', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A742010', N'misc. tax, Consumption tax', N'Consumption tax', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A742100N', N'misc. tax, Non deductible national tax', N'ND national tax', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A742200N', N'misc. tax- Non deductible regional tax', N'Misc tax (N) reg tax', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A743010', N'Storage, Finished goods storage fee', N'FG storage fee', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A743900', N'Storage, Other1', N'Storage,Other1', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A744010', N'misc. exps, membership fee', N'membership fee', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A744020', N'misc. exps, Books & magazines', N'Books & magazines', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A744030', N'misc. exps, Conference exps', N'Conference exps', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A744040', N'misc. exps, Vehicle Expenses', N'Vehicle Expenses', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A744040N', N'misc. exps, Vehicle Expenses (ND)', N'Vehile Expenses(ND)', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A744050', N'misc. exps, Bank commissions', N'Bank commissions', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A744720', N'misc. exps- Other MFC related expenses 2', N'Other MFC 2', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A744800', N'misc. exps, Outgoing recharge', N'Outgo recharge', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A744900', N'misc. exps, Other1', N'misc. exps,Other1', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A745030', N'Rent exps- Company housings', N'Company housings', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A745040', N'Rent exps, Other house rents', N'Other house rents', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A745050', N'Rent exps - Parking lot exps', N'Parking lot exps', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A745070', N'Rent exps, Warehouse exps', N'Warehouse exps', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A745080', N'Rent exps, Vehicles exps', N'Vehicles exps', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A745080N', N'Rent exps, Vehicles exps(ND)', N'Vehicles exps(ND)', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A745090', N'Rent exps, Office rent', N'Office rent', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A745095', N'Rent Exps, Office rent (SysInt)', N'Rent Exps, Office', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A745100', N'Rent exps, Shop rent', N'Rent exps,Shop rent', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A745110', N'Rent Exps- Rental Cars', N'Rent - Rental Cars', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A745115', N'Rent Exps- Rental Cars (SysInt)', N'Rent Exps- Rental Ca', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A745800', N'Rent exps, Outgoing recharge', N'Rent,Outgo recharge', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A745900', N'Rent exps, Other1', N'Rent exps,Other1', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A748010', N'Prof service fee, CPA Audit fee', N'CPA Audit fee', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A748020', N'Prof service fee, Temp staff service fee (agency)', N'Temp staff agency fe', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A748030', N'Prof service fee, Legal Services', N'Legal Services', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A748040', N'Prof service fee, IS consultant fees', N'IS consultant fees', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A748050', N'Prof service fee, Other consultant fees', N'O.consultant fees', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A748060', N'Prof service fee, Market research', N'Market research', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A748090', N'Prof service fee, Business Process Outsourcing', N'BPO', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A748900', N'Prof service fee- Other1', N'Prof serv Other1', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A749020', N'Dep(ARO)- L/h impr', N'Dep(ARO),L/h impr', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A749101', N'Dep(ARO)- Lease assets-build.(Finance)', N'Dep(ARO), Lease(Fi)', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A750000', N'IS Service Fee- Global Data Svc Charge', N'Global Data Svc Chge', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A750001', N'IS Service Fee- Global Infra Comm', N'Global Infra Comm', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A750010', N'IS Service Fee- H/W maintenance', N'H/W maintenance', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A750011', N'IS Service Fee- S/W maintenance', N'S/W maintenance', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A750020', N'IS Service Fee- Network', N'IS Service Fee- Netw', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A750900', N'IS Service Fee- Other', N'IS Service Fee- Othe', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A771010', N'AD&Pro exps, Media expenses, Newspaper', N'Media exps,Newspaper', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A771030', N'AD&Pro exps, Media expenses, Radio', N'Media exps,Radio', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A771040', N'AD&Pro exps, Media, Outdoor/Transit advertising', N'Media,OutdoorTransit', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A771070', N'AD&Pro exps, Media, Internet (Search Engine Mkt)', N'Internet(SearchEngin', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A771090', N'AD&Pro exps- Media expenses- Internet others', N'Internet others', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A771090N', N'AD&Pro exps-Key Opinion leader (influenc', N'Key Opinion leader', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A771100', N'AD&Pro exps, Contents Creation for Media', N'CC for Media', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A771100N', N'AD&Pro exps-Maintenance, repair', N'A&P,Maintenance,rep', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A771101', N'AD&pro exps – TV production', N'TV Production', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A771105', N'AD&pro exps – Press production', N'Press Production', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A771106', N'AD&pro exps – Digital production', N'Digital Production', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A771110', N'AD&Pro exps, Sponsorship', N'Sponsorship', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A771111', N'AD&Pro exps- Dealer Support', N'Dealer Support', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A771200', N'AD&Pro exps- Promoter expenses', N'Promoter expenses', N'N/A')
GO
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A771210', N'AD&Pro exps, Event&Exhibition', N'Event&Exhibition', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A771210N', N'AD&Pro exps-Product Seminar / Workshops', N'Seminar/WkshpOnline', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A771211', N'AD&Pro exps- PR & Press Events', N'PR & Press Event', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A771220', N'AD&Pro exps, Others, Sample', N'AD&Pro exps,Sample', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A771220N', N'AD&Pro exps- Dealer convention', N'Dealer convention', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A771230', N'AD&Pro exps, Others, Give Away', N'Give Away', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A771230N', N'AD&Pro exps-Product Seminar / Workshops', N'Seminar/WkshpOffline', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A771240', N'AD&Pro exps, Incentive Trips/Training', N'IncentivTrip/Traini', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A771300', N'AD&Pro exps, Shop front communication, POP', N'Shop front,POP', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A771310', N'AD&Pro exps, Shop front communication, Catalog', N'Shop front,Catalog', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A771320', N'AD&Pro exps, Shop front communication, Fixture', N'Shop front,Fixture', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A771330', N'AD&Pro exps, Shop Fixtures/Renovation', N'Shop Fixtures/Renov', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A771400', N'AD&Pro exps- Market research', N'AD&Pro exps-Mkt Res', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A771410', N'AD&Pro exps-Promotor Incentives', N'Promotor Incentives', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A771420', N'AD&Pro exps-Media,eCommence Shopping/Mar', N'Media,eCom,Shp/Mkt', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A771430', N'AD&Pro exps, CRM', N'AD&Pro exps, CRM', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A771440', N'AD&Pro exps-Field Force/Visual Merchandi', N'Field Force/Merch', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A771450', N'AD&Pro exps-Promotor Related Cost', N'Promotor Rel Cost', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A771900', N'AD&Pro, General/Strategic marketing/Other expenses', N'Gen/Strat Mktg/O Ex', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A771950', N'AD&Pro exps, Warehousing and Transportation', N'Warehousing&Transpo', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A774010', N'Sales commission, General', N'Sales commission,Gen', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A774030', N'Commission-eCommerce', N'Sales commissn,eCom', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A775010', N'Service, Inwarranty, exchange', N'Service,IW,exchange', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A775020', N'Service, Inwarranty, other', N'Service,IW,other', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A775030', N'Service, Inwarranty, parts', N'Service, IW,parts', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A775100', N'Service- Outwarranty', N'Service,Outwarranty', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A775710', N'Service, Contact Center Outsourcing', N'Service,Contact.C OS', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A775810', N'Service, Prov for product warranties (accrual)', N'Service,Prov(accrual', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A775840', N'Service, RMA Reimbursement', N'Service, RMA Reimb', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A775900', N'Service, Other1', N'Service,Other1', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A778010', N'Tax & Levies General', N'Tax & Levies General', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A780010', N'OGE, Gain on disposal of PP&E', N'OGE,GOD of PP&E', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A780030', N'OGE, Loss on disposal of PP&E', N'OGE,LOD of PP&E', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A780091', N'OGE/Gain relate to Lease contract modification', N'OGE/Gain Lease Cont', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A780092', N'OGE/Loss relate to Lease contract modification', N'OGE/Loss Lease Cont', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A901000', N'Purchase merchandise', N'Purchase merchandise', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A921900', N'Internal purchase', N'Internal purchase', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A923100', N'Interim account, GL', N'Interim account,GL', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A923110', N'Interim asset dispos', N'Interim asset dispos', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A999994', N'Clearing account, FIXED ASSET Migration', N'Clr - FA migration', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A999995', N'Clearing account- GL CONVERSION', N'GL CONVERSION', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A999996', N'Clearing account, AR OPEN ITEM CONVERSION', N'AR OPEN ITEM CONVERS', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A999997', N'Clearing account, AP OPEN ITEM CONVERSION', N'AP OPEN ITEM CONVERS', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A999999', N'Clearing account- FIXED ASSET CONVERSION', N'FIXED ASSET CONVERS', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A014194', N'Emirates NBD - NC1 (incoming)', N'I Clr Emirates - NC1', N'#N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A089030', N'Other misc. current assets, Time deposits', N'OCA,Time deposits', N'#N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A089093', N'OCA- LVA Supply Direct GL', N'OCA- LVA Supply DGL', N'#N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A144010', N'Valuation allowance-non-curr- National tax', N'VA-National tax', N'#N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A159050', N'Other non-curr assets, deposit', N'Oth NC Asset,Deposit', N'#N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A159070', N'Other non-curr assets- Cash Restricted', N'ONCA-Cash Restricted', N'#N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A215194', N'Emirates NBD - NC1 (outgoing)', N'O Clr Emirates - NC1', N'#N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A216901', N'Accrd exps, EDP', N'AE,Other2', N'#N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A224010', N'Dividends payable, General', N'Dividend payable,Gen', N'#N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A443090', N'Controlling Interest - Dividend paid', N'CI - Dividend paid', N'#N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A631040', N'NOR- Dividend earned', N'NOR,Dividend earned', N'#N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A704300R', N'Retirement bnf exps- Termination(Restructuring)', N'Termination', N'#N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A745035', N'Rent Exps- Company housings (SysInt)', N'Rent Exps- Company', N'#N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A771104', N'AD&pro exps – Billboard production', N'Billboard Production', N'#N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A771130', N'AD&Pro exps- Allocation', N'AD&Pro exps,Alloc', N'#N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A012002', N'Cash on Hand - USD', N'Cash on Hand - USD', N'#N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A039020', N'Allowance for doubtful debts, Specific', N'ADA,Specific', N'#N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A212850', N'Trade AP, direct GL entry, OIM', N'T AP,D GL entry, OIM', N'#N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A231400', N'Income tax payable- Reserve for UTP', N'ITP-Reserv', N'#N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A248010', N'Current portion of LT debts (Op Lease)', N'Curr por,LT debts-Op', N'#N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A542400', N'Current income tax expense- Additional (national)', N'CIT,Addit(national)', N'#N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A722020R', N'R&T exps- Training exps (Restructuring)', N'Training exps', N'#N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A744900N', N'misc. exps- Other1 (Non deductible)', N'misc.exps-Other1(ND)', N'#N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A771800', N'AD&Pro exps- Outgoing recharge', N'Outgo recharge', N'#N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A780040', N'OGE- Loss on disposal of intangibles', N'OGE, LOD of intangib', N'#N/A')
GO
