USE [DIVA_US00_FY21_22_23]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[AM_AR_CLEARING](
	[ZF_ACCOUNTS] [nvarchar](255) NULL,
	[SKAT_TXT50] [nvarchar](255) NULL,
	[SKAT_TXT20] [nvarchar](255) NULL,
	[ZF_AR_CLEARING] [nvarchar](255) NULL
) ON [PRIMARY]
GO
INSERT [dbo].[AM_AR_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_CLEARING]) VALUES (N'A012196', N'Barclays Bank - NC', N'Barclays Bank - NC', N'N/A')
INSERT [dbo].[AM_AR_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_CLEARING]) VALUES (N'A012197', N'Barclays Bank - USD', N'Barclays Bank - USD', N'N/A')
INSERT [dbo].[AM_AR_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_CLEARING]) VALUES (N'A014100', N'Citibank - National Currency (incoming)', N'I Clr Citibank - NC', N'x')
INSERT [dbo].[AM_AR_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_CLEARING]) VALUES (N'A014101', N'Citibank - USD (incoming)', N'I Clr Citibank - USD', N'x')
INSERT [dbo].[AM_AR_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_CLEARING]) VALUES (N'A014103', N'Citibank - EUR (incoming)', N'I Clr Citibank - EUR', N'x')
INSERT [dbo].[AM_AR_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_CLEARING]) VALUES (N'A014105', N'HSBC - National Currency (incoming)', N'I Clr HSBC - NC', N'x')
INSERT [dbo].[AM_AR_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_CLEARING]) VALUES (N'A014106', N'HSBC - USD (incoming)', N'I Clr HSBC - USD', N'x')
INSERT [dbo].[AM_AR_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_CLEARING]) VALUES (N'A014109', N'HSBC - National curr 2 (incoming)', N'HSBC - National curr', N'x')
INSERT [dbo].[AM_AR_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_CLEARING]) VALUES (N'A014110', N'HSBC - ANZ National curr 3 (incoming)', N'I Clr HSBC - NC3', N'x')
INSERT [dbo].[AM_AR_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_CLEARING]) VALUES (N'A014135', N'BPI - PH NC2 (incoming)', N'I Clr, BPI - PH NC2', N'x')
INSERT [dbo].[AM_AR_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_CLEARING]) VALUES (N'A014138', N'BDO - PH National Curr 2 (incoming)', N'I Clr BDO - PH NC2', N'x')
INSERT [dbo].[AM_AR_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_CLEARING]) VALUES (N'A014140', N'BCA - National currency (incoming)', N'I Clr BCA - NC', N'x')
INSERT [dbo].[AM_AR_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_CLEARING]) VALUES (N'A014141', N'BCA - National currency 1 (incoming)', N'I Clr BCA - NC 1', N'x')
INSERT [dbo].[AM_AR_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_CLEARING]) VALUES (N'A014156', N'BBL - National Currency incoming', N'I Clr BBL - NC', N'x')
INSERT [dbo].[AM_AR_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_CLEARING]) VALUES (N'A014159', N'Kasikorn Bank - National Currency incoming', N'I Clr Kbank - NC', N'x')
INSERT [dbo].[AM_AR_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_CLEARING]) VALUES (N'A014162', N'SIAM COMMERCIAL BANK - NC incoming', N'I Clr Siam CB - NC', N'x')
INSERT [dbo].[AM_AR_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_CLEARING]) VALUES (N'A014163', N'SIAM COMMERCIAL BANK - NC1 incoming', N'I Clr Siam CB - NC1', N'x')
INSERT [dbo].[AM_AR_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_CLEARING]) VALUES (N'A014166', N'Krungthai Bank - National Currency incoming', N'I Clr Krungthai Bank', N'x')
INSERT [dbo].[AM_AR_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_CLEARING]) VALUES (N'A014182', N'Robinson Bank - NC (incoming)', N'I Clr, Robinson - NC', N'x')
INSERT [dbo].[AM_AR_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_CLEARING]) VALUES (N'A014193', N'Emirates NBD - NC (incoming)', N'I Clr Emirates - NC', N'x')
INSERT [dbo].[AM_AR_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_CLEARING]) VALUES (N'A014195', N'Emirates NBD - USD (incoming)', N'I Clr Emirates - USD', N'x')
INSERT [dbo].[AM_AR_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_CLEARING]) VALUES (N'A014209', N'Citibank - ZAR (Incoming)', N'I Clr Citibank - ZAR', N'x')
INSERT [dbo].[AM_AR_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_CLEARING]) VALUES (N'A014307', N'Incoming Clearing- RAS ACCOUNT USD', N'I Clr, RAS USD', N'x')
INSERT [dbo].[AM_AR_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_CLEARING]) VALUES (N'A014316', N'Incoming Clearing- RAS ACCOUNT AUD', N'I Clr, RAS AUD', N'x')
INSERT [dbo].[AM_AR_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_CLEARING]) VALUES (N'A014318', N'Incoming Clearing- RAS ACCOUNT NZD', N'I Clr, RAS NZD', N'x')
INSERT [dbo].[AM_AR_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_CLEARING]) VALUES (N'A021015', N'Products- Merchandise & FG- direct GL entry OIM', N'M&FG,D GL,OIM', N'N/A')
INSERT [dbo].[AM_AR_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_CLEARING]) VALUES (N'A021030', N'Products, Merchandise & FG, In transit', N'M&FG,In transit', N'N/A')
INSERT [dbo].[AM_AR_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_CLEARING]) VALUES (N'A024020', N'WIP, direct GL entry – System service', N'WIP-D GL-sys ser', N'N/A')
INSERT [dbo].[AM_AR_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_CLEARING]) VALUES (N'A032850', N'Other AR-current- direct GL entry- OIM', N'OtherAR-D GL ent-OIM', N'N/A')
INSERT [dbo].[AM_AR_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_CLEARING]) VALUES (N'A035900', N'Expense to be recharged, Other1', N'Exp to be rec,Other1', N'N/A')
INSERT [dbo].[AM_AR_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_CLEARING]) VALUES (N'A037010', N'Accrd income, General', N'Accrd income,Gen', N'N/A')
INSERT [dbo].[AM_AR_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_CLEARING]) VALUES (N'A038010', N'VAT-receivable on purchase, general', N'VAT-R on purch,gen', N'N/A')
INSERT [dbo].[AM_AR_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_CLEARING]) VALUES (N'A038460', N'Vat-Receivable (Clearing)TH', N'Vat-Recl TH', N'N/A')
INSERT [dbo].[AM_AR_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_CLEARING]) VALUES (N'A089010', N'Other misc. current assets, General', N'OCA,Gen', N'N/A')
INSERT [dbo].[AM_AR_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_CLEARING]) VALUES (N'A089100', N'OCA - Withholding tax – receivable', N'OCA,WHT-receivable', N'N/A')
INSERT [dbo].[AM_AR_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_CLEARING]) VALUES (N'A176010', N'Prepaid Income Tax - Non current', N'Prepaid I.T - NC', N'N/A')
INSERT [dbo].[AM_AR_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_CLEARING]) VALUES (N'A215105', N'HSBC - National Currency (outgoing)', N'O Clr HSBC - NC', N'N/A')
INSERT [dbo].[AM_AR_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_CLEARING]) VALUES (N'A215109', N'HSBC - National curr 2 (outgoing)', N'HSBC - National curr', N'N/A')
INSERT [dbo].[AM_AR_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_CLEARING]) VALUES (N'A215159', N'Kasikorn Bank - National Currency outgoing', N'O Clr Kbank - NC', N'N/A')
INSERT [dbo].[AM_AR_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_CLEARING]) VALUES (N'A215851', N'Other AP-non trade-Doc Splitting Account', N'Oth AP-NT Doc Split', N'N/A')
INSERT [dbo].[AM_AR_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_CLEARING]) VALUES (N'A216100', N'Provision for Activity Based Co-Op A&P', N'Accrd Co-op AD(MDF)1', N'N/A')
INSERT [dbo].[AM_AR_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_CLEARING]) VALUES (N'A216101', N'Provision for Co Op A&P - General', N'Accrd Co-op AD(MDF)2', N'N/A')
INSERT [dbo].[AM_AR_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_CLEARING]) VALUES (N'A216140', N'Accrd exps, SR, Stock Compensation (Activity)', N'Accrd Stock Comp1', N'N/A')
INSERT [dbo].[AM_AR_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_CLEARING]) VALUES (N'A216164', N'Accrd exps, SR, Sell Thru/Promo Rebate (Activity)', N'Accrd SR, STR PR Act', N'N/A')
INSERT [dbo].[AM_AR_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_CLEARING]) VALUES (N'A216165', N'Accrd exps, SR, Sell Thru/Promo Rebate (General)', N'Accrd SR, STR PR Gen', N'N/A')
INSERT [dbo].[AM_AR_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_CLEARING]) VALUES (N'A216180', N'Accrd exps, SR, Sell-in allowance(Activity)', N'Accrd SR, SIA Act', N'N/A')
INSERT [dbo].[AM_AR_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_CLEARING]) VALUES (N'A216230', N'Accrd exps, SR, Other manual price adj', N'ASR,O.man price adj', N'N/A')
INSERT [dbo].[AM_AR_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_CLEARING]) VALUES (N'A216310', N'Accrd exps, Salaries & Wages', N'AE,Salaries & Wages', N'N/A')
INSERT [dbo].[AM_AR_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_CLEARING]) VALUES (N'A216900', N'Accrd exps, Other1', N'AE,Other1', N'N/A')
INSERT [dbo].[AM_AR_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_CLEARING]) VALUES (N'A216902', N'Accrued exps - SGA Other', N'AE,Other3', N'N/A')
INSERT [dbo].[AM_AR_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_CLEARING]) VALUES (N'A220010', N'Tax payable on sales, General', N'Tax-P on sales,Gen', N'N/A')
INSERT [dbo].[AM_AR_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_CLEARING]) VALUES (N'A226010', N'Deferred revenue-current, General', N'Def rev,Gen', N'N/A')
INSERT [dbo].[AM_AR_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_CLEARING]) VALUES (N'A232900', N'Accrued other taxes, Other1', N'AOT,Other1', N'N/A')
INSERT [dbo].[AM_AR_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_CLEARING]) VALUES (N'A273020', N'Other misc. CL-Deposits1', N'O.misc.CL.Deposits1', N'N/A')
INSERT [dbo].[AM_AR_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_CLEARING]) VALUES (N'A505010', N'COGS- Products', N'COGS,Products', N'N/A')
INSERT [dbo].[AM_AR_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_CLEARING]) VALUES (N'A505030', N'COGS- Other', N'COGS,Other', N'N/A')
INSERT [dbo].[AM_AR_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_CLEARING]) VALUES (N'A531010', N'NOE- Interest on borrowing', N'Inter on borrowing', N'N/A')
INSERT [dbo].[AM_AR_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_CLEARING]) VALUES (N'A531400', N'NOE- FX Translation losses', N'NOE,FX Trans losses', N'N/A')
INSERT [dbo].[AM_AR_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_CLEARING]) VALUES (N'A531900', N'NOE- Other1', N'NOE,Other1', N'N/A')
INSERT [dbo].[AM_AR_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_CLEARING]) VALUES (N'A621010', N'Gross Sales- Products', N'Gross Sales,Products', N'N/A')
INSERT [dbo].[AM_AR_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_CLEARING]) VALUES (N'A621050', N'Gross Sales- Service & Repair', N'G sales,Service&Repa', N'N/A')
INSERT [dbo].[AM_AR_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_CLEARING]) VALUES (N'A621055', N'Gross Sales - Spare Parts', N'Gross Sales - SP', N'N/A')
INSERT [dbo].[AM_AR_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_CLEARING]) VALUES (N'A621900', N'Gross Sales- Other1', N'Gross Sales,Other1', N'N/A')
INSERT [dbo].[AM_AR_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_CLEARING]) VALUES (N'A622110', N'Sales reduction, On-invoice discount Merchandise', N'SR,OID Merchandise', N'N/A')
INSERT [dbo].[AM_AR_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_CLEARING]) VALUES (N'A622210', N'Sales reduction, Co-op AD(Activity)', N'SR,Co-op AD (Act)', N'N/A')
INSERT [dbo].[AM_AR_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_CLEARING]) VALUES (N'A622310', N'Sales reduction, Stock Compensation(Activity)', N'SR,Stock Comp (Act)', N'N/A')
INSERT [dbo].[AM_AR_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_CLEARING]) VALUES (N'A622421', N'Sales Reduction - Cashback (Activity)', N'SR, Cashback (Act)', N'N/A')
INSERT [dbo].[AM_AR_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_CLEARING]) VALUES (N'A622424', N'Sales reduction, Sell Thru/Promo Rebate (Activity)', N'SR, STR (Act)', N'N/A')
INSERT [dbo].[AM_AR_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_CLEARING]) VALUES (N'A622430', N'Sales reduction, Sell-in allowance (Activity)', N'SR,SIA (Act)', N'N/A')
INSERT [dbo].[AM_AR_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_CLEARING]) VALUES (N'A622620', N'Sales reduction, Other manual price adj', N'SR,O.manual adj', N'N/A')
INSERT [dbo].[AM_AR_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_CLEARING]) VALUES (N'A625900', N'OPR- Other1', N'OPR,Other1', N'N/A')
INSERT [dbo].[AM_AR_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_CLEARING]) VALUES (N'A631030', N'NOR- Other interest income', N'NOR- Other interest', N'N/A')
INSERT [dbo].[AM_AR_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_CLEARING]) VALUES (N'A631300', N'NOR- FX Translation gain', N'NOR,FX Trans gain', N'N/A')
INSERT [dbo].[AM_AR_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_CLEARING]) VALUES (N'A631900', N'NOR- Other1', N'NOR,Other1', N'N/A')
INSERT [dbo].[AM_AR_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_CLEARING]) VALUES (N'A702010', N'S&W- Base salaries', N'S&W,Base salaries', N'N/A')
INSERT [dbo].[AM_AR_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_CLEARING]) VALUES (N'A711020', N'Freight- Finished goods freightage(Air)', N'Freight,FG (Air)', N'N/A')
INSERT [dbo].[AM_AR_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_CLEARING]) VALUES (N'A711030', N'Freight- Finished goods freightage(Land)', N'Freight,FG (Land)', N'N/A')
INSERT [dbo].[AM_AR_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_CLEARING]) VALUES (N'A711100', N'Freight- Office cost on export', N'Freight,Office Expor', N'N/A')
INSERT [dbo].[AM_AR_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_CLEARING]) VALUES (N'A711900', N'Freight- Other1', N'Freight,Other1', N'N/A')
INSERT [dbo].[AM_AR_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_CLEARING]) VALUES (N'A744050', N'misc. exps, Bank commissions', N'Bank commissions', N'N/A')
INSERT [dbo].[AM_AR_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_CLEARING]) VALUES (N'A748020', N'Prof service fee, Temp staff service fee (agency)', N'Temp staff agency fe', N'N/A')
INSERT [dbo].[AM_AR_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_CLEARING]) VALUES (N'A771090N', N'AD&Pro exps-Key Opinion leader (influenc', N'Key Opinion leader', N'N/A')
INSERT [dbo].[AM_AR_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_CLEARING]) VALUES (N'A774010', N'Sales commission, General', N'Sales commission,Gen', N'N/A')
INSERT [dbo].[AM_AR_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_CLEARING]) VALUES (N'A774030', N'Commission-eCommerce', N'Sales commissn,eCom', N'N/A')
INSERT [dbo].[AM_AR_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_CLEARING]) VALUES (N'A775010', N'Service, Inwarranty, exchange', N'Service,IW,exchange', N'N/A')
INSERT [dbo].[AM_AR_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_CLEARING]) VALUES (N'A775020', N'Service, Inwarranty, other', N'Service,IW,other', N'N/A')
INSERT [dbo].[AM_AR_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_CLEARING]) VALUES (N'A775030', N'Service, Inwarranty, parts', N'Service, IW,parts', N'N/A')
INSERT [dbo].[AM_AR_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_CLEARING]) VALUES (N'A775100', N'Service- Outwarranty', N'Service,Outwarranty', N'N/A')
INSERT [dbo].[AM_AR_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_CLEARING]) VALUES (N'A775900', N'Service, Other1', N'Service,Other1', N'N/A')
INSERT [dbo].[AM_AR_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_CLEARING]) VALUES (N'A923100', N'Interim account, GL', N'Interim account,GL', N'N/A')
INSERT [dbo].[AM_AR_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_CLEARING]) VALUES (N'A923110', N'Interim asset dispos', N'Interim asset dispos', N'N/A')
INSERT [dbo].[AM_AR_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_CLEARING]) VALUES (N'A062010', N'Contract assets- rights to recover goods', N'Rights to recover go', N'#N/A')
INSERT [dbo].[AM_AR_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_CLEARING]) VALUES (N'A215100', N'Citibank - National Currency (outgoing)', N'O Clr Citibank - NC', N'#N/A')
INSERT [dbo].[AM_AR_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_CLEARING]) VALUES (N'A215318', N'Outgoing Clearing- RAS ACCOUNT NZD', N'O Clr, RAS NZD', N'#N/A')
INSERT [dbo].[AM_AR_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_CLEARING]) VALUES (N'A215321', N'Outgoing Clearing- RAS ACCOUNT THB', N'O Clr, RAS THB', N'#N/A')
INSERT [dbo].[AM_AR_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_CLEARING]) VALUES (N'A229010', N'Reserve for warranty, General', N'Reserve for warranty', N'#N/A')
INSERT [dbo].[AM_AR_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_CLEARING]) VALUES (N'A505410N', N'COGS- Special loss on disposal of inventories (N)', N'COGS- Sp.Loss (N)', N'#N/A')
INSERT [dbo].[AM_AR_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_CLEARING]) VALUES (N'A744800', N'misc. exps, Outgoing recharge', N'Outgo recharge', N'#N/A')
INSERT [dbo].[AM_AR_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_CLEARING]) VALUES (N'A748050', N'Prof service fee, Other consultant fees', N'O.consultant fees', N'#N/A')
INSERT [dbo].[AM_AR_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_CLEARING]) VALUES (N'A771330', N'AD&Pro exps, Shop Fixtures/Renovation', N'Shop Fixtures/Renov', N'#N/A')
GO
INSERT [dbo].[AM_AR_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_CLEARING]) VALUES (N'A771440', N'AD&Pro exps-Field Force/Visual Merchandi', N'Field Force/Merch', N'#N/A')
INSERT [dbo].[AM_AR_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_CLEARING]) VALUES (N'A012001', N'Cash on Hand - National Currency', N'Cash on Hand - NC', N'#N/A')
INSERT [dbo].[AM_AR_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_CLEARING]) VALUES (N'A012105', N'HSBC - National Currency', N'HSBC - NC', N'#N/A')
INSERT [dbo].[AM_AR_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_CLEARING]) VALUES (N'A226060', N'Deferred revenue-current, Voucher', N'Def rev,Voucher', N'#N/A')
INSERT [dbo].[AM_AR_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_CLEARING]) VALUES (N'A734010', N'Allowance for doubtful debts, General', N'ADA,Gen', N'#N/A')
INSERT [dbo].[AM_AR_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_CLEARING]) VALUES (N'A744900', N'misc. exps, Other1', N'misc. exps,Other1', N'#N/A')
INSERT [dbo].[AM_AR_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_CLEARING]) VALUES (N'A771090', N'AD&Pro exps- Media expenses- Internet others', N'Internet others', N'#N/A')
INSERT [dbo].[AM_AR_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_CLEARING]) VALUES (N'A771220', N'AD&Pro exps, Others, Sample', N'AD&Pro exps,Sample', N'#N/A')
GO
