USE [DIVA_US00_FY21_22_23]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[AM_DSM](
	[DSM_DIVISION] [varchar](50) NULL,
	[DSM_DESCRIPTION] [varchar](100) NULL,
	[DSM_BUSINESS_SEGMENT] [varchar](100) NULL
) ON [PRIMARY]
GO
