USE [DIVA_US00_FY21_22_23]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[AM_VAT_CLF](
	[ACCOUNT] [nvarchar](255) NULL,
	[GL TEXT] [nvarchar](255) NULL,
	[CLASSIFICATION] [nvarchar](255) NULL
) ON [PRIMARY]
GO
INSERT [dbo].[AM_VAT_CLF] ([ACCOUNT], [GL TEXT], [CLASSIFICATION]) VALUES (N'A038010', N'VAT-R on purch,gen', N'VAT on purchases')
INSERT [dbo].[AM_VAT_CLF] ([ACCOUNT], [GL TEXT], [CLASSIFICATION]) VALUES (N'A056010', N'DTA,National tax', N'VAT on purchases')
INSERT [dbo].[AM_VAT_CLF] ([ACCOUNT], [GL TEXT], [CLASSIFICATION]) VALUES (N'A215851', N'Oth AP-NT Doc Split', N'VAT on purchases')
INSERT [dbo].[AM_VAT_CLF] ([ACCOUNT], [GL TEXT], [CLASSIFICATION]) VALUES (N'A220010', N'Tax-P on sales,Gen', N'VAT on sales')
INSERT [dbo].[AM_VAT_CLF] ([ACCOUNT], [GL TEXT], [CLASSIFICATION]) VALUES (N'A220020', N'Tax-P on sales-D GL', N'VAT on sales')
INSERT [dbo].[AM_VAT_CLF] ([ACCOUNT], [GL TEXT], [CLASSIFICATION]) VALUES (N'A220100', N'Tax-P,VAT O.tax', N'VAT on sales')
INSERT [dbo].[AM_VAT_CLF] ([ACCOUNT], [GL TEXT], [CLASSIFICATION]) VALUES (N'A014010', N'T AR-Gen', N'')
INSERT [dbo].[AM_VAT_CLF] ([ACCOUNT], [GL TEXT], [CLASSIFICATION]) VALUES (N'A038360', N'VAT-R clr CA', N'')
INSERT [dbo].[AM_VAT_CLF] ([ACCOUNT], [GL TEXT], [CLASSIFICATION]) VALUES (N'A038361', N'VAT-R clr CA RITC', N'')
INSERT [dbo].[AM_VAT_CLF] ([ACCOUNT], [GL TEXT], [CLASSIFICATION]) VALUES (N'A038362', N'VAT-R clr CA ITC', N'')
INSERT [dbo].[AM_VAT_CLF] ([ACCOUNT], [GL TEXT], [CLASSIFICATION]) VALUES (N'A212010', N'T AP-Gen', N'')
INSERT [dbo].[AM_VAT_CLF] ([ACCOUNT], [GL TEXT], [CLASSIFICATION]) VALUES (N'A212100', N'T AP- GRIR 1', N'')
INSERT [dbo].[AM_VAT_CLF] ([ACCOUNT], [GL TEXT], [CLASSIFICATION]) VALUES (N'A232110', N'AOT-use tax(US only)', N'')
GO
