USE [DIVA_SEV_FY2023]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[AM_GL_BANK_ACC](
	[GL_BANK_ACC_MANDT] [nvarchar](5) NULL,
	[GL_BANK_ACC_BUKRS] [nvarchar](6) NULL,
	[GL_BANK_ACC_HKONT] [nvarchar](12) NULL,
	[GL_BANK_TEXT1] [varchar](1) NOT NULL
) ON [PRIMARY]
GO
INSERT [dbo].[AM_GL_BANK_ACC] ([GL_BANK_ACC_MANDT], [GL_BANK_ACC_BUKRS], [GL_BANK_ACC_HKONT], [GL_BANK_TEXT1]) VALUES (N'888', N'VN00', N'A012100', N'')
INSERT [dbo].[AM_GL_BANK_ACC] ([GL_BANK_ACC_MANDT], [GL_BANK_ACC_BUKRS], [GL_BANK_ACC_HKONT], [GL_BANK_TEXT1]) VALUES (N'888', N'VN00', N'A012101', N'')
INSERT [dbo].[AM_GL_BANK_ACC] ([GL_BANK_ACC_MANDT], [GL_BANK_ACC_BUKRS], [GL_BANK_ACC_HKONT], [GL_BANK_TEXT1]) VALUES (N'888', N'VN00', N'A012105', N'')
INSERT [dbo].[AM_GL_BANK_ACC] ([GL_BANK_ACC_MANDT], [GL_BANK_ACC_BUKRS], [GL_BANK_ACC_HKONT], [GL_BANK_TEXT1]) VALUES (N'888', N'VN00', N'A012106', N'')
INSERT [dbo].[AM_GL_BANK_ACC] ([GL_BANK_ACC_MANDT], [GL_BANK_ACC_BUKRS], [GL_BANK_ACC_HKONT], [GL_BANK_TEXT1]) VALUES (N'888', N'VN00', N'A012114', N'')
INSERT [dbo].[AM_GL_BANK_ACC] ([GL_BANK_ACC_MANDT], [GL_BANK_ACC_BUKRS], [GL_BANK_ACC_HKONT], [GL_BANK_TEXT1]) VALUES (N'888', N'VN00', N'A012132', N'')
INSERT [dbo].[AM_GL_BANK_ACC] ([GL_BANK_ACC_MANDT], [GL_BANK_ACC_BUKRS], [GL_BANK_ACC_HKONT], [GL_BANK_TEXT1]) VALUES (N'888', N'VN00', N'A012133', N'')
GO
