USE [DIVA_SEV_FY2023]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[AM_EXCHNG](
	[EXCHNG_FROM] [varchar](3) NOT NULL,
	[EXCHNG_TO] [nvarchar](3) NOT NULL,
	[EXCHNG_RATIO] [float] NULL,
	[EXCHNG_SOURCE] [nvarchar](max) NULL,
 CONSTRAINT [PK_AM_EXCHANGE] PRIMARY KEY CLUSTERED 
(
	[EXCHNG_FROM] ASC,
	[EXCHNG_TO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
INSERT [dbo].[AM_EXCHNG] ([EXCHNG_FROM], [EXCHNG_TO], [EXCHNG_RATIO], [EXCHNG_SOURCE]) VALUES (N'AED', N'USD', NULL, NULL)
INSERT [dbo].[AM_EXCHNG] ([EXCHNG_FROM], [EXCHNG_TO], [EXCHNG_RATIO], [EXCHNG_SOURCE]) VALUES (N'AUD', N'USD', NULL, NULL)
INSERT [dbo].[AM_EXCHNG] ([EXCHNG_FROM], [EXCHNG_TO], [EXCHNG_RATIO], [EXCHNG_SOURCE]) VALUES (N'EUR', N'USD', NULL, NULL)
INSERT [dbo].[AM_EXCHNG] ([EXCHNG_FROM], [EXCHNG_TO], [EXCHNG_RATIO], [EXCHNG_SOURCE]) VALUES (N'GBP', N'USD', NULL, NULL)
INSERT [dbo].[AM_EXCHNG] ([EXCHNG_FROM], [EXCHNG_TO], [EXCHNG_RATIO], [EXCHNG_SOURCE]) VALUES (N'IDR', N'USD', NULL, NULL)
INSERT [dbo].[AM_EXCHNG] ([EXCHNG_FROM], [EXCHNG_TO], [EXCHNG_RATIO], [EXCHNG_SOURCE]) VALUES (N'JPY', N'USD', NULL, NULL)
INSERT [dbo].[AM_EXCHNG] ([EXCHNG_FROM], [EXCHNG_TO], [EXCHNG_RATIO], [EXCHNG_SOURCE]) VALUES (N'KWD', N'USD', NULL, NULL)
INSERT [dbo].[AM_EXCHNG] ([EXCHNG_FROM], [EXCHNG_TO], [EXCHNG_RATIO], [EXCHNG_SOURCE]) VALUES (N'MAD', N'USD', NULL, NULL)
INSERT [dbo].[AM_EXCHNG] ([EXCHNG_FROM], [EXCHNG_TO], [EXCHNG_RATIO], [EXCHNG_SOURCE]) VALUES (N'NZD', N'USD', NULL, NULL)
INSERT [dbo].[AM_EXCHNG] ([EXCHNG_FROM], [EXCHNG_TO], [EXCHNG_RATIO], [EXCHNG_SOURCE]) VALUES (N'PHP', N'USD', NULL, NULL)
INSERT [dbo].[AM_EXCHNG] ([EXCHNG_FROM], [EXCHNG_TO], [EXCHNG_RATIO], [EXCHNG_SOURCE]) VALUES (N'SGD', N'USD', NULL, NULL)
INSERT [dbo].[AM_EXCHNG] ([EXCHNG_FROM], [EXCHNG_TO], [EXCHNG_RATIO], [EXCHNG_SOURCE]) VALUES (N'THB', N'USD', NULL, NULL)
INSERT [dbo].[AM_EXCHNG] ([EXCHNG_FROM], [EXCHNG_TO], [EXCHNG_RATIO], [EXCHNG_SOURCE]) VALUES (N'USD', N'USD', NULL, NULL)
INSERT [dbo].[AM_EXCHNG] ([EXCHNG_FROM], [EXCHNG_TO], [EXCHNG_RATIO], [EXCHNG_SOURCE]) VALUES (N'VND', N'USD', NULL, NULL)
INSERT [dbo].[AM_EXCHNG] ([EXCHNG_FROM], [EXCHNG_TO], [EXCHNG_RATIO], [EXCHNG_SOURCE]) VALUES (N'ZAR', N'USD', NULL, NULL)
GO
