USE [DIVA_SEV_FY2023]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[AM_SCOPE](
	[SCOPE_MANDANT] [nvarchar](100) NULL,
	[SCOPE_CMPNY_CODE] [nvarchar](100) NULL,
	[SCOPE_BUSINESS_DMN_L1] [nvarchar](100) NULL,
	[SCOPE_BUSINESS_DMN_L2] [nvarchar](100) NULL,
	[SCOPE_SYSTEM] [nvarchar](100) NULL,
	[ZF_REGION_FLAG] [varchar](4) NOT NULL
) ON [PRIMARY]
GO
INSERT [dbo].[AM_SCOPE] ([SCOPE_MANDANT], [SCOPE_CMPNY_CODE], [SCOPE_BUSINESS_DMN_L1], [SCOPE_BUSINESS_DMN_L2], [SCOPE_SYSTEM], [ZF_REGION_FLAG]) VALUES (N'888', N'VN00', N'NA', N'SONY ELECTRONICS VIETNAM', N'NA', N'APAC')
INSERT [dbo].[AM_SCOPE] ([SCOPE_MANDANT], [SCOPE_CMPNY_CODE], [SCOPE_BUSINESS_DMN_L1], [SCOPE_BUSINESS_DMN_L2], [SCOPE_SYSTEM], [ZF_REGION_FLAG]) VALUES (N'888', N'VN50', N'NA', N'SONY ELECTRONICS VIETNAM', N'NA', N'APAC')
GO
