USE [DIVA_SEV_FY2023]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[AM_COPA_MAPPING](
	[COPA_MANDT] [nvarchar](100) NULL,
	[COPA_BUKRS] [nvarchar](100) NULL,
	[COPA_KOKRS] [nvarchar](100) NULL,
	[COPA_RACCT] [nvarchar](100) NULL,
	[COPA_RACCT_TXT50] [nvarchar](100) NULL,
	[COPA_RACCT_Hierarchy_L1] [nvarchar](100) NULL,
	[COPA_RACCT_Hierarchy_L2] [nvarchar](100) NULL,
	[COPA_RACCT_Hierarchy_L3] [nvarchar](100) NULL,
	[COPA_Contractual_Condition] [nvarchar](100) NULL,
	[COPA_Settlement_method] [nvarchar](100) NULL,
	[COPA_Rebate_basis] [nvarchar](100) NULL,
	[COPA_CI_or_non_CI] [nvarchar](100) NULL,
	[COPA_Value] [nvarchar](100) NULL
) ON [PRIMARY]
GO
INSERT [dbo].[AM_COPA_MAPPING] ([COPA_MANDT], [COPA_BUKRS], [COPA_KOKRS], [COPA_RACCT], [COPA_RACCT_TXT50], [COPA_RACCT_Hierarchy_L1], [COPA_RACCT_Hierarchy_L2], [COPA_RACCT_Hierarchy_L3], [COPA_Contractual_Condition], [COPA_Settlement_method], [COPA_Rebate_basis], [COPA_CI_or_non_CI], [COPA_Value]) VALUES (N'888', N'VN00', N'E001', N'A505010', N'COGS- Products', N'COGS', N'COGS', N'COGS', N'N/A', N'N/A', N'N/A', N'N/A', N'NULL')
INSERT [dbo].[AM_COPA_MAPPING] ([COPA_MANDT], [COPA_BUKRS], [COPA_KOKRS], [COPA_RACCT], [COPA_RACCT_TXT50], [COPA_RACCT_Hierarchy_L1], [COPA_RACCT_Hierarchy_L2], [COPA_RACCT_Hierarchy_L3], [COPA_Contractual_Condition], [COPA_Settlement_method], [COPA_Rebate_basis], [COPA_CI_or_non_CI], [COPA_Value]) VALUES (N'888', N'VN00', N'E001', N'A505030', N'COGS- Other', N'COGS', N'COGS', N'COGS', N'N/A', N'N/A', N'N/A', N'N/A', N'NULL')
INSERT [dbo].[AM_COPA_MAPPING] ([COPA_MANDT], [COPA_BUKRS], [COPA_KOKRS], [COPA_RACCT], [COPA_RACCT_TXT50], [COPA_RACCT_Hierarchy_L1], [COPA_RACCT_Hierarchy_L2], [COPA_RACCT_Hierarchy_L3], [COPA_Contractual_Condition], [COPA_Settlement_method], [COPA_Rebate_basis], [COPA_CI_or_non_CI], [COPA_Value]) VALUES (N'888', N'VN00', N'E001', N'A505055', N'COGS - Spare Parts', N'COGS', N'COGS', N'COGS', N'N/A', N'N/A', N'N/A', N'N/A', N'NULL')
INSERT [dbo].[AM_COPA_MAPPING] ([COPA_MANDT], [COPA_BUKRS], [COPA_KOKRS], [COPA_RACCT], [COPA_RACCT_TXT50], [COPA_RACCT_Hierarchy_L1], [COPA_RACCT_Hierarchy_L2], [COPA_RACCT_Hierarchy_L3], [COPA_Contractual_Condition], [COPA_Settlement_method], [COPA_Rebate_basis], [COPA_CI_or_non_CI], [COPA_Value]) VALUES (N'888', N'VN00', N'E001', N'A505300', N'COGS- Devaluation', N'COGS', N'COGS', N'COGS', N'N/A', N'N/A', N'N/A', N'N/A', N'NULL')
INSERT [dbo].[AM_COPA_MAPPING] ([COPA_MANDT], [COPA_BUKRS], [COPA_KOKRS], [COPA_RACCT], [COPA_RACCT_TXT50], [COPA_RACCT_Hierarchy_L1], [COPA_RACCT_Hierarchy_L2], [COPA_RACCT_Hierarchy_L3], [COPA_Contractual_Condition], [COPA_Settlement_method], [COPA_Rebate_basis], [COPA_CI_or_non_CI], [COPA_Value]) VALUES (N'888', N'VN00', N'E001', N'A505410', N'COGS- Special loss on disposal of inventories', N'COGS', N'COGS', N'COGS', N'N/A', N'N/A', N'N/A', N'N/A', N'NULL')
INSERT [dbo].[AM_COPA_MAPPING] ([COPA_MANDT], [COPA_BUKRS], [COPA_KOKRS], [COPA_RACCT], [COPA_RACCT_TXT50], [COPA_RACCT_Hierarchy_L1], [COPA_RACCT_Hierarchy_L2], [COPA_RACCT_Hierarchy_L3], [COPA_Contractual_Condition], [COPA_Settlement_method], [COPA_Rebate_basis], [COPA_CI_or_non_CI], [COPA_Value]) VALUES (N'888', N'VN00', N'E001', N'A621010', N'Gross Sales- Products', N'Gross Sales', N'Gross Sales', N'Gross Sales', N'N/A', N'N/A', N'Rebate basis', N'N/A', N'NULL')
INSERT [dbo].[AM_COPA_MAPPING] ([COPA_MANDT], [COPA_BUKRS], [COPA_KOKRS], [COPA_RACCT], [COPA_RACCT_TXT50], [COPA_RACCT_Hierarchy_L1], [COPA_RACCT_Hierarchy_L2], [COPA_RACCT_Hierarchy_L3], [COPA_Contractual_Condition], [COPA_Settlement_method], [COPA_Rebate_basis], [COPA_CI_or_non_CI], [COPA_Value]) VALUES (N'888', N'VN00', N'E001', N'A621050', N'Gross Sales- Service & Repair', N'Gross Sales', N'Gross Sales', N'Gross Sales', N'N/A', N'N/A', N'Rebate basis', N'N/A', N'NULL')
INSERT [dbo].[AM_COPA_MAPPING] ([COPA_MANDT], [COPA_BUKRS], [COPA_KOKRS], [COPA_RACCT], [COPA_RACCT_TXT50], [COPA_RACCT_Hierarchy_L1], [COPA_RACCT_Hierarchy_L2], [COPA_RACCT_Hierarchy_L3], [COPA_Contractual_Condition], [COPA_Settlement_method], [COPA_Rebate_basis], [COPA_CI_or_non_CI], [COPA_Value]) VALUES (N'888', N'VN00', N'E001', N'A621055', N'Gross Sales - Spare Parts', N'Gross Sales', N'Gross Sales', N'Gross Sales', N'N/A', N'N/A', N'Rebate basis', N'N/A', N'NULL')
INSERT [dbo].[AM_COPA_MAPPING] ([COPA_MANDT], [COPA_BUKRS], [COPA_KOKRS], [COPA_RACCT], [COPA_RACCT_TXT50], [COPA_RACCT_Hierarchy_L1], [COPA_RACCT_Hierarchy_L2], [COPA_RACCT_Hierarchy_L3], [COPA_Contractual_Condition], [COPA_Settlement_method], [COPA_Rebate_basis], [COPA_CI_or_non_CI], [COPA_Value]) VALUES (N'888', N'VN00', N'E001', N'A622110', N'Sales reduction, On-invoice discount Merchandise', N'Sales Reductions', N'1_OID contractual', N'OID poducts', N'Contracted', N'OID', N'Rebate basis', N'CI', N'NULL')
INSERT [dbo].[AM_COPA_MAPPING] ([COPA_MANDT], [COPA_BUKRS], [COPA_KOKRS], [COPA_RACCT], [COPA_RACCT_TXT50], [COPA_RACCT_Hierarchy_L1], [COPA_RACCT_Hierarchy_L2], [COPA_RACCT_Hierarchy_L3], [COPA_Contractual_Condition], [COPA_Settlement_method], [COPA_Rebate_basis], [COPA_CI_or_non_CI], [COPA_Value]) VALUES (N'888', N'VN00', N'E001', N'A622111', N'Sales reduction, On-invoice discount Spare Parts', N'Sales Reductions', N'1_OID contractual', N'OID spare parts', N'Contracted', N'OID', N'Rebate basis', N'Non-CI', N'NULL')
INSERT [dbo].[AM_COPA_MAPPING] ([COPA_MANDT], [COPA_BUKRS], [COPA_KOKRS], [COPA_RACCT], [COPA_RACCT_TXT50], [COPA_RACCT_Hierarchy_L1], [COPA_RACCT_Hierarchy_L2], [COPA_RACCT_Hierarchy_L3], [COPA_Contractual_Condition], [COPA_Settlement_method], [COPA_Rebate_basis], [COPA_CI_or_non_CI], [COPA_Value]) VALUES (N'888', N'VN00', N'E001', N'A622112', N'Sales reduction, On-invoice discount Round diff', N'Sales Reductions', N'1_OID contractual', N'OID others', N'Contracted', N'OID', N'Rebate basis', N'Non-CI', N'NULL')
INSERT [dbo].[AM_COPA_MAPPING] ([COPA_MANDT], [COPA_BUKRS], [COPA_KOKRS], [COPA_RACCT], [COPA_RACCT_TXT50], [COPA_RACCT_Hierarchy_L1], [COPA_RACCT_Hierarchy_L2], [COPA_RACCT_Hierarchy_L3], [COPA_Contractual_Condition], [COPA_Settlement_method], [COPA_Rebate_basis], [COPA_CI_or_non_CI], [COPA_Value]) VALUES (N'888', N'VN00', N'E001', N'A622210', N'Sales reduction, Co-op AD(Activity)', N'Sales Reductions', N'3_Tactical', N'CO-OP', N'Marketing tactical', N'Credit note', N'N/A', N'CI', N'NULL')
INSERT [dbo].[AM_COPA_MAPPING] ([COPA_MANDT], [COPA_BUKRS], [COPA_KOKRS], [COPA_RACCT], [COPA_RACCT_TXT50], [COPA_RACCT_Hierarchy_L1], [COPA_RACCT_Hierarchy_L2], [COPA_RACCT_Hierarchy_L3], [COPA_Contractual_Condition], [COPA_Settlement_method], [COPA_Rebate_basis], [COPA_CI_or_non_CI], [COPA_Value]) VALUES (N'888', N'VN00', N'E001', N'A622310', N'Sales reduction, Stock Compensation(Activity)', N'Sales Reductions', N'4_Stock comp', N'Stock comp', N'Marketing tactical', N'Credit note', N'N/A', N'CI', N'NULL')
INSERT [dbo].[AM_COPA_MAPPING] ([COPA_MANDT], [COPA_BUKRS], [COPA_KOKRS], [COPA_RACCT], [COPA_RACCT_TXT50], [COPA_RACCT_Hierarchy_L1], [COPA_RACCT_Hierarchy_L2], [COPA_RACCT_Hierarchy_L3], [COPA_Contractual_Condition], [COPA_Settlement_method], [COPA_Rebate_basis], [COPA_CI_or_non_CI], [COPA_Value]) VALUES (N'888', N'VN00', N'E001', N'A622311', N'Sales reduction, Stock Compensation (General)', N'Sales Reductions', N'4_Stock comp', N'Stock comp', N'Marketing tactical', N'Credit note', N'N/A', N'CI', N'NULL')
INSERT [dbo].[AM_COPA_MAPPING] ([COPA_MANDT], [COPA_BUKRS], [COPA_KOKRS], [COPA_RACCT], [COPA_RACCT_TXT50], [COPA_RACCT_Hierarchy_L1], [COPA_RACCT_Hierarchy_L2], [COPA_RACCT_Hierarchy_L3], [COPA_Contractual_Condition], [COPA_Settlement_method], [COPA_Rebate_basis], [COPA_CI_or_non_CI], [COPA_Value]) VALUES (N'888', N'VN00', N'E001', N'A622424', N'Sales reduction, Sell Thru/Promo Rebate (Activity)', N'Sales Reductions', N'3_Tactical', N'STR', N'Sales tactical', N'Credit note', N'N/A', N'CI', N'NULL')
INSERT [dbo].[AM_COPA_MAPPING] ([COPA_MANDT], [COPA_BUKRS], [COPA_KOKRS], [COPA_RACCT], [COPA_RACCT_TXT50], [COPA_RACCT_Hierarchy_L1], [COPA_RACCT_Hierarchy_L2], [COPA_RACCT_Hierarchy_L3], [COPA_Contractual_Condition], [COPA_Settlement_method], [COPA_Rebate_basis], [COPA_CI_or_non_CI], [COPA_Value]) VALUES (N'888', N'VN00', N'E001', N'A622425', N'Sales reduction, Sell Thru/Promo Rebate (General)', N'Sales Reductions', N'3_Tactical', N'STR', N'Sales tactical', N'Credit note', N'N/A', N'CI', N'NULL')
INSERT [dbo].[AM_COPA_MAPPING] ([COPA_MANDT], [COPA_BUKRS], [COPA_KOKRS], [COPA_RACCT], [COPA_RACCT_TXT50], [COPA_RACCT_Hierarchy_L1], [COPA_RACCT_Hierarchy_L2], [COPA_RACCT_Hierarchy_L3], [COPA_Contractual_Condition], [COPA_Settlement_method], [COPA_Rebate_basis], [COPA_CI_or_non_CI], [COPA_Value]) VALUES (N'888', N'VN00', N'E001', N'A622430', N'Sales reduction, Sell-in allowance (Activity)', N'Sales Reductions', N'2_rebates', N'SIA', N'Contracted', N'Credit note', N'N/A', N'CI', N'NULL')
INSERT [dbo].[AM_COPA_MAPPING] ([COPA_MANDT], [COPA_BUKRS], [COPA_KOKRS], [COPA_RACCT], [COPA_RACCT_TXT50], [COPA_RACCT_Hierarchy_L1], [COPA_RACCT_Hierarchy_L2], [COPA_RACCT_Hierarchy_L3], [COPA_Contractual_Condition], [COPA_Settlement_method], [COPA_Rebate_basis], [COPA_CI_or_non_CI], [COPA_Value]) VALUES (N'888', N'VN00', N'E001', N'A622431', N'Sales reduction, Sell-in allowance (General)', N'Sales Reductions', N'2_rebates', N'SIA', N'Contracted', N'Credit note', N'N/A', N'CI', N'NULL')
INSERT [dbo].[AM_COPA_MAPPING] ([COPA_MANDT], [COPA_BUKRS], [COPA_KOKRS], [COPA_RACCT], [COPA_RACCT_TXT50], [COPA_RACCT_Hierarchy_L1], [COPA_RACCT_Hierarchy_L2], [COPA_RACCT_Hierarchy_L3], [COPA_Contractual_Condition], [COPA_Settlement_method], [COPA_Rebate_basis], [COPA_CI_or_non_CI], [COPA_Value]) VALUES (N'888', N'VN00', N'E001', N'A622620', N'Sales reduction, Other manual price adj', N'Sales Reductions', N'5_Others', N'Others', N'N/A', N'OID', N'Rebate basis', N'CI', N'NULL')
INSERT [dbo].[AM_COPA_MAPPING] ([COPA_MANDT], [COPA_BUKRS], [COPA_KOKRS], [COPA_RACCT], [COPA_RACCT_TXT50], [COPA_RACCT_Hierarchy_L1], [COPA_RACCT_Hierarchy_L2], [COPA_RACCT_Hierarchy_L3], [COPA_Contractual_Condition], [COPA_Settlement_method], [COPA_Rebate_basis], [COPA_CI_or_non_CI], [COPA_Value]) VALUES (N'888', N'VN00', N'E001', N'A625900', N'OPR- Other1', N'Gross Sales', N'Operating Revenue', N'Operating Revenue', N'N/A', N'N/A', N'N/A', N'N/A', N'NULL')
GO
