USE [DIVA_SEV_FY2023]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[AM_CURRENT_USER_FROM_DATABASE](
	[ZF_SOURCE_USNAM] [nvarchar](50) NULL,
	[ZF_SOURCE_TABLE] [nvarchar](50) NULL
) ON [PRIMARY]
GO
INSERT [dbo].[AM_CURRENT_USER_FROM_DATABASE] ([ZF_SOURCE_USNAM], [ZF_SOURCE_TABLE]) VALUES (N'5015094072', N'V_USERNAME_BNAME')
GO
