USE [DIVA_SEV_FY2023]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[AM_IRGR_GINI_ARDR_MAPPING](
	[IRGR_GL_ACCT] [nvarchar](100) NULL,
	[IRGR_GL_TXT] [nvarchar](100) NULL,
	[IRGR_OR_GINI_OR_ARDR] [nvarchar](100) NULL
) ON [PRIMARY]
GO
INSERT [dbo].[AM_IRGR_GINI_ARDR_MAPPING] ([IRGR_GL_ACCT], [IRGR_GL_TXT], [IRGR_OR_GINI_OR_ARDR]) VALUES (N'A014580', N'Incoming Clearing- 77Bank Tagajyo', N'GINI')
INSERT [dbo].[AM_IRGR_GINI_ARDR_MAPPING] ([IRGR_GL_ACCT], [IRGR_GL_TXT], [IRGR_OR_GINI_OR_ARDR]) VALUES (N'A014581', N'Incoming Clearing- Japan Post Bank Furikae', N'GINI')
INSERT [dbo].[AM_IRGR_GINI_ARDR_MAPPING] ([IRGR_GL_ACCT], [IRGR_GL_TXT], [IRGR_OR_GINI_OR_ARDR]) VALUES (N'A021060', N'Goods issued not invoiced', N'GINI')
INSERT [dbo].[AM_IRGR_GINI_ARDR_MAPPING] ([IRGR_GL_ACCT], [IRGR_GL_TXT], [IRGR_OR_GINI_OR_ARDR]) VALUES (N'A032851', N'Other AR-current- direct GL entry- NOIM', N'GINI')
INSERT [dbo].[AM_IRGR_GINI_ARDR_MAPPING] ([IRGR_GL_ACCT], [IRGR_GL_TXT], [IRGR_OR_GINI_OR_ARDR]) VALUES (N'A037010', N'Accrd income, General', N'ARDR')
INSERT [dbo].[AM_IRGR_GINI_ARDR_MAPPING] ([IRGR_GL_ACCT], [IRGR_GL_TXT], [IRGR_OR_GINI_OR_ARDR]) VALUES (N'A212100', N'Trade AP- invoice to be received- GRIR 1', N'IRGR')
INSERT [dbo].[AM_IRGR_GINI_ARDR_MAPPING] ([IRGR_GL_ACCT], [IRGR_GL_TXT], [IRGR_OR_GINI_OR_ARDR]) VALUES (N'A212101', N'Trade AP- invoice to be received- GRIR 2', N'IRGR')
INSERT [dbo].[AM_IRGR_GINI_ARDR_MAPPING] ([IRGR_GL_ACCT], [IRGR_GL_TXT], [IRGR_OR_GINI_OR_ARDR]) VALUES (N'A212110', N'Trade AP- invoice to be received- direct GL entry', N'IRGR')
INSERT [dbo].[AM_IRGR_GINI_ARDR_MAPPING] ([IRGR_GL_ACCT], [IRGR_GL_TXT], [IRGR_OR_GINI_OR_ARDR]) VALUES (N'A215070', N'AP-non trade, invoice to be received, GRIR', N'IRGR')
INSERT [dbo].[AM_IRGR_GINI_ARDR_MAPPING] ([IRGR_GL_ACCT], [IRGR_GL_TXT], [IRGR_OR_GINI_OR_ARDR]) VALUES (N'A215071', N'GR/IR', N'IRGR')
INSERT [dbo].[AM_IRGR_GINI_ARDR_MAPPING] ([IRGR_GL_ACCT], [IRGR_GL_TXT], [IRGR_OR_GINI_OR_ARDR]) VALUES (N'A215080', N'AP-non trade,invoice to be received,direct GLentry', N'IRGR')
GO
