USE [DIVA_SEV_FY2023]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[AM_VENDOR_EXCEPTION_LIST](
	[VEL_COMPANY_CODE] [varchar](4) NOT NULL,
	[VEL_SUPPLIER_NUM] [varchar](2) NOT NULL,
	[_VENDOR_EXCEPTIO] [nvarchar](3) NULL
) ON [PRIMARY]
GO
