USE [DIVA_SEV_FY2023]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[AM_TANGO](
	[TANGO_GL_ACCT] [nvarchar](100) NULL,
	[TANGO_ACCT] [nvarchar](100) NULL,
	[TANGO_ACCT_MAP_TXT] [nvarchar](100) NULL,
	[TANGO_ACCT_TXT] [nvarchar](100) NULL
) ON [PRIMARY]
GO
INSERT [dbo].[AM_TANGO] ([TANGO_GL_ACCT], [TANGO_ACCT], [TANGO_ACCT_MAP_TXT], [TANGO_ACCT_TXT]) VALUES (N'A012001', N'12000', N'Cash on Hand - National Currency', N'Cash and cash equivalents')
INSERT [dbo].[AM_TANGO] ([TANGO_GL_ACCT], [TANGO_ACCT], [TANGO_ACCT_MAP_TXT], [TANGO_ACCT_TXT]) VALUES (N'A012002', N'12000', N'Cash on Hand - USD', N'Cash and cash equivalents')
INSERT [dbo].[AM_TANGO] ([TANGO_GL_ACCT], [TANGO_ACCT], [TANGO_ACCT_MAP_TXT], [TANGO_ACCT_TXT]) VALUES (N'A012007', N'12000', N'Cash on Hand - National Currency 2', N'Cash and cash equivalents')
INSERT [dbo].[AM_TANGO] ([TANGO_GL_ACCT], [TANGO_ACCT], [TANGO_ACCT_MAP_TXT], [TANGO_ACCT_TXT]) VALUES (N'A012100', N'12000', N'Citibank - National Currency', N'Cash and cash equivalents')
INSERT [dbo].[AM_TANGO] ([TANGO_GL_ACCT], [TANGO_ACCT], [TANGO_ACCT_MAP_TXT], [TANGO_ACCT_TXT]) VALUES (N'A012101', N'12000', N'Citibank - USD', N'Cash and cash equivalents')
INSERT [dbo].[AM_TANGO] ([TANGO_GL_ACCT], [TANGO_ACCT], [TANGO_ACCT_MAP_TXT], [TANGO_ACCT_TXT]) VALUES (N'A012105', N'12000', N'HSBC - National Currency', N'Cash and cash equivalents')
INSERT [dbo].[AM_TANGO] ([TANGO_GL_ACCT], [TANGO_ACCT], [TANGO_ACCT_MAP_TXT], [TANGO_ACCT_TXT]) VALUES (N'A012106', N'12000', N'HSBC - USD', N'Cash and cash equivalents')
INSERT [dbo].[AM_TANGO] ([TANGO_GL_ACCT], [TANGO_ACCT], [TANGO_ACCT_MAP_TXT], [TANGO_ACCT_TXT]) VALUES (N'A012114', N'12000', N'SMBC - National Currency', N'Cash and cash equivalents')
INSERT [dbo].[AM_TANGO] ([TANGO_GL_ACCT], [TANGO_ACCT], [TANGO_ACCT_MAP_TXT], [TANGO_ACCT_TXT]) VALUES (N'A012117', N'12000', N'BTMU - National Currency', N'Cash and cash equivalents')
INSERT [dbo].[AM_TANGO] ([TANGO_GL_ACCT], [TANGO_ACCT], [TANGO_ACCT_MAP_TXT], [TANGO_ACCT_TXT]) VALUES (N'A012118', N'12000', N'BTMU - USD', N'Cash and cash equivalents')
INSERT [dbo].[AM_TANGO] ([TANGO_GL_ACCT], [TANGO_ACCT], [TANGO_ACCT_MAP_TXT], [TANGO_ACCT_TXT]) VALUES (N'A012126', N'12000', N'DB - National Currency', N'Cash and cash equivalents')
INSERT [dbo].[AM_TANGO] ([TANGO_GL_ACCT], [TANGO_ACCT], [TANGO_ACCT_MAP_TXT], [TANGO_ACCT_TXT]) VALUES (N'A012127', N'12000', N'DB - USD', N'Cash and cash equivalents')
INSERT [dbo].[AM_TANGO] ([TANGO_GL_ACCT], [TANGO_ACCT], [TANGO_ACCT_MAP_TXT], [TANGO_ACCT_TXT]) VALUES (N'A012129', N'12000', N'SCB - National Currency', N'Cash and cash equivalents')
INSERT [dbo].[AM_TANGO] ([TANGO_GL_ACCT], [TANGO_ACCT], [TANGO_ACCT_MAP_TXT], [TANGO_ACCT_TXT]) VALUES (N'A012132', N'12000', N'BNP Paribas - National Currency', N'Cash and cash equivalents')
INSERT [dbo].[AM_TANGO] ([TANGO_GL_ACCT], [TANGO_ACCT], [TANGO_ACCT_MAP_TXT], [TANGO_ACCT_TXT]) VALUES (N'A012133', N'12000', N'Techcombank - National Currency', N'Cash and cash equivalents')
INSERT [dbo].[AM_TANGO] ([TANGO_GL_ACCT], [TANGO_ACCT], [TANGO_ACCT_MAP_TXT], [TANGO_ACCT_TXT]) VALUES (N'A012990', N'12000', N'Cash on hand- FX Translation', N'Cash and cash equivalents')
INSERT [dbo].[AM_TANGO] ([TANGO_GL_ACCT], [TANGO_ACCT], [TANGO_ACCT_MAP_TXT], [TANGO_ACCT_TXT]) VALUES (N'A014010', N'14000', N'Trade account receivable, General', N'Accounts Receivables')
INSERT [dbo].[AM_TANGO] ([TANGO_GL_ACCT], [TANGO_ACCT], [TANGO_ACCT_MAP_TXT], [TANGO_ACCT_TXT]) VALUES (N'A014100', N'14000', N'Citibank - National Currency (incoming)', N'Accounts Receivables')
INSERT [dbo].[AM_TANGO] ([TANGO_GL_ACCT], [TANGO_ACCT], [TANGO_ACCT_MAP_TXT], [TANGO_ACCT_TXT]) VALUES (N'A014101', N'14000', N'Citibank - USD (incoming)', N'Accounts Receivables')
INSERT [dbo].[AM_TANGO] ([TANGO_GL_ACCT], [TANGO_ACCT], [TANGO_ACCT_MAP_TXT], [TANGO_ACCT_TXT]) VALUES (N'A014105', N'14000', N'HSBC - National Currency (incoming)', N'Accounts Receivables')
INSERT [dbo].[AM_TANGO] ([TANGO_GL_ACCT], [TANGO_ACCT], [TANGO_ACCT_MAP_TXT], [TANGO_ACCT_TXT]) VALUES (N'A014106', N'14000', N'HSBC - USD (incoming)', N'Accounts Receivables')
INSERT [dbo].[AM_TANGO] ([TANGO_GL_ACCT], [TANGO_ACCT], [TANGO_ACCT_MAP_TXT], [TANGO_ACCT_TXT]) VALUES (N'A014850', N'14000', N'Trade account receivable, direct GL entry, OIM', N'Accounts Receivables')
INSERT [dbo].[AM_TANGO] ([TANGO_GL_ACCT], [TANGO_ACCT], [TANGO_ACCT_MAP_TXT], [TANGO_ACCT_TXT]) VALUES (N'A014990', N'14000', N'Trade account receivable, FX Translation', N'Accounts Receivables')
INSERT [dbo].[AM_TANGO] ([TANGO_GL_ACCT], [TANGO_ACCT], [TANGO_ACCT_MAP_TXT], [TANGO_ACCT_TXT]) VALUES (N'A021010', N'21000', N'Products, Merchandise & Finished goods, SAP main', N'Inventory -  Finished Goods')
INSERT [dbo].[AM_TANGO] ([TANGO_GL_ACCT], [TANGO_ACCT], [TANGO_ACCT_MAP_TXT], [TANGO_ACCT_TXT]) VALUES (N'A021015', N'21000', N'Products- Merchandise & FG- direct GL entry OIM', N'Inventory -  Finished Goods')
INSERT [dbo].[AM_TANGO] ([TANGO_GL_ACCT], [TANGO_ACCT], [TANGO_ACCT_MAP_TXT], [TANGO_ACCT_TXT]) VALUES (N'A021020', N'21000', N'Products, Merchandise & FG, direct GL, balance', N'Inventory -  Finished Goods')
INSERT [dbo].[AM_TANGO] ([TANGO_GL_ACCT], [TANGO_ACCT], [TANGO_ACCT_MAP_TXT], [TANGO_ACCT_TXT]) VALUES (N'A021030', N'21024', N'Products, Merchandise & FG, In transit', N'Inventory -  Finished Goods')
INSERT [dbo].[AM_TANGO] ([TANGO_GL_ACCT], [TANGO_ACCT], [TANGO_ACCT_MAP_TXT], [TANGO_ACCT_TXT]) VALUES (N'A021050', N'21091', N'Products, Merchandise & FG, Devaluation', N'Provision for Devaluation - Merchandise')
INSERT [dbo].[AM_TANGO] ([TANGO_GL_ACCT], [TANGO_ACCT], [TANGO_ACCT_MAP_TXT], [TANGO_ACCT_TXT]) VALUES (N'A025100', N'25000', N'Other inventory, Spare parts, SAP-MM', N'Inventory -  Raw Materials')
INSERT [dbo].[AM_TANGO] ([TANGO_GL_ACCT], [TANGO_ACCT], [TANGO_ACCT_MAP_TXT], [TANGO_ACCT_TXT]) VALUES (N'A031030', N'31000', N'Prepaid exps, Rental/Leasing', N'Prepaid Expenses')
INSERT [dbo].[AM_TANGO] ([TANGO_GL_ACCT], [TANGO_ACCT], [TANGO_ACCT_MAP_TXT], [TANGO_ACCT_TXT]) VALUES (N'A031060', N'31000', N'Prepaid exps, Insurance', N'Prepaid Expenses')
INSERT [dbo].[AM_TANGO] ([TANGO_GL_ACCT], [TANGO_ACCT], [TANGO_ACCT_MAP_TXT], [TANGO_ACCT_TXT]) VALUES (N'A031100', N'31000', N'Prepaid exps, Deferred Cost - Goods/Services', N'Prepaid Expenses')
INSERT [dbo].[AM_TANGO] ([TANGO_GL_ACCT], [TANGO_ACCT], [TANGO_ACCT_MAP_TXT], [TANGO_ACCT_TXT]) VALUES (N'A031900', N'31000', N'Prepaid exps, Other1', N'Prepaid Expenses')
INSERT [dbo].[AM_TANGO] ([TANGO_GL_ACCT], [TANGO_ACCT], [TANGO_ACCT_MAP_TXT], [TANGO_ACCT_TXT]) VALUES (N'A032010', N'32000', N'Other account receivable-current, General', N'Other Current Assets')
INSERT [dbo].[AM_TANGO] ([TANGO_GL_ACCT], [TANGO_ACCT], [TANGO_ACCT_MAP_TXT], [TANGO_ACCT_TXT]) VALUES (N'A032990', N'32000', N'Other AR-current, FX Translation', N'Other Current Assets')
INSERT [dbo].[AM_TANGO] ([TANGO_GL_ACCT], [TANGO_ACCT], [TANGO_ACCT_MAP_TXT], [TANGO_ACCT_TXT]) VALUES (N'A034010', N'34000', N'Adv paymts, General', N'Advanced Payment')
INSERT [dbo].[AM_TANGO] ([TANGO_GL_ACCT], [TANGO_ACCT], [TANGO_ACCT_MAP_TXT], [TANGO_ACCT_TXT]) VALUES (N'A034040', N'34000', N'Adv paymts- Sales Reductions- Tactical Cash Back', N'Advanced Payment')
INSERT [dbo].[AM_TANGO] ([TANGO_GL_ACCT], [TANGO_ACCT], [TANGO_ACCT_MAP_TXT], [TANGO_ACCT_TXT]) VALUES (N'A035900', N'35000', N'Expense to be recharged, Other1', N'Expense to be recharged')
INSERT [dbo].[AM_TANGO] ([TANGO_GL_ACCT], [TANGO_ACCT], [TANGO_ACCT_MAP_TXT], [TANGO_ACCT_TXT]) VALUES (N'A037010', N'37000', N'Accrd income, General', N'Accrued income')
INSERT [dbo].[AM_TANGO] ([TANGO_GL_ACCT], [TANGO_ACCT], [TANGO_ACCT_MAP_TXT], [TANGO_ACCT_TXT]) VALUES (N'A037990', N'37000', N'Accrd income- FX Translation', N'Accrued income')
INSERT [dbo].[AM_TANGO] ([TANGO_GL_ACCT], [TANGO_ACCT], [TANGO_ACCT_MAP_TXT], [TANGO_ACCT_TXT]) VALUES (N'A038010', N'38000', N'VAT-receivable on purchase, general', N'Value added tax-receivable')
INSERT [dbo].[AM_TANGO] ([TANGO_GL_ACCT], [TANGO_ACCT], [TANGO_ACCT_MAP_TXT], [TANGO_ACCT_TXT]) VALUES (N'A038480', N'38000', N'VAT-receivable (clearing) VN', N'Value added tax-receivable')
INSERT [dbo].[AM_TANGO] ([TANGO_GL_ACCT], [TANGO_ACCT], [TANGO_ACCT_MAP_TXT], [TANGO_ACCT_TXT]) VALUES (N'A040010', N'40000', N'Derivative Assets-current, Frgn exchange forward', N'Derivative assets - current')
INSERT [dbo].[AM_TANGO] ([TANGO_GL_ACCT], [TANGO_ACCT], [TANGO_ACCT_MAP_TXT], [TANGO_ACCT_TXT]) VALUES (N'A089010', N'89000', N'Other misc. current assets, General', N'Other Current Assets')
INSERT [dbo].[AM_TANGO] ([TANGO_GL_ACCT], [TANGO_ACCT], [TANGO_ACCT_MAP_TXT], [TANGO_ACCT_TXT]) VALUES (N'A089030', N'89015', N'Other misc. current assets, Time deposits', N'OCA,Time deposits')
INSERT [dbo].[AM_TANGO] ([TANGO_GL_ACCT], [TANGO_ACCT], [TANGO_ACCT_MAP_TXT], [TANGO_ACCT_TXT]) VALUES (N'A089090', N'89000', N'Other Current Asset - Cannibalization', N'Other Current Assets')
INSERT [dbo].[AM_TANGO] ([TANGO_GL_ACCT], [TANGO_ACCT], [TANGO_ACCT_MAP_TXT], [TANGO_ACCT_TXT]) VALUES (N'A089091', N'89000', N'Other Current Asset - Interim Service', N'Other Current Assets')
INSERT [dbo].[AM_TANGO] ([TANGO_GL_ACCT], [TANGO_ACCT], [TANGO_ACCT_MAP_TXT], [TANGO_ACCT_TXT]) VALUES (N'A089092', N'89000', N'OCA- LVA Supply', N'Other Current Assets')
INSERT [dbo].[AM_TANGO] ([TANGO_GL_ACCT], [TANGO_ACCT], [TANGO_ACCT_MAP_TXT], [TANGO_ACCT_TXT]) VALUES (N'A089093', N'89000', N'OCA- LVA Supply Direct GL', N'Other Current Assets')
INSERT [dbo].[AM_TANGO] ([TANGO_GL_ACCT], [TANGO_ACCT], [TANGO_ACCT_MAP_TXT], [TANGO_ACCT_TXT]) VALUES (N'A089990', N'89000', N'Other misc. current assets- FX Translation', N'Other Current Assets')
INSERT [dbo].[AM_TANGO] ([TANGO_GL_ACCT], [TANGO_ACCT], [TANGO_ACCT_MAP_TXT], [TANGO_ACCT_TXT]) VALUES (N'A110010', N'110000', N'Right of use assets- Buildings', N'Right of use assets- Buildings')
INSERT [dbo].[AM_TANGO] ([TANGO_GL_ACCT], [TANGO_ACCT], [TANGO_ACCT_MAP_TXT], [TANGO_ACCT_TXT]) VALUES (N'A110012', N'110000', N'ROU- Buildings - Direct GL-NOIM', N'Right of use assets- Buildings')
INSERT [dbo].[AM_TANGO] ([TANGO_GL_ACCT], [TANGO_ACCT], [TANGO_ACCT_MAP_TXT], [TANGO_ACCT_TXT]) VALUES (N'A110070', N'110064', N'Right of use assets- Vehicles', N'Right of use assets- Vehicles')
INSERT [dbo].[AM_TANGO] ([TANGO_GL_ACCT], [TANGO_ACCT], [TANGO_ACCT_MAP_TXT], [TANGO_ACCT_TXT]) VALUES (N'A110072', N'110065', N'ROU- Vehicles-Direct-NOIM', N'Right of use assets- Vehicles')
INSERT [dbo].[AM_TANGO] ([TANGO_GL_ACCT], [TANGO_ACCT], [TANGO_ACCT_MAP_TXT], [TANGO_ACCT_TXT]) VALUES (N'A110202', N'110307', N'Right of use assets- Acc/Amort- buildings - NOIM', N'Right of use assets- Acc/Amort- buildings')
INSERT [dbo].[AM_TANGO] ([TANGO_GL_ACCT], [TANGO_ACCT], [TANGO_ACCT_MAP_TXT], [TANGO_ACCT_TXT]) VALUES (N'A110262', N'110360', N'ROU- Acc/Amort- Veh-Direct-NOIM', N'Right of use assets- Acc/Amort- vehicles')
INSERT [dbo].[AM_TANGO] ([TANGO_GL_ACCT], [TANGO_ACCT], [TANGO_ACCT_MAP_TXT], [TANGO_ACCT_TXT]) VALUES (N'A112100', N'112038', N'Leasehold imp, ARO', N'Leasehold imp, ARO')
INSERT [dbo].[AM_TANGO] ([TANGO_GL_ACCT], [TANGO_ACCT], [TANGO_ACCT_MAP_TXT], [TANGO_ACCT_TXT]) VALUES (N'A112300', N'112125', N'Leasehold imp, Acc/Dep, ARO', N'Leasehold imp, Acc/Dep, ARO')
INSERT [dbo].[AM_TANGO] ([TANGO_GL_ACCT], [TANGO_ACCT], [TANGO_ACCT_MAP_TXT], [TANGO_ACCT_TXT]) VALUES (N'A114010', N'114019', N'M&E, at cost, General', N'M&E, at cost, General')
INSERT [dbo].[AM_TANGO] ([TANGO_GL_ACCT], [TANGO_ACCT], [TANGO_ACCT_MAP_TXT], [TANGO_ACCT_TXT]) VALUES (N'A114200', N'114152', N'M&E, Acc/Dep, General', N'M&E, Acc/Dep, General')
INSERT [dbo].[AM_TANGO] ([TANGO_GL_ACCT], [TANGO_ACCT], [TANGO_ACCT_MAP_TXT], [TANGO_ACCT_TXT]) VALUES (N'A116010', N'116014', N'Furniture & fixtures, at cost, General', N'Furniture & fixtures, at cost, General')
INSERT [dbo].[AM_TANGO] ([TANGO_GL_ACCT], [TANGO_ACCT], [TANGO_ACCT_MAP_TXT], [TANGO_ACCT_TXT]) VALUES (N'A116200', N'116177', N'Furniture & fixtures, Acc/Dep, General', N'Furniture & fixtures, Acc/Dep, General')
INSERT [dbo].[AM_TANGO] ([TANGO_GL_ACCT], [TANGO_ACCT], [TANGO_ACCT_MAP_TXT], [TANGO_ACCT_TXT]) VALUES (N'A117200', N'117180', N'Vehicles, Acc/Dep, General', N'Vehicles, Acc/Dep, General')
INSERT [dbo].[AM_TANGO] ([TANGO_GL_ACCT], [TANGO_ACCT], [TANGO_ACCT_MAP_TXT], [TANGO_ACCT_TXT]) VALUES (N'A119200', N'119076', N'Construction in Progress, Assets interim account', N'Construction in Progress, at cost, general')
INSERT [dbo].[AM_TANGO] ([TANGO_GL_ACCT], [TANGO_ACCT], [TANGO_ACCT_MAP_TXT], [TANGO_ACCT_TXT]) VALUES (N'A119205', N'119076', N'CIP, Assets interim account (SysInt)', N'Construction in Progress, at cost, general')
INSERT [dbo].[AM_TANGO] ([TANGO_GL_ACCT], [TANGO_ACCT], [TANGO_ACCT_MAP_TXT], [TANGO_ACCT_TXT]) VALUES (N'A123030', N'123060', N'Software, Ext. Software for own use, General', N'Software, Ext. Software for own use, General')
INSERT [dbo].[AM_TANGO] ([TANGO_GL_ACCT], [TANGO_ACCT], [TANGO_ACCT_MAP_TXT], [TANGO_ACCT_TXT]) VALUES (N'A123220', N'123160', N'Software, Acc/Amort (Ext. SW for own use), General', N'Software, Acc/Amort (Ext. SW for own use), General')
INSERT [dbo].[AM_TANGO] ([TANGO_GL_ACCT], [TANGO_ACCT], [TANGO_ACCT_MAP_TXT], [TANGO_ACCT_TXT]) VALUES (N'A136010', N'136000', N'LT loan, General', N'LT loan, General')
INSERT [dbo].[AM_TANGO] ([TANGO_GL_ACCT], [TANGO_ACCT], [TANGO_ACCT_MAP_TXT], [TANGO_ACCT_TXT]) VALUES (N'A142010', N'142000', N'Def tax assets-non-curr, National tax', N'Def tax assets-non-curr, National tax')
INSERT [dbo].[AM_TANGO] ([TANGO_GL_ACCT], [TANGO_ACCT], [TANGO_ACCT_MAP_TXT], [TANGO_ACCT_TXT]) VALUES (N'A158010', N'158000', N'Security Deposit - Non Current', N'Security deposit - non current')
INSERT [dbo].[AM_TANGO] ([TANGO_GL_ACCT], [TANGO_ACCT], [TANGO_ACCT_MAP_TXT], [TANGO_ACCT_TXT]) VALUES (N'A159010', N'159000', N'Other non-curr assets, General', N'Other non-curr assets, General')
INSERT [dbo].[AM_TANGO] ([TANGO_GL_ACCT], [TANGO_ACCT], [TANGO_ACCT_MAP_TXT], [TANGO_ACCT_TXT]) VALUES (N'A159050', N'159000', N'Other non-curr assets, deposit', N'Other non-curr assets, General')
INSERT [dbo].[AM_TANGO] ([TANGO_GL_ACCT], [TANGO_ACCT], [TANGO_ACCT_MAP_TXT], [TANGO_ACCT_TXT]) VALUES (N'A212010', N'212000', N'Trade AP, General', N'Trade AP, General')
INSERT [dbo].[AM_TANGO] ([TANGO_GL_ACCT], [TANGO_ACCT], [TANGO_ACCT_MAP_TXT], [TANGO_ACCT_TXT]) VALUES (N'A212100', N'212000', N'Trade AP- invoice to be received- GRIR 1', N'Trade AP, General')
INSERT [dbo].[AM_TANGO] ([TANGO_GL_ACCT], [TANGO_ACCT], [TANGO_ACCT_MAP_TXT], [TANGO_ACCT_TXT]) VALUES (N'A212101', N'212000', N'Trade AP- invoice to be received- GRIR 2', N'Trade AP, General')
INSERT [dbo].[AM_TANGO] ([TANGO_GL_ACCT], [TANGO_ACCT], [TANGO_ACCT_MAP_TXT], [TANGO_ACCT_TXT]) VALUES (N'A212990', N'212000', N'Trade AP, FX Translation', N'Trade AP, General')
INSERT [dbo].[AM_TANGO] ([TANGO_GL_ACCT], [TANGO_ACCT], [TANGO_ACCT_MAP_TXT], [TANGO_ACCT_TXT]) VALUES (N'A213010', N'213096', N'Short Term Borrowing, General', N'Short-term borrowings (other)')
INSERT [dbo].[AM_TANGO] ([TANGO_GL_ACCT], [TANGO_ACCT], [TANGO_ACCT_MAP_TXT], [TANGO_ACCT_TXT]) VALUES (N'A213100', N'213096', N'Short Term Borrowing, SGTS', N'Short-term borrowings (other)')
INSERT [dbo].[AM_TANGO] ([TANGO_GL_ACCT], [TANGO_ACCT], [TANGO_ACCT_MAP_TXT], [TANGO_ACCT_TXT]) VALUES (N'A213990', N'213096', N'Short Term Borrowing- FX Translation', N'Short-term borrowings (other)')
INSERT [dbo].[AM_TANGO] ([TANGO_GL_ACCT], [TANGO_ACCT], [TANGO_ACCT_MAP_TXT], [TANGO_ACCT_TXT]) VALUES (N'A215010', N'215000', N'AP-non trade, General', N'Other accounts payable')
INSERT [dbo].[AM_TANGO] ([TANGO_GL_ACCT], [TANGO_ACCT], [TANGO_ACCT_MAP_TXT], [TANGO_ACCT_TXT]) VALUES (N'A215070', N'215000', N'AP-non trade, invoice to be received, GRIR', N'Other accounts payable')
INSERT [dbo].[AM_TANGO] ([TANGO_GL_ACCT], [TANGO_ACCT], [TANGO_ACCT_MAP_TXT], [TANGO_ACCT_TXT]) VALUES (N'A215100', N'215000', N'Citibank - National Currency (outgoing)', N'Other accounts payable')
INSERT [dbo].[AM_TANGO] ([TANGO_GL_ACCT], [TANGO_ACCT], [TANGO_ACCT_MAP_TXT], [TANGO_ACCT_TXT]) VALUES (N'A215101', N'215000', N'Citibank - USD (outgoing)', N'Other accounts payable')
INSERT [dbo].[AM_TANGO] ([TANGO_GL_ACCT], [TANGO_ACCT], [TANGO_ACCT_MAP_TXT], [TANGO_ACCT_TXT]) VALUES (N'A215105', N'215000', N'HSBC - National Currency (outgoing)', N'Other accounts payable')
INSERT [dbo].[AM_TANGO] ([TANGO_GL_ACCT], [TANGO_ACCT], [TANGO_ACCT_MAP_TXT], [TANGO_ACCT_TXT]) VALUES (N'A215106', N'215000', N'HSBC - USD (outgoing)', N'Other accounts payable')
INSERT [dbo].[AM_TANGO] ([TANGO_GL_ACCT], [TANGO_ACCT], [TANGO_ACCT_MAP_TXT], [TANGO_ACCT_TXT]) VALUES (N'A215850', N'215000', N'Other AP-non trade- direct GL entry- OIM', N'Other accounts payable')
INSERT [dbo].[AM_TANGO] ([TANGO_GL_ACCT], [TANGO_ACCT], [TANGO_ACCT_MAP_TXT], [TANGO_ACCT_TXT]) VALUES (N'A215851', N'215000', N'Other AP-non trade-Doc Splitting Account', N'Other accounts payable')
INSERT [dbo].[AM_TANGO] ([TANGO_GL_ACCT], [TANGO_ACCT], [TANGO_ACCT_MAP_TXT], [TANGO_ACCT_TXT]) VALUES (N'A215990', N'215000', N'Other AP-non trade- FX Translation for others', N'Other accounts payable')
INSERT [dbo].[AM_TANGO] ([TANGO_GL_ACCT], [TANGO_ACCT], [TANGO_ACCT_MAP_TXT], [TANGO_ACCT_TXT]) VALUES (N'A216100', N'216100', N'Provision for Activity Based Co-Op A&P', N'Accrued sales reduction')
INSERT [dbo].[AM_TANGO] ([TANGO_GL_ACCT], [TANGO_ACCT], [TANGO_ACCT_MAP_TXT], [TANGO_ACCT_TXT]) VALUES (N'A216101', N'216100', N'Provision for Co Op A&P - General', N'Accrued sales reduction')
INSERT [dbo].[AM_TANGO] ([TANGO_GL_ACCT], [TANGO_ACCT], [TANGO_ACCT_MAP_TXT], [TANGO_ACCT_TXT]) VALUES (N'A216140', N'216100', N'Accrd exps, SR, Stock Compensation (Activity)', N'Accrued sales reduction')
INSERT [dbo].[AM_TANGO] ([TANGO_GL_ACCT], [TANGO_ACCT], [TANGO_ACCT_MAP_TXT], [TANGO_ACCT_TXT]) VALUES (N'A216141', N'216100', N'Accrd exps, SR, Stock Compensation (General)', N'Accrued sales reduction')
INSERT [dbo].[AM_TANGO] ([TANGO_GL_ACCT], [TANGO_ACCT], [TANGO_ACCT_MAP_TXT], [TANGO_ACCT_TXT]) VALUES (N'A216164', N'216100', N'Accrd exps, SR, Sell Thru/Promo Rebate (Activity)', N'Accrued sales reduction')
INSERT [dbo].[AM_TANGO] ([TANGO_GL_ACCT], [TANGO_ACCT], [TANGO_ACCT_MAP_TXT], [TANGO_ACCT_TXT]) VALUES (N'A216165', N'216100', N'Accrd exps, SR, Sell Thru/Promo Rebate (General)', N'Accrued sales reduction')
INSERT [dbo].[AM_TANGO] ([TANGO_GL_ACCT], [TANGO_ACCT], [TANGO_ACCT_MAP_TXT], [TANGO_ACCT_TXT]) VALUES (N'A216180', N'216100', N'Accrd exps, SR, Sell-in allowance(Activity)', N'Accrued sales reduction')
INSERT [dbo].[AM_TANGO] ([TANGO_GL_ACCT], [TANGO_ACCT], [TANGO_ACCT_MAP_TXT], [TANGO_ACCT_TXT]) VALUES (N'A216181', N'216100', N'Accrd exps, SR, Sell-in allowance(General)', N'Accrued sales reduction')
INSERT [dbo].[AM_TANGO] ([TANGO_GL_ACCT], [TANGO_ACCT], [TANGO_ACCT_MAP_TXT], [TANGO_ACCT_TXT]) VALUES (N'A216230', N'216100', N'Accrd exps, SR, Other manual price adj', N'Accrued sales reduction')
INSERT [dbo].[AM_TANGO] ([TANGO_GL_ACCT], [TANGO_ACCT], [TANGO_ACCT_MAP_TXT], [TANGO_ACCT_TXT]) VALUES (N'A216260', N'216100', N'Accrd Exp, Sales Discount', N'Accrued sales reduction')
INSERT [dbo].[AM_TANGO] ([TANGO_GL_ACCT], [TANGO_ACCT], [TANGO_ACCT_MAP_TXT], [TANGO_ACCT_TXT]) VALUES (N'A216310', N'216200', N'Accrd exps, Salaries & Wages', N'Accrd exps, Salaries & Wages')
INSERT [dbo].[AM_TANGO] ([TANGO_GL_ACCT], [TANGO_ACCT], [TANGO_ACCT_MAP_TXT], [TANGO_ACCT_TXT]) VALUES (N'A216320', N'216200', N'Accrd exps, Bonuses, General', N'Accrd exps, Salaries & Wages')
GO
INSERT [dbo].[AM_TANGO] ([TANGO_GL_ACCT], [TANGO_ACCT], [TANGO_ACCT_MAP_TXT], [TANGO_ACCT_TXT]) VALUES (N'A216322', N'216200', N'Accrd exps- Bonuses- Managements', N'Accrd exps, Salaries & Wages')
INSERT [dbo].[AM_TANGO] ([TANGO_GL_ACCT], [TANGO_ACCT], [TANGO_ACCT_MAP_TXT], [TANGO_ACCT_TXT]) VALUES (N'A216340', N'216963', N'Accrd exps, Compensated absence', N'Accrd exps, Compensated absence')
INSERT [dbo].[AM_TANGO] ([TANGO_GL_ACCT], [TANGO_ACCT], [TANGO_ACCT_MAP_TXT], [TANGO_ACCT_TXT]) VALUES (N'A216350', N'216200', N'Accrd exps, Welfare expense', N'Accrd exps, Salaries & Wages')
INSERT [dbo].[AM_TANGO] ([TANGO_GL_ACCT], [TANGO_ACCT], [TANGO_ACCT_MAP_TXT], [TANGO_ACCT_TXT]) VALUES (N'A216440', N'216000', N'Accrd exps, SGA freight', N'Accrd exps, SGA freight')
INSERT [dbo].[AM_TANGO] ([TANGO_GL_ACCT], [TANGO_ACCT], [TANGO_ACCT_MAP_TXT], [TANGO_ACCT_TXT]) VALUES (N'A216460', N'216200', N'Accrd exps, SGA sales commission, General', N'Accrd exps, Salaries & Wages')
INSERT [dbo].[AM_TANGO] ([TANGO_GL_ACCT], [TANGO_ACCT], [TANGO_ACCT_MAP_TXT], [TANGO_ACCT_TXT]) VALUES (N'A216500', N'216000', N'Accrd exps, SGA Consultant fee', N'Accrd exps, SGA freight')
INSERT [dbo].[AM_TANGO] ([TANGO_GL_ACCT], [TANGO_ACCT], [TANGO_ACCT_MAP_TXT], [TANGO_ACCT_TXT]) VALUES (N'A216510', N'216000', N'Accrd exps, SGA Advertising & promotion', N'Accrd exps, SGA freight')
INSERT [dbo].[AM_TANGO] ([TANGO_GL_ACCT], [TANGO_ACCT], [TANGO_ACCT_MAP_TXT], [TANGO_ACCT_TXT]) VALUES (N'A216900', N'216000', N'Accrd exps, Other1', N'Accrd exps, SGA freight')
INSERT [dbo].[AM_TANGO] ([TANGO_GL_ACCT], [TANGO_ACCT], [TANGO_ACCT_MAP_TXT], [TANGO_ACCT_TXT]) VALUES (N'A216901', N'216000', N'Accrd exps, EDP', N'Accrd exps, SGA freight')
INSERT [dbo].[AM_TANGO] ([TANGO_GL_ACCT], [TANGO_ACCT], [TANGO_ACCT_MAP_TXT], [TANGO_ACCT_TXT]) VALUES (N'A216902', N'216000', N'Accrued exps - SGA Other', N'Accrd exps, SGA freight')
INSERT [dbo].[AM_TANGO] ([TANGO_GL_ACCT], [TANGO_ACCT], [TANGO_ACCT_MAP_TXT], [TANGO_ACCT_TXT]) VALUES (N'A216903', N'216000', N'Accrd exps, Customer Svc', N'Accrd exps, SGA freight')
INSERT [dbo].[AM_TANGO] ([TANGO_GL_ACCT], [TANGO_ACCT], [TANGO_ACCT_MAP_TXT], [TANGO_ACCT_TXT]) VALUES (N'A216904', N'216000', N'Accrued Exp, COGS Others', N'Accrd exps, SGA freight')
INSERT [dbo].[AM_TANGO] ([TANGO_GL_ACCT], [TANGO_ACCT], [TANGO_ACCT_MAP_TXT], [TANGO_ACCT_TXT]) VALUES (N'A216990', N'216000', N'Accrd exps- FX Translation', N'Accrd exps, SGA freight')
INSERT [dbo].[AM_TANGO] ([TANGO_GL_ACCT], [TANGO_ACCT], [TANGO_ACCT_MAP_TXT], [TANGO_ACCT_TXT]) VALUES (N'A220010', N'220000', N'Tax payable on sales, General', N'Value added tax-payable')
INSERT [dbo].[AM_TANGO] ([TANGO_GL_ACCT], [TANGO_ACCT], [TANGO_ACCT_MAP_TXT], [TANGO_ACCT_TXT]) VALUES (N'A226035', N'226000', N'Deferred revenue-Current Loyalty Points', N'Advances received- General')
INSERT [dbo].[AM_TANGO] ([TANGO_GL_ACCT], [TANGO_ACCT], [TANGO_ACCT_MAP_TXT], [TANGO_ACCT_TXT]) VALUES (N'A226060', N'226000', N'Deferred revenue-current, Voucher', N'Advances received- General')
INSERT [dbo].[AM_TANGO] ([TANGO_GL_ACCT], [TANGO_ACCT], [TANGO_ACCT_MAP_TXT], [TANGO_ACCT_TXT]) VALUES (N'A229010', N'229000', N'Reserve for warranty, General', N'Reserve for warranty, General')
INSERT [dbo].[AM_TANGO] ([TANGO_GL_ACCT], [TANGO_ACCT], [TANGO_ACCT_MAP_TXT], [TANGO_ACCT_TXT]) VALUES (N'A231010', N'231000', N'Income tax payable- current- General', N'Income tax payable, National tax')
INSERT [dbo].[AM_TANGO] ([TANGO_GL_ACCT], [TANGO_ACCT], [TANGO_ACCT_MAP_TXT], [TANGO_ACCT_TXT]) VALUES (N'A232030', N'232000', N'Accrued other taxes, payroll1', N'Accrd exps, Salaries & Wages')
INSERT [dbo].[AM_TANGO] ([TANGO_GL_ACCT], [TANGO_ACCT], [TANGO_ACCT_MAP_TXT], [TANGO_ACCT_TXT]) VALUES (N'A232900', N'232000', N'Accrued other taxes, Other1', N'Accrued other taxes- payroll - PAYE')
INSERT [dbo].[AM_TANGO] ([TANGO_GL_ACCT], [TANGO_ACCT], [TANGO_ACCT_MAP_TXT], [TANGO_ACCT_TXT]) VALUES (N'A232990', N'232000', N'Accrued other taxes- FX Translation', N'Accrued other taxes- payroll - PAYE')
INSERT [dbo].[AM_TANGO] ([TANGO_GL_ACCT], [TANGO_ACCT], [TANGO_ACCT_MAP_TXT], [TANGO_ACCT_TXT]) VALUES (N'A237010', N'237000', N'Derivative liabilities-current- FX forward', N'Derivative liabilities-current- FX forward')
INSERT [dbo].[AM_TANGO] ([TANGO_GL_ACCT], [TANGO_ACCT], [TANGO_ACCT_MAP_TXT], [TANGO_ACCT_TXT]) VALUES (N'A247010', N'247071', N'Lease liability- Current portion of LTD', N'Current portion of long-term debts (lease)')
INSERT [dbo].[AM_TANGO] ([TANGO_GL_ACCT], [TANGO_ACCT], [TANGO_ACCT_MAP_TXT], [TANGO_ACCT_TXT]) VALUES (N'A247030', N'247071', N'Lease liability- Current Interest Accrual', N'Current portion of long-term debts (lease)')
INSERT [dbo].[AM_TANGO] ([TANGO_GL_ACCT], [TANGO_ACCT], [TANGO_ACCT_MAP_TXT], [TANGO_ACCT_TXT]) VALUES (N'A248010', N'248071', N'Current portion of LT debts (Op Lease)', N'Current portion of LT debts (Op Lease)')
INSERT [dbo].[AM_TANGO] ([TANGO_GL_ACCT], [TANGO_ACCT], [TANGO_ACCT_MAP_TXT], [TANGO_ACCT_TXT]) VALUES (N'A273020', N'273000', N'Other misc. CL-Deposits1', N'Other misc. CL, General')
INSERT [dbo].[AM_TANGO] ([TANGO_GL_ACCT], [TANGO_ACCT], [TANGO_ACCT_MAP_TXT], [TANGO_ACCT_TXT]) VALUES (N'A273030', N'273000', N'Other misc. CL- Deposits received- coupon/Point', N'Other misc. CL, General')
INSERT [dbo].[AM_TANGO] ([TANGO_GL_ACCT], [TANGO_ACCT], [TANGO_ACCT_MAP_TXT], [TANGO_ACCT_TXT]) VALUES (N'A307010', N'306071', N'Long Term Debts (Op Lease)', N'Long Term Debts (Op Lease)')
INSERT [dbo].[AM_TANGO] ([TANGO_GL_ACCT], [TANGO_ACCT], [TANGO_ACCT_MAP_TXT], [TANGO_ACCT_TXT]) VALUES (N'A313010', N'313006', N'Liability for DB&DC, severance(DB)', N'Net defined benefit liability (pension)')
INSERT [dbo].[AM_TANGO] ([TANGO_GL_ACCT], [TANGO_ACCT], [TANGO_ACCT_MAP_TXT], [TANGO_ACCT_TXT]) VALUES (N'A320010', N'320000', N'Asset retirement obligation-non-curr, General', N'Asset retirement obligation-non-curr, General')
INSERT [dbo].[AM_TANGO] ([TANGO_GL_ACCT], [TANGO_ACCT], [TANGO_ACCT_MAP_TXT], [TANGO_ACCT_TXT]) VALUES (N'A340040', N'340000', N'Other non-curr liabilities- Severance', N'Other miscellaneous non-current liabilities')
INSERT [dbo].[AM_TANGO] ([TANGO_GL_ACCT], [TANGO_ACCT], [TANGO_ACCT_MAP_TXT], [TANGO_ACCT_TXT]) VALUES (N'A411010', N'411000', N'Common stock, General', N'Common stock, General')
INSERT [dbo].[AM_TANGO] ([TANGO_GL_ACCT], [TANGO_ACCT], [TANGO_ACCT_MAP_TXT], [TANGO_ACCT_TXT]) VALUES (N'A443010', N'443000', N'R/E other than legal reserve, R/E brought forward', N'R/E other than legal reserve, R/E brought forward')
INSERT [dbo].[AM_TANGO] ([TANGO_GL_ACCT], [TANGO_ACCT], [TANGO_ACCT_MAP_TXT], [TANGO_ACCT_TXT]) VALUES (N'A443090', N'443000', N'Controlling Interest - Dividend paid', N'Controlling Interest - Dividend paid')
INSERT [dbo].[AM_TANGO] ([TANGO_GL_ACCT], [TANGO_ACCT], [TANGO_ACCT_MAP_TXT], [TANGO_ACCT_TXT]) VALUES (N'A505010', N'505100', N'COGS- Products', N'Cost of sales')
INSERT [dbo].[AM_TANGO] ([TANGO_GL_ACCT], [TANGO_ACCT], [TANGO_ACCT_MAP_TXT], [TANGO_ACCT_TXT]) VALUES (N'A505030', N'505100', N'COGS- Other', N'Cost of sales')
INSERT [dbo].[AM_TANGO] ([TANGO_GL_ACCT], [TANGO_ACCT], [TANGO_ACCT_MAP_TXT], [TANGO_ACCT_TXT]) VALUES (N'A505040', N'505100', N'COGS- Service & Repair', N'Cost of sales')
INSERT [dbo].[AM_TANGO] ([TANGO_GL_ACCT], [TANGO_ACCT], [TANGO_ACCT_MAP_TXT], [TANGO_ACCT_TXT]) VALUES (N'A505055', N'505100', N'COGS - Spare Parts', N'Cost of sales')
INSERT [dbo].[AM_TANGO] ([TANGO_GL_ACCT], [TANGO_ACCT], [TANGO_ACCT_MAP_TXT], [TANGO_ACCT_TXT]) VALUES (N'A505300', N'505700', N'COGS- Devaluation', N'Inventory devaluation')
INSERT [dbo].[AM_TANGO] ([TANGO_GL_ACCT], [TANGO_ACCT], [TANGO_ACCT_MAP_TXT], [TANGO_ACCT_TXT]) VALUES (N'A505410', N'505900', N'COGS- Special loss on disposal of inventories', N'Other cost')
INSERT [dbo].[AM_TANGO] ([TANGO_GL_ACCT], [TANGO_ACCT], [TANGO_ACCT_MAP_TXT], [TANGO_ACCT_TXT]) VALUES (N'A531010', N'531010', N'NOE- Interest on borrowing', N'NOE/Interest expenses')
INSERT [dbo].[AM_TANGO] ([TANGO_GL_ACCT], [TANGO_ACCT], [TANGO_ACCT_MAP_TXT], [TANGO_ACCT_TXT]) VALUES (N'A531110', N'531020', N'NOE/ Intr exps on liability to make lease payments', N'NOE/ Intr exps on liability to make lease payments')
INSERT [dbo].[AM_TANGO] ([TANGO_GL_ACCT], [TANGO_ACCT], [TANGO_ACCT_MAP_TXT], [TANGO_ACCT_TXT]) VALUES (N'A531400', N'531419', N'NOE- FX Translation losses', N'NOE- FX Translation losses')
INSERT [dbo].[AM_TANGO] ([TANGO_GL_ACCT], [TANGO_ACCT], [TANGO_ACCT_MAP_TXT], [TANGO_ACCT_TXT]) VALUES (N'A531510', N'531181', N'NOE- ARO accretion expense', N'NOE/ARO accretion expense')
INSERT [dbo].[AM_TANGO] ([TANGO_GL_ACCT], [TANGO_ACCT], [TANGO_ACCT_MAP_TXT], [TANGO_ACCT_TXT]) VALUES (N'A531900', N'531995', N'NOE- Other1', N'NOE/Other')
INSERT [dbo].[AM_TANGO] ([TANGO_GL_ACCT], [TANGO_ACCT], [TANGO_ACCT_MAP_TXT], [TANGO_ACCT_TXT]) VALUES (N'A542010', N'542000', N'Current income tax expense- National tax', N'Current income tax expense')
INSERT [dbo].[AM_TANGO] ([TANGO_GL_ACCT], [TANGO_ACCT], [TANGO_ACCT_MAP_TXT], [TANGO_ACCT_TXT]) VALUES (N'A543010', N'543000', N'Deferred income tax expense- National tax', N'Deferred income tax expense- National tax')
INSERT [dbo].[AM_TANGO] ([TANGO_GL_ACCT], [TANGO_ACCT], [TANGO_ACCT_MAP_TXT], [TANGO_ACCT_TXT]) VALUES (N'A621010', N'621000', N'Gross Sales- Products', N'Gross Sales- Products')
INSERT [dbo].[AM_TANGO] ([TANGO_GL_ACCT], [TANGO_ACCT], [TANGO_ACCT_MAP_TXT], [TANGO_ACCT_TXT]) VALUES (N'A621050', N'621000', N'Gross Sales- Service & Repair', N'Gross Sales- Products')
INSERT [dbo].[AM_TANGO] ([TANGO_GL_ACCT], [TANGO_ACCT], [TANGO_ACCT_MAP_TXT], [TANGO_ACCT_TXT]) VALUES (N'A621055', N'621000', N'Gross Sales - Spare Parts', N'Gross Sales- Products')
INSERT [dbo].[AM_TANGO] ([TANGO_GL_ACCT], [TANGO_ACCT], [TANGO_ACCT_MAP_TXT], [TANGO_ACCT_TXT]) VALUES (N'A622110', N'622011', N'Sales reduction, On-invoice discount Merchandise', N'On invoice discount')
INSERT [dbo].[AM_TANGO] ([TANGO_GL_ACCT], [TANGO_ACCT], [TANGO_ACCT_MAP_TXT], [TANGO_ACCT_TXT]) VALUES (N'A622111', N'622011', N'Sales reduction, On-invoice discount Spare Parts', N'On invoice discount')
INSERT [dbo].[AM_TANGO] ([TANGO_GL_ACCT], [TANGO_ACCT], [TANGO_ACCT_MAP_TXT], [TANGO_ACCT_TXT]) VALUES (N'A622112', N'622011', N'Sales reduction, On-invoice discount Round diff', N'On invoice discount')
INSERT [dbo].[AM_TANGO] ([TANGO_GL_ACCT], [TANGO_ACCT], [TANGO_ACCT_MAP_TXT], [TANGO_ACCT_TXT]) VALUES (N'A622210', N'622021', N'Sales reduction, Co-op AD(Activity)', N'Co-op ad&pro')
INSERT [dbo].[AM_TANGO] ([TANGO_GL_ACCT], [TANGO_ACCT], [TANGO_ACCT_MAP_TXT], [TANGO_ACCT_TXT]) VALUES (N'A622310', N'622031', N'Sales reduction, Stock Compensation(Activity)', N'Stock compensation')
INSERT [dbo].[AM_TANGO] ([TANGO_GL_ACCT], [TANGO_ACCT], [TANGO_ACCT_MAP_TXT], [TANGO_ACCT_TXT]) VALUES (N'A622311', N'622031', N'Sales reduction, Stock Compensation (General)', N'Stock compensation')
INSERT [dbo].[AM_TANGO] ([TANGO_GL_ACCT], [TANGO_ACCT], [TANGO_ACCT_MAP_TXT], [TANGO_ACCT_TXT]) VALUES (N'A622424', N'622041', N'Sales reduction, Sell Thru/Promo Rebate (Activity)', N'Rebate')
INSERT [dbo].[AM_TANGO] ([TANGO_GL_ACCT], [TANGO_ACCT], [TANGO_ACCT_MAP_TXT], [TANGO_ACCT_TXT]) VALUES (N'A622425', N'622041', N'Sales reduction, Sell Thru/Promo Rebate (General)', N'Rebate')
INSERT [dbo].[AM_TANGO] ([TANGO_GL_ACCT], [TANGO_ACCT], [TANGO_ACCT_MAP_TXT], [TANGO_ACCT_TXT]) VALUES (N'A622430', N'622041', N'Sales reduction, Sell-in allowance (Activity)', N'Rebate')
INSERT [dbo].[AM_TANGO] ([TANGO_GL_ACCT], [TANGO_ACCT], [TANGO_ACCT_MAP_TXT], [TANGO_ACCT_TXT]) VALUES (N'A622431', N'622041', N'Sales reduction, Sell-in allowance (General)', N'Rebate')
INSERT [dbo].[AM_TANGO] ([TANGO_GL_ACCT], [TANGO_ACCT], [TANGO_ACCT_MAP_TXT], [TANGO_ACCT_TXT]) VALUES (N'A622620', N'622901', N'Sales reduction, Other manual price adj', N'Other sales adjustment')
INSERT [dbo].[AM_TANGO] ([TANGO_GL_ACCT], [TANGO_ACCT], [TANGO_ACCT_MAP_TXT], [TANGO_ACCT_TXT]) VALUES (N'A625900', N'625900', N'OPR- Other1', N'OPR- Other1')
INSERT [dbo].[AM_TANGO] ([TANGO_GL_ACCT], [TANGO_ACCT], [TANGO_ACCT_MAP_TXT], [TANGO_ACCT_TXT]) VALUES (N'A631010', N'631010', N'NOR- Interest income', N'NOR- Interest income')
INSERT [dbo].[AM_TANGO] ([TANGO_GL_ACCT], [TANGO_ACCT], [TANGO_ACCT_MAP_TXT], [TANGO_ACCT_TXT]) VALUES (N'A631300', N'631410', N'NOR- FX Translation gain', N'NOR- FX Translation gain')
INSERT [dbo].[AM_TANGO] ([TANGO_GL_ACCT], [TANGO_ACCT], [TANGO_ACCT_MAP_TXT], [TANGO_ACCT_TXT]) VALUES (N'A631900', N'631127', N'NOR- Other1', N'NOR/Other')
INSERT [dbo].[AM_TANGO] ([TANGO_GL_ACCT], [TANGO_ACCT], [TANGO_ACCT_MAP_TXT], [TANGO_ACCT_TXT]) VALUES (N'A702010', N'702000', N'S&W- Base salaries', N'S&W- Base salaries')
INSERT [dbo].[AM_TANGO] ([TANGO_GL_ACCT], [TANGO_ACCT], [TANGO_ACCT_MAP_TXT], [TANGO_ACCT_TXT]) VALUES (N'A702011', N'702000', N'S&W- Base salaries(Management)', N'S&W- Base salaries')
INSERT [dbo].[AM_TANGO] ([TANGO_GL_ACCT], [TANGO_ACCT], [TANGO_ACCT_MAP_TXT], [TANGO_ACCT_TXT]) VALUES (N'A702100', N'702000', N'S&W- Temporary employees', N'S&W- Base salaries')
INSERT [dbo].[AM_TANGO] ([TANGO_GL_ACCT], [TANGO_ACCT], [TANGO_ACCT_MAP_TXT], [TANGO_ACCT_TXT]) VALUES (N'A702200', N'702981', N'S&W- Compensated absence', N'S&W- Compensated absence')
INSERT [dbo].[AM_TANGO] ([TANGO_GL_ACCT], [TANGO_ACCT], [TANGO_ACCT_MAP_TXT], [TANGO_ACCT_TXT]) VALUES (N'A702900', N'702000', N'S&W- Other1', N'S&W- Base salaries')
INSERT [dbo].[AM_TANGO] ([TANGO_GL_ACCT], [TANGO_ACCT], [TANGO_ACCT_MAP_TXT], [TANGO_ACCT_TXT]) VALUES (N'A702910', N'702000', N'S&W- Taxation remuneration in kind VAT full rate', N'S&W- Base salaries')
INSERT [dbo].[AM_TANGO] ([TANGO_GL_ACCT], [TANGO_ACCT], [TANGO_ACCT_MAP_TXT], [TANGO_ACCT_TXT]) VALUES (N'A703010', N'703000', N'Bonuses & allowance- General', N'MFC/Bonuses')
INSERT [dbo].[AM_TANGO] ([TANGO_GL_ACCT], [TANGO_ACCT], [TANGO_ACCT_MAP_TXT], [TANGO_ACCT_TXT]) VALUES (N'A703020', N'703000', N'Bonuses & allowance- Management', N'MFC/Bonuses')
INSERT [dbo].[AM_TANGO] ([TANGO_GL_ACCT], [TANGO_ACCT], [TANGO_ACCT_MAP_TXT], [TANGO_ACCT_TXT]) VALUES (N'A704300R', N'804040', N'Retirement bnf exps- Termination(Restructuring)', N'SGA/Termination benefits')
INSERT [dbo].[AM_TANGO] ([TANGO_GL_ACCT], [TANGO_ACCT], [TANGO_ACCT_MAP_TXT], [TANGO_ACCT_TXT]) VALUES (N'A705010', N'705000', N'Social security- Unemployment act contribution', N'MFC/Social security')
INSERT [dbo].[AM_TANGO] ([TANGO_GL_ACCT], [TANGO_ACCT], [TANGO_ACCT_MAP_TXT], [TANGO_ACCT_TXT]) VALUES (N'A705050', N'705000', N'Social security- Insurance1', N'MFC/Social security')
INSERT [dbo].[AM_TANGO] ([TANGO_GL_ACCT], [TANGO_ACCT], [TANGO_ACCT_MAP_TXT], [TANGO_ACCT_TXT]) VALUES (N'A706010', N'706000', N'Welfare exps- Private Healthcare Insurance', N'MFC/Welfare')
INSERT [dbo].[AM_TANGO] ([TANGO_GL_ACCT], [TANGO_ACCT], [TANGO_ACCT_MAP_TXT], [TANGO_ACCT_TXT]) VALUES (N'A706900', N'706000', N'Welfare exps- Other1', N'MFC/Welfare')
INSERT [dbo].[AM_TANGO] ([TANGO_GL_ACCT], [TANGO_ACCT], [TANGO_ACCT_MAP_TXT], [TANGO_ACCT_TXT]) VALUES (N'A706901', N'706000', N'Welfare exps- Other2', N'MFC/Welfare')
INSERT [dbo].[AM_TANGO] ([TANGO_GL_ACCT], [TANGO_ACCT], [TANGO_ACCT_MAP_TXT], [TANGO_ACCT_TXT]) VALUES (N'A706902', N'706000', N'Welfare exps,General Expat', N'MFC/Welfare')
INSERT [dbo].[AM_TANGO] ([TANGO_GL_ACCT], [TANGO_ACCT], [TANGO_ACCT_MAP_TXT], [TANGO_ACCT_TXT]) VALUES (N'A711010', N'711000', N'Freight- Finished goods freightage(Ship)', N'MFC/Inbound freight')
INSERT [dbo].[AM_TANGO] ([TANGO_GL_ACCT], [TANGO_ACCT], [TANGO_ACCT_MAP_TXT], [TANGO_ACCT_TXT]) VALUES (N'A711020', N'711000', N'Freight- Finished goods freightage(Air)', N'MFC/Inbound freight')
INSERT [dbo].[AM_TANGO] ([TANGO_GL_ACCT], [TANGO_ACCT], [TANGO_ACCT_MAP_TXT], [TANGO_ACCT_TXT]) VALUES (N'A711030', N'711000', N'Freight- Finished goods freightage(Land)', N'MFC/Inbound freight')
INSERT [dbo].[AM_TANGO] ([TANGO_GL_ACCT], [TANGO_ACCT], [TANGO_ACCT_MAP_TXT], [TANGO_ACCT_TXT]) VALUES (N'A711100', N'711000', N'Freight- Office cost on export', N'MFC/Inbound freight')
INSERT [dbo].[AM_TANGO] ([TANGO_GL_ACCT], [TANGO_ACCT], [TANGO_ACCT_MAP_TXT], [TANGO_ACCT_TXT]) VALUES (N'A711900', N'711000', N'Freight- Other1', N'MFC/Inbound freight')
INSERT [dbo].[AM_TANGO] ([TANGO_GL_ACCT], [TANGO_ACCT], [TANGO_ACCT_MAP_TXT], [TANGO_ACCT_TXT]) VALUES (N'A712010', N'712000', N'Equipment- tools & software expensed- E&T', N'MFC/Equipment & tools expensed excl. molding dies')
INSERT [dbo].[AM_TANGO] ([TANGO_GL_ACCT], [TANGO_ACCT], [TANGO_ACCT_MAP_TXT], [TANGO_ACCT_TXT]) VALUES (N'A712100', N'712000', N'Equipment- tools & software expensed- Soft', N'MFC/Equipment & tools expensed excl. molding dies')
INSERT [dbo].[AM_TANGO] ([TANGO_GL_ACCT], [TANGO_ACCT], [TANGO_ACCT_MAP_TXT], [TANGO_ACCT_TXT]) VALUES (N'A714010', N'714000', N'Utilities exps- Electrical power', N'MFC/Electricity- water & gas')
INSERT [dbo].[AM_TANGO] ([TANGO_GL_ACCT], [TANGO_ACCT], [TANGO_ACCT_MAP_TXT], [TANGO_ACCT_TXT]) VALUES (N'A714020', N'714000', N'Utilities exps- Water charges', N'MFC/Electricity- water & gas')
INSERT [dbo].[AM_TANGO] ([TANGO_GL_ACCT], [TANGO_ACCT], [TANGO_ACCT_MAP_TXT], [TANGO_ACCT_TXT]) VALUES (N'A722010', N'722000', N'R&T exps- Recruiting expense', N'MFC/Recruting & training')
INSERT [dbo].[AM_TANGO] ([TANGO_GL_ACCT], [TANGO_ACCT], [TANGO_ACCT_MAP_TXT], [TANGO_ACCT_TXT]) VALUES (N'A722020', N'722000', N'R&T exps- Training exps', N'MFC/Recruting & training')
INSERT [dbo].[AM_TANGO] ([TANGO_GL_ACCT], [TANGO_ACCT], [TANGO_ACCT_MAP_TXT], [TANGO_ACCT_TXT]) VALUES (N'A722020R', N'722000', N'R&T exps- Training exps (Restructuring)', N'MFC/Recruting & training')
INSERT [dbo].[AM_TANGO] ([TANGO_GL_ACCT], [TANGO_ACCT], [TANGO_ACCT_MAP_TXT], [TANGO_ACCT_TXT]) VALUES (N'A723010', N'723000', N'Travelling & commutation- Fare', N'MFC/Travelling & commutation')
INSERT [dbo].[AM_TANGO] ([TANGO_GL_ACCT], [TANGO_ACCT], [TANGO_ACCT_MAP_TXT], [TANGO_ACCT_TXT]) VALUES (N'A723020', N'723000', N'Travelling & commutation- Accommodation', N'MFC/Travelling & commutation')
INSERT [dbo].[AM_TANGO] ([TANGO_GL_ACCT], [TANGO_ACCT], [TANGO_ACCT_MAP_TXT], [TANGO_ACCT_TXT]) VALUES (N'A723900', N'723000', N'Travelling & commutation- Other1', N'MFC/Travelling & commutation')
INSERT [dbo].[AM_TANGO] ([TANGO_GL_ACCT], [TANGO_ACCT], [TANGO_ACCT_MAP_TXT], [TANGO_ACCT_TXT]) VALUES (N'A725010', N'725000', N'Commu exps- Postal exps', N'MFC/Communication expense')
INSERT [dbo].[AM_TANGO] ([TANGO_GL_ACCT], [TANGO_ACCT], [TANGO_ACCT_MAP_TXT], [TANGO_ACCT_TXT]) VALUES (N'A725030', N'725000', N'Commu exps- Cell phone & Land phone', N'MFC/Communication expense')
INSERT [dbo].[AM_TANGO] ([TANGO_GL_ACCT], [TANGO_ACCT], [TANGO_ACCT_MAP_TXT], [TANGO_ACCT_TXT]) VALUES (N'A726010', N'726000', N'Meals and Entmt exps, Meal', N'MFC/Entertainment')
INSERT [dbo].[AM_TANGO] ([TANGO_GL_ACCT], [TANGO_ACCT], [TANGO_ACCT_MAP_TXT], [TANGO_ACCT_TXT]) VALUES (N'A731900', N'731000', N'Insurance exps, Other1', N'MFC/Insurance')
INSERT [dbo].[AM_TANGO] ([TANGO_GL_ACCT], [TANGO_ACCT], [TANGO_ACCT_MAP_TXT], [TANGO_ACCT_TXT]) VALUES (N'A731920', N'731000', N'Insurance exps, Credit insurance', N'MFC/Insurance')
GO
INSERT [dbo].[AM_TANGO] ([TANGO_GL_ACCT], [TANGO_ACCT], [TANGO_ACCT_MAP_TXT], [TANGO_ACCT_TXT]) VALUES (N'A732010', N'732000', N'Repair&maintenance exps, M&Es', N'MFC/Repair & maintenance')
INSERT [dbo].[AM_TANGO] ([TANGO_GL_ACCT], [TANGO_ACCT], [TANGO_ACCT_MAP_TXT], [TANGO_ACCT_TXT]) VALUES (N'A732020', N'732000', N'Repair&maintenance exps, Bld/LI/struc', N'MFC/Repair & maintenance')
INSERT [dbo].[AM_TANGO] ([TANGO_GL_ACCT], [TANGO_ACCT], [TANGO_ACCT_MAP_TXT], [TANGO_ACCT_TXT]) VALUES (N'A733040', N'733100', N'Dep, M&Es', N'MFC/Depreciation of PP&E excl. molding dies')
INSERT [dbo].[AM_TANGO] ([TANGO_GL_ACCT], [TANGO_ACCT], [TANGO_ACCT_MAP_TXT], [TANGO_ACCT_TXT]) VALUES (N'A733220', N'733500', N'Dep- Ext. Software for own use(Amort)', N'MFC/Software amortization')
INSERT [dbo].[AM_TANGO] ([TANGO_GL_ACCT], [TANGO_ACCT], [TANGO_ACCT_MAP_TXT], [TANGO_ACCT_TXT]) VALUES (N'A733300', N'733400', N'Dep, Lease assets-buildings(Operating)', N'MFC/Depreciation (Right-of-use assets) (lessee)')
INSERT [dbo].[AM_TANGO] ([TANGO_GL_ACCT], [TANGO_ACCT], [TANGO_ACCT_MAP_TXT], [TANGO_ACCT_TXT]) VALUES (N'A733360', N'733400', N'Dep- Lease assets-vehicles(Amort)', N'MFC/Depreciation (Right-of-use assets) (lessee)')
INSERT [dbo].[AM_TANGO] ([TANGO_GL_ACCT], [TANGO_ACCT], [TANGO_ACCT_MAP_TXT], [TANGO_ACCT_TXT]) VALUES (N'A741010N', N'841000', N'Donation, General (Non deductible)', N'Donation, General')
INSERT [dbo].[AM_TANGO] ([TANGO_GL_ACCT], [TANGO_ACCT], [TANGO_ACCT_MAP_TXT], [TANGO_ACCT_TXT]) VALUES (N'A742010', N'742200', N'misc. tax, Consumption tax', N'MFC/Miscellaneous tax')
INSERT [dbo].[AM_TANGO] ([TANGO_GL_ACCT], [TANGO_ACCT], [TANGO_ACCT_MAP_TXT], [TANGO_ACCT_TXT]) VALUES (N'A743010', N'743000', N'Storage, Finished goods storage fee', N'Storage, Finished goods storage fee')
INSERT [dbo].[AM_TANGO] ([TANGO_GL_ACCT], [TANGO_ACCT], [TANGO_ACCT_MAP_TXT], [TANGO_ACCT_TXT]) VALUES (N'A744020', N'744000', N'misc. exps, Books & magazines', N'MFC/Other')
INSERT [dbo].[AM_TANGO] ([TANGO_GL_ACCT], [TANGO_ACCT], [TANGO_ACCT_MAP_TXT], [TANGO_ACCT_TXT]) VALUES (N'A744030', N'744000', N'misc. exps, Conference exps', N'MFC/Other')
INSERT [dbo].[AM_TANGO] ([TANGO_GL_ACCT], [TANGO_ACCT], [TANGO_ACCT_MAP_TXT], [TANGO_ACCT_TXT]) VALUES (N'A744040N', N'744000', N'misc. exps, Vehicle Expenses (ND)', N'MFC/Other')
INSERT [dbo].[AM_TANGO] ([TANGO_GL_ACCT], [TANGO_ACCT], [TANGO_ACCT_MAP_TXT], [TANGO_ACCT_TXT]) VALUES (N'A744050', N'744000', N'misc. exps, Bank commissions', N'MFC/Other')
INSERT [dbo].[AM_TANGO] ([TANGO_GL_ACCT], [TANGO_ACCT], [TANGO_ACCT_MAP_TXT], [TANGO_ACCT_TXT]) VALUES (N'A744720', N'744000', N'misc. exps- Other MFC related expenses 2', N'MFC/Other')
INSERT [dbo].[AM_TANGO] ([TANGO_GL_ACCT], [TANGO_ACCT], [TANGO_ACCT_MAP_TXT], [TANGO_ACCT_TXT]) VALUES (N'A744800', N'744000', N'misc. exps, Outgoing recharge', N'MFC/Other')
INSERT [dbo].[AM_TANGO] ([TANGO_GL_ACCT], [TANGO_ACCT], [TANGO_ACCT_MAP_TXT], [TANGO_ACCT_TXT]) VALUES (N'A744900', N'744000', N'misc. exps, Other1', N'MFC/Other')
INSERT [dbo].[AM_TANGO] ([TANGO_GL_ACCT], [TANGO_ACCT], [TANGO_ACCT_MAP_TXT], [TANGO_ACCT_TXT]) VALUES (N'A745030', N'745000', N'Rent exps- Company housings', N'MFC/Rental expense')
INSERT [dbo].[AM_TANGO] ([TANGO_GL_ACCT], [TANGO_ACCT], [TANGO_ACCT_MAP_TXT], [TANGO_ACCT_TXT]) VALUES (N'A745035', N'745000', N'Rent Exps- Company housings (SysInt)', N'MFC/Rental expense')
INSERT [dbo].[AM_TANGO] ([TANGO_GL_ACCT], [TANGO_ACCT], [TANGO_ACCT_MAP_TXT], [TANGO_ACCT_TXT]) VALUES (N'A745080N', N'745000', N'Rent exps, Vehicles exps(ND)', N'MFC/Rental expense')
INSERT [dbo].[AM_TANGO] ([TANGO_GL_ACCT], [TANGO_ACCT], [TANGO_ACCT_MAP_TXT], [TANGO_ACCT_TXT]) VALUES (N'A745090', N'745000', N'Rent exps, Office rent', N'MFC/Rental expense')
INSERT [dbo].[AM_TANGO] ([TANGO_GL_ACCT], [TANGO_ACCT], [TANGO_ACCT_MAP_TXT], [TANGO_ACCT_TXT]) VALUES (N'A745095', N'745000', N'Rent Exps, Office rent (SysInt)', N'MFC/Rental expense')
INSERT [dbo].[AM_TANGO] ([TANGO_GL_ACCT], [TANGO_ACCT], [TANGO_ACCT_MAP_TXT], [TANGO_ACCT_TXT]) VALUES (N'A745110', N'745000', N'Rent Exps- Rental Cars', N'MFC/Rental expense')
INSERT [dbo].[AM_TANGO] ([TANGO_GL_ACCT], [TANGO_ACCT], [TANGO_ACCT_MAP_TXT], [TANGO_ACCT_TXT]) VALUES (N'A745115', N'745000', N'Rent Exps- Rental Cars (SysInt)', N'MFC/Rental expense')
INSERT [dbo].[AM_TANGO] ([TANGO_GL_ACCT], [TANGO_ACCT], [TANGO_ACCT_MAP_TXT], [TANGO_ACCT_TXT]) VALUES (N'A745900', N'745000', N'Rent exps, Other1', N'MFC/Rental expense')
INSERT [dbo].[AM_TANGO] ([TANGO_GL_ACCT], [TANGO_ACCT], [TANGO_ACCT_MAP_TXT], [TANGO_ACCT_TXT]) VALUES (N'A748010', N'848200', N'Prof service fee, CPA Audit fee', N'SGA/Independent auditors'' fee')
INSERT [dbo].[AM_TANGO] ([TANGO_GL_ACCT], [TANGO_ACCT], [TANGO_ACCT_MAP_TXT], [TANGO_ACCT_TXT]) VALUES (N'A748020', N'748008', N'Prof service fee, Temp staff service fee (agency)', N'MFC/Temporary staff service fee')
INSERT [dbo].[AM_TANGO] ([TANGO_GL_ACCT], [TANGO_ACCT], [TANGO_ACCT_MAP_TXT], [TANGO_ACCT_TXT]) VALUES (N'A748030', N'748100', N'Prof service fee, Legal Services', N'MFC/Legal expense')
INSERT [dbo].[AM_TANGO] ([TANGO_GL_ACCT], [TANGO_ACCT], [TANGO_ACCT_MAP_TXT], [TANGO_ACCT_TXT]) VALUES (N'A748050', N'748000', N'Prof service fee, Other consultant fees', N'SGA/Other professional service fee')
INSERT [dbo].[AM_TANGO] ([TANGO_GL_ACCT], [TANGO_ACCT], [TANGO_ACCT_MAP_TXT], [TANGO_ACCT_TXT]) VALUES (N'A748060', N'748000', N'Prof service fee, Market research', N'SGA/Other professional service fee')
INSERT [dbo].[AM_TANGO] ([TANGO_GL_ACCT], [TANGO_ACCT], [TANGO_ACCT_MAP_TXT], [TANGO_ACCT_TXT]) VALUES (N'A748090', N'748000', N'Prof service fee, Business Process Outsourcing', N'SGA/Other professional service fee')
INSERT [dbo].[AM_TANGO] ([TANGO_GL_ACCT], [TANGO_ACCT], [TANGO_ACCT_MAP_TXT], [TANGO_ACCT_TXT]) VALUES (N'A749020', N'749000', N'Dep(ARO)- L/h impr', N'MFC/Depreciation (ARO)')
INSERT [dbo].[AM_TANGO] ([TANGO_GL_ACCT], [TANGO_ACCT], [TANGO_ACCT_MAP_TXT], [TANGO_ACCT_TXT]) VALUES (N'A750010', N'750000', N'IS Service Fee- H/W maintenance', N'MFC/Information system service fee')
INSERT [dbo].[AM_TANGO] ([TANGO_GL_ACCT], [TANGO_ACCT], [TANGO_ACCT_MAP_TXT], [TANGO_ACCT_TXT]) VALUES (N'A750011', N'750000', N'IS Service Fee- S/W maintenance', N'MFC/Information system service fee')
INSERT [dbo].[AM_TANGO] ([TANGO_GL_ACCT], [TANGO_ACCT], [TANGO_ACCT_MAP_TXT], [TANGO_ACCT_TXT]) VALUES (N'A750020', N'750000', N'IS Service Fee- Network', N'MFC/Information system service fee')
INSERT [dbo].[AM_TANGO] ([TANGO_GL_ACCT], [TANGO_ACCT], [TANGO_ACCT_MAP_TXT], [TANGO_ACCT_TXT]) VALUES (N'A750900', N'750000', N'IS Service Fee- Other', N'MFC/Information system service fee')
INSERT [dbo].[AM_TANGO] ([TANGO_GL_ACCT], [TANGO_ACCT], [TANGO_ACCT_MAP_TXT], [TANGO_ACCT_TXT]) VALUES (N'A771010', N'871000', N'AD&Pro exps, Media expenses, Newspaper', N'SGA/Advertising & sales promotion')
INSERT [dbo].[AM_TANGO] ([TANGO_GL_ACCT], [TANGO_ACCT], [TANGO_ACCT_MAP_TXT], [TANGO_ACCT_TXT]) VALUES (N'A771040', N'871000', N'AD&Pro exps, Media, Outdoor/Transit advertising', N'SGA/Advertising & sales promotion')
INSERT [dbo].[AM_TANGO] ([TANGO_GL_ACCT], [TANGO_ACCT], [TANGO_ACCT_MAP_TXT], [TANGO_ACCT_TXT]) VALUES (N'A771090', N'871000', N'AD&Pro exps- Media expenses- Internet others', N'SGA/Advertising & sales promotion')
INSERT [dbo].[AM_TANGO] ([TANGO_GL_ACCT], [TANGO_ACCT], [TANGO_ACCT_MAP_TXT], [TANGO_ACCT_TXT]) VALUES (N'A771090N', N'871000', N'AD&Pro exps-Key Opinion leader (influenc', N'SGA/Advertising & sales promotion')
INSERT [dbo].[AM_TANGO] ([TANGO_GL_ACCT], [TANGO_ACCT], [TANGO_ACCT_MAP_TXT], [TANGO_ACCT_TXT]) VALUES (N'A771100N', N'871000', N'AD&Pro exps-Maintenance, repair', N'SGA/Advertising & sales promotion')
INSERT [dbo].[AM_TANGO] ([TANGO_GL_ACCT], [TANGO_ACCT], [TANGO_ACCT_MAP_TXT], [TANGO_ACCT_TXT]) VALUES (N'A771106', N'871000', N'AD&pro exps – Digital production', N'SGA/Advertising & sales promotion')
INSERT [dbo].[AM_TANGO] ([TANGO_GL_ACCT], [TANGO_ACCT], [TANGO_ACCT_MAP_TXT], [TANGO_ACCT_TXT]) VALUES (N'A771110', N'871000', N'AD&Pro exps, Sponsorship', N'SGA/Advertising & sales promotion')
INSERT [dbo].[AM_TANGO] ([TANGO_GL_ACCT], [TANGO_ACCT], [TANGO_ACCT_MAP_TXT], [TANGO_ACCT_TXT]) VALUES (N'A771111', N'871000', N'AD&Pro exps- Dealer Support', N'SGA/Advertising & sales promotion')
INSERT [dbo].[AM_TANGO] ([TANGO_GL_ACCT], [TANGO_ACCT], [TANGO_ACCT_MAP_TXT], [TANGO_ACCT_TXT]) VALUES (N'A771200', N'871000', N'AD&Pro exps- Promoter expenses', N'SGA/Advertising & sales promotion')
INSERT [dbo].[AM_TANGO] ([TANGO_GL_ACCT], [TANGO_ACCT], [TANGO_ACCT_MAP_TXT], [TANGO_ACCT_TXT]) VALUES (N'A771210', N'871000', N'AD&Pro exps, Event&Exhibition', N'SGA/Advertising & sales promotion')
INSERT [dbo].[AM_TANGO] ([TANGO_GL_ACCT], [TANGO_ACCT], [TANGO_ACCT_MAP_TXT], [TANGO_ACCT_TXT]) VALUES (N'A771210N', N'871000', N'AD&Pro exps-Product Seminar / Workshops', N'SGA/Advertising & sales promotion')
INSERT [dbo].[AM_TANGO] ([TANGO_GL_ACCT], [TANGO_ACCT], [TANGO_ACCT_MAP_TXT], [TANGO_ACCT_TXT]) VALUES (N'A771211', N'871000', N'AD&Pro exps- PR & Press Events', N'SGA/Advertising & sales promotion')
INSERT [dbo].[AM_TANGO] ([TANGO_GL_ACCT], [TANGO_ACCT], [TANGO_ACCT_MAP_TXT], [TANGO_ACCT_TXT]) VALUES (N'A771220', N'871000', N'AD&Pro exps, Others, Sample', N'SGA/Advertising & sales promotion')
INSERT [dbo].[AM_TANGO] ([TANGO_GL_ACCT], [TANGO_ACCT], [TANGO_ACCT_MAP_TXT], [TANGO_ACCT_TXT]) VALUES (N'A771220N', N'871000', N'AD&Pro exps- Dealer convention', N'SGA/Advertising & sales promotion')
INSERT [dbo].[AM_TANGO] ([TANGO_GL_ACCT], [TANGO_ACCT], [TANGO_ACCT_MAP_TXT], [TANGO_ACCT_TXT]) VALUES (N'A771230', N'871000', N'AD&Pro exps, Others, Give Away', N'SGA/Advertising & sales promotion')
INSERT [dbo].[AM_TANGO] ([TANGO_GL_ACCT], [TANGO_ACCT], [TANGO_ACCT_MAP_TXT], [TANGO_ACCT_TXT]) VALUES (N'A771230N', N'871000', N'AD&Pro exps-Product Seminar / Workshops', N'SGA/Advertising & sales promotion')
INSERT [dbo].[AM_TANGO] ([TANGO_GL_ACCT], [TANGO_ACCT], [TANGO_ACCT_MAP_TXT], [TANGO_ACCT_TXT]) VALUES (N'A771240', N'871000', N'AD&Pro exps, Incentive Trips/Training', N'SGA/Advertising & sales promotion')
INSERT [dbo].[AM_TANGO] ([TANGO_GL_ACCT], [TANGO_ACCT], [TANGO_ACCT_MAP_TXT], [TANGO_ACCT_TXT]) VALUES (N'A771300', N'871000', N'AD&Pro exps, Shop front communication, POP', N'SGA/Advertising & sales promotion')
INSERT [dbo].[AM_TANGO] ([TANGO_GL_ACCT], [TANGO_ACCT], [TANGO_ACCT_MAP_TXT], [TANGO_ACCT_TXT]) VALUES (N'A771320', N'871000', N'AD&Pro exps, Shop front communication, Fixture', N'SGA/Advertising & sales promotion')
INSERT [dbo].[AM_TANGO] ([TANGO_GL_ACCT], [TANGO_ACCT], [TANGO_ACCT_MAP_TXT], [TANGO_ACCT_TXT]) VALUES (N'A771330', N'871000', N'AD&Pro exps, Shop Fixtures/Renovation', N'SGA/Advertising & sales promotion')
INSERT [dbo].[AM_TANGO] ([TANGO_GL_ACCT], [TANGO_ACCT], [TANGO_ACCT_MAP_TXT], [TANGO_ACCT_TXT]) VALUES (N'A771400', N'871000', N'AD&Pro exps- Market research', N'SGA/Advertising & sales promotion')
INSERT [dbo].[AM_TANGO] ([TANGO_GL_ACCT], [TANGO_ACCT], [TANGO_ACCT_MAP_TXT], [TANGO_ACCT_TXT]) VALUES (N'A771410', N'871000', N'AD&Pro exps-Promotor Incentives', N'SGA/Advertising & sales promotion')
INSERT [dbo].[AM_TANGO] ([TANGO_GL_ACCT], [TANGO_ACCT], [TANGO_ACCT_MAP_TXT], [TANGO_ACCT_TXT]) VALUES (N'A771420', N'871000', N'AD&Pro exps-Media,eCommence Shopping/Mar', N'SGA/Advertising & sales promotion')
INSERT [dbo].[AM_TANGO] ([TANGO_GL_ACCT], [TANGO_ACCT], [TANGO_ACCT_MAP_TXT], [TANGO_ACCT_TXT]) VALUES (N'A771430', N'871000', N'AD&Pro exps, CRM', N'SGA/Advertising & sales promotion')
INSERT [dbo].[AM_TANGO] ([TANGO_GL_ACCT], [TANGO_ACCT], [TANGO_ACCT_MAP_TXT], [TANGO_ACCT_TXT]) VALUES (N'A771440', N'871000', N'AD&Pro exps-Field Force/Visual Merchandi', N'SGA/Advertising & sales promotion')
INSERT [dbo].[AM_TANGO] ([TANGO_GL_ACCT], [TANGO_ACCT], [TANGO_ACCT_MAP_TXT], [TANGO_ACCT_TXT]) VALUES (N'A771450', N'871000', N'AD&Pro exps-Promotor Related Cost', N'SGA/Advertising & sales promotion')
INSERT [dbo].[AM_TANGO] ([TANGO_GL_ACCT], [TANGO_ACCT], [TANGO_ACCT_MAP_TXT], [TANGO_ACCT_TXT]) VALUES (N'A771900', N'871000', N'AD&Pro, General/Strategic marketing/Other expenses', N'SGA/Advertising & sales promotion')
INSERT [dbo].[AM_TANGO] ([TANGO_GL_ACCT], [TANGO_ACCT], [TANGO_ACCT_MAP_TXT], [TANGO_ACCT_TXT]) VALUES (N'A771950', N'871000', N'AD&Pro exps, Warehousing and Transportation', N'SGA/Advertising & sales promotion')
INSERT [dbo].[AM_TANGO] ([TANGO_GL_ACCT], [TANGO_ACCT], [TANGO_ACCT_MAP_TXT], [TANGO_ACCT_TXT]) VALUES (N'A774030', N'874000', N'Commission-eCommerce', N'Commission Paid')
INSERT [dbo].[AM_TANGO] ([TANGO_GL_ACCT], [TANGO_ACCT], [TANGO_ACCT_MAP_TXT], [TANGO_ACCT_TXT]) VALUES (N'A775010', N'875000', N'Service, Inwarranty, exchange', N'In-Warranty')
INSERT [dbo].[AM_TANGO] ([TANGO_GL_ACCT], [TANGO_ACCT], [TANGO_ACCT_MAP_TXT], [TANGO_ACCT_TXT]) VALUES (N'A775020', N'875000', N'Service, Inwarranty, other', N'In-Warranty')
INSERT [dbo].[AM_TANGO] ([TANGO_GL_ACCT], [TANGO_ACCT], [TANGO_ACCT_MAP_TXT], [TANGO_ACCT_TXT]) VALUES (N'A775030', N'875000', N'Service, Inwarranty, parts', N'In-Warranty')
INSERT [dbo].[AM_TANGO] ([TANGO_GL_ACCT], [TANGO_ACCT], [TANGO_ACCT_MAP_TXT], [TANGO_ACCT_TXT]) VALUES (N'A775100', N'875000', N'Service- Outwarranty', N'In-Warranty')
INSERT [dbo].[AM_TANGO] ([TANGO_GL_ACCT], [TANGO_ACCT], [TANGO_ACCT_MAP_TXT], [TANGO_ACCT_TXT]) VALUES (N'A775710', N'875000', N'Service, Contact Center Outsourcing', N'In-Warranty')
INSERT [dbo].[AM_TANGO] ([TANGO_GL_ACCT], [TANGO_ACCT], [TANGO_ACCT_MAP_TXT], [TANGO_ACCT_TXT]) VALUES (N'A775810', N'875000', N'Service, Prov for product warranties (accrual)', N'In-Warranty')
INSERT [dbo].[AM_TANGO] ([TANGO_GL_ACCT], [TANGO_ACCT], [TANGO_ACCT_MAP_TXT], [TANGO_ACCT_TXT]) VALUES (N'A775840', N'875000', N'Service, RMA Reimbursement', N'In-Warranty')
INSERT [dbo].[AM_TANGO] ([TANGO_GL_ACCT], [TANGO_ACCT], [TANGO_ACCT_MAP_TXT], [TANGO_ACCT_TXT]) VALUES (N'A775900', N'875000', N'Service, Other1', N'In-Warranty')
INSERT [dbo].[AM_TANGO] ([TANGO_GL_ACCT], [TANGO_ACCT], [TANGO_ACCT_MAP_TXT], [TANGO_ACCT_TXT]) VALUES (N'A780030', N'780021', N'OGE, Loss on disposal of PP&E', N'OGE/Loss on disposal of PP&E')
INSERT [dbo].[AM_TANGO] ([TANGO_GL_ACCT], [TANGO_ACCT], [TANGO_ACCT_MAP_TXT], [TANGO_ACCT_TXT]) VALUES (N'A780092', N'780092', N'OGE/Loss relate to Lease contract modification', N'OGE/Impairment Loss of PP&E')
INSERT [dbo].[AM_TANGO] ([TANGO_GL_ACCT], [TANGO_ACCT], [TANGO_ACCT_MAP_TXT], [TANGO_ACCT_TXT]) VALUES (N'A901000', N'999999', N'Purchase merchandise', N'Not applicable for TANGO')
INSERT [dbo].[AM_TANGO] ([TANGO_GL_ACCT], [TANGO_ACCT], [TANGO_ACCT_MAP_TXT], [TANGO_ACCT_TXT]) VALUES (N'A921900', N'999999', N'Internal purchase', N'Not applicable for TANGO')
INSERT [dbo].[AM_TANGO] ([TANGO_GL_ACCT], [TANGO_ACCT], [TANGO_ACCT_MAP_TXT], [TANGO_ACCT_TXT]) VALUES (N'A923100', N'999999', N'Interim account, GL', N'Not applicable for TANGO')
INSERT [dbo].[AM_TANGO] ([TANGO_GL_ACCT], [TANGO_ACCT], [TANGO_ACCT_MAP_TXT], [TANGO_ACCT_TXT]) VALUES (N'A999940', N'999999', N'Technical clearing Asset Management', N'Not applicable for TANGO')
INSERT [dbo].[AM_TANGO] ([TANGO_GL_ACCT], [TANGO_ACCT], [TANGO_ACCT_MAP_TXT], [TANGO_ACCT_TXT]) VALUES (N'A999994', N'999999', N'Clearing account, FIXED ASSET Migration', N'Not applicable for TANGO')
INSERT [dbo].[AM_TANGO] ([TANGO_GL_ACCT], [TANGO_ACCT], [TANGO_ACCT_MAP_TXT], [TANGO_ACCT_TXT]) VALUES (N'A999995', N'999999', N'Clearing account- GL CONVERSION', N'Not applicable for TANGO')
INSERT [dbo].[AM_TANGO] ([TANGO_GL_ACCT], [TANGO_ACCT], [TANGO_ACCT_MAP_TXT], [TANGO_ACCT_TXT]) VALUES (N'A999996', N'999999', N'Clearing account, AR OPEN ITEM CONVERSION', N'Not applicable for TANGO')
INSERT [dbo].[AM_TANGO] ([TANGO_GL_ACCT], [TANGO_ACCT], [TANGO_ACCT_MAP_TXT], [TANGO_ACCT_TXT]) VALUES (N'A999997', N'999999', N'Clearing account, AP OPEN ITEM CONVERSION', N'Not applicable for TANGO')
INSERT [dbo].[AM_TANGO] ([TANGO_GL_ACCT], [TANGO_ACCT], [TANGO_ACCT_MAP_TXT], [TANGO_ACCT_TXT]) VALUES (N'A999998', N'999999', N'Clearing account, STOCK CONVERSION', N'Not applicable for TANGO')
INSERT [dbo].[AM_TANGO] ([TANGO_GL_ACCT], [TANGO_ACCT], [TANGO_ACCT_MAP_TXT], [TANGO_ACCT_TXT]) VALUES (N'A999999', N'999999', N'Clearing account- FIXED ASSET CONVERSION', N'Not applicable for TANGO')
GO
