USE [DIVA_SEV_FY2023]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[AM_COMPANY_CODE](
	[COMPANY_CODE] [nvarchar](100) NULL,
	[BUKRS_MAPPING] [nvarchar](max) NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
INSERT [dbo].[AM_COMPANY_CODE] ([COMPANY_CODE], [BUKRS_MAPPING]) VALUES (N'VN00', N'VN00,VN50')
INSERT [dbo].[AM_COMPANY_CODE] ([COMPANY_CODE], [BUKRS_MAPPING]) VALUES (N'VN50', N'VN00,VN50')
GO
