USE [DIVA_SEV_FY2023]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[AM_IRGR_MATERIAL_GROUP_HIERARCHY](
	[T023T_MATKL] [nvarchar](50) NULL,
	[T023T_WGBEZ] [nvarchar](50) NULL,
	[IRGR_SPEND_CAT_LEVEL_1] [nvarchar](50) NULL,
	[IRGR_SPEND_CAT_LEVEL_2] [nvarchar](50) NULL,
	[IRGR_SPEND_CAT_LEVEL_3] [nvarchar](50) NULL,
	[IRGR_SPEND_CAT_LEVEL_4] [nvarchar](50) NULL
) ON [PRIMARY]
GO
INSERT [dbo].[AM_IRGR_MATERIAL_GROUP_HIERARCHY] ([T023T_MATKL], [T023T_WGBEZ], [IRGR_SPEND_CAT_LEVEL_1], [IRGR_SPEND_CAT_LEVEL_2], [IRGR_SPEND_CAT_LEVEL_3], [IRGR_SPEND_CAT_LEVEL_4]) VALUES (N'01', N'Material group 1', N'Product procurement', N'Other', N'Other', N'Material group 1')
INSERT [dbo].[AM_IRGR_MATERIAL_GROUP_HIERARCHY] ([T023T_MATKL], [T023T_WGBEZ], [IRGR_SPEND_CAT_LEVEL_1], [IRGR_SPEND_CAT_LEVEL_2], [IRGR_SPEND_CAT_LEVEL_3], [IRGR_SPEND_CAT_LEVEL_4]) VALUES (N'4020', N'AUTOMOTIVE BUSINESS', N'Product procurement', N'SSS', N'SSS', N'AUTOMOTIVE BUSINESS')
INSERT [dbo].[AM_IRGR_MATERIAL_GROUP_HIERARCHY] ([T023T_MATKL], [T023T_WGBEZ], [IRGR_SPEND_CAT_LEVEL_1], [IRGR_SPEND_CAT_LEVEL_2], [IRGR_SPEND_CAT_LEVEL_3], [IRGR_SPEND_CAT_LEVEL_4]) VALUES (N'4230', N'PERSONAL BIZ', N'Product procurement', N'ET&S', N'ET&S', N'PERSONAL BIZ')
INSERT [dbo].[AM_IRGR_MATERIAL_GROUP_HIERARCHY] ([T023T_MATKL], [T023T_WGBEZ], [IRGR_SPEND_CAT_LEVEL_1], [IRGR_SPEND_CAT_LEVEL_2], [IRGR_SPEND_CAT_LEVEL_3], [IRGR_SPEND_CAT_LEVEL_4]) VALUES (N'5110', N'TV', N'Product procurement', N'ET&S', N'ET&S', N'TV')
INSERT [dbo].[AM_IRGR_MATERIAL_GROUP_HIERARCHY] ([T023T_MATKL], [T023T_WGBEZ], [IRGR_SPEND_CAT_LEVEL_1], [IRGR_SPEND_CAT_LEVEL_2], [IRGR_SPEND_CAT_LEVEL_3], [IRGR_SPEND_CAT_LEVEL_4]) VALUES (N'5300', N'IP&S', N'Product procurement', N'IP&S', N'IP&S', N'IP&S')
INSERT [dbo].[AM_IRGR_MATERIAL_GROUP_HIERARCHY] ([T023T_MATKL], [T023T_WGBEZ], [IRGR_SPEND_CAT_LEVEL_1], [IRGR_SPEND_CAT_LEVEL_2], [IRGR_SPEND_CAT_LEVEL_3], [IRGR_SPEND_CAT_LEVEL_4]) VALUES (N'5765', N'HOME AUDIO BIZ', N'Product procurement', N'ET&S', N'ET&S', N'HOME AUDIO BIZ')
INSERT [dbo].[AM_IRGR_MATERIAL_GROUP_HIERARCHY] ([T023T_MATKL], [T023T_WGBEZ], [IRGR_SPEND_CAT_LEVEL_1], [IRGR_SPEND_CAT_LEVEL_2], [IRGR_SPEND_CAT_LEVEL_3], [IRGR_SPEND_CAT_LEVEL_4]) VALUES (N'6700', N'MOBILE COMMUNICATION', N'Product procurement', N'ET&S', N'ET&S', N'MOBILE COMMUNICATION')
INSERT [dbo].[AM_IRGR_MATERIAL_GROUP_HIERARCHY] ([T023T_MATKL], [T023T_WGBEZ], [IRGR_SPEND_CAT_LEVEL_1], [IRGR_SPEND_CAT_LEVEL_2], [IRGR_SPEND_CAT_LEVEL_3], [IRGR_SPEND_CAT_LEVEL_4]) VALUES (N'8500', N'ET&S Others', N'Product procurement', N'EP&S', N'EP&S', N'ET&S Others')
INSERT [dbo].[AM_IRGR_MATERIAL_GROUP_HIERARCHY] ([T023T_MATKL], [T023T_WGBEZ], [IRGR_SPEND_CAT_LEVEL_1], [IRGR_SPEND_CAT_LEVEL_2], [IRGR_SPEND_CAT_LEVEL_3], [IRGR_SPEND_CAT_LEVEL_4]) VALUES (N'9900', N'OTHERS', N'Other', N'Other', N'Other', N'OTHERS')
GO
