USE [DIVA_SEV_FY2023]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[AM_AR_ACCOUNT](
	[ACDOCA_RACCT] [nvarchar](100) NULL,
	[SKAT_TXT50] [nvarchar](1000) NULL,
	[SKAT_TXT20] [nvarchar](1000) NULL,
	[ZF_AR_ACCOUNT] [nvarchar](100) NULL
) ON [PRIMARY]
GO
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A012001', N'Cash on Hand - National Currency', N'Cash on Hand - NC', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A012007', N'Cash on Hand - National Currency 2', N'Cash on Hand - NC 2', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A012100', N'Citibank - National Currency', N'Citibank - NC', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A012101', N'Citibank - USD', N'Citibank - USD', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A012105', N'HSBC - National Currency', N'HSBC - NC', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A012106', N'HSBC - USD', N'HSBC - USD', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A012990', N'Cash on hand- FX Translation', N'Cash OH-FX Trans', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A014100', N'Citibank - National Currency (incoming)', N'I Clr Citibank - NC', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A014101', N'Citibank - USD (incoming)', N'I Clr Citibank - USD', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A014105', N'HSBC - National Currency (incoming)', N'I Clr HSBC - NC', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A014106', N'HSBC - USD (incoming)', N'I Clr HSBC - USD', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A014850', N'Trade account receivable, direct GL entry, OIM', N'T AR,D GL entry,OIM', N'x')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A014990', N'Trade account receivable, FX Translation', N'T AR,FX Trans', N'x')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A021015', N'Products- Merchandise & FG- direct GL entry OIM', N'M&FG,D GL,OIM', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A021020', N'Products, Merchandise & FG, direct GL, balance', N'M&FG,D GL,balance', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A021030', N'Products, Merchandise & FG, In transit', N'M&FG,In transit', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A021050', N'Products, Merchandise & FG, Devaluation', N'M&FG,Devaluation', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A031030', N'Prepaid exps, Rental/Leasing', N'PE,Rental/Leasing', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A031060', N'Prepaid exps, Insurance', N'PE,Insurance', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A031900', N'Prepaid exps, Other1', N'PE,Other1', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A032990', N'Other AR-current, FX Translation', N'Other AR,FX Trans', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A035900', N'Expense to be recharged, Other1', N'Exp to be rec,Other1', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A037010', N'Accrd income, General', N'Accrd income,Gen', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A037990', N'Accrd income- FX Translation', N'AI-FX Trans', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A038010', N'VAT-receivable on purchase, general', N'VAT-R on purch,gen', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A038480', N'VAT-receivable (clearing) VN', N'VAT-R clr VN', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A040010', N'Derivative Assets-current, Frgn exchange forward', N'Deriv FX forward', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A089010', N'Other misc. current assets, General', N'OCA,Gen', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A089090', N'Other Current Asset - Cannibalization', N'OCA, Cannibalization', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A089091', N'Other Current Asset - Interim Service', N'OCA, Interim Service', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A089093', N'OCA- LVA Supply Direct GL', N'OCA- LVA Supply DGL', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A089990', N'Other misc. current assets- FX Translation', N'OCA-FX Trans', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A110012', N'ROU- Buildings - Direct GL-NOIM', N'ROU- Buildings', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A110072', N'ROU- Vehicles-Direct-NOIM', N'ROU- Vehicles', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A110202', N'Right of use assets- Acc/Amort- buildings - NOIM', N'ROU, A.Amort Bldg', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A110262', N'ROU- Acc/Amort- Veh-Direct-NOIM', N'ROU- Acc/Amort- Veh', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A119200', N'Construction in Progress, Assets interim account', N'Assets interim acct', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A119205', N'CIP, Assets interim account (SysInt)', N'CIP, AInterim SysInt', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A142010', N'Def tax assets-non-curr, National tax', N'DTA,National tax', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A158010', N'Security Deposit - Non Current', N'Sec.Dep-NC', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A212100', N'Trade AP- invoice to be received- GRIR 1', N'T AP, GRIR 1', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A212101', N'Trade AP- invoice to be received- GRIR 2', N'T AP, GRIR 2', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A212990', N'Trade AP, FX Translation', N'T AP,FX Trans', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A213010', N'Short Term Borrowing, General', N'ST Borrowing,Gen', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A213100', N'Short Term Borrowing, SGTS', N'ST Borrowing,SGTS', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A213990', N'Short Term Borrowing- FX Translation', N'ST Borrow-FX Trans', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A215070', N'AP-non trade, invoice to be received, GRIR', N'AP-NT,GRIR', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A215100', N'Citibank - National Currency (outgoing)', N'O Clr Citibank - NC', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A215101', N'Citibank - USD (outgoing)', N'O Clr Citibank - USD', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A215105', N'HSBC - National Currency (outgoing)', N'O Clr HSBC - NC', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A215106', N'HSBC - USD (outgoing)', N'O Clr HSBC - USD', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A215850', N'Other AP-non trade- direct GL entry- OIM', N'Other AP-NT-D GL-OIM', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A215851', N'Other AP-non trade-Doc Splitting Account', N'Oth AP-NT Doc Split', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A215990', N'Other AP-non trade- FX Translation for others', N'O.AP-NT,FX Tra othe', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A216100', N'Provision for Activity Based Co-Op A&P', N'Accrd Co-op AD(MDF)1', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A216140', N'Accrd exps, SR, Stock Compensation (Activity)', N'Accrd Stock Comp1', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A216141', N'Accrd exps, SR, Stock Compensation (General)', N'Accrd Stock Comp2', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A216164', N'Accrd exps, SR, Sell Thru/Promo Rebate (Activity)', N'Accrd SR, STR PR Act', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A216165', N'Accrd exps, SR, Sell Thru/Promo Rebate (General)', N'Accrd SR, STR PR Gen', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A216180', N'Accrd exps, SR, Sell-in allowance(Activity)', N'Accrd SR, SIA Act', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A216181', N'Accrd exps, SR, Sell-in allowance(General)', N'Accrd SR, SIA Gen', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A216230', N'Accrd exps, SR, Other manual price adj', N'ASR,O.man price adj', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A216260', N'Accrd Exp, Sales Discount', N'Accrd SR, Sales Disc', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A216310', N'Accrd exps, Salaries & Wages', N'AE,Salaries & Wages', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A216320', N'Accrd exps, Bonuses, General', N'AE,Bonuses,Gen', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A216322', N'Accrd exps- Bonuses- Managements', N'AE,Bonuses,Mgt', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A216340', N'Accrd exps, Compensated absence', N'AE,Compens absence', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A216350', N'Accrd exps, Welfare expense', N'AE,Welfare Exp', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A216440', N'Accrd exps, SGA freight', N'AE,freight', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A216460', N'Accrd exps, SGA sales commission, General', N'AE,S.commission,Gen', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A216500', N'Accrd exps, SGA Consultant fee', N'AE,Consultant fee', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A216510', N'Accrd exps, SGA Advertising & promotion', N'AE,Ad&Pro', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A216900', N'Accrd exps, Other1', N'AE,Other1', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A216901', N'Accrd exps, EDP', N'AE,Other2', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A216902', N'Accrued exps - SGA Other', N'AE,Other3', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A216903', N'Accrd exps, Customer Svc', N'AE, Customer Svc', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A216904', N'Accrued Exp, COGS Others', N'AE, Other 4', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A216990', N'Accrd exps- FX Translation', N'AE-FX Trans', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A220010', N'Tax payable on sales, General', N'Tax-P on sales,Gen', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A226035', N'Deferred revenue-Current Loyalty Points', N'Def rev-Loyalty Pts', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A226060', N'Deferred revenue-current, Voucher', N'Def rev,Voucher', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A229010', N'Reserve for warranty, General', N'Reserve for warranty', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A231010', N'Income tax payable- current- General', N'ITP, Curr Gen', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A232030', N'Accrued other taxes, payroll1', N'AOT,payroll1', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A232900', N'Accrued other taxes, Other1', N'AOT,Other1', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A232990', N'Accrued other taxes- FX Translation', N'AOT-FX Trans', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A237010', N'Derivative liabilities-current- FX forward', N'Deriv liab-FXforward', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A247010', N'Lease liability- Current portion of LTD', N'L.L - curr LTD', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A247030', N'Lease liability- Current Interest Accrual', N'L.L -curr Interest A', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A273020', N'Other misc. CL-Deposits1', N'O.misc.CL.Deposits1', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A273030', N'Other misc. CL- Deposits received- coupon/Point', N'OCL-coupon/Point', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A307010', N'Long Term Debts (Op Lease)', N'LT debts-Op Lease', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A320010', N'Asset retirement obligation-non-curr, General', N'ARO,Gen', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A340040', N'Other non-curr liabilities- Severance', N'ONCL-Severance', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A443010', N'R/E other than legal reserve, R/E brought forward', N'R/E brought forward', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A443090', N'Controlling Interest - Dividend paid', N'CI - Dividend paid', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A505010', N'COGS- Products', N'COGS,Products', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A505030', N'COGS- Other', N'COGS,Other', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A505040', N'COGS- Service & Repair', N'COGS,Service&Repair', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A505055', N'COGS - Spare Parts', N'COGS - SP', N'N/A')
GO
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A505300', N'COGS- Devaluation', N'COGS,Devaluation', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A505410', N'COGS- Special loss on disposal of inventories', N'COGS,Special LOD inv', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A531010', N'NOE- Interest on borrowing', N'Inter on borrowing', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A531110', N'NOE/ Intr exps on liability to make lease payments', N'NOE/Int exp in lease', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A531400', N'NOE- FX Translation losses', N'NOE,FX Trans losses', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A531510', N'NOE- ARO accretion expense', N'NOE- ARO accre.exp', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A531900', N'NOE- Other1', N'NOE,Other1', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A542010', N'Current income tax expense- National tax', N'CIT,National', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A543010', N'Deferred income tax expense- National tax', N'DIT,National', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A621010', N'Gross Sales- Products', N'Gross Sales,Products', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A621050', N'Gross Sales- Service & Repair', N'G sales,Service&Repa', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A621055', N'Gross Sales - Spare Parts', N'Gross Sales - SP', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A622110', N'Sales reduction, On-invoice discount Merchandise', N'SR,OID Merchandise', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A622111', N'Sales reduction, On-invoice discount Spare Parts', N'SR,OID Spare Parts', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A622112', N'Sales reduction, On-invoice discount Round diff', N'SR,OID Round diff', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A622210', N'Sales reduction, Co-op AD(Activity)', N'SR,Co-op AD (Act)', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A622310', N'Sales reduction, Stock Compensation(Activity)', N'SR,Stock Comp (Act)', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A622311', N'Sales reduction, Stock Compensation (General)', N'SR,Stock Comp (Gen)', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A622424', N'Sales reduction, Sell Thru/Promo Rebate (Activity)', N'SR, STR (Act)', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A622425', N'Sales reduction, Sell Thru/Promo Rebate (General)', N'SR, STR (Gen)', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A622430', N'Sales reduction, Sell-in allowance (Activity)', N'SR,SIA (Act)', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A622431', N'Sales reduction, Sell-in allowance (General)', N'SR,SIA (Gen)', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A622620', N'Sales reduction, Other manual price adj', N'SR,O.manual adj', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A625900', N'OPR- Other1', N'OPR,Other1', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A631010', N'NOR- Interest income', N'NOR,Inter income', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A631300', N'NOR- FX Translation gain', N'NOR,FX Trans gain', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A631900', N'NOR- Other1', N'NOR,Other1', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A702010', N'S&W- Base salaries', N'S&W,Base salaries', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A702011', N'S&W- Base salaries(Management)', N'S&W,Base salary Mgt', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A702100', N'S&W- Temporary employees', N'S&W,Temp employees', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A702200', N'S&W- Compensated absence', N'S&W,Compensated abse', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A702900', N'S&W- Other1', N'S&W,Other1', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A702910', N'S&W- Taxation remuneration in kind VAT full rate', N'S&W,VAT full rate', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A703010', N'Bonuses & allowance- General', N'Bonuses,Gen', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A703020', N'Bonuses & allowance- Management', N'Bonuses, Mgt', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A704300R', N'Retirement bnf exps- Termination(Restructuring)', N'Termination', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A705010', N'Social security- Unemployment act contribution', N'Unemploy act contri', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A705050', N'Social security- Insurance1', N'SS,Insurance1', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A706010', N'Welfare exps- Private Healthcare Insurance', N'PrivateHealthcareIns', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A706900', N'Welfare exps- Other1', N'Welfare exps,Other1', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A706901', N'Welfare exps- Other2', N'Welfare exps,Other2', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A706902', N'Welfare exps,General Expat', N'Welfare exps,Expat', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A711010', N'Freight- Finished goods freightage(Ship)', N'Freight,FG (Ship)', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A711020', N'Freight- Finished goods freightage(Air)', N'Freight,FG (Air)', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A711030', N'Freight- Finished goods freightage(Land)', N'Freight,FG (Land)', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A711100', N'Freight- Office cost on export', N'Freight,Office Expor', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A711900', N'Freight- Other1', N'Freight,Other1', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A712010', N'Equipment- tools & software expensed- E&T', N'E&T expensed', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A712100', N'Equipment- tools & software expensed- Soft', N'SW expensed', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A714010', N'Utilities exps- Electrical power', N'Electrical power', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A714020', N'Utilities exps- Water charges', N'Water charges', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A722010', N'R&T exps- Recruiting expense', N'Recruiting exp', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A722020', N'R&T exps- Training exps', N'Training exps', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A722020R', N'R&T exps- Training exps (Restructuring)', N'Training exps', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A723010', N'Travelling & commutation- Fare', N'Fare', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A723020', N'Travelling & commutation- Accommodation', N'Accommodation', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A723900', N'Travelling & commutation- Other1', N'Trav&commut,Other1', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A725010', N'Commu exps- Postal exps', N'Postal exps', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A725030', N'Commu exps- Cell phone & Land phone', N'Cellphone & Landline', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A726010', N'Meals and Entmt exps, Meal', N'Meal', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A731900', N'Insurance exps, Other1', N'Insurance Other1', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A731920', N'Insurance exps, Credit insurance', N'Credit insurance', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A732010', N'Repair&maintenance exps, M&Es', N'R&M,M&Es', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A732020', N'Repair&maintenance exps, Bld/LI/struc', N'R&M,Bld/LI/struc', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A733040', N'Dep, M&Es', N'Dep,M&Es', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A733220', N'Dep- Ext. Software for own use(Amort)', N'Dep,Ext. SWOU(Amort)', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A733300', N'Dep, Lease assets-buildings(Operating)', N'Dep, LA Bldg (Op)', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A733360', N'Dep- Lease assets-vehicles(Amort)', N'Dep, Leased Vehicle', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A741010N', N'Donation, General (Non deductible)', N'Donation,Gen (ND)', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A742010', N'misc. tax, Consumption tax', N'Consumption tax', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A743010', N'Storage, Finished goods storage fee', N'FG storage fee', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A744020', N'misc. exps, Books & magazines', N'Books & magazines', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A744030', N'misc. exps, Conference exps', N'Conference exps', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A744040N', N'misc. exps, Vehicle Expenses (ND)', N'Vehile Expenses(ND)', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A744050', N'misc. exps, Bank commissions', N'Bank commissions', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A744720', N'misc. exps- Other MFC related expenses 2', N'Other MFC 2', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A744800', N'misc. exps, Outgoing recharge', N'Outgo recharge', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A744900', N'misc. exps, Other1', N'misc. exps,Other1', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A745030', N'Rent exps- Company housings', N'Company housings', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A745035', N'Rent Exps- Company housings (SysInt)', N'Rent Exps- Company', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A745080N', N'Rent exps, Vehicles exps(ND)', N'Vehicles exps(ND)', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A745090', N'Rent exps, Office rent', N'Office rent', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A745095', N'Rent Exps, Office rent (SysInt)', N'Rent Exps, Office', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A745110', N'Rent Exps- Rental Cars', N'Rent - Rental Cars', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A745115', N'Rent Exps- Rental Cars (SysInt)', N'Rent Exps- Rental Ca', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A745900', N'Rent exps, Other1', N'Rent exps,Other1', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A748010', N'Prof service fee, CPA Audit fee', N'CPA Audit fee', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A748020', N'Prof service fee, Temp staff service fee (agency)', N'Temp staff agency fe', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A748030', N'Prof service fee, Legal Services', N'Legal Services', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A748050', N'Prof service fee, Other consultant fees', N'O.consultant fees', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A748060', N'Prof service fee, Market research', N'Market research', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A748090', N'Prof service fee, Business Process Outsourcing', N'BPO', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A749020', N'Dep(ARO)- L/h impr', N'Dep(ARO),L/h impr', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A750010', N'IS Service Fee- H/W maintenance', N'H/W maintenance', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A750011', N'IS Service Fee- S/W maintenance', N'S/W maintenance', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A750020', N'IS Service Fee- Network', N'IS Service Fee- Netw', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A750900', N'IS Service Fee- Other', N'IS Service Fee- Othe', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A771010', N'AD&Pro exps, Media expenses, Newspaper', N'Media exps,Newspaper', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A771040', N'AD&Pro exps, Media, Outdoor/Transit advertising', N'Media,OutdoorTransit', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A771090', N'AD&Pro exps- Media expenses- Internet others', N'Internet others', N'N/A')
GO
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A771090N', N'AD&Pro exps-Key Opinion leader (influenc', N'Key Opinion leader', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A771100N', N'AD&Pro exps-Maintenance, repair', N'A&P,Maintenance,rep', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A771106', N'AD&pro exps – Digital production', N'Digital Production', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A771110', N'AD&Pro exps, Sponsorship', N'Sponsorship', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A771111', N'AD&Pro exps- Dealer Support', N'Dealer Support', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A771200', N'AD&Pro exps- Promoter expenses', N'Promoter expenses', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A771210', N'AD&Pro exps, Event&Exhibition', N'Event&Exhibition', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A771210N', N'AD&Pro exps-Product Seminar / Workshops', N'Seminar/WkshpOnline', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A771211', N'AD&Pro exps- PR & Press Events', N'PR & Press Event', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A771220', N'AD&Pro exps, Others, Sample', N'AD&Pro exps,Sample', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A771220N', N'AD&Pro exps- Dealer convention', N'Dealer convention', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A771230', N'AD&Pro exps, Others, Give Away', N'Give Away', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A771230N', N'AD&Pro exps-Product Seminar / Workshops', N'Seminar/WkshpOffline', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A771240', N'AD&Pro exps, Incentive Trips/Training', N'IncentivTrip/Traini', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A771300', N'AD&Pro exps, Shop front communication, POP', N'Shop front,POP', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A771320', N'AD&Pro exps, Shop front communication, Fixture', N'Shop front,Fixture', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A771330', N'AD&Pro exps, Shop Fixtures/Renovation', N'Shop Fixtures/Renov', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A771400', N'AD&Pro exps- Market research', N'AD&Pro exps-Mkt Res', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A771410', N'AD&Pro exps-Promotor Incentives', N'Promotor Incentives', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A771420', N'AD&Pro exps-Media,eCommence Shopping/Mar', N'Media,eCom,Shp/Mkt', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A771430', N'AD&Pro exps, CRM', N'AD&Pro exps, CRM', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A771440', N'AD&Pro exps-Field Force/Visual Merchandi', N'Field Force/Merch', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A771450', N'AD&Pro exps-Promotor Related Cost', N'Promotor Rel Cost', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A771900', N'AD&Pro, General/Strategic marketing/Other expenses', N'Gen/Strat Mktg/O Ex', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A771950', N'AD&Pro exps, Warehousing and Transportation', N'Warehousing&Transpo', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A774030', N'Commission-eCommerce', N'Sales commissn,eCom', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A775010', N'Service, Inwarranty, exchange', N'Service,IW,exchange', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A775020', N'Service, Inwarranty, other', N'Service,IW,other', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A775030', N'Service, Inwarranty, parts', N'Service, IW,parts', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A775100', N'Service- Outwarranty', N'Service,Outwarranty', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A775710', N'Service, Contact Center Outsourcing', N'Service,Contact.C OS', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A775810', N'Service, Prov for product warranties (accrual)', N'Service,Prov(accrual', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A775840', N'Service, RMA Reimbursement', N'Service, RMA Reimb', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A775900', N'Service, Other1', N'Service,Other1', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A780030', N'OGE, Loss on disposal of PP&E', N'OGE,LOD of PP&E', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A780092', N'OGE/Loss relate to Lease contract modification', N'OGE/Loss Lease Cont', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A901000', N'Purchase merchandise', N'Purchase merchandise', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A921900', N'Internal purchase', N'Internal purchase', N'N/A')
INSERT [dbo].[AM_AR_ACCOUNT] ([ACDOCA_RACCT], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_ACCOUNT]) VALUES (N'A923100', N'Interim account, GL', N'Interim account,GL', N'N/A')
GO
