USE [DIVA_SPE_FY2024_Q2]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[AM_GLOBALS](
	[GLOBALS_PARAMETER] [nvarchar](50) NOT NULL,
	[GLOBALS_VALUE] [nvarchar](500) NULL,
	[GLOBALS_DESCRIPTION] [nvarchar](200) NULL
) ON [PRIMARY]
GO
INSERT [dbo].[AM_GLOBALS] ([GLOBALS_PARAMETER], [GLOBALS_VALUE], [GLOBALS_DESCRIPTION]) VALUES (N'COPA_TABLE_NAME', N'', N'INPUT COPA TABLE NAME TO THIS LINE')
INSERT [dbo].[AM_GLOBALS] ([GLOBALS_PARAMETER], [GLOBALS_VALUE], [GLOBALS_DESCRIPTION]) VALUES (N'currency', N'USD', N'Reporting currency. Required')
INSERT [dbo].[AM_GLOBALS] ([GLOBALS_PARAMETER], [GLOBALS_VALUE], [GLOBALS_DESCRIPTION]) VALUES (N'custom_currency_field', N'KSL', N'Custom_currency')
INSERT [dbo].[AM_GLOBALS] ([GLOBALS_PARAMETER], [GLOBALS_VALUE], [GLOBALS_DESCRIPTION]) VALUES (N'date1', N'20201001', N'Scope - date from. Required')
INSERT [dbo].[AM_GLOBALS] ([GLOBALS_PARAMETER], [GLOBALS_VALUE], [GLOBALS_DESCRIPTION]) VALUES (N'date2', N'20230930', N'Scope - date to. Required')
INSERT [dbo].[AM_GLOBALS] ([GLOBALS_PARAMETER], [GLOBALS_VALUE], [GLOBALS_DESCRIPTION]) VALUES (N'dateformat', N'ymd', N'Date syntax format. Required')
INSERT [dbo].[AM_GLOBALS] ([GLOBALS_PARAMETER], [GLOBALS_VALUE], [GLOBALS_DESCRIPTION]) VALUES (N'downloaddate', N'20231101', N'Date of download. Required')
INSERT [dbo].[AM_GLOBALS] ([GLOBALS_PARAMETER], [GLOBALS_VALUE], [GLOBALS_DESCRIPTION]) VALUES (N'exchangeratetype', N'M', N'Exchange rate type used (see table T001A) for determing the exchange rates')
INSERT [dbo].[AM_GLOBALS] ([GLOBALS_PARAMETER], [GLOBALS_VALUE], [GLOBALS_DESCRIPTION]) VALUES (N'FISCAL_YEAR_FROM', N'2021', NULL)
INSERT [dbo].[AM_GLOBALS] ([GLOBALS_PARAMETER], [GLOBALS_VALUE], [GLOBALS_DESCRIPTION]) VALUES (N'FISCAL_YEAR_TO', N'2024', NULL)
INSERT [dbo].[AM_GLOBALS] ([GLOBALS_PARAMETER], [GLOBALS_VALUE], [GLOBALS_DESCRIPTION]) VALUES (N'id', N'SPE', N'System name. Required')
INSERT [dbo].[AM_GLOBALS] ([GLOBALS_PARAMETER], [GLOBALS_VALUE], [GLOBALS_DESCRIPTION]) VALUES (N'language1', N'EN', N'Primary language. Required')
INSERT [dbo].[AM_GLOBALS] ([GLOBALS_PARAMETER], [GLOBALS_VALUE], [GLOBALS_DESCRIPTION]) VALUES (N'language2', N'E', N'Secondary languageq. Required')
INSERT [dbo].[AM_GLOBALS] ([GLOBALS_PARAMETER], [GLOBALS_VALUE], [GLOBALS_DESCRIPTION]) VALUES (N'LIMIT_RECORDS', N'0', N'Enter 0 to run on full data sets or 100 to limit to 100 lines')
INSERT [dbo].[AM_GLOBALS] ([GLOBALS_PARAMETER], [GLOBALS_VALUE], [GLOBALS_DESCRIPTION]) VALUES (N'New_GL', N'N', N'New SAP ledger in use. Required')
INSERT [dbo].[AM_GLOBALS] ([GLOBALS_PARAMETER], [GLOBALS_VALUE], [GLOBALS_DESCRIPTION]) VALUES (N'path', N'E:\DIVA_SPE_S4_FY22\01_Input\DATA\DATA\output', N'Raw data location. Required')
INSERT [dbo].[AM_GLOBALS] ([GLOBALS_PARAMETER], [GLOBALS_VALUE], [GLOBALS_DESCRIPTION]) VALUES (N'SAP_DDIC_version', N'S4HANA', N'(SAP46C, SAP47, SAPECC50, SAPECC60). Version of SAP data dictionary. Required for staging data. ')
INSERT [dbo].[AM_GLOBALS] ([GLOBALS_PARAMETER], [GLOBALS_VALUE], [GLOBALS_DESCRIPTION]) VALUES (N'year', N'2024', N'Scope - year. Required')
INSERT [dbo].[AM_GLOBALS] ([GLOBALS_PARAMETER], [GLOBALS_VALUE], [GLOBALS_DESCRIPTION]) VALUES (N'ZV_ACDOCA_RLDNR', N'0L', N'Ledger in General Ledger Accounting')
INSERT [dbo].[AM_GLOBALS] ([GLOBALS_PARAMETER], [GLOBALS_VALUE], [GLOBALS_DESCRIPTION]) VALUES (N'ZV_CLIENT', N'500', N'Filter on Specific Client')
INSERT [dbo].[AM_GLOBALS] ([GLOBALS_PARAMETER], [GLOBALS_VALUE], [GLOBALS_DESCRIPTION]) VALUES (N'ZV_SYSTEM_VERSION', N'S4HANA', N'PARALELL or S4HANA')
INSERT [dbo].[AM_GLOBALS] ([GLOBALS_PARAMETER], [GLOBALS_VALUE], [GLOBALS_DESCRIPTION]) VALUES (N'ZV_TB_RRCTY', N'0', N'0L Legder')
GO
