USE [DIVA_SPE_FY2024_Q2]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[AM_IRGR_GINI_ARDR_MAPPING](
	[IRGR_GL_ACCT] [nvarchar](255) NULL,
	[IRGR_GL_TXT] [nvarchar](255) NULL,
	[IRGR_OR_GINI_OR_ARDR] [nvarchar](255) NULL
) ON [PRIMARY]
GO
INSERT [dbo].[AM_IRGR_GINI_ARDR_MAPPING] ([IRGR_GL_ACCT], [IRGR_GL_TXT], [IRGR_OR_GINI_OR_ARDR]) VALUES (N'0000200702', N'Account Receivables-DefinedRev-AdvLocSalesProject', N'ARDR')
INSERT [dbo].[AM_IRGR_GINI_ARDR_MAPPING] ([IRGR_GL_ACCT], [IRGR_GL_TXT], [IRGR_OR_GINI_OR_ARDR]) VALUES (N'0000200708', N'Deferred Revenue - Licensing', N'ARDR')
INSERT [dbo].[AM_IRGR_GINI_ARDR_MAPPING] ([IRGR_GL_ACCT], [IRGR_GL_TXT], [IRGR_OR_GINI_OR_ARDR]) VALUES (N'0000200709', N'Deferred Revenue – Licensing Reval', N'ARDR')
INSERT [dbo].[AM_IRGR_GINI_ARDR_MAPPING] ([IRGR_GL_ACCT], [IRGR_GL_TXT], [IRGR_OR_GINI_OR_ARDR]) VALUES (N'0000203000', N'Deferred Revenue - Short Term', N'ARDR')
INSERT [dbo].[AM_IRGR_GINI_ARDR_MAPPING] ([IRGR_GL_ACCT], [IRGR_GL_TXT], [IRGR_OR_GINI_OR_ARDR]) VALUES (N'0000203001', N'Deferred Revenue 1', N'ARDR')
INSERT [dbo].[AM_IRGR_GINI_ARDR_MAPPING] ([IRGR_GL_ACCT], [IRGR_GL_TXT], [IRGR_OR_GINI_OR_ARDR]) VALUES (N'0000203003', N'MGM Pre-Close Deferred Revenue Contra', N'ARDR')
INSERT [dbo].[AM_IRGR_GINI_ARDR_MAPPING] ([IRGR_GL_ACCT], [IRGR_GL_TXT], [IRGR_OR_GINI_OR_ARDR]) VALUES (N'0000203004', N'Shadow Deferred Revenue', N'ARDR')
INSERT [dbo].[AM_IRGR_GINI_ARDR_MAPPING] ([IRGR_GL_ACCT], [IRGR_GL_TXT], [IRGR_OR_GINI_OR_ARDR]) VALUES (N'0000203005', N'Deferred Revenue - Short Term - Accrual', N'ARDR')
INSERT [dbo].[AM_IRGR_GINI_ARDR_MAPPING] ([IRGR_GL_ACCT], [IRGR_GL_TXT], [IRGR_OR_GINI_OR_ARDR]) VALUES (N'0000203050', N'Deferred Revenue-Short Term Net Down', N'ARDR')
INSERT [dbo].[AM_IRGR_GINI_ARDR_MAPPING] ([IRGR_GL_ACCT], [IRGR_GL_TXT], [IRGR_OR_GINI_OR_ARDR]) VALUES (N'0000203100', N'Deferred Revenue - Retransmissions', N'ARDR')
INSERT [dbo].[AM_IRGR_GINI_ARDR_MAPPING] ([IRGR_GL_ACCT], [IRGR_GL_TXT], [IRGR_OR_GINI_OR_ARDR]) VALUES (N'0000203110', N'Deferred Revenue - Future Release Date', N'ARDR')
INSERT [dbo].[AM_IRGR_GINI_ARDR_MAPPING] ([IRGR_GL_ACCT], [IRGR_GL_TXT], [IRGR_OR_GINI_OR_ARDR]) VALUES (N'0000204000', N'Deferred Revenue-Short Term-Intl Tig', N'ARDR')
INSERT [dbo].[AM_IRGR_GINI_ARDR_MAPPING] ([IRGR_GL_ACCT], [IRGR_GL_TXT], [IRGR_OR_GINI_OR_ARDR]) VALUES (N'0000204100', N'Deferred Revenue - Network Billings', N'ARDR')
INSERT [dbo].[AM_IRGR_GINI_ARDR_MAPPING] ([IRGR_GL_ACCT], [IRGR_GL_TXT], [IRGR_OR_GINI_OR_ARDR]) VALUES (N'0000220302', N'3rd Party Royalty Liability - Non-US', N'ARDR')
INSERT [dbo].[AM_IRGR_GINI_ARDR_MAPPING] ([IRGR_GL_ACCT], [IRGR_GL_TXT], [IRGR_OR_GINI_OR_ARDR]) VALUES (N'0000230025', N'Deferred Revenue Special Customers - Short Term', N'ARDR')
INSERT [dbo].[AM_IRGR_GINI_ARDR_MAPPING] ([IRGR_GL_ACCT], [IRGR_GL_TXT], [IRGR_OR_GINI_OR_ARDR]) VALUES (N'0000290000', N'Deferred Revenue - Long Term', N'ARDR')
INSERT [dbo].[AM_IRGR_GINI_ARDR_MAPPING] ([IRGR_GL_ACCT], [IRGR_GL_TXT], [IRGR_OR_GINI_OR_ARDR]) VALUES (N'0000290070', N'Deferred Revenue - Long Term Net Down', N'ARDR')
INSERT [dbo].[AM_IRGR_GINI_ARDR_MAPPING] ([IRGR_GL_ACCT], [IRGR_GL_TXT], [IRGR_OR_GINI_OR_ARDR]) VALUES (N'0000290080', N'Deferred Liability', N'ARDR')
INSERT [dbo].[AM_IRGR_GINI_ARDR_MAPPING] ([IRGR_GL_ACCT], [IRGR_GL_TXT], [IRGR_OR_GINI_OR_ARDR]) VALUES (N'0000290100', N'Deferred Print Rebates', N'ARDR')
INSERT [dbo].[AM_IRGR_GINI_ARDR_MAPPING] ([IRGR_GL_ACCT], [IRGR_GL_TXT], [IRGR_OR_GINI_OR_ARDR]) VALUES (N'0000200120', N'GR/IR Unvouchered Receipts', N'IRGR')
INSERT [dbo].[AM_IRGR_GINI_ARDR_MAPPING] ([IRGR_GL_ACCT], [IRGR_GL_TXT], [IRGR_OR_GINI_OR_ARDR]) VALUES (N'0000200075', N'Goods Received Invoice Received Clearing', N'IRGR')
GO
