USE [DIVA_SPE_FY2024_Q2]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[AM_IRGR_MATERIAL_GROUP](
	[T023T_MATKL] [nvarchar](255) NULL,
	[T023T_WGBEZ] [nvarchar](255) NULL,
	[IRGR_SPEND_CAT_LEVEL_1] [nvarchar](255) NULL,
	[IRGR_SPEND_CAT_LEVEL_2] [nvarchar](255) NULL,
	[IRGR_SPEND_CAT_LEVEL_3] [nvarchar](255) NULL,
	[IRGR_SPEND_CAT_LEVEL_4] [nvarchar](255) NULL
) ON [PRIMARY]
GO
INSERT [dbo].[AM_IRGR_MATERIAL_GROUP] ([T023T_MATKL], [T023T_WGBEZ], [IRGR_SPEND_CAT_LEVEL_1], [IRGR_SPEND_CAT_LEVEL_2], [IRGR_SPEND_CAT_LEVEL_3], [IRGR_SPEND_CAT_LEVEL_4]) VALUES (N'MA30', N'Materials and finished goods', N'Production procurement', N'Production procurement', N'Production procurement', N'Materials and finished goods')
INSERT [dbo].[AM_IRGR_MATERIAL_GROUP] ([T023T_MATKL], [T023T_WGBEZ], [IRGR_SPEND_CAT_LEVEL_1], [IRGR_SPEND_CAT_LEVEL_2], [IRGR_SPEND_CAT_LEVEL_3], [IRGR_SPEND_CAT_LEVEL_4]) VALUES (N'MA01', N'PS4 HW', N'Product procurement', N'Hardware', N'Console', N'PS4 HW')
INSERT [dbo].[AM_IRGR_MATERIAL_GROUP] ([T023T_MATKL], [T023T_WGBEZ], [IRGR_SPEND_CAT_LEVEL_1], [IRGR_SPEND_CAT_LEVEL_2], [IRGR_SPEND_CAT_LEVEL_3], [IRGR_SPEND_CAT_LEVEL_4]) VALUES (N'MA05', N'DS4 Black', N'Product procurement', N'Hardware', N'DS controler', N'DS4 Black')
INSERT [dbo].[AM_IRGR_MATERIAL_GROUP] ([T023T_MATKL], [T023T_WGBEZ], [IRGR_SPEND_CAT_LEVEL_1], [IRGR_SPEND_CAT_LEVEL_2], [IRGR_SPEND_CAT_LEVEL_3], [IRGR_SPEND_CAT_LEVEL_4]) VALUES (N'MA06', N'DS4 Color', N'Product procurement', N'Hardware', N'DS controler', N'DS4 Color')
INSERT [dbo].[AM_IRGR_MATERIAL_GROUP] ([T023T_MATKL], [T023T_WGBEZ], [IRGR_SPEND_CAT_LEVEL_1], [IRGR_SPEND_CAT_LEVEL_2], [IRGR_SPEND_CAT_LEVEL_3], [IRGR_SPEND_CAT_LEVEL_4]) VALUES (N'MA08', N'PS4 Peripheral', N'Product procurement', N'Hardware', N'Other', N'PS4 Peripheral')
INSERT [dbo].[AM_IRGR_MATERIAL_GROUP] ([T023T_MATKL], [T023T_WGBEZ], [IRGR_SPEND_CAT_LEVEL_1], [IRGR_SPEND_CAT_LEVEL_2], [IRGR_SPEND_CAT_LEVEL_3], [IRGR_SPEND_CAT_LEVEL_4]) VALUES (N'MA11', N'PSVR HW', N'Product procurement', N'Hardware', N'Other', N'PSVR HW')
INSERT [dbo].[AM_IRGR_MATERIAL_GROUP] ([T023T_MATKL], [T023T_WGBEZ], [IRGR_SPEND_CAT_LEVEL_1], [IRGR_SPEND_CAT_LEVEL_2], [IRGR_SPEND_CAT_LEVEL_3], [IRGR_SPEND_CAT_LEVEL_4]) VALUES (N'MA12', N'PSVR Peripheral', N'Product procurement', N'Hardware', N'Other', N'PSVR Peripheral')
INSERT [dbo].[AM_IRGR_MATERIAL_GROUP] ([T023T_MATKL], [T023T_WGBEZ], [IRGR_SPEND_CAT_LEVEL_1], [IRGR_SPEND_CAT_LEVEL_2], [IRGR_SPEND_CAT_LEVEL_3], [IRGR_SPEND_CAT_LEVEL_4]) VALUES (N'MA13', N'Software', N'Product procurement', N'Software', N'Software', N'Software')
INSERT [dbo].[AM_IRGR_MATERIAL_GROUP] ([T023T_MATKL], [T023T_WGBEZ], [IRGR_SPEND_CAT_LEVEL_1], [IRGR_SPEND_CAT_LEVEL_2], [IRGR_SPEND_CAT_LEVEL_3], [IRGR_SPEND_CAT_LEVEL_4]) VALUES (N'MA14', N'Dev Kit', N'Product procurement', N'Software', N'Software', N'Dev Kit')
INSERT [dbo].[AM_IRGR_MATERIAL_GROUP] ([T023T_MATKL], [T023T_WGBEZ], [IRGR_SPEND_CAT_LEVEL_1], [IRGR_SPEND_CAT_LEVEL_2], [IRGR_SPEND_CAT_LEVEL_3], [IRGR_SPEND_CAT_LEVEL_4]) VALUES (N'MA18', N'Plastic', N'Warehousing materials', N'Consumables', N'Consumables', N'Plastic')
INSERT [dbo].[AM_IRGR_MATERIAL_GROUP] ([T023T_MATKL], [T023T_WGBEZ], [IRGR_SPEND_CAT_LEVEL_1], [IRGR_SPEND_CAT_LEVEL_2], [IRGR_SPEND_CAT_LEVEL_3], [IRGR_SPEND_CAT_LEVEL_4]) VALUES (N'MA19', N'Corrugate', N'Warehousing materials', N'Consumables', N'Consumables', N'Corrugate')
INSERT [dbo].[AM_IRGR_MATERIAL_GROUP] ([T023T_MATKL], [T023T_WGBEZ], [IRGR_SPEND_CAT_LEVEL_1], [IRGR_SPEND_CAT_LEVEL_2], [IRGR_SPEND_CAT_LEVEL_3], [IRGR_SPEND_CAT_LEVEL_4]) VALUES (N'MA20', N'Paper Prints', N'Warehousing materials', N'Consumables', N'Consumables', N'Paper Prints')
INSERT [dbo].[AM_IRGR_MATERIAL_GROUP] ([T023T_MATKL], [T023T_WGBEZ], [IRGR_SPEND_CAT_LEVEL_1], [IRGR_SPEND_CAT_LEVEL_2], [IRGR_SPEND_CAT_LEVEL_3], [IRGR_SPEND_CAT_LEVEL_4]) VALUES (N'MA21', N'Label / Sticker', N'Warehousing materials', N'Consumables', N'Consumables', N'Label / Sticker')
INSERT [dbo].[AM_IRGR_MATERIAL_GROUP] ([T023T_MATKL], [T023T_WGBEZ], [IRGR_SPEND_CAT_LEVEL_1], [IRGR_SPEND_CAT_LEVEL_2], [IRGR_SPEND_CAT_LEVEL_3], [IRGR_SPEND_CAT_LEVEL_4]) VALUES (N'MA22', N'Insert', N'Warehousing materials', N'Consumables', N'Consumables', N'Insert')
INSERT [dbo].[AM_IRGR_MATERIAL_GROUP] ([T023T_MATKL], [T023T_WGBEZ], [IRGR_SPEND_CAT_LEVEL_1], [IRGR_SPEND_CAT_LEVEL_2], [IRGR_SPEND_CAT_LEVEL_3], [IRGR_SPEND_CAT_LEVEL_4]) VALUES (N'MA24', N'Headset', N'Product procurement', N'Hardware', N'Other', N'Headset')
INSERT [dbo].[AM_IRGR_MATERIAL_GROUP] ([T023T_MATKL], [T023T_WGBEZ], [IRGR_SPEND_CAT_LEVEL_1], [IRGR_SPEND_CAT_LEVEL_2], [IRGR_SPEND_CAT_LEVEL_3], [IRGR_SPEND_CAT_LEVEL_4]) VALUES (N'MA32', N'Finance Item', N'Non product procurement', N'Other', N'Other', N'Finance Item')
INSERT [dbo].[AM_IRGR_MATERIAL_GROUP] ([T023T_MATKL], [T023T_WGBEZ], [IRGR_SPEND_CAT_LEVEL_1], [IRGR_SPEND_CAT_LEVEL_2], [IRGR_SPEND_CAT_LEVEL_3], [IRGR_SPEND_CAT_LEVEL_4]) VALUES (N'MA34', N'Paperboard', N'Warehousing materials', N'Consumables', N'Consumables', N'Paperboard')
INSERT [dbo].[AM_IRGR_MATERIAL_GROUP] ([T023T_MATKL], [T023T_WGBEZ], [IRGR_SPEND_CAT_LEVEL_1], [IRGR_SPEND_CAT_LEVEL_2], [IRGR_SPEND_CAT_LEVEL_3], [IRGR_SPEND_CAT_LEVEL_4]) VALUES (N'MA51', N'PS5 STANDARD', N'Product procurement', N'Hardware', N'Console', N'PS5 STANDARD')
INSERT [dbo].[AM_IRGR_MATERIAL_GROUP] ([T023T_MATKL], [T023T_WGBEZ], [IRGR_SPEND_CAT_LEVEL_1], [IRGR_SPEND_CAT_LEVEL_2], [IRGR_SPEND_CAT_LEVEL_3], [IRGR_SPEND_CAT_LEVEL_4]) VALUES (N'MA53', N'PS5 DIGITAL EDITION', N'Product procurement', N'Hardware', N'Console', N'PS5 DIGITAL EDITION')
INSERT [dbo].[AM_IRGR_MATERIAL_GROUP] ([T023T_MATKL], [T023T_WGBEZ], [IRGR_SPEND_CAT_LEVEL_1], [IRGR_SPEND_CAT_LEVEL_2], [IRGR_SPEND_CAT_LEVEL_3], [IRGR_SPEND_CAT_LEVEL_4]) VALUES (N'MA55', N'PS5 DUALSENSE', N'Product procurement', N'Hardware', N'DS controler', N'PS5 DUALSENSE')
INSERT [dbo].[AM_IRGR_MATERIAL_GROUP] ([T023T_MATKL], [T023T_WGBEZ], [IRGR_SPEND_CAT_LEVEL_1], [IRGR_SPEND_CAT_LEVEL_2], [IRGR_SPEND_CAT_LEVEL_3], [IRGR_SPEND_CAT_LEVEL_4]) VALUES (N'MA57', N'PS5 PERIPHERAL', N'Product procurement', N'Hardware', N'Other', N'PS5 PERIPHERAL')
INSERT [dbo].[AM_IRGR_MATERIAL_GROUP] ([T023T_MATKL], [T023T_WGBEZ], [IRGR_SPEND_CAT_LEVEL_1], [IRGR_SPEND_CAT_LEVEL_2], [IRGR_SPEND_CAT_LEVEL_3], [IRGR_SPEND_CAT_LEVEL_4]) VALUES (N'MA16', N'Collector''s Edition', N'Product procurement', N'Hardware', N'Console', N'Collector''s Edition')
INSERT [dbo].[AM_IRGR_MATERIAL_GROUP] ([T023T_MATKL], [T023T_WGBEZ], [IRGR_SPEND_CAT_LEVEL_1], [IRGR_SPEND_CAT_LEVEL_2], [IRGR_SPEND_CAT_LEVEL_3], [IRGR_SPEND_CAT_LEVEL_4]) VALUES (N'MA17', N'Employee Store', N'Product procurement', N'Hardware', N'Other', N'Employee Store')
INSERT [dbo].[AM_IRGR_MATERIAL_GROUP] ([T023T_MATKL], [T023T_WGBEZ], [IRGR_SPEND_CAT_LEVEL_1], [IRGR_SPEND_CAT_LEVEL_2], [IRGR_SPEND_CAT_LEVEL_3], [IRGR_SPEND_CAT_LEVEL_4]) VALUES (N'MA23', N'Cable', N'Product procurement', N'Hardware', N'Other', N'Cable')
INSERT [dbo].[AM_IRGR_MATERIAL_GROUP] ([T023T_MATKL], [T023T_WGBEZ], [IRGR_SPEND_CAT_LEVEL_1], [IRGR_SPEND_CAT_LEVEL_2], [IRGR_SPEND_CAT_LEVEL_3], [IRGR_SPEND_CAT_LEVEL_4]) VALUES (N'MA25', N'Aim Controller', N'Product procurement', N'Hardware', N'Other', N'Aim Controller')
INSERT [dbo].[AM_IRGR_MATERIAL_GROUP] ([T023T_MATKL], [T023T_WGBEZ], [IRGR_SPEND_CAT_LEVEL_1], [IRGR_SPEND_CAT_LEVEL_2], [IRGR_SPEND_CAT_LEVEL_3], [IRGR_SPEND_CAT_LEVEL_4]) VALUES (N'MA26', N'Other', N'Product procurement', N'Hardware', N'Other', N'Other')
INSERT [dbo].[AM_IRGR_MATERIAL_GROUP] ([T023T_MATKL], [T023T_WGBEZ], [IRGR_SPEND_CAT_LEVEL_1], [IRGR_SPEND_CAT_LEVEL_2], [IRGR_SPEND_CAT_LEVEL_3], [IRGR_SPEND_CAT_LEVEL_4]) VALUES (N'MA35', N'PSN $ Cards', N'Product procurement', N'Cards', N'Cards', N'PSN $ Cards')
INSERT [dbo].[AM_IRGR_MATERIAL_GROUP] ([T023T_MATKL], [T023T_WGBEZ], [IRGR_SPEND_CAT_LEVEL_1], [IRGR_SPEND_CAT_LEVEL_2], [IRGR_SPEND_CAT_LEVEL_3], [IRGR_SPEND_CAT_LEVEL_4]) VALUES (N'MA37', N'NFR SOFTWARE', N'Product procurement', N'Software', N'Other', N'NFR SOFTWARE')
GO
