USE [DIVA_SPE_FY2024_Q2]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[AM_SALES_DIST_KAPPL_CODES](
	[SPRAS] [nvarchar](3) NULL,
	[KAPPL] [nvarchar](4) NULL,
	[VTEXT] [nvarchar](22) NULL
) ON [PRIMARY]
GO
