USE [DIVA_SPE_FY2024_Q2]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[AM_PAHI_TEST_VALUE](
	[AM_PAHI_HOSTNAME] [nvarchar](255) NULL,
	[AM_PAHI_PARDATE] [datetime] NULL,
	[AM_PAHI_PARNAME] [nvarchar](255) NULL,
	[AM_PAHI_PARNAME_DESC] [nvarchar](255) NULL,
	[PAHI_PARVALUE] [nvarchar](255) NULL,
	[AM_PAHI_TEST_VALUE] [nvarchar](255) NULL
) ON [PRIMARY]
GO
