USE [DIVA_SPE_FY2024_Q2]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[AM_COMPANY_CODE](
	[COMPANY_CODE] [nvarchar](100) NULL,
	[BUKRS_MAPPING] [nvarchar](100) NULL
) ON [PRIMARY]
GO
INSERT [dbo].[AM_COMPANY_CODE] ([COMPANY_CODE], [BUKRS_MAPPING]) VALUES (N'5385', N'5385')
INSERT [dbo].[AM_COMPANY_CODE] ([COMPANY_CODE], [BUKRS_MAPPING]) VALUES (N'5386', N'5386')
INSERT [dbo].[AM_COMPANY_CODE] ([COMPANY_CODE], [BUKRS_MAPPING]) VALUES (N'5387', N'5387')
INSERT [dbo].[AM_COMPANY_CODE] ([COMPANY_CODE], [BUKRS_MAPPING]) VALUES (N'5388', N'5388')
INSERT [dbo].[AM_COMPANY_CODE] ([COMPANY_CODE], [BUKRS_MAPPING]) VALUES (N'5389', N'5389')
INSERT [dbo].[AM_COMPANY_CODE] ([COMPANY_CODE], [BUKRS_MAPPING]) VALUES (N'5396', N'5396')
INSERT [dbo].[AM_COMPANY_CODE] ([COMPANY_CODE], [BUKRS_MAPPING]) VALUES (N'5397', N'5397')
INSERT [dbo].[AM_COMPANY_CODE] ([COMPANY_CODE], [BUKRS_MAPPING]) VALUES (N'5398', N'5398')
INSERT [dbo].[AM_COMPANY_CODE] ([COMPANY_CODE], [BUKRS_MAPPING]) VALUES (N'5403', N'5403')
INSERT [dbo].[AM_COMPANY_CODE] ([COMPANY_CODE], [BUKRS_MAPPING]) VALUES (N'5406', N'5406')
INSERT [dbo].[AM_COMPANY_CODE] ([COMPANY_CODE], [BUKRS_MAPPING]) VALUES (N'5410', N'5410')
INSERT [dbo].[AM_COMPANY_CODE] ([COMPANY_CODE], [BUKRS_MAPPING]) VALUES (N'5411', N'5411')
INSERT [dbo].[AM_COMPANY_CODE] ([COMPANY_CODE], [BUKRS_MAPPING]) VALUES (N'5412', N'5412')
INSERT [dbo].[AM_COMPANY_CODE] ([COMPANY_CODE], [BUKRS_MAPPING]) VALUES (N'5413', N'5413')
INSERT [dbo].[AM_COMPANY_CODE] ([COMPANY_CODE], [BUKRS_MAPPING]) VALUES (N'5414', N'5414')
INSERT [dbo].[AM_COMPANY_CODE] ([COMPANY_CODE], [BUKRS_MAPPING]) VALUES (N'5415', N'5415')
INSERT [dbo].[AM_COMPANY_CODE] ([COMPANY_CODE], [BUKRS_MAPPING]) VALUES (N'5416', N'5416')
INSERT [dbo].[AM_COMPANY_CODE] ([COMPANY_CODE], [BUKRS_MAPPING]) VALUES (N'5417', N'5417')
INSERT [dbo].[AM_COMPANY_CODE] ([COMPANY_CODE], [BUKRS_MAPPING]) VALUES (N'5419', N'5419')
INSERT [dbo].[AM_COMPANY_CODE] ([COMPANY_CODE], [BUKRS_MAPPING]) VALUES (N'5420', N'5420')
INSERT [dbo].[AM_COMPANY_CODE] ([COMPANY_CODE], [BUKRS_MAPPING]) VALUES (N'5421', N'5421')
INSERT [dbo].[AM_COMPANY_CODE] ([COMPANY_CODE], [BUKRS_MAPPING]) VALUES (N'5422', N'5422')
INSERT [dbo].[AM_COMPANY_CODE] ([COMPANY_CODE], [BUKRS_MAPPING]) VALUES (N'5424', N'5424')
INSERT [dbo].[AM_COMPANY_CODE] ([COMPANY_CODE], [BUKRS_MAPPING]) VALUES (N'5425', N'5425')
INSERT [dbo].[AM_COMPANY_CODE] ([COMPANY_CODE], [BUKRS_MAPPING]) VALUES (N'5426', N'5426')
INSERT [dbo].[AM_COMPANY_CODE] ([COMPANY_CODE], [BUKRS_MAPPING]) VALUES (N'5427', N'5427')
INSERT [dbo].[AM_COMPANY_CODE] ([COMPANY_CODE], [BUKRS_MAPPING]) VALUES (N'5428', N'5428')
INSERT [dbo].[AM_COMPANY_CODE] ([COMPANY_CODE], [BUKRS_MAPPING]) VALUES (N'5431', N'5431')
INSERT [dbo].[AM_COMPANY_CODE] ([COMPANY_CODE], [BUKRS_MAPPING]) VALUES (N'5432', N'5432')
INSERT [dbo].[AM_COMPANY_CODE] ([COMPANY_CODE], [BUKRS_MAPPING]) VALUES (N'5444', N'5444')
GO
