USE [DIVA_SPE_FY2024_Q2]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[AM_SALE_REDUCTION_AGING](
	[SR_GL_ACCT] [nvarchar](255) NULL,
	[SR_GL_TXT] [nvarchar](255) NULL,
	[SR_FLAG] [nvarchar](255) NULL
) ON [PRIMARY]
GO
INSERT [dbo].[AM_SALE_REDUCTION_AGING] ([SR_GL_ACCT], [SR_GL_TXT], [SR_FLAG]) VALUES (N'A216100', N'Provision for Activity Based Co-Op A&P', N'COOP')
INSERT [dbo].[AM_SALE_REDUCTION_AGING] ([SR_GL_ACCT], [SR_GL_TXT], [SR_FLAG]) VALUES (N'A216140', N'Accrd exps, SR, Stock Compensation (Activity)', N'Stock comp')
INSERT [dbo].[AM_SALE_REDUCTION_AGING] ([SR_GL_ACCT], [SR_GL_TXT], [SR_FLAG]) VALUES (N'A216141', N'Accrd exps, SR, Stock Compensation (General)', N'Stock comp')
INSERT [dbo].[AM_SALE_REDUCTION_AGING] ([SR_GL_ACCT], [SR_GL_TXT], [SR_FLAG]) VALUES (N'A216164', N'Accrd exps, SR, Sell Thru/Promo Rebate (Activity)', N'Sell out')
INSERT [dbo].[AM_SALE_REDUCTION_AGING] ([SR_GL_ACCT], [SR_GL_TXT], [SR_FLAG]) VALUES (N'A216165', N'Accrd exps, SR, Sell Thru/Promo Rebate (General)', N'Sell out')
INSERT [dbo].[AM_SALE_REDUCTION_AGING] ([SR_GL_ACCT], [SR_GL_TXT], [SR_FLAG]) VALUES (N'A622210', NULL, NULL)
INSERT [dbo].[AM_SALE_REDUCTION_AGING] ([SR_GL_ACCT], [SR_GL_TXT], [SR_FLAG]) VALUES (N'A622310', NULL, NULL)
INSERT [dbo].[AM_SALE_REDUCTION_AGING] ([SR_GL_ACCT], [SR_GL_TXT], [SR_FLAG]) VALUES (N'A622311', NULL, NULL)
INSERT [dbo].[AM_SALE_REDUCTION_AGING] ([SR_GL_ACCT], [SR_GL_TXT], [SR_FLAG]) VALUES (N'A622424', NULL, NULL)
INSERT [dbo].[AM_SALE_REDUCTION_AGING] ([SR_GL_ACCT], [SR_GL_TXT], [SR_FLAG]) VALUES (N'A622425', NULL, NULL)
GO
