USE [DIVA_SPE_FY2024_Q2]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[AM_PROC_CAT](
	[PROC_CAT_ID] [nvarchar](42) NULL,
	[PROC_CAT_L1] [nvarchar](27) NULL,
	[PROC_CAT_MTRL_GRP_CODE] [nvarchar](11) NULL,
	[PROC_CAT_L2] [nvarchar](22) NULL,
	[PROC_CAT_L3] [nvarchar](42) NULL
) ON [PRIMARY]
GO
