USE [DIVA_SPE_FY2024_Q2]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[AM_OTHER_ACCOUTS](
	[SKAT_SAKNR] [nvarchar](12) NULL,
	[SKAT_TXT50] [nvarchar](52) NULL
) ON [PRIMARY]
GO
