USE [DIVA_SPE_FY2024_Q2]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[AM_VENDOR_EXCEPTION_LIST](
	[VEL_COMPANY_CODE] [varchar](4) NOT NULL,
	[VEL_SUPPLIER_NUM] [varchar](2) NOT NULL
) ON [PRIMARY]
GO
