USE [DIVA_SPE_FY2024_Q2]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[AM_SCOPE](
	[SCOPE_MANDANT] [nvarchar](100) NULL,
	[SCOPE_CMPNY_CODE] [nvarchar](100) NULL,
	[SCOPE_BUSINESS_DMN_L1] [nvarchar](100) NULL,
	[SCOPE_BUSINESS_DMN_L2] [nvarchar](100) NULL,
	[SCOPE_SYSTEM] [nvarchar](100) NULL
) ON [PRIMARY]
GO
INSERT [dbo].[AM_SCOPE] ([SCOPE_MANDANT], [SCOPE_CMPNY_CODE], [SCOPE_BUSINESS_DMN_L1], [SCOPE_BUSINESS_DMN_L2], [SCOPE_SYSTEM]) VALUES (N'500', N'5385', N'NA', N'Left Bank Pictures Ltd', N'NA')
INSERT [dbo].[AM_SCOPE] ([SCOPE_MANDANT], [SCOPE_CMPNY_CODE], [SCOPE_BUSINESS_DMN_L1], [SCOPE_BUSINESS_DMN_L2], [SCOPE_SYSTEM]) VALUES (N'500', N'5386', N'NA', N'Left Bank Pictures(TV)Ltd', N'NA')
INSERT [dbo].[AM_SCOPE] ([SCOPE_MANDANT], [SCOPE_CMPNY_CODE], [SCOPE_BUSINESS_DMN_L1], [SCOPE_BUSINESS_DMN_L2], [SCOPE_SYSTEM]) VALUES (N'500', N'5387', N'NA', N'Left Bank Pic (Film) Ltd', N'NA')
INSERT [dbo].[AM_SCOPE] ([SCOPE_MANDANT], [SCOPE_CMPNY_CODE], [SCOPE_BUSINESS_DMN_L1], [SCOPE_BUSINESS_DMN_L2], [SCOPE_SYSTEM]) VALUES (N'500', N'5388', N'NA', N'LBM Redemption', N'NA')
INSERT [dbo].[AM_SCOPE] ([SCOPE_MANDANT], [SCOPE_CMPNY_CODE], [SCOPE_BUSINESS_DMN_L1], [SCOPE_BUSINESS_DMN_L2], [SCOPE_SYSTEM]) VALUES (N'500', N'5389', N'NA', N'LBM TFIB LTD', N'NA')
INSERT [dbo].[AM_SCOPE] ([SCOPE_MANDANT], [SCOPE_CMPNY_CODE], [SCOPE_BUSINESS_DMN_L1], [SCOPE_BUSINESS_DMN_L2], [SCOPE_SYSTEM]) VALUES (N'500', N'5396', N'NA', N'LBP (Strike Bank 7) Ltd', N'NA')
INSERT [dbo].[AM_SCOPE] ([SCOPE_MANDANT], [SCOPE_CMPNY_CODE], [SCOPE_BUSINESS_DMN_L1], [SCOPE_BUSINESS_DMN_L2], [SCOPE_SYSTEM]) VALUES (N'500', N'5397', N'NA', N'LBP Outlander 4 Ltd', N'NA')
INSERT [dbo].[AM_SCOPE] ([SCOPE_MANDANT], [SCOPE_CMPNY_CODE], [SCOPE_BUSINESS_DMN_L1], [SCOPE_BUSINESS_DMN_L2], [SCOPE_SYSTEM]) VALUES (N'500', N'5398', N'NA', N'LBP Outlander Series2 Ltd', N'NA')
INSERT [dbo].[AM_SCOPE] ([SCOPE_MANDANT], [SCOPE_CMPNY_CODE], [SCOPE_BUSINESS_DMN_L1], [SCOPE_BUSINESS_DMN_L2], [SCOPE_SYSTEM]) VALUES (N'500', N'5403', N'NA', N'LBP Strike Back 8 Ltd', N'NA')
INSERT [dbo].[AM_SCOPE] ([SCOPE_MANDANT], [SCOPE_CMPNY_CODE], [SCOPE_BUSINESS_DMN_L1], [SCOPE_BUSINESS_DMN_L2], [SCOPE_SYSTEM]) VALUES (N'500', N'5406', N'NA', N'LBP (The Crown) Ltd', N'NA')
INSERT [dbo].[AM_SCOPE] ([SCOPE_MANDANT], [SCOPE_CMPNY_CODE], [SCOPE_BUSINESS_DMN_L1], [SCOPE_BUSINESS_DMN_L2], [SCOPE_SYSTEM]) VALUES (N'500', N'5410', N'NA', N'LBP Outlander Series3 Ltd', N'NA')
INSERT [dbo].[AM_SCOPE] ([SCOPE_MANDANT], [SCOPE_CMPNY_CODE], [SCOPE_BUSINESS_DMN_L1], [SCOPE_BUSINESS_DMN_L2], [SCOPE_SYSTEM]) VALUES (N'500', N'5411', N'NA', N'LBP The Crown Series2 Ltd', N'NA')
INSERT [dbo].[AM_SCOPE] ([SCOPE_MANDANT], [SCOPE_CMPNY_CODE], [SCOPE_BUSINESS_DMN_L1], [SCOPE_BUSINESS_DMN_L2], [SCOPE_SYSTEM]) VALUES (N'500', N'5412', N'NA', N'LBP Electric Dreams Ltd', N'NA')
INSERT [dbo].[AM_SCOPE] ([SCOPE_MANDANT], [SCOPE_CMPNY_CODE], [SCOPE_BUSINESS_DMN_L1], [SCOPE_BUSINESS_DMN_L2], [SCOPE_SYSTEM]) VALUES (N'500', N'5413', N'NA', N'LBP The Crown Series3 Ltd', N'NA')
INSERT [dbo].[AM_SCOPE] ([SCOPE_MANDANT], [SCOPE_CMPNY_CODE], [SCOPE_BUSINESS_DMN_L1], [SCOPE_BUSINESS_DMN_L2], [SCOPE_SYSTEM]) VALUES (N'500', N'5414', N'NA', N'LBP Outlander 5 Ltd', N'NA')
INSERT [dbo].[AM_SCOPE] ([SCOPE_MANDANT], [SCOPE_CMPNY_CODE], [SCOPE_BUSINESS_DMN_L1], [SCOPE_BUSINESS_DMN_L2], [SCOPE_SYSTEM]) VALUES (N'500', N'5415', N'NA', N'LBP The Crown Series4 Ltd', N'NA')
INSERT [dbo].[AM_SCOPE] ([SCOPE_MANDANT], [SCOPE_CMPNY_CODE], [SCOPE_BUSINESS_DMN_L1], [SCOPE_BUSINESS_DMN_L2], [SCOPE_SYSTEM]) VALUES (N'500', N'5416', N'NA', N'LBP Outlander 6 Ltd', N'NA')
INSERT [dbo].[AM_SCOPE] ([SCOPE_MANDANT], [SCOPE_CMPNY_CODE], [SCOPE_BUSINESS_DMN_L1], [SCOPE_BUSINESS_DMN_L2], [SCOPE_SYSTEM]) VALUES (N'500', N'5417', N'NA', N'LBP The Crown Series5 Ltd', N'NA')
INSERT [dbo].[AM_SCOPE] ([SCOPE_MANDANT], [SCOPE_CMPNY_CODE], [SCOPE_BUSINESS_DMN_L1], [SCOPE_BUSINESS_DMN_L2], [SCOPE_SYSTEM]) VALUES (N'500', N'5419', N'NA', N'LBP The Crown 6 Ltd', N'NA')
INSERT [dbo].[AM_SCOPE] ([SCOPE_MANDANT], [SCOPE_CMPNY_CODE], [SCOPE_BUSINESS_DMN_L1], [SCOPE_BUSINESS_DMN_L2], [SCOPE_SYSTEM]) VALUES (N'500', N'5420', N'NA', N'Left Bank Media Ltd', N'NA')
INSERT [dbo].[AM_SCOPE] ([SCOPE_MANDANT], [SCOPE_CMPNY_CODE], [SCOPE_BUSINESS_DMN_L1], [SCOPE_BUSINESS_DMN_L2], [SCOPE_SYSTEM]) VALUES (N'500', N'5421', N'NA', N'LBP TV 2 Ltd', N'NA')
INSERT [dbo].[AM_SCOPE] ([SCOPE_MANDANT], [SCOPE_CMPNY_CODE], [SCOPE_BUSINESS_DMN_L1], [SCOPE_BUSINESS_DMN_L2], [SCOPE_SYSTEM]) VALUES (N'500', N'5422', N'NA', N'LB Media Film Ltd', N'NA')
INSERT [dbo].[AM_SCOPE] ([SCOPE_MANDANT], [SCOPE_CMPNY_CODE], [SCOPE_BUSINESS_DMN_L1], [SCOPE_BUSINESS_DMN_L2], [SCOPE_SYSTEM]) VALUES (N'500', N'5424', N'NA', N'LBP Origin Ltd', N'NA')
INSERT [dbo].[AM_SCOPE] ([SCOPE_MANDANT], [SCOPE_CMPNY_CODE], [SCOPE_BUSINESS_DMN_L1], [SCOPE_BUSINESS_DMN_L2], [SCOPE_SYSTEM]) VALUES (N'500', N'5425', N'NA', N'LBM White Lines Ltd', N'NA')
INSERT [dbo].[AM_SCOPE] ([SCOPE_MANDANT], [SCOPE_CMPNY_CODE], [SCOPE_BUSINESS_DMN_L1], [SCOPE_BUSINESS_DMN_L2], [SCOPE_SYSTEM]) VALUES (N'500', N'5426', N'NA', N'LBM Behind Her Eyes Ltd', N'NA')
INSERT [dbo].[AM_SCOPE] ([SCOPE_MANDANT], [SCOPE_CMPNY_CODE], [SCOPE_BUSINESS_DMN_L1], [SCOPE_BUSINESS_DMN_L2], [SCOPE_SYSTEM]) VALUES (N'500', N'5427', N'NA', N'LBM Quiz Ltd', N'NA')
INSERT [dbo].[AM_SCOPE] ([SCOPE_MANDANT], [SCOPE_CMPNY_CODE], [SCOPE_BUSINESS_DMN_L1], [SCOPE_BUSINESS_DMN_L2], [SCOPE_SYSTEM]) VALUES (N'500', N'5428', N'NA', N'LBM INSOMNIA LIMITED', N'NA')
INSERT [dbo].[AM_SCOPE] ([SCOPE_MANDANT], [SCOPE_CMPNY_CODE], [SCOPE_BUSINESS_DMN_L1], [SCOPE_BUSINESS_DMN_L2], [SCOPE_SYSTEM]) VALUES (N'500', N'5431', N'NA', N'LBM The Fear Index Ltd', N'NA')
INSERT [dbo].[AM_SCOPE] ([SCOPE_MANDANT], [SCOPE_CMPNY_CODE], [SCOPE_BUSINESS_DMN_L1], [SCOPE_BUSINESS_DMN_L2], [SCOPE_SYSTEM]) VALUES (N'500', N'5432', N'NA', N'LBM Three Pines Ltd', N'NA')
INSERT [dbo].[AM_SCOPE] ([SCOPE_MANDANT], [SCOPE_CMPNY_CODE], [SCOPE_BUSINESS_DMN_L1], [SCOPE_BUSINESS_DMN_L2], [SCOPE_SYSTEM]) VALUES (N'500', N'5444', N'NA', N'LBM Palomino Ltd', N'NA')
GO
