USE [DIVA_AUS_FY19_23Q2]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[AM_VAT_CLF](
	[ACCOUNT] [nvarchar](255) NULL,
	[GL TEXT] [nvarchar](255) NULL,
	[CLASSIFICATION] [nvarchar](255) NULL
) ON [PRIMARY]
GO
INSERT [dbo].[AM_VAT_CLF] ([ACCOUNT], [GL TEXT], [CLASSIFICATION]) VALUES (N'A038010', N'VAT-R on purch,gen', N'VAT on purchases')
INSERT [dbo].[AM_VAT_CLF] ([ACCOUNT], [GL TEXT], [CLASSIFICATION]) VALUES (N'A056010', N'DTA,National tax', N'VAT on purchases')
INSERT [dbo].[AM_VAT_CLF] ([ACCOUNT], [GL TEXT], [CLASSIFICATION]) VALUES (N'A215851', N'Oth AP-NT Doc Split', N'VAT on purchases')
INSERT [dbo].[AM_VAT_CLF] ([ACCOUNT], [GL TEXT], [CLASSIFICATION]) VALUES (N'A220010', N'Tax-P on sales,Gen', N'VAT on sales')
INSERT [dbo].[AM_VAT_CLF] ([ACCOUNT], [GL TEXT], [CLASSIFICATION]) VALUES (N'A220020', N'Tax-P on sales-D GL', N'VAT on sales')
INSERT [dbo].[AM_VAT_CLF] ([ACCOUNT], [GL TEXT], [CLASSIFICATION]) VALUES (N'A220100', N'Tax-P,VAT O.tax', N'VAT on sales')
GO
