USE [DIVA_AUS_FY19_23Q2]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[AM_IRGR_MATERIAL_GROUP_HIERARCHY](
	[T023T_MATKL] [nvarchar](255) NULL,
	[T023T_WGBEZ] [nvarchar](255) NULL,
	[IRGR_SPEND_CAT_LEVEL_1] [nvarchar](255) NULL,
	[IRGR_SPEND_CAT_LEVEL_2] [nvarchar](255) NULL,
	[IRGR_SPEND_CAT_LEVEL_3] [nvarchar](255) NULL,
	[IRGR_SPEND_CAT_LEVEL_4] [nvarchar](255) NULL
) ON [PRIMARY]
GO
INSERT [dbo].[AM_IRGR_MATERIAL_GROUP_HIERARCHY] ([T023T_MATKL], [T023T_WGBEZ], [IRGR_SPEND_CAT_LEVEL_1], [IRGR_SPEND_CAT_LEVEL_2], [IRGR_SPEND_CAT_LEVEL_3], [IRGR_SPEND_CAT_LEVEL_4]) VALUES (N'01', N'Material group 1', N'Product procurement', N'Other', N'Other', N'Material group 1')
INSERT [dbo].[AM_IRGR_MATERIAL_GROUP_HIERARCHY] ([T023T_MATKL], [T023T_WGBEZ], [IRGR_SPEND_CAT_LEVEL_1], [IRGR_SPEND_CAT_LEVEL_2], [IRGR_SPEND_CAT_LEVEL_3], [IRGR_SPEND_CAT_LEVEL_4]) VALUES (N'1', N'Material group 1', N'Product procurement', N'Other', N'Other', N'Material group 1')
INSERT [dbo].[AM_IRGR_MATERIAL_GROUP_HIERARCHY] ([T023T_MATKL], [T023T_WGBEZ], [IRGR_SPEND_CAT_LEVEL_1], [IRGR_SPEND_CAT_LEVEL_2], [IRGR_SPEND_CAT_LEVEL_3], [IRGR_SPEND_CAT_LEVEL_4]) VALUES (N'4020', N'AUTOMOTIVE BUSINESS', N'Product procurement', N'SSS', N'SSS', N'AUTOMOTIVE BUSINESS')
INSERT [dbo].[AM_IRGR_MATERIAL_GROUP_HIERARCHY] ([T023T_MATKL], [T023T_WGBEZ], [IRGR_SPEND_CAT_LEVEL_1], [IRGR_SPEND_CAT_LEVEL_2], [IRGR_SPEND_CAT_LEVEL_3], [IRGR_SPEND_CAT_LEVEL_4]) VALUES (N'4230', N'VIDEO&SOUND PRODUCTS', N'Product procurement', N'ET&S', N'ET&S', N'VIDEO&SOUND PRODUCTS')
INSERT [dbo].[AM_IRGR_MATERIAL_GROUP_HIERARCHY] ([T023T_MATKL], [T023T_WGBEZ], [IRGR_SPEND_CAT_LEVEL_1], [IRGR_SPEND_CAT_LEVEL_2], [IRGR_SPEND_CAT_LEVEL_3], [IRGR_SPEND_CAT_LEVEL_4]) VALUES (N'4710', N'ENERGY BIZ', N'Product procurement', N'RME', N'RME', N'ENERGY BIZ')
INSERT [dbo].[AM_IRGR_MATERIAL_GROUP_HIERARCHY] ([T023T_MATKL], [T023T_WGBEZ], [IRGR_SPEND_CAT_LEVEL_1], [IRGR_SPEND_CAT_LEVEL_2], [IRGR_SPEND_CAT_LEVEL_3], [IRGR_SPEND_CAT_LEVEL_4]) VALUES (N'4720', N'STORAGE MEDIA', N'Product procurement', N'RME', N'RME', N'STORAGE MEDIA')
INSERT [dbo].[AM_IRGR_MATERIAL_GROUP_HIERARCHY] ([T023T_MATKL], [T023T_WGBEZ], [IRGR_SPEND_CAT_LEVEL_1], [IRGR_SPEND_CAT_LEVEL_2], [IRGR_SPEND_CAT_LEVEL_3], [IRGR_SPEND_CAT_LEVEL_4]) VALUES (N'4870', N'MEDIA SOLUTION', N'Product procurement', N'ET&S', N'ET&S', N'MEDIA SOLUTION')
INSERT [dbo].[AM_IRGR_MATERIAL_GROUP_HIERARCHY] ([T023T_MATKL], [T023T_WGBEZ], [IRGR_SPEND_CAT_LEVEL_1], [IRGR_SPEND_CAT_LEVEL_2], [IRGR_SPEND_CAT_LEVEL_3], [IRGR_SPEND_CAT_LEVEL_4]) VALUES (N'4890', N'BUSINESS SOLUTION', N'Product procurement', N'ET&S', N'ET&S', N'BUSINESS SOLUTION')
INSERT [dbo].[AM_IRGR_MATERIAL_GROUP_HIERARCHY] ([T023T_MATKL], [T023T_WGBEZ], [IRGR_SPEND_CAT_LEVEL_1], [IRGR_SPEND_CAT_LEVEL_2], [IRGR_SPEND_CAT_LEVEL_3], [IRGR_SPEND_CAT_LEVEL_4]) VALUES (N'4900', N'SERVICE BUSINESS', N'Product procurement', N'ET&S', N'ET&S', N'SERVICE BUSINESS')
INSERT [dbo].[AM_IRGR_MATERIAL_GROUP_HIERARCHY] ([T023T_MATKL], [T023T_WGBEZ], [IRGR_SPEND_CAT_LEVEL_1], [IRGR_SPEND_CAT_LEVEL_2], [IRGR_SPEND_CAT_LEVEL_3], [IRGR_SPEND_CAT_LEVEL_4]) VALUES (N'5100', N'TV', N'Product procurement', N'ET&S', N'ET&S', N'TV')
INSERT [dbo].[AM_IRGR_MATERIAL_GROUP_HIERARCHY] ([T023T_MATKL], [T023T_WGBEZ], [IRGR_SPEND_CAT_LEVEL_1], [IRGR_SPEND_CAT_LEVEL_2], [IRGR_SPEND_CAT_LEVEL_3], [IRGR_SPEND_CAT_LEVEL_4]) VALUES (N'5110', N'TV', N'Product procurement', N'ET&S', N'ET&S', N'TV')
INSERT [dbo].[AM_IRGR_MATERIAL_GROUP_HIERARCHY] ([T023T_MATKL], [T023T_WGBEZ], [IRGR_SPEND_CAT_LEVEL_1], [IRGR_SPEND_CAT_LEVEL_2], [IRGR_SPEND_CAT_LEVEL_3], [IRGR_SPEND_CAT_LEVEL_4]) VALUES (N'5120', N'LARGEDISPLAYSOLUTION', N'Product procurement', N'ET&S', N'ET&S', N'LARGEDISPLAYSOLUTION')
INSERT [dbo].[AM_IRGR_MATERIAL_GROUP_HIERARCHY] ([T023T_MATKL], [T023T_WGBEZ], [IRGR_SPEND_CAT_LEVEL_1], [IRGR_SPEND_CAT_LEVEL_2], [IRGR_SPEND_CAT_LEVEL_3], [IRGR_SPEND_CAT_LEVEL_4]) VALUES (N'5300', N'IP&S', N'Product procurement', N'IP&S', N'IP&S', N'IP&S')
INSERT [dbo].[AM_IRGR_MATERIAL_GROUP_HIERARCHY] ([T023T_MATKL], [T023T_WGBEZ], [IRGR_SPEND_CAT_LEVEL_1], [IRGR_SPEND_CAT_LEVEL_2], [IRGR_SPEND_CAT_LEVEL_3], [IRGR_SPEND_CAT_LEVEL_4]) VALUES (N'5765', N'HOME AUDIO BIZ', N'Product procurement', N'ET&S', N'ET&S', N'HOME AUDIO BIZ')
INSERT [dbo].[AM_IRGR_MATERIAL_GROUP_HIERARCHY] ([T023T_MATKL], [T023T_WGBEZ], [IRGR_SPEND_CAT_LEVEL_1], [IRGR_SPEND_CAT_LEVEL_2], [IRGR_SPEND_CAT_LEVEL_3], [IRGR_SPEND_CAT_LEVEL_4]) VALUES (N'6600', N'MEDICAL BUSINESS UNI', N'Product procurement', N'IP&S', N'IP&S', N'MEDICAL BUSINESS UNI')
INSERT [dbo].[AM_IRGR_MATERIAL_GROUP_HIERARCHY] ([T023T_MATKL], [T023T_WGBEZ], [IRGR_SPEND_CAT_LEVEL_1], [IRGR_SPEND_CAT_LEVEL_2], [IRGR_SPEND_CAT_LEVEL_3], [IRGR_SPEND_CAT_LEVEL_4]) VALUES (N'6700', N'SONY MOBILE COMMUNIC', N'Product procurement', N'ET&S', N'ET&S', N'SONY MOBILE COMMUNIC')
INSERT [dbo].[AM_IRGR_MATERIAL_GROUP_HIERARCHY] ([T023T_MATKL], [T023T_WGBEZ], [IRGR_SPEND_CAT_LEVEL_1], [IRGR_SPEND_CAT_LEVEL_2], [IRGR_SPEND_CAT_LEVEL_3], [IRGR_SPEND_CAT_LEVEL_4]) VALUES (N'8500', N'EP&S OTHERS', N'Product procurement', N'EP&S', N'EP&S', N'EP&S OTHERS')
INSERT [dbo].[AM_IRGR_MATERIAL_GROUP_HIERARCHY] ([T023T_MATKL], [T023T_WGBEZ], [IRGR_SPEND_CAT_LEVEL_1], [IRGR_SPEND_CAT_LEVEL_2], [IRGR_SPEND_CAT_LEVEL_3], [IRGR_SPEND_CAT_LEVEL_4]) VALUES (N'9890', N'OTHER BUSINESS', N'Product procurement', N'Other', N'Other', N'OTHER BUSINESS')
INSERT [dbo].[AM_IRGR_MATERIAL_GROUP_HIERARCHY] ([T023T_MATKL], [T023T_WGBEZ], [IRGR_SPEND_CAT_LEVEL_1], [IRGR_SPEND_CAT_LEVEL_2], [IRGR_SPEND_CAT_LEVEL_3], [IRGR_SPEND_CAT_LEVEL_4]) VALUES (N'9900', N'OTHERS', N'Other', N'Other', N'Other', N'OTHERS')
INSERT [dbo].[AM_IRGR_MATERIAL_GROUP_HIERARCHY] ([T023T_MATKL], [T023T_WGBEZ], [IRGR_SPEND_CAT_LEVEL_1], [IRGR_SPEND_CAT_LEVEL_2], [IRGR_SPEND_CAT_LEVEL_3], [IRGR_SPEND_CAT_LEVEL_4]) VALUES (N'9990', N'CORP&ELIM.', N'Other', N'Other', N'Other', N'CORP&ELIM.')
INSERT [dbo].[AM_IRGR_MATERIAL_GROUP_HIERARCHY] ([T023T_MATKL], [T023T_WGBEZ], [IRGR_SPEND_CAT_LEVEL_1], [IRGR_SPEND_CAT_LEVEL_2], [IRGR_SPEND_CAT_LEVEL_3], [IRGR_SPEND_CAT_LEVEL_4]) VALUES (N'4000', N'V&S BUSINESS GROUP', N'Product procurement', N'ET&S', N'ET&S', N'V&S BUSINESS GROUP')
GO
