USE [DIVA_AUS_FY19_23Q2]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[AM_SCOPE_BK](
	[SCOPE_MANDANT] [varchar](3) NOT NULL,
	[SCOPE_CMPNY_CODE] [varchar](20) NOT NULL,
	[SCOPE_BUSINESS_DMN_L1] [varchar](100) NULL,
	[SCOPE_BUSINESS_DMN_L2] [nvarchar](100) NULL,
	[SCOPE_SYSTEM] [varchar](20) NULL
) ON [PRIMARY]
GO
INSERT [dbo].[AM_SCOPE_BK] ([SCOPE_MANDANT], [SCOPE_CMPNY_CODE], [SCOPE_BUSINESS_DMN_L1], [SCOPE_BUSINESS_DMN_L2], [SCOPE_SYSTEM]) VALUES (N'888', N'ID00', N'NA', N'PT. SONY INDONESIA', N'NA')
INSERT [dbo].[AM_SCOPE_BK] ([SCOPE_MANDANT], [SCOPE_CMPNY_CODE], [SCOPE_BUSINESS_DMN_L1], [SCOPE_BUSINESS_DMN_L2], [SCOPE_SYSTEM]) VALUES (N'888', N'NZ00', N'NA', N'SONY NEW ZEALAND LIMITED.', N'NA')
INSERT [dbo].[AM_SCOPE_BK] ([SCOPE_MANDANT], [SCOPE_CMPNY_CODE], [SCOPE_BUSINESS_DMN_L1], [SCOPE_BUSINESS_DMN_L2], [SCOPE_SYSTEM]) VALUES (N'888', N'AU00', N'NA', N'SONY Australia Limited', N'NA')
INSERT [dbo].[AM_SCOPE_BK] ([SCOPE_MANDANT], [SCOPE_CMPNY_CODE], [SCOPE_BUSINESS_DMN_L1], [SCOPE_BUSINESS_DMN_L2], [SCOPE_SYSTEM]) VALUES (N'888', N'VN00', N'NA', N'SONY ELECTRONICS VIETNAM', N'NA')
INSERT [dbo].[AM_SCOPE_BK] ([SCOPE_MANDANT], [SCOPE_CMPNY_CODE], [SCOPE_BUSINESS_DMN_L1], [SCOPE_BUSINESS_DMN_L2], [SCOPE_SYSTEM]) VALUES (N'888', N'PH00', N'NA', N'SONY PHILIPPINES, INC.', N'NA')
INSERT [dbo].[AM_SCOPE_BK] ([SCOPE_MANDANT], [SCOPE_CMPNY_CODE], [SCOPE_BUSINESS_DMN_L1], [SCOPE_BUSINESS_DMN_L2], [SCOPE_SYSTEM]) VALUES (N'888', N'PH10', N'NA', NULL, N'NA')
INSERT [dbo].[AM_SCOPE_BK] ([SCOPE_MANDANT], [SCOPE_CMPNY_CODE], [SCOPE_BUSINESS_DMN_L1], [SCOPE_BUSINESS_DMN_L2], [SCOPE_SYSTEM]) VALUES (N'888', N'GA81', N'NA', NULL, N'NA')
INSERT [dbo].[AM_SCOPE_BK] ([SCOPE_MANDANT], [SCOPE_CMPNY_CODE], [SCOPE_BUSINESS_DMN_L1], [SCOPE_BUSINESS_DMN_L2], [SCOPE_SYSTEM]) VALUES (N'888', N'TH00', N'NA', N'Sony Thai Co., Ltd.', N'NA')
INSERT [dbo].[AM_SCOPE_BK] ([SCOPE_MANDANT], [SCOPE_CMPNY_CODE], [SCOPE_BUSINESS_DMN_L1], [SCOPE_BUSINESS_DMN_L2], [SCOPE_SYSTEM]) VALUES (N'888', N'NZ10', N'NA', NULL, N'NA')
INSERT [dbo].[AM_SCOPE_BK] ([SCOPE_MANDANT], [SCOPE_CMPNY_CODE], [SCOPE_BUSINESS_DMN_L1], [SCOPE_BUSINESS_DMN_L2], [SCOPE_SYSTEM]) VALUES (N'888', N'VN50', N'NA', NULL, N'NA')
INSERT [dbo].[AM_SCOPE_BK] ([SCOPE_MANDANT], [SCOPE_CMPNY_CODE], [SCOPE_BUSINESS_DMN_L1], [SCOPE_BUSINESS_DMN_L2], [SCOPE_SYSTEM]) VALUES (N'888', N'AE00', N'NA', N'Sony Middle East and Afri', N'NA')
INSERT [dbo].[AM_SCOPE_BK] ([SCOPE_MANDANT], [SCOPE_CMPNY_CODE], [SCOPE_BUSINESS_DMN_L1], [SCOPE_BUSINESS_DMN_L2], [SCOPE_SYSTEM]) VALUES (N'888', N'SI', N'NA', NULL, N'NA')
INSERT [dbo].[AM_SCOPE_BK] ([SCOPE_MANDANT], [SCOPE_CMPNY_CODE], [SCOPE_BUSINESS_DMN_L1], [SCOPE_BUSINESS_DMN_L2], [SCOPE_SYSTEM]) VALUES (N'888', N'TH10', N'NA', N'Sony Device Technology', N'NA')
INSERT [dbo].[AM_SCOPE_BK] ([SCOPE_MANDANT], [SCOPE_CMPNY_CODE], [SCOPE_BUSINESS_DMN_L1], [SCOPE_BUSINESS_DMN_L2], [SCOPE_SYSTEM]) VALUES (N'888', N'AU40', N'NA', NULL, N'NA')
GO
