USE [DIVA_AUS_FY19_23Q2]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[AM_AP_CLEARING](
	[ZF_ACCOUNTS] [nvarchar](255) NULL,
	[SKAT_TXT50] [nvarchar](255) NULL,
	[SKAT_TXT20] [nvarchar](255) NULL,
	[ZF_AP_CLEARING] [nvarchar](255) NULL
) ON [PRIMARY]
GO
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A012001', N'Cash on Hand - NC', N'Cash on Hand - National Currency', N'N/A')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A012105', N'HSBC - NC', N'HSBC - National Currency', N'N/A')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A012109', N'HSBC - National curr', N'HSBC - National curr 2', N'N/A')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A012123', N'JPMG - NC', N'JPMG - National Currency', N'N/A')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A012198', N'Barclay Bank - EUR', N'Barclay Bank - EUR', N'N/A')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A014101', N'I Clr Citibank - USD', N'Citibank - USD (incoming)', N'N/A')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A014105', N'I Clr HSBC - NC', N'HSBC - National Currency (incoming)', N'N/A')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A014109', N'HSBC - National curr', N'HSBC - National curr 2 (incoming)', N'N/A')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A014316', N'I Clr, RAS AUD', N'Incoming Clearing- RAS ACCOUNT AUD', N'N/A')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A021015', N'M&FG,D GL,OIM', N'Products- Merchandise & FG- direct GL entry OIM', N'N/A')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A024020', N'WIP-D GL-sys ser', N'WIP, direct GL entry – System service', N'N/A')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A024021', N'WIP-D GL-LT contract', N'WIP- direct GL entry- LT contract', N'N/A')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A031050', N'PE, Non income tax', N'Prepaid exps- Non income tax', N'N/A')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A031060', N'PE,Insurance', N'Prepaid exps, Insurance', N'N/A')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A031900', N'PE,Other1', N'Prepaid exps, Other1', N'N/A')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A034040', N'Adv-Tact Cash Back', N'Adv paymts- Sales Reductions- Tactical Cash Back', N'N/A')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A035900', N'Exp to be rec,Other1', N'Expense to be recharged, Other1', N'N/A')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A038010', N'VAT-R on purch,gen', N'VAT-receivable on purchase, general', N'N/A')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A038340', N'VAT-R clr AU', N'VAT-receivable (clearing) AU', N'N/A')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A038440', N'VAT-R clr PH', N'VAT-receivable (clearing) PH', N'N/A')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A089010', N'OCA,Gen', N'Other misc. current assets, General', N'N/A')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A158010', N'Sec.Dep-NC', N'Security Deposit - Non Current', N'N/A')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A212100', N'T AP, GRIR 1', N'Trade AP- invoice to be received- GRIR 1', N'N/A')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A212101', N'T AP, GRIR 2', N'Trade AP- invoice to be received- GRIR 2', N'N/A')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A215070', N'AP-NT,GRIR', N'AP-non trade, invoice to be received, GRIR', N'N/A')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A215100', N'O Clr Citibank - NC', N'Citibank - National Currency (outgoing)', N'x')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A215101', N'O Clr Citibank - USD', N'Citibank - USD (outgoing)', N'x')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A215103', N'O Clr Citibank - EUR', N'Citibank - EUR (outgoing)', N'x')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A215105', N'O Clr HSBC - NC', N'HSBC - National Currency (outgoing)', N'x')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A215106', N'O Clr HSBC - USD', N'HSBC - USD (outgoing)', N'x')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A215109', N'HSBC - National curr', N'HSBC - National curr 2 (outgoing)', N'x')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A215123', N'O Clr JPMG - NC', N'JPMG - National Currency (outgoing)', N'x')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A215136', N'O Clr, Union Bank-NC', N'Union Bank - NC (outgoing)', N'x')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A215138', N'O Clr BDO - PH NC2', N'BDO - PH National Curr 2 (outgoing)', N'x')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A215140', N'O Clr BCA - NC', N'BCA - National currency (outgoing)', N'x')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A215162', N'O Clr Siam CB - NC', N'SIAM COMMERCIAL BANK - NC outgoing', N'x')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A215193', N'O Clr Emirates - NC', N'Emirates NBD - NC (outgoing)', N'x')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A215195', N'O Clr Emirates - USD', N'Emirates NBD - USD (outgoing)', N'x')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A215250', N'O Clr AUB - NC', N'Asia United Bank - National Currency (outgoing)', N'x')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A215302', N'O Clr, RAS EUR', N'Outgoing Clearing- RAS ACCOUNT EUR', N'x')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A215307', N'O Clr, RAS USD', N'Outgoing Clearing- RAS ACCOUNT USD', N'x')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A215309', N'O Clr, RAS JPY', N'Outgoing Clearing- RAS ACCOUNT JPY', N'x')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A215316', N'O Clr, RAS AUD', N'Outgoing Clearing- RAS ACCOUNT AUD', N'x')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A215318', N'O Clr, RAS NZD', N'Outgoing Clearing- RAS ACCOUNT NZD', N'x')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A215321', N'O Clr, RAS THB', N'Outgoing Clearing- RAS ACCOUNT THB', N'x')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A215851', N'Oth AP-NT Doc Split', N'Other AP-non trade-Doc Splitting Account', N'N/A')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A216310', N'AE,Salaries & Wages', N'Accrd exps, Salaries & Wages', N'N/A')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A216345', N'AE,SS Exp', N'Accrd exps, Social security expense', N'N/A')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A216440', N'AE,freight', N'Accrd exps, SGA freight', N'N/A')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A216854', N'AE delivery & encodi', N'Accrd exps, COGS contents delivery & encoding fees', N'N/A')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A216900', N'AE,Other1', N'Accrd exps, Other1', N'N/A')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A216902', N'AE,Other3', N'Accrued exps - SGA Other', N'N/A')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A216903', N'AE, Customer Svc', N'Accrd exps, Customer Svc', N'N/A')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A231010', N'ITP, Curr Gen', N'Income tax payable- current- General', N'N/A')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A232900', N'AOT,Other1', N'Accrued other taxes, Other1', N'N/A')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A232901', N'AOT-Int tax', N'Accrued other taxes- International', N'N/A')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A247010', N'L.L - curr LTD', N'Lease liability- Current portion of LTD', N'N/A')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A273020', N'O.misc.CL.Deposits1', N'Other misc. CL-Deposits1', N'N/A')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A505010', N'COGS,Products', N'COGS- Products', N'N/A')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A505030', N'COGS,Other', N'COGS- Other', N'N/A')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A505040', N'COGS,Service&Repair', N'COGS- Service & Repair', N'N/A')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A505055', N'COGS - SP', N'COGS - Spare Parts', N'N/A')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A531080', N'D.inter OD(national)', N'NOE- tax deductible inter for overdue(national)', N'N/A')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A531400', N'NOE,FX Trans losses', N'NOE- FX Translation losses', N'N/A')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A531900', N'NOE,Other1', N'NOE- Other1', N'N/A')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A631300', N'NOR,FX Trans gain', N'NOR- FX Translation gain', N'N/A')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A631900', N'NOR,Other1', N'NOR- Other1', N'N/A')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A702010', N'S&W,Base salaries', N'S&W- Base salaries', N'N/A')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A702011', N'S&W,Base salary Mgt', N'S&W- Base salaries(Management)', N'N/A')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A706010', N'PrivateHealthcareIns', N'Welfare exps- Private Healthcare Insurance', N'N/A')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A706900', N'Welfare exps,Other1', N'Welfare exps- Other1', N'N/A')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A706902', N'Welfare exps,Expat', N'Welfare exps,General Expat', N'N/A')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A711010', N'Freight,FG (Ship)', N'Freight- Finished goods freightage(Ship)', N'N/A')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A711020', N'Freight,FG (Air)', N'Freight- Finished goods freightage(Air)', N'N/A')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A711030', N'Freight,FG (Land)', N'Freight- Finished goods freightage(Land)', N'N/A')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A711100', N'Freight,Office Expor', N'Freight- Office cost on export', N'N/A')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A711900', N'Freight,Other1', N'Freight- Other1', N'N/A')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A714010', N'Electrical power', N'Utilities exps- Electrical power', N'N/A')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A722020', N'Training exps', N'R&T exps- Training exps', N'N/A')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A723010', N'Fare', N'Travelling & commutation- Fare', N'N/A')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A723030', N'Vehicle running exp', N'Travelling & commutation- vehicle running exp', N'N/A')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A723900', N'Trav&commut,Other1', N'Travelling & commutation- Other1', N'N/A')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A725010', N'Postal exps', N'Commu exps- Postal exps', N'N/A')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A725030', N'Cellphone & Landline', N'Commu exps- Cell phone & Land phone', N'N/A')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A731900', N'Insurance Other1', N'Insurance exps, Other1', N'N/A')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A742010', N'Consumption tax', N'misc. tax, Consumption tax', N'N/A')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A742100N', N'ND national tax', N'misc. tax, Non deductible national tax', N'N/A')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A744040N', N'Vehile Expenses(ND)', N'misc. exps, Vehicle Expenses (ND)', N'N/A')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A744050', N'Bank commissions', N'misc. exps, Bank commissions', N'N/A')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A744720', N'Other MFC 2', N'misc. exps- Other MFC related expenses 2', N'N/A')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A744900', N'misc. exps,Other1', N'misc. exps, Other1', N'N/A')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A745080N', N'Vehicles exps(ND)', N'Rent exps, Vehicles exps(ND)', N'N/A')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A745100', N'Rent exps,Shop rent', N'Rent exps, Shop rent', N'N/A')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A745800', N'Rent,Outgo recharge', N'Rent exps, Outgoing recharge', N'N/A')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A748020', N'Temp staff agency fe', N'Prof service fee, Temp staff service fee (agency)', N'N/A')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A748030', N'Legal Services', N'Prof service fee, Legal Services', N'N/A')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A748050', N'O.consultant fees', N'Prof service fee, Other consultant fees', N'N/A')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A750020', N'IS Service Fee- Netw', N'IS Service Fee- Network', N'N/A')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A750900', N'IS Service Fee- Othe', N'IS Service Fee- Other', N'N/A')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A771040', N'Media,OutdoorTransit', N'AD&Pro exps, Media, Outdoor/Transit advertising', N'N/A')
GO
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A771090', N'Internet others', N'AD&Pro exps- Media expenses- Internet others', N'N/A')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A771090N', N'Key Opinion leader', N'AD&Pro exps-Key Opinion leader (influenc', N'N/A')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A771100N', N'A&P,Maintenance,rep', N'AD&Pro exps-Maintenance, repair', N'N/A')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A771106', N'Digital Production', N'AD&pro exps – Digital production', N'N/A')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A771110', N'Sponsorship', N'AD&Pro exps, Sponsorship', N'N/A')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A771210', N'Event&Exhibition', N'AD&Pro exps, Event&Exhibition', N'N/A')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A771220', N'AD&Pro exps,Sample', N'AD&Pro exps, Others, Sample', N'N/A')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A771220N', N'Dealer convention', N'AD&Pro exps- Dealer convention', N'N/A')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A771230', N'Give Away', N'AD&Pro exps, Others, Give Away', N'N/A')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A771300', N'Shop front,POP', N'AD&Pro exps, Shop front communication, POP', N'N/A')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A771320', N'Shop front,Fixture', N'AD&Pro exps, Shop front communication, Fixture', N'N/A')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A771330', N'Shop Fixtures/Renov', N'AD&Pro exps, Shop Fixtures/Renovation', N'N/A')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A771420', N'Media,eCom,Shp/Mkt', N'AD&Pro exps-Media,eCommence Shopping/Mar', N'N/A')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A771900', N'Gen/Strat Mktg/O Ex', N'AD&Pro, General/Strategic marketing/Other expenses', N'N/A')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A774010', N'Sales commission,Gen', N'Sales commission, General', N'N/A')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A775010', N'Service,IW,exchange', N'Service, Inwarranty, exchange', N'N/A')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A775030', N'Service, IW,parts', N'Service, Inwarranty, parts', N'N/A')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A775100', N'Service,Outwarranty', N'Service- Outwarranty', N'N/A')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A775710', N'Service,Contact.C OS', N'Service, Contact Center Outsourcing', N'N/A')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A775840', N'Service, RMA Reimb', N'Service, RMA Reimbursement', N'N/A')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A775900', N'Service,Other1', N'Service, Other1', N'N/A')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A901000', N'Purchase merchandise', N'Purchase merchandise', N'N/A')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A923100', N'Interim account,GL', N'Interim account, GL', N'N/A')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A012100', N'Citibank - NC', N'Citibank - National Currency', N'N/A')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A012316', N'RAS cash,RAS AUD', N'RAS cash, RAS ACCOUNT AUD', N'N/A')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A014100', N'I Clr Citibank - NC', N'Citibank - National Currency (incoming)', N'N/A')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A021020', N'M&FG,D GL,balance', N'Products, Merchandise & FG, direct GL, balance', N'N/A')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A021030', N'M&FG,In transit', N'Products, Merchandise & FG, In transit', N'N/A')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A031030', N'PE,Rental/Leasing', N'Prepaid exps, Rental/Leasing', N'N/A')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A119200', N'Assets interim acct', N'Construction in Progress, Assets interim account', N'N/A')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A215135', N'O Clr, BPI - PH NC2', N'BPI - PH NC2 (outgoing)', N'x')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A215194', N'O Clr Emirates - NC1', N'Emirates NBD - NC1 (outgoing)', N'x')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A229010', N'Reserve for warranty', N'Reserve for warranty, General', N'N/A')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A232031', N'AOT-Payroll-FBT', N'Accrued other taxes- payroll - FBT', N'N/A')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A706901', N'Welfare exps,Other2', N'Welfare exps- Other2', N'N/A')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A722010', N'Recruiting exp', N'R&T exps- Recruiting expense', N'N/A')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A725020', N'Network', N'Commu exps- Network', N'N/A')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A725110', N'S/W maintenance', N'Commu exps, S/W maintenance', N'N/A')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A726010', N'Meal', N'Meals and Entmt exps, Meal', N'N/A')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A732010', N'R&M,M&Es', N'Repair&maintenance exps, M&Es', N'N/A')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A732100', N'R&M-company cleaning', N'Repair&maintenance exps- In-company cleaning fee', N'N/A')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A741010N', N'Donation,Gen (ND)', N'Donation, General (Non deductible)', N'N/A')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A750010', N'H/W maintenance', N'IS Service Fee- H/W maintenance', N'N/A')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A771070', N'Internet(SearchEngin', N'AD&Pro exps, Media, Internet (Search Engine Mkt)', N'N/A')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A771111', N'Dealer Support', N'AD&Pro exps- Dealer Support', N'N/A')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A771200', N'Promoter expenses', N'AD&Pro exps- Promoter expenses', N'N/A')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A771450', N'Promotor Rel Cost', N'AD&Pro exps-Promotor Related Cost', N'N/A')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A771950', N'Warehousing&Transpo', N'AD&Pro exps, Warehousing and Transportation', N'N/A')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A012307', N'RAS cash,RAS USD', N'RAS cash, RAS ACCOUNT USD', N'N/A')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A012318', N'RAS cash,RAS NZD', N'RAS cash, RAS ACCOUNT NZD', N'N/A')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A014106', N'I Clr HSBC - USD', N'HSBC - USD (incoming)', N'N/A')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A014307', N'I Clr, RAS USD', N'Incoming Clearing- RAS ACCOUNT USD', N'N/A')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A014318', N'I Clr, RAS NZD', N'Incoming Clearing- RAS ACCOUNT NZD', N'N/A')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A014320', N'I Clr, RAS SGD', N'Incoming Clearing- RAS ACCOUNT SGD', N'N/A')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A031010', N'PE,Ad&pro', N'Prepaid exps, Advertizing & promotion', N'N/A')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A039010', N'ADA,Gen', N'Allowance for doubtful debts, General', N'N/A')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A159050', N'Oth NC Asset,Deposit', N'Other non-curr assets, deposit', N'N/A')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A215306', N'O Clr, RAS GBP', N'Outgoing Clearing- RAS ACCOUNT GBP', N'x')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A215320', N'O Clr, RAS SGD', N'Outgoing Clearing- RAS ACCOUNT SGD', N'x')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A216101', N'Accrd Co-op AD(MDF)2', N'Provision for Co Op A&P - General', N'N/A')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A248010', N'Curr por,LT debts-Op', N'Current portion of LT debts (Op Lease)', N'N/A')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A443090', N'CI - Dividend paid', N'Controlling Interest - Dividend paid', N'N/A')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A702910', N'S&W,VAT full rate', N'S&W- Taxation remuneration in kind VAT full rate', N'N/A')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A712010', N'E&T expensed', N'Equipment- tools & software expensed- E&T', N'N/A')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A725060', N'Global Infra Comm', N'Commu exps, Global Infra Comm', N'N/A')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A725100', N'H/W maintenance', N'Commu exps, H/W maintenance', N'N/A')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A725900', N'Commu exps,Other1', N'Commu exps, Other1', N'N/A')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A732020', N'R&M,Bld/LI/struc', N'Repair&maintenance exps, Bld/LI/struc', N'N/A')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A743010', N'FG storage fee', N'Storage, Finished goods storage fee', N'N/A')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A744010', N'membership fee', N'misc. exps, membership fee', N'N/A')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A744020', N'Books & magazines', N'misc. exps, Books & magazines', N'N/A')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A744030', N'Conference exps', N'misc. exps, Conference exps', N'N/A')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A744800', N'Outgo recharge', N'misc. exps, Outgoing recharge', N'N/A')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A745090', N'Office rent', N'Rent exps, Office rent', N'N/A')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A748060', N'Market research', N'Prof service fee, Market research', N'N/A')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A771010', N'Media exps,Newspaper', N'AD&Pro exps, Media expenses, Newspaper', N'N/A')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A771030', N'Media exps,Radio', N'AD&Pro exps, Media expenses, Radio', N'N/A')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A771050', N'Media exps,TV', N'AD&Pro exps, Media expenses, TV', N'N/A')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A771100', N'CC for Media', N'AD&Pro exps, Contents Creation for Media', N'N/A')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A771130', N'AD&Pro exps,Alloc', N'AD&Pro exps- Allocation', N'N/A')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A771211', N'PR & Press Event', N'AD&Pro exps- PR & Press Events', N'N/A')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A771230N', N'Seminar/WkshpOffline', N'AD&Pro exps-Product Seminar / Workshops', N'N/A')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A771240', N'IncentivTrip/Traini', N'AD&Pro exps, Incentive Trips/Training', N'N/A')
INSERT [dbo].[AM_AP_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AP_CLEARING]) VALUES (N'A775020', N'Service,IW,other', N'Service, Inwarranty, other', N'N/A')
GO
