USE [DIVA_AUS_FY19_23Q2]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[AM_COMPANY_CODE](
	[COMPANY_CODE] [varchar](20) NOT NULL,
	[BUKRS_MAPPING] [nvarchar](max) NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
INSERT [dbo].[AM_COMPANY_CODE] ([COMPANY_CODE], [BUKRS_MAPPING]) VALUES (N'AE00', N'AE00,GA81')
INSERT [dbo].[AM_COMPANY_CODE] ([COMPANY_CODE], [BUKRS_MAPPING]) VALUES (N'AU00', N'AU00,AU40')
INSERT [dbo].[AM_COMPANY_CODE] ([COMPANY_CODE], [BUKRS_MAPPING]) VALUES (N'AU40', N'AU00,AU40')
INSERT [dbo].[AM_COMPANY_CODE] ([COMPANY_CODE], [BUKRS_MAPPING]) VALUES (N'GA81', N'AE00,GA81')
INSERT [dbo].[AM_COMPANY_CODE] ([COMPANY_CODE], [BUKRS_MAPPING]) VALUES (N'ID00', N'ID00,SI')
INSERT [dbo].[AM_COMPANY_CODE] ([COMPANY_CODE], [BUKRS_MAPPING]) VALUES (N'NZ00', N'NZ00,NZ10')
INSERT [dbo].[AM_COMPANY_CODE] ([COMPANY_CODE], [BUKRS_MAPPING]) VALUES (N'NZ10', N'NZ00,NZ10')
INSERT [dbo].[AM_COMPANY_CODE] ([COMPANY_CODE], [BUKRS_MAPPING]) VALUES (N'PH00', N'PH10,PH00')
INSERT [dbo].[AM_COMPANY_CODE] ([COMPANY_CODE], [BUKRS_MAPPING]) VALUES (N'PH10', N'PH10,PH00')
INSERT [dbo].[AM_COMPANY_CODE] ([COMPANY_CODE], [BUKRS_MAPPING]) VALUES (N'SI', N'ID00,SI')
INSERT [dbo].[AM_COMPANY_CODE] ([COMPANY_CODE], [BUKRS_MAPPING]) VALUES (N'TH00', N'TH00,TH10')
INSERT [dbo].[AM_COMPANY_CODE] ([COMPANY_CODE], [BUKRS_MAPPING]) VALUES (N'TH10', N'TH00,TH10')
INSERT [dbo].[AM_COMPANY_CODE] ([COMPANY_CODE], [BUKRS_MAPPING]) VALUES (N'VN00', N'VN00,VN50')
INSERT [dbo].[AM_COMPANY_CODE] ([COMPANY_CODE], [BUKRS_MAPPING]) VALUES (N'VN50', N'VN00,VN50')
GO
