USE [DIVA_SOLA_FY20Q4_INCREMENTAL]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[AM_FSMC](
	[FSMC_ID] [nvarchar](1000) NULL,
	[FSMC_NAME] [nvarchar](1000) NULL,
	[FSMC_CNTRY_CODE] [nvarchar](1000) NULL,
	[FSMC_REGION] [nvarchar](1000) NULL,
	[FSMC_CONTROLLING_AREA] [nvarchar](1000) NULL,
	[FSMC_COMPANY_CODE] [nvarchar](1000) NULL,
	[_FSMC_MANDT] [nvarchar](3) NULL
) ON [PRIMARY]
GO
INSERT [dbo].[AM_FSMC] ([FSMC_ID], [FSMC_NAME], [FSMC_CNTRY_CODE], [FSMC_REGION], [FSMC_CONTROLLING_AREA], [FSMC_COMPANY_CODE], [_FSMC_MANDT]) VALUES (N'SAR', N'Sony Argentina', N'ARG', N'Sony Argentina (SAR)', N'SOLA', N'AR10', N'')
INSERT [dbo].[AM_FSMC] ([FSMC_ID], [FSMC_NAME], [FSMC_CNTRY_CODE], [FSMC_REGION], [FSMC_CONTROLLING_AREA], [FSMC_COMPANY_CODE], [_FSMC_MANDT]) VALUES (N'SCI', N'Sony Chile', N'BOL', N'Sony Chile Ltda. (SCI)', N'SOLA', N'BO12', N'')
INSERT [dbo].[AM_FSMC] ([FSMC_ID], [FSMC_NAME], [FSMC_CNTRY_CODE], [FSMC_REGION], [FSMC_CONTROLLING_AREA], [FSMC_COMPANY_CODE], [_FSMC_MANDT]) VALUES (N'SBR', N'Sony Brazil', N'BRA', N'Sony Brazil', N'SOLA', N'BR10', N'')
INSERT [dbo].[AM_FSMC] ([FSMC_ID], [FSMC_NAME], [FSMC_CNTRY_CODE], [FSMC_REGION], [FSMC_CONTROLLING_AREA], [FSMC_COMPANY_CODE], [_FSMC_MANDT]) VALUES (N'SBR', N'Sony Brazil', N'BRA', N'Sony Brazil', N'SOLA', N'BR20', N'')
INSERT [dbo].[AM_FSMC] ([FSMC_ID], [FSMC_NAME], [FSMC_CNTRY_CODE], [FSMC_REGION], [FSMC_CONTROLLING_AREA], [FSMC_COMPANY_CODE], [_FSMC_MANDT]) VALUES (N'SCI', N'Sony Chile', N'CHL', N'Sony Chile Ltda. (SCI)', N'SOLA', N'CL10', N'')
INSERT [dbo].[AM_FSMC] ([FSMC_ID], [FSMC_NAME], [FSMC_CNTRY_CODE], [FSMC_REGION], [FSMC_CONTROLLING_AREA], [FSMC_COMPANY_CODE], [_FSMC_MANDT]) VALUES (N'SCI', N'Sony Chile', N'CHL', N'Sony Chile Ltda. (SCI)', N'SOLA', N'CL20', N'')
INSERT [dbo].[AM_FSMC] ([FSMC_ID], [FSMC_NAME], [FSMC_CNTRY_CODE], [FSMC_REGION], [FSMC_CONTROLLING_AREA], [FSMC_COMPANY_CODE], [_FSMC_MANDT]) VALUES (N'SCI', N'Sony Chile', N'CHL', N'Sony Chile Ltda. (SCI)', N'SOLA', N'CL30', N'')
INSERT [dbo].[AM_FSMC] ([FSMC_ID], [FSMC_NAME], [FSMC_CNTRY_CODE], [FSMC_REGION], [FSMC_CONTROLLING_AREA], [FSMC_COMPANY_CODE], [_FSMC_MANDT]) VALUES (N'SIA', N'Sony Colombia', N'COL', N'Sony Inter American, S.A (SIA)', N'SOLA', N'CO10', N'')
INSERT [dbo].[AM_FSMC] ([FSMC_ID], [FSMC_NAME], [FSMC_CNTRY_CODE], [FSMC_REGION], [FSMC_CONTROLLING_AREA], [FSMC_COMPANY_CODE], [_FSMC_MANDT]) VALUES (N'SIA', N'Sony Colombia', N'COL', N'Sony Inter American, S.A (SIA)', N'SOLA', N'CO20', N'')
INSERT [dbo].[AM_FSMC] ([FSMC_ID], [FSMC_NAME], [FSMC_CNTRY_CODE], [FSMC_REGION], [FSMC_CONTROLLING_AREA], [FSMC_COMPANY_CODE], [_FSMC_MANDT]) VALUES (N'SIA', N'Sony Costa Rica', N'CRI', N'Sony Inter American, S.A (SIA)', N'SOLA', N'CR10', N'')
INSERT [dbo].[AM_FSMC] ([FSMC_ID], [FSMC_NAME], [FSMC_CNTRY_CODE], [FSMC_REGION], [FSMC_CONTROLLING_AREA], [FSMC_COMPANY_CODE], [_FSMC_MANDT]) VALUES (N'SIA', N'Sony Costa Rica', N'CRI', N'Sony Inter American, S.A (SIA)', N'SOLA', N'CR20', N'')
INSERT [dbo].[AM_FSMC] ([FSMC_ID], [FSMC_NAME], [FSMC_CNTRY_CODE], [FSMC_REGION], [FSMC_CONTROLLING_AREA], [FSMC_COMPANY_CODE], [_FSMC_MANDT]) VALUES (N'SIA', N'Sony Ecuador', N'ECU', N'Sony Inter American, S.A (SIA)', N'SOLA', N'EC10', N'')
INSERT [dbo].[AM_FSMC] ([FSMC_ID], [FSMC_NAME], [FSMC_CNTRY_CODE], [FSMC_REGION], [FSMC_CONTROLLING_AREA], [FSMC_COMPANY_CODE], [_FSMC_MANDT]) VALUES (N'SIA', N'Sony Ecuador', N'ECU', N'Sony Inter American, S.A (SIA)', N'SOLA', N'EC20', N'')
INSERT [dbo].[AM_FSMC] ([FSMC_ID], [FSMC_NAME], [FSMC_CNTRY_CODE], [FSMC_REGION], [FSMC_CONTROLLING_AREA], [FSMC_COMPANY_CODE], [_FSMC_MANDT]) VALUES (N'SMX', N'Sony Mexico', N'MEX', N'Sony Mexico (SMX)', N'SOLA', N'MX10', N'')
INSERT [dbo].[AM_FSMC] ([FSMC_ID], [FSMC_NAME], [FSMC_CNTRY_CODE], [FSMC_REGION], [FSMC_CONTROLLING_AREA], [FSMC_COMPANY_CODE], [_FSMC_MANDT]) VALUES (N'SMX', N'Sony Mexico', N'MEX', N'Sony Mexico (SMX)', N'SOLA', N'MX20', N'')
INSERT [dbo].[AM_FSMC] ([FSMC_ID], [FSMC_NAME], [FSMC_CNTRY_CODE], [FSMC_REGION], [FSMC_CONTROLLING_AREA], [FSMC_COMPANY_CODE], [_FSMC_MANDT]) VALUES (N'SMX', N'Sony Mexico', N'MEX', N'Sony Mexico (SMX)', N'SOLA', N'MX30', N'')
INSERT [dbo].[AM_FSMC] ([FSMC_ID], [FSMC_NAME], [FSMC_CNTRY_CODE], [FSMC_REGION], [FSMC_CONTROLLING_AREA], [FSMC_COMPANY_CODE], [_FSMC_MANDT]) VALUES (N'SIA', N'Sony Panama', N'PAN', N'Sony Inter American, S.A (SIA)', N'SOLA', N'PA10 ', N'')
INSERT [dbo].[AM_FSMC] ([FSMC_ID], [FSMC_NAME], [FSMC_CNTRY_CODE], [FSMC_REGION], [FSMC_CONTROLLING_AREA], [FSMC_COMPANY_CODE], [_FSMC_MANDT]) VALUES (N'SIA', N'Sony Panama', N'PAN', N'Sony Inter American, S.A (SIA)', N'SOLA', N'PA20', N'')
INSERT [dbo].[AM_FSMC] ([FSMC_ID], [FSMC_NAME], [FSMC_CNTRY_CODE], [FSMC_REGION], [FSMC_CONTROLLING_AREA], [FSMC_COMPANY_CODE], [_FSMC_MANDT]) VALUES (N'SIA', N'Sony Panama', N'PAN', N'Sony Inter American, S.A (SIA)', N'SOLA', N'PA30', N'')
INSERT [dbo].[AM_FSMC] ([FSMC_ID], [FSMC_NAME], [FSMC_CNTRY_CODE], [FSMC_REGION], [FSMC_CONTROLLING_AREA], [FSMC_COMPANY_CODE], [_FSMC_MANDT]) VALUES (N'SIA', N'Sony Panama', N'PAN', N'Sony Inter American, S.A (SIA)', N'SOLA', N'PA40', N'')
INSERT [dbo].[AM_FSMC] ([FSMC_ID], [FSMC_NAME], [FSMC_CNTRY_CODE], [FSMC_REGION], [FSMC_CONTROLLING_AREA], [FSMC_COMPANY_CODE], [_FSMC_MANDT]) VALUES (N'SPE', N'Sony Peru ', N'PER', N'Sony Peru ', N'SOLA', N'PE10', N'')
INSERT [dbo].[AM_FSMC] ([FSMC_ID], [FSMC_NAME], [FSMC_CNTRY_CODE], [FSMC_REGION], [FSMC_CONTROLLING_AREA], [FSMC_COMPANY_CODE], [_FSMC_MANDT]) VALUES (N'SPE', N'Sony Peru ', N'PER', N'Sony Peru ', N'SOLA', N'PE20', N'')
INSERT [dbo].[AM_FSMC] ([FSMC_ID], [FSMC_NAME], [FSMC_CNTRY_CODE], [FSMC_REGION], [FSMC_CONTROLLING_AREA], [FSMC_COMPANY_CODE], [_FSMC_MANDT]) VALUES (N'SPE', N'Sony Peru ', N'PER', N'Sony Peru ', N'SOLA', N'PE30', N'')
INSERT [dbo].[AM_FSMC] ([FSMC_ID], [FSMC_NAME], [FSMC_CNTRY_CODE], [FSMC_REGION], [FSMC_CONTROLLING_AREA], [FSMC_COMPANY_CODE], [_FSMC_MANDT]) VALUES (N'SPE', N'Sony Peru ', N'PER', N'Sony Peru ', N'SOLA', N'PE40', N'')
INSERT [dbo].[AM_FSMC] ([FSMC_ID], [FSMC_NAME], [FSMC_CNTRY_CODE], [FSMC_REGION], [FSMC_CONTROLLING_AREA], [FSMC_COMPANY_CODE], [_FSMC_MANDT]) VALUES (N'SIA', N'Sony Puerto Rico', N'PRI', N'Sony Inter American, S.A (SIA)', N'SOLA', N'PR10', N'')
INSERT [dbo].[AM_FSMC] ([FSMC_ID], [FSMC_NAME], [FSMC_CNTRY_CODE], [FSMC_REGION], [FSMC_CONTROLLING_AREA], [FSMC_COMPANY_CODE], [_FSMC_MANDT]) VALUES (N'SAR', N'Sony Argentina', N'ARG', N'Sony Argentina (SAR)', N'SOLA', N'UR40', N'')
INSERT [dbo].[AM_FSMC] ([FSMC_ID], [FSMC_NAME], [FSMC_CNTRY_CODE], [FSMC_REGION], [FSMC_CONTROLLING_AREA], [FSMC_COMPANY_CODE], [_FSMC_MANDT]) VALUES (N'SOLA', N'Sony Latin America (SOLA)', N'USA', N'Sony Latin America (SOLA)', N'SOLA', N'US10', N'')
GO
