USE [DIVA_SOLA_FY20Q4_INCREMENTAL]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[AM_COPA_FILTER_MAPPING](
	[COPA_SAP_FIELD] [nvarchar](255) NULL,
	[COPA_FILTER] [nvarchar](255) NULL,
	[COPA_FIELD_DESC] [nvarchar](255) NULL,
	[_COPA_FILTER_MAP] [nvarchar](3) NULL
) ON [PRIMARY]
GO
INSERT [dbo].[AM_COPA_FILTER_MAPPING] ([COPA_SAP_FIELD], [COPA_FILTER], [COPA_FIELD_DESC], [_COPA_FILTER_MAP]) VALUES (NULL, N'ZF_COPA_SALE_REGION', N'SALE REGION', N'')
INSERT [dbo].[AM_COPA_FILTER_MAPPING] ([COPA_SAP_FIELD], [COPA_FILTER], [COPA_FIELD_DESC], [_COPA_FILTER_MAP]) VALUES (N'[COPA_VKORG] + '' - '' + [TVKOT_VTEXT]', N'ZF_COPA_ORGANISATION', N'ORGANISATION', N'')
INSERT [dbo].[AM_COPA_FILTER_MAPPING] ([COPA_SAP_FIELD], [COPA_FILTER], [COPA_FIELD_DESC], [_COPA_FILTER_MAP]) VALUES (N'[COPA_VTWEG] + '' - '' + [TVTWT_VTEXT]', N'ZF_COPA_DISTRIBUTION_CHANNEL', N'DISTRIBUTION CHANNEL', N'')
INSERT [dbo].[AM_COPA_FILTER_MAPPING] ([COPA_SAP_FIELD], [COPA_FILTER], [COPA_FIELD_DESC], [_COPA_FILTER_MAP]) VALUES (N'[COPA_SPART] + '' - '' + [TSPAT_VTEXT]', N'ZF_COPA_DIVISION', N'DIVISION', N'')
INSERT [dbo].[AM_COPA_FILTER_MAPPING] ([COPA_SAP_FIELD], [COPA_FILTER], [COPA_FIELD_DESC], [_COPA_FILTER_MAP]) VALUES (N'[COPA_PRCTR] + '' - '' + [ZF_CEPCT_MCTXT_NAME]', N'ZF_COPA_PROFIT_CENTER', N'PROFIT CENTER', N'')
INSERT [dbo].[AM_COPA_FILTER_MAPPING] ([COPA_SAP_FIELD], [COPA_FILTER], [COPA_FIELD_DESC], [_COPA_FILTER_MAP]) VALUES (N'[KNA1_NAME1] + '' - '' + [COPA_KNDNR]', N'ZF_COPA_CUSTOMER', N'CUSTOMER', N'')
INSERT [dbo].[AM_COPA_FILTER_MAPPING] ([COPA_SAP_FIELD], [COPA_FILTER], [COPA_FIELD_DESC], [_COPA_FILTER_MAP]) VALUES (N'[KNA1_BRAN1]', N'ZF_COPA_ECOT1', N'ECOT CODE 1', N'')
INSERT [dbo].[AM_COPA_FILTER_MAPPING] ([COPA_SAP_FIELD], [COPA_FILTER], [COPA_FIELD_DESC], [_COPA_FILTER_MAP]) VALUES (N'[KNA1_BRAN2]', N'ZF_COPA_ECOT2', N'ECOT CODE 2', N'')
INSERT [dbo].[AM_COPA_FILTER_MAPPING] ([COPA_SAP_FIELD], [COPA_FILTER], [COPA_FIELD_DESC], [_COPA_FILTER_MAP]) VALUES (N'[KNA1_BRAN3]', N'ZF_COPA_ECOT3', N'ECOT CODE 3', N'')
INSERT [dbo].[AM_COPA_FILTER_MAPPING] ([COPA_SAP_FIELD], [COPA_FILTER], [COPA_FIELD_DESC], [_COPA_FILTER_MAP]) VALUES (N'[KNA1_BRAN4]', N'ZF_COPA_ECOT4', N'ECOT CODE 4', N'')
INSERT [dbo].[AM_COPA_FILTER_MAPPING] ([COPA_SAP_FIELD], [COPA_FILTER], [COPA_FIELD_DESC], [_COPA_FILTER_MAP]) VALUES (N'[KNA1_BRAN5]', N'ZF_COPA_ECOT5', N'ECOT CODE 5', N'')
INSERT [dbo].[AM_COPA_FILTER_MAPPING] ([COPA_SAP_FIELD], [COPA_FILTER], [COPA_FIELD_DESC], [_COPA_FILTER_MAP]) VALUES (N'[KNA1_NAME1] + '' - '' + [COPA_KUNWE]', N'ZF_COPA_SHIP_TO_PARTY', N'SHIP-TO PARTY', N'')
INSERT [dbo].[AM_COPA_FILTER_MAPPING] ([COPA_SAP_FIELD], [COPA_FILTER], [COPA_FIELD_DESC], [_COPA_FILTER_MAP]) VALUES (N'[KNA1_NAME1] + '' - '' + [COPA_KUNWE]', N'ZF_COPA_BILL_TO_PARTY', N'BILL-TO PARTY', N'')
INSERT [dbo].[AM_COPA_FILTER_MAPPING] ([COPA_SAP_FIELD], [COPA_FILTER], [COPA_FIELD_DESC], [_COPA_FILTER_MAP]) VALUES (NULL, N'ZF_COPA_TRADING_PARTNER', N'TRADING PARTNER', N'')
INSERT [dbo].[AM_COPA_FILTER_MAPPING] ([COPA_SAP_FIELD], [COPA_FILTER], [COPA_FIELD_DESC], [_COPA_FILTER_MAP]) VALUES (N'ZF_KNB1_AKONT_INTER_COM', N'ZF_COPA_SALE_TYPE', N'SALES TYPE', N'')
INSERT [dbo].[AM_COPA_FILTER_MAPPING] ([COPA_SAP_FIELD], [COPA_FILTER], [COPA_FIELD_DESC], [_COPA_FILTER_MAP]) VALUES (N'[COPA_ARTNR] + '' - '' + [MAKT_MAKTX]', N'ZF_COPA_MATERIAL', N'MATERIAL', N'')
INSERT [dbo].[AM_COPA_FILTER_MAPPING] ([COPA_SAP_FIELD], [COPA_FILTER], [COPA_FIELD_DESC], [_COPA_FILTER_MAP]) VALUES (N'COPA_KMMAKL', N'ZF_COPA_MATERIAL_GROUP', N'MATERIAL GROUP', N'')
INSERT [dbo].[AM_COPA_FILTER_MAPPING] ([COPA_SAP_FIELD], [COPA_FILTER], [COPA_FIELD_DESC], [_COPA_FILTER_MAP]) VALUES (N'SUBSTRING(COPA_PROHA,11,4)', N'ZF_TOKYO_4_DIGIT', N'TOKYO 4 DIGIT', N'')
INSERT [dbo].[AM_COPA_FILTER_MAPPING] ([COPA_SAP_FIELD], [COPA_FILTER], [COPA_FIELD_DESC], [_COPA_FILTER_MAP]) VALUES (N'SUBSTRING(COPA_PRCTR,1,6)', N'ZF_TOKYO_6_DIGIT', N'TOKYO 6 DIGIT', N'')
INSERT [dbo].[AM_COPA_FILTER_MAPPING] ([COPA_SAP_FIELD], [COPA_FILTER], [COPA_FIELD_DESC], [_COPA_FILTER_MAP]) VALUES (N'COPA_MATWA', N'ZF_TOKYO_8_DIGIT', N'TOKYO 8 DIGIT', N'')
INSERT [dbo].[AM_COPA_FILTER_MAPPING] ([COPA_SAP_FIELD], [COPA_FILTER], [COPA_FIELD_DESC], [_COPA_FILTER_MAP]) VALUES (N'SUBSTRING(COPA_WWBD5,1,4)', N'ZF_COPA_PROD_L1', N'PRODUCT_HIERARCHY_L1', N'')
INSERT [dbo].[AM_COPA_FILTER_MAPPING] ([COPA_SAP_FIELD], [COPA_FILTER], [COPA_FIELD_DESC], [_COPA_FILTER_MAP]) VALUES (N'SUBSTRING(COPA_WWBD5,5,3)', N'ZF_COPA_PROD_L2', N'PRODUCT_HIERARCHY_L2', N'')
INSERT [dbo].[AM_COPA_FILTER_MAPPING] ([COPA_SAP_FIELD], [COPA_FILTER], [COPA_FIELD_DESC], [_COPA_FILTER_MAP]) VALUES (N'SUBSTRING(COPA_WWBD5,8,3)', N'ZF_COPA_PROD_L3', N'PRODUCT_HIERARCHY_L3', N'')
INSERT [dbo].[AM_COPA_FILTER_MAPPING] ([COPA_SAP_FIELD], [COPA_FILTER], [COPA_FIELD_DESC], [_COPA_FILTER_MAP]) VALUES (N'SUBSTRING(COPA_WWBD5,11,4)', N'ZF_COPA_PROD_L4', N'PRODUCT_HIERARCHY_L4', N'')
INSERT [dbo].[AM_COPA_FILTER_MAPPING] ([COPA_SAP_FIELD], [COPA_FILTER], [COPA_FIELD_DESC], [_COPA_FILTER_MAP]) VALUES (N'SUBSTRING(COPA_WWBD5,15,4)', N'ZF_COPA_PROD_L5', N'PRODUCT_HIERARCHY_L5', N'')
INSERT [dbo].[AM_COPA_FILTER_MAPPING] ([COPA_SAP_FIELD], [COPA_FILTER], [COPA_FIELD_DESC], [_COPA_FILTER_MAP]) VALUES (N'[COPA_FKART] + '' - '' + [TVFKT_VTEXT]', N'ZF_COPA_BILLING_DOC', N'BILLING DOCUMENT', N'')
INSERT [dbo].[AM_COPA_FILTER_MAPPING] ([COPA_SAP_FIELD], [COPA_FILTER], [COPA_FIELD_DESC], [_COPA_FILTER_MAP]) VALUES (N'COPA_VRGAR', N'ZF_COPA_RECORD_TYPE', N'RECORD TYPE', N'')
INSERT [dbo].[AM_COPA_FILTER_MAPPING] ([COPA_SAP_FIELD], [COPA_FILTER], [COPA_FIELD_DESC], [_COPA_FILTER_MAP]) VALUES (N'TVFKT_VTEXT', N'ZF_COPA_ACC_GRP', N'ACCOUNT ASSIGNMENT GROUP', N'')
INSERT [dbo].[AM_COPA_FILTER_MAPPING] ([COPA_SAP_FIELD], [COPA_FILTER], [COPA_FIELD_DESC], [_COPA_FILTER_MAP]) VALUES (N'[VBAK_AUART] + '' - '' + [TVAKT_BEZEI]', N'ZF_COPA_SALE_DOC_TYPE', N'SALES DOCUMENT TYPE', N'')
GO
