USE [DIVA_SOLA_FY20Q4_INCREMENTAL]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[AM_SCOPE](
	[SCOPE_MANDANT] [nvarchar](1000) NULL,
	[SCOPE_CMPNY_CODE] [nvarchar](1000) NULL,
	[SCOPE_BUSINESS_DMN_L1] [nvarchar](1000) NULL,
	[SCOPE_BUSINESS_DMN_L2] [nvarchar](1000) NULL,
	[SCOPE_SYSTEM] [nvarchar](1000) NULL,
	[_SCOPE_MANDT] [nvarchar](3) NULL
) ON [PRIMARY]
GO
INSERT [dbo].[AM_SCOPE] ([SCOPE_MANDANT], [SCOPE_CMPNY_CODE], [SCOPE_BUSINESS_DMN_L1], [SCOPE_BUSINESS_DMN_L2], [SCOPE_SYSTEM], [_SCOPE_MANDT]) VALUES (N'100', N'AR10', N'Sony Argentina (SAR)', N'Argentina', N'SOLA', N'')
INSERT [dbo].[AM_SCOPE] ([SCOPE_MANDANT], [SCOPE_CMPNY_CODE], [SCOPE_BUSINESS_DMN_L1], [SCOPE_BUSINESS_DMN_L2], [SCOPE_SYSTEM], [_SCOPE_MANDT]) VALUES (N'100', N'BO12', N'Sony Chile Ltda. (SCI)', N'Bolivia', N'SOLA', N'')
INSERT [dbo].[AM_SCOPE] ([SCOPE_MANDANT], [SCOPE_CMPNY_CODE], [SCOPE_BUSINESS_DMN_L1], [SCOPE_BUSINESS_DMN_L2], [SCOPE_SYSTEM], [_SCOPE_MANDT]) VALUES (N'100', N'BR10', N'Sony Brazil', N'Brazil', N'SOLA', N'')
INSERT [dbo].[AM_SCOPE] ([SCOPE_MANDANT], [SCOPE_CMPNY_CODE], [SCOPE_BUSINESS_DMN_L1], [SCOPE_BUSINESS_DMN_L2], [SCOPE_SYSTEM], [_SCOPE_MANDT]) VALUES (N'100', N'BR20', N'Sony Brazil', N'Brazil', N'SOLA', N'')
INSERT [dbo].[AM_SCOPE] ([SCOPE_MANDANT], [SCOPE_CMPNY_CODE], [SCOPE_BUSINESS_DMN_L1], [SCOPE_BUSINESS_DMN_L2], [SCOPE_SYSTEM], [_SCOPE_MANDT]) VALUES (N'100', N'CL10', N'Sony Chile Ltda. (SCI)', N'Chile', N'SOLA', N'')
INSERT [dbo].[AM_SCOPE] ([SCOPE_MANDANT], [SCOPE_CMPNY_CODE], [SCOPE_BUSINESS_DMN_L1], [SCOPE_BUSINESS_DMN_L2], [SCOPE_SYSTEM], [_SCOPE_MANDT]) VALUES (N'100', N'CL20', N'Sony Chile Ltda. (SCI)', N'Chile', N'SOLA', N'')
INSERT [dbo].[AM_SCOPE] ([SCOPE_MANDANT], [SCOPE_CMPNY_CODE], [SCOPE_BUSINESS_DMN_L1], [SCOPE_BUSINESS_DMN_L2], [SCOPE_SYSTEM], [_SCOPE_MANDT]) VALUES (N'100', N'CL30', N'Sony Chile Ltda. (SCI)', N'Iquique', N'SOLA', N'')
INSERT [dbo].[AM_SCOPE] ([SCOPE_MANDANT], [SCOPE_CMPNY_CODE], [SCOPE_BUSINESS_DMN_L1], [SCOPE_BUSINESS_DMN_L2], [SCOPE_SYSTEM], [_SCOPE_MANDT]) VALUES (N'100', N'CO10', N'Sony Inter American, S.A (SIA)', N'Colombia', N'SOLA', N'')
INSERT [dbo].[AM_SCOPE] ([SCOPE_MANDANT], [SCOPE_CMPNY_CODE], [SCOPE_BUSINESS_DMN_L1], [SCOPE_BUSINESS_DMN_L2], [SCOPE_SYSTEM], [_SCOPE_MANDT]) VALUES (N'100', N'CO20', N'Sony Inter American, S.A (SIA)', N'Colombia', N'SOLA', N'')
INSERT [dbo].[AM_SCOPE] ([SCOPE_MANDANT], [SCOPE_CMPNY_CODE], [SCOPE_BUSINESS_DMN_L1], [SCOPE_BUSINESS_DMN_L2], [SCOPE_SYSTEM], [_SCOPE_MANDT]) VALUES (N'100', N'CR10', N'Sony Inter American, S.A (SIA)', N'Costa Rica', N'SOLA', N'')
INSERT [dbo].[AM_SCOPE] ([SCOPE_MANDANT], [SCOPE_CMPNY_CODE], [SCOPE_BUSINESS_DMN_L1], [SCOPE_BUSINESS_DMN_L2], [SCOPE_SYSTEM], [_SCOPE_MANDT]) VALUES (N'100', N'CR20', N'Sony Inter American, S.A (SIA)', N'Costa Rica', N'SOLA', N'')
INSERT [dbo].[AM_SCOPE] ([SCOPE_MANDANT], [SCOPE_CMPNY_CODE], [SCOPE_BUSINESS_DMN_L1], [SCOPE_BUSINESS_DMN_L2], [SCOPE_SYSTEM], [_SCOPE_MANDT]) VALUES (N'100', N'EC10', N'Sony Inter American, S.A (SIA)', N'Ecuador', N'SOLA', N'')
INSERT [dbo].[AM_SCOPE] ([SCOPE_MANDANT], [SCOPE_CMPNY_CODE], [SCOPE_BUSINESS_DMN_L1], [SCOPE_BUSINESS_DMN_L2], [SCOPE_SYSTEM], [_SCOPE_MANDT]) VALUES (N'100', N'EC20', N'Sony Inter American, S.A (SIA)', N'Ecuador', N'SOLA', N'')
INSERT [dbo].[AM_SCOPE] ([SCOPE_MANDANT], [SCOPE_CMPNY_CODE], [SCOPE_BUSINESS_DMN_L1], [SCOPE_BUSINESS_DMN_L2], [SCOPE_SYSTEM], [_SCOPE_MANDT]) VALUES (N'100', N'MX10', N'Sony Mexico (SMX)', N'Mexico', N'SOLA', N'')
INSERT [dbo].[AM_SCOPE] ([SCOPE_MANDANT], [SCOPE_CMPNY_CODE], [SCOPE_BUSINESS_DMN_L1], [SCOPE_BUSINESS_DMN_L2], [SCOPE_SYSTEM], [_SCOPE_MANDT]) VALUES (N'100', N'MX20', N'Sony Mexico (SMX)', N'Mexico', N'SOLA', N'')
INSERT [dbo].[AM_SCOPE] ([SCOPE_MANDANT], [SCOPE_CMPNY_CODE], [SCOPE_BUSINESS_DMN_L1], [SCOPE_BUSINESS_DMN_L2], [SCOPE_SYSTEM], [_SCOPE_MANDT]) VALUES (N'100', N'MX30', N'Sony Mexico (SMX)', N'Mexico', N'SOLA', N'')
INSERT [dbo].[AM_SCOPE] ([SCOPE_MANDANT], [SCOPE_CMPNY_CODE], [SCOPE_BUSINESS_DMN_L1], [SCOPE_BUSINESS_DMN_L2], [SCOPE_SYSTEM], [_SCOPE_MANDT]) VALUES (N'100', N'PA10', N'Sony Inter American, S.A (SIA)', N'Panama', N'SOLA', N'')
INSERT [dbo].[AM_SCOPE] ([SCOPE_MANDANT], [SCOPE_CMPNY_CODE], [SCOPE_BUSINESS_DMN_L1], [SCOPE_BUSINESS_DMN_L2], [SCOPE_SYSTEM], [_SCOPE_MANDT]) VALUES (N'100', N'PA20', N'Sony Inter American, S.A (SIA)', N'Panama', N'SOLA', N'')
INSERT [dbo].[AM_SCOPE] ([SCOPE_MANDANT], [SCOPE_CMPNY_CODE], [SCOPE_BUSINESS_DMN_L1], [SCOPE_BUSINESS_DMN_L2], [SCOPE_SYSTEM], [_SCOPE_MANDT]) VALUES (N'100', N'PA30', N'Sony Inter American, S.A (SIA)', N'Panama', N'SOLA', N'')
INSERT [dbo].[AM_SCOPE] ([SCOPE_MANDANT], [SCOPE_CMPNY_CODE], [SCOPE_BUSINESS_DMN_L1], [SCOPE_BUSINESS_DMN_L2], [SCOPE_SYSTEM], [_SCOPE_MANDT]) VALUES (N'100', N'PA40', N'Sony Inter American, S.A (SIA)', N'Panama', N'SOLA', N'')
INSERT [dbo].[AM_SCOPE] ([SCOPE_MANDANT], [SCOPE_CMPNY_CODE], [SCOPE_BUSINESS_DMN_L1], [SCOPE_BUSINESS_DMN_L2], [SCOPE_SYSTEM], [_SCOPE_MANDT]) VALUES (N'100', N'PE10', N'Sony Peru', N'Peru', N'SOLA', N'')
INSERT [dbo].[AM_SCOPE] ([SCOPE_MANDANT], [SCOPE_CMPNY_CODE], [SCOPE_BUSINESS_DMN_L1], [SCOPE_BUSINESS_DMN_L2], [SCOPE_SYSTEM], [_SCOPE_MANDT]) VALUES (N'100', N'PE20', N'Sony Peru', N'Peru', N'SOLA', N'')
INSERT [dbo].[AM_SCOPE] ([SCOPE_MANDANT], [SCOPE_CMPNY_CODE], [SCOPE_BUSINESS_DMN_L1], [SCOPE_BUSINESS_DMN_L2], [SCOPE_SYSTEM], [_SCOPE_MANDT]) VALUES (N'100', N'PE30', N'Sony Peru', N'Peru', N'SOLA', N'')
INSERT [dbo].[AM_SCOPE] ([SCOPE_MANDANT], [SCOPE_CMPNY_CODE], [SCOPE_BUSINESS_DMN_L1], [SCOPE_BUSINESS_DMN_L2], [SCOPE_SYSTEM], [_SCOPE_MANDT]) VALUES (N'100', N'PE40', N'Sony Peru', N'Peru', N'SOLA', N'')
INSERT [dbo].[AM_SCOPE] ([SCOPE_MANDANT], [SCOPE_CMPNY_CODE], [SCOPE_BUSINESS_DMN_L1], [SCOPE_BUSINESS_DMN_L2], [SCOPE_SYSTEM], [_SCOPE_MANDT]) VALUES (N'100', N'PR10', N'Sony Inter American, S.A (SIA)', N'Puerto Rico', N'SOLA', N'')
INSERT [dbo].[AM_SCOPE] ([SCOPE_MANDANT], [SCOPE_CMPNY_CODE], [SCOPE_BUSINESS_DMN_L1], [SCOPE_BUSINESS_DMN_L2], [SCOPE_SYSTEM], [_SCOPE_MANDT]) VALUES (N'100', N'UR40', N'Sony Argentina (SAR)', N'Argentina', N'SOLA', N'')
INSERT [dbo].[AM_SCOPE] ([SCOPE_MANDANT], [SCOPE_CMPNY_CODE], [SCOPE_BUSINESS_DMN_L1], [SCOPE_BUSINESS_DMN_L2], [SCOPE_SYSTEM], [_SCOPE_MANDT]) VALUES (N'100', N'US10', N'Sony Latin America (SOLA)', N'Miami', N'SOLA', N'')
INSERT [dbo].[AM_SCOPE] ([SCOPE_MANDANT], [SCOPE_CMPNY_CODE], [SCOPE_BUSINESS_DMN_L1], [SCOPE_BUSINESS_DMN_L2], [SCOPE_SYSTEM], [_SCOPE_MANDT]) VALUES (N'100', N'VE10', N'Sony Inter American, S.A (SIA)', N'Venezuela', N'SOLA', N'')
INSERT [dbo].[AM_SCOPE] ([SCOPE_MANDANT], [SCOPE_CMPNY_CODE], [SCOPE_BUSINESS_DMN_L1], [SCOPE_BUSINESS_DMN_L2], [SCOPE_SYSTEM], [_SCOPE_MANDT]) VALUES (N'100', N'VE12', N'Sony Inter American, S.A (SIA)', N'Venezuela', N'SOLA', N'')
INSERT [dbo].[AM_SCOPE] ([SCOPE_MANDANT], [SCOPE_CMPNY_CODE], [SCOPE_BUSINESS_DMN_L1], [SCOPE_BUSINESS_DMN_L2], [SCOPE_SYSTEM], [_SCOPE_MANDT]) VALUES (N'100', N'VE13', N'Sony Inter American, S.A (SIA)', N'Venezuela', N'SOLA', N'')
INSERT [dbo].[AM_SCOPE] ([SCOPE_MANDANT], [SCOPE_CMPNY_CODE], [SCOPE_BUSINESS_DMN_L1], [SCOPE_BUSINESS_DMN_L2], [SCOPE_SYSTEM], [_SCOPE_MANDT]) VALUES (N'100', N'VE14', N'Sony Inter American, S.A (SIA)', N'Venezuela', N'SOLA', N'')
INSERT [dbo].[AM_SCOPE] ([SCOPE_MANDANT], [SCOPE_CMPNY_CODE], [SCOPE_BUSINESS_DMN_L1], [SCOPE_BUSINESS_DMN_L2], [SCOPE_SYSTEM], [_SCOPE_MANDT]) VALUES (N'100', N'VE15', N'Sony Inter American, S.A (SIA)', N'Venezuela', N'SOLA', N'')
INSERT [dbo].[AM_SCOPE] ([SCOPE_MANDANT], [SCOPE_CMPNY_CODE], [SCOPE_BUSINESS_DMN_L1], [SCOPE_BUSINESS_DMN_L2], [SCOPE_SYSTEM], [_SCOPE_MANDT]) VALUES (N'100', N'VE16', N'Sony Inter American, S.A (SIA)', N'Venezuela', N'SOLA', N'')
INSERT [dbo].[AM_SCOPE] ([SCOPE_MANDANT], [SCOPE_CMPNY_CODE], [SCOPE_BUSINESS_DMN_L1], [SCOPE_BUSINESS_DMN_L2], [SCOPE_SYSTEM], [_SCOPE_MANDT]) VALUES (N'100', N'VE20', N'Sony Inter American, S.A (SIA)', N'Venezuela', N'SOLA', N'')
INSERT [dbo].[AM_SCOPE] ([SCOPE_MANDANT], [SCOPE_CMPNY_CODE], [SCOPE_BUSINESS_DMN_L1], [SCOPE_BUSINESS_DMN_L2], [SCOPE_SYSTEM], [_SCOPE_MANDT]) VALUES (N'100', N'AR20', N'Sony SOLA Other', N'Other', N'SOLA', N'')
INSERT [dbo].[AM_SCOPE] ([SCOPE_MANDANT], [SCOPE_CMPNY_CODE], [SCOPE_BUSINESS_DMN_L1], [SCOPE_BUSINESS_DMN_L2], [SCOPE_SYSTEM], [_SCOPE_MANDT]) VALUES (N'100', N'BO10', N'Sony SOLA Other', N'Other', N'SOLA', N'')
INSERT [dbo].[AM_SCOPE] ([SCOPE_MANDANT], [SCOPE_CMPNY_CODE], [SCOPE_BUSINESS_DMN_L1], [SCOPE_BUSINESS_DMN_L2], [SCOPE_SYSTEM], [_SCOPE_MANDT]) VALUES (N'100', N'BO11', N'Sony SOLA Other', N'Other', N'SOLA', N'')
INSERT [dbo].[AM_SCOPE] ([SCOPE_MANDANT], [SCOPE_CMPNY_CODE], [SCOPE_BUSINESS_DMN_L1], [SCOPE_BUSINESS_DMN_L2], [SCOPE_SYSTEM], [_SCOPE_MANDT]) VALUES (N'100', N'PU10', N'Sony SOLA Other', N'Other', N'SOLA', N'')
INSERT [dbo].[AM_SCOPE] ([SCOPE_MANDANT], [SCOPE_CMPNY_CODE], [SCOPE_BUSINESS_DMN_L1], [SCOPE_BUSINESS_DMN_L2], [SCOPE_SYSTEM], [_SCOPE_MANDT]) VALUES (N'100', N'PU20', N'Sony SOLA Other', N'Other', N'SOLA', N'')
INSERT [dbo].[AM_SCOPE] ([SCOPE_MANDANT], [SCOPE_CMPNY_CODE], [SCOPE_BUSINESS_DMN_L1], [SCOPE_BUSINESS_DMN_L2], [SCOPE_SYSTEM], [_SCOPE_MANDT]) VALUES (N'100', N'UR10', N'Sony SOLA Other', N'Other', N'SOLA', N'')
INSERT [dbo].[AM_SCOPE] ([SCOPE_MANDANT], [SCOPE_CMPNY_CODE], [SCOPE_BUSINESS_DMN_L1], [SCOPE_BUSINESS_DMN_L2], [SCOPE_SYSTEM], [_SCOPE_MANDT]) VALUES (N'100', N'UR20', N'Sony SOLA Other', N'Other', N'SOLA', N'')
INSERT [dbo].[AM_SCOPE] ([SCOPE_MANDANT], [SCOPE_CMPNY_CODE], [SCOPE_BUSINESS_DMN_L1], [SCOPE_BUSINESS_DMN_L2], [SCOPE_SYSTEM], [_SCOPE_MANDT]) VALUES (N'100', N'UR30', N'Sony SOLA Other', N'Other', N'SOLA', N'')
INSERT [dbo].[AM_SCOPE] ([SCOPE_MANDANT], [SCOPE_CMPNY_CODE], [SCOPE_BUSINESS_DMN_L1], [SCOPE_BUSINESS_DMN_L2], [SCOPE_SYSTEM], [_SCOPE_MANDT]) VALUES (N'100', N'US30', N'Sony SOLA Other', N'Other', N'SOLA', N'')
GO
