USE [DIVA_SOLA_FY20Q4_INCREMENTAL]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[AM_LIST_KEY_WORDS](
	[KEY_WORD_ID] [nvarchar](255) NULL,
	[ZF_KEY_WORD] [nvarchar](255) NULL,
	[ZF_NOT_KEY_WORD1] [nvarchar](255) NULL,
	[ZF_NOT_KEY_WORD2] [nvarchar](255) NULL,
	[ZF_NOT_KEY_WORD3] [nvarchar](255) NULL,
	[ZF_NOT_KEY_WORD4] [nvarchar](255) NULL,
	[ZF_NOT_KEY_WORD5] [nvarchar](255) NULL
) ON [PRIMARY]
GO
INSERT [dbo].[AM_LIST_KEY_WORDS] ([KEY_WORD_ID], [ZF_KEY_WORD], [ZF_NOT_KEY_WORD1], [ZF_NOT_KEY_WORD2], [ZF_NOT_KEY_WORD3], [ZF_NOT_KEY_WORD4], [ZF_NOT_KEY_WORD5]) VALUES (N'1', N'consult', N'', N'', N'', N'', N'')
INSERT [dbo].[AM_LIST_KEY_WORDS] ([KEY_WORD_ID], [ZF_KEY_WORD], [ZF_NOT_KEY_WORD1], [ZF_NOT_KEY_WORD2], [ZF_NOT_KEY_WORD3], [ZF_NOT_KEY_WORD4], [ZF_NOT_KEY_WORD5]) VALUES (N'2', N'process', N'', N'', N'', N'', N'')
INSERT [dbo].[AM_LIST_KEY_WORDS] ([KEY_WORD_ID], [ZF_KEY_WORD], [ZF_NOT_KEY_WORD1], [ZF_NOT_KEY_WORD2], [ZF_NOT_KEY_WORD3], [ZF_NOT_KEY_WORD4], [ZF_NOT_KEY_WORD5]) VALUES (N'3', N'referral', N'', N'', N'', N'', N'')
INSERT [dbo].[AM_LIST_KEY_WORDS] ([KEY_WORD_ID], [ZF_KEY_WORD], [ZF_NOT_KEY_WORD1], [ZF_NOT_KEY_WORD2], [ZF_NOT_KEY_WORD3], [ZF_NOT_KEY_WORD4], [ZF_NOT_KEY_WORD5]) VALUES (N'4', N'donate', N'', N'', N'', N'', N'')
INSERT [dbo].[AM_LIST_KEY_WORDS] ([KEY_WORD_ID], [ZF_KEY_WORD], [ZF_NOT_KEY_WORD1], [ZF_NOT_KEY_WORD2], [ZF_NOT_KEY_WORD3], [ZF_NOT_KEY_WORD4], [ZF_NOT_KEY_WORD5]) VALUES (N'5', N'donation', N'', N'', N'', N'', N'')
INSERT [dbo].[AM_LIST_KEY_WORDS] ([KEY_WORD_ID], [ZF_KEY_WORD], [ZF_NOT_KEY_WORD1], [ZF_NOT_KEY_WORD2], [ZF_NOT_KEY_WORD3], [ZF_NOT_KEY_WORD4], [ZF_NOT_KEY_WORD5]) VALUES (N'6', N'goodwill', N'', N'', N'', N'', N'')
INSERT [dbo].[AM_LIST_KEY_WORDS] ([KEY_WORD_ID], [ZF_KEY_WORD], [ZF_NOT_KEY_WORD1], [ZF_NOT_KEY_WORD2], [ZF_NOT_KEY_WORD3], [ZF_NOT_KEY_WORD4], [ZF_NOT_KEY_WORD5]) VALUES (N'7', N'incentive payment', N'', N'', N'', N'', N'')
INSERT [dbo].[AM_LIST_KEY_WORDS] ([KEY_WORD_ID], [ZF_KEY_WORD], [ZF_NOT_KEY_WORD1], [ZF_NOT_KEY_WORD2], [ZF_NOT_KEY_WORD3], [ZF_NOT_KEY_WORD4], [ZF_NOT_KEY_WORD5]) VALUES (N'8', N'one time', N'', N'', N'', N'', N'')
INSERT [dbo].[AM_LIST_KEY_WORDS] ([KEY_WORD_ID], [ZF_KEY_WORD], [ZF_NOT_KEY_WORD1], [ZF_NOT_KEY_WORD2], [ZF_NOT_KEY_WORD3], [ZF_NOT_KEY_WORD4], [ZF_NOT_KEY_WORD5]) VALUES (N'9', N'one off', N'', N'', N'', N'', N'')
INSERT [dbo].[AM_LIST_KEY_WORDS] ([KEY_WORD_ID], [ZF_KEY_WORD], [ZF_NOT_KEY_WORD1], [ZF_NOT_KEY_WORD2], [ZF_NOT_KEY_WORD3], [ZF_NOT_KEY_WORD4], [ZF_NOT_KEY_WORD5]) VALUES (N'10', N'special payment', N'', N'', N'', N'', N'')
INSERT [dbo].[AM_LIST_KEY_WORDS] ([KEY_WORD_ID], [ZF_KEY_WORD], [ZF_NOT_KEY_WORD1], [ZF_NOT_KEY_WORD2], [ZF_NOT_KEY_WORD3], [ZF_NOT_KEY_WORD4], [ZF_NOT_KEY_WORD5]) VALUES (N'11', N'commission', N'', N'', N'', N'', N'')
INSERT [dbo].[AM_LIST_KEY_WORDS] ([KEY_WORD_ID], [ZF_KEY_WORD], [ZF_NOT_KEY_WORD1], [ZF_NOT_KEY_WORD2], [ZF_NOT_KEY_WORD3], [ZF_NOT_KEY_WORD4], [ZF_NOT_KEY_WORD5]) VALUES (N'12', N'reverse', N'', N'', N'', N'', N'')
INSERT [dbo].[AM_LIST_KEY_WORDS] ([KEY_WORD_ID], [ZF_KEY_WORD], [ZF_NOT_KEY_WORD1], [ZF_NOT_KEY_WORD2], [ZF_NOT_KEY_WORD3], [ZF_NOT_KEY_WORD4], [ZF_NOT_KEY_WORD5]) VALUES (N'13', N'reversal', N'', N'', N'', N'', N'')
INSERT [dbo].[AM_LIST_KEY_WORDS] ([KEY_WORD_ID], [ZF_KEY_WORD], [ZF_NOT_KEY_WORD1], [ZF_NOT_KEY_WORD2], [ZF_NOT_KEY_WORD3], [ZF_NOT_KEY_WORD4], [ZF_NOT_KEY_WORD5]) VALUES (N'14', N'catch', N'', N'', N'', N'', N'')
INSERT [dbo].[AM_LIST_KEY_WORDS] ([KEY_WORD_ID], [ZF_KEY_WORD], [ZF_NOT_KEY_WORD1], [ZF_NOT_KEY_WORD2], [ZF_NOT_KEY_WORD3], [ZF_NOT_KEY_WORD4], [ZF_NOT_KEY_WORD5]) VALUES (N'15', N'write', N'', N'', N'', N'', N'')
INSERT [dbo].[AM_LIST_KEY_WORDS] ([KEY_WORD_ID], [ZF_KEY_WORD], [ZF_NOT_KEY_WORD1], [ZF_NOT_KEY_WORD2], [ZF_NOT_KEY_WORD3], [ZF_NOT_KEY_WORD4], [ZF_NOT_KEY_WORD5]) VALUES (N'16', N'reduce', N'', N'', N'', N'', N'')
INSERT [dbo].[AM_LIST_KEY_WORDS] ([KEY_WORD_ID], [ZF_KEY_WORD], [ZF_NOT_KEY_WORD1], [ZF_NOT_KEY_WORD2], [ZF_NOT_KEY_WORD3], [ZF_NOT_KEY_WORD4], [ZF_NOT_KEY_WORD5]) VALUES (N'17', N'cut off', N'', N'', N'', N'', N'')
INSERT [dbo].[AM_LIST_KEY_WORDS] ([KEY_WORD_ID], [ZF_KEY_WORD], [ZF_NOT_KEY_WORD1], [ZF_NOT_KEY_WORD2], [ZF_NOT_KEY_WORD3], [ZF_NOT_KEY_WORD4], [ZF_NOT_KEY_WORD5]) VALUES (N'18', N'round', N'', N'', N'', N'', N'')
INSERT [dbo].[AM_LIST_KEY_WORDS] ([KEY_WORD_ID], [ZF_KEY_WORD], [ZF_NOT_KEY_WORD1], [ZF_NOT_KEY_WORD2], [ZF_NOT_KEY_WORD3], [ZF_NOT_KEY_WORD4], [ZF_NOT_KEY_WORD5]) VALUES (N'19', N'reserve', N'', N'', N'', N'', N'')
INSERT [dbo].[AM_LIST_KEY_WORDS] ([KEY_WORD_ID], [ZF_KEY_WORD], [ZF_NOT_KEY_WORD1], [ZF_NOT_KEY_WORD2], [ZF_NOT_KEY_WORD3], [ZF_NOT_KEY_WORD4], [ZF_NOT_KEY_WORD5]) VALUES (N'20', N'early', N'yearly', N'', N'', N'', N'')
INSERT [dbo].[AM_LIST_KEY_WORDS] ([KEY_WORD_ID], [ZF_KEY_WORD], [ZF_NOT_KEY_WORD1], [ZF_NOT_KEY_WORD2], [ZF_NOT_KEY_WORD3], [ZF_NOT_KEY_WORD4], [ZF_NOT_KEY_WORD5]) VALUES (N'21', N'adjust', N'', N'', N'', N'', N'')
INSERT [dbo].[AM_LIST_KEY_WORDS] ([KEY_WORD_ID], [ZF_KEY_WORD], [ZF_NOT_KEY_WORD1], [ZF_NOT_KEY_WORD2], [ZF_NOT_KEY_WORD3], [ZF_NOT_KEY_WORD4], [ZF_NOT_KEY_WORD5]) VALUES (N'22', N'adjustment', N'', N'', N'', N'', N'')
INSERT [dbo].[AM_LIST_KEY_WORDS] ([KEY_WORD_ID], [ZF_KEY_WORD], [ZF_NOT_KEY_WORD1], [ZF_NOT_KEY_WORD2], [ZF_NOT_KEY_WORD3], [ZF_NOT_KEY_WORD4], [ZF_NOT_KEY_WORD5]) VALUES (N'23', N'kickback', N'', N'', N'', N'', N'')
GO
