USE [DIVA_SOLA_FY20Q4_INCREMENTAL]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[AM_DSM](
	[DSM_DIVISION] [nvarchar](1000) NULL,
	[DSM_DESCRIPTION] [nvarchar](1000) NULL,
	[DSM_BUSINESS_SEGMENT] [nvarchar](1000) NULL,
	[_DSM_MANDT] [nvarchar](3) NULL
) ON [PRIMARY]
GO
