USE [DIVA_SOLA_FY20Q4_INCREMENTAL]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[AM_IRGR_GINI_ARDR_MAPPING](
	[IRGR_GL_ACCT] [nvarchar](100) NULL,
	[IRGR_GL_TXT] [nvarchar](100) NULL,
	[IRGR_OR_GINI_OR_ARDR] [nvarchar](100) NULL
) ON [PRIMARY]
GO
INSERT [dbo].[AM_IRGR_GINI_ARDR_MAPPING] ([IRGR_GL_ACCT], [IRGR_GL_TXT], [IRGR_OR_GINI_OR_ARDR]) VALUES (N'2211000310', N'Accrual outstanding invoices inventory', N'IRGR')
INSERT [dbo].[AM_IRGR_GINI_ARDR_MAPPING] ([IRGR_GL_ACCT], [IRGR_GL_TXT], [IRGR_OR_GINI_OR_ARDR]) VALUES (N'2211000311', N'Goods received/Invoices received - other materials', N'IRGR')
INSERT [dbo].[AM_IRGR_GINI_ARDR_MAPPING] ([IRGR_GL_ACCT], [IRGR_GL_TXT], [IRGR_OR_GINI_OR_ARDR]) VALUES (N'2211000320', N'Accrual outstanding invoices expenses', N'IRGR')
INSERT [dbo].[AM_IRGR_GINI_ARDR_MAPPING] ([IRGR_GL_ACCT], [IRGR_GL_TXT], [IRGR_OR_GINI_OR_ARDR]) VALUES (N'2211000321', N'Accrual outstanding invoices serv.expenses', N'IRGR')
INSERT [dbo].[AM_IRGR_GINI_ARDR_MAPPING] ([IRGR_GL_ACCT], [IRGR_GL_TXT], [IRGR_OR_GINI_OR_ARDR]) VALUES (N'2211000345', N'Unbilled Revenue', N'ARDR')
INSERT [dbo].[AM_IRGR_GINI_ARDR_MAPPING] ([IRGR_GL_ACCT], [IRGR_GL_TXT], [IRGR_OR_GINI_OR_ARDR]) VALUES (N'2225000000', N'Deferred revenue ST', N'ARDR')
INSERT [dbo].[AM_IRGR_GINI_ARDR_MAPPING] ([IRGR_GL_ACCT], [IRGR_GL_TXT], [IRGR_OR_GINI_OR_ARDR]) VALUES (N'2225000005', N'Unbilled Revenue', N'ARDR')
GO
