USE [DIVA_SOLA_FY20Q4_INCREMENTAL]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[AM_GLOBALS](
	[GLOBALS_PARAMETER] [nvarchar](1000) NULL,
	[GLOBALS_VALUE] [nvarchar](1000) NULL,
	[GLOBALS_DESCRIPTION] [nvarchar](1000) NULL,
	[_GLOBALS_MANDT] [nvarchar](3) NULL
) ON [PRIMARY]
GO
INSERT [dbo].[AM_GLOBALS] ([GLOBALS_PARAMETER], [GLOBALS_VALUE], [GLOBALS_DESCRIPTION], [_GLOBALS_MANDT]) VALUES (N'id', N'SOLA', N'System name', N'100')
INSERT [dbo].[AM_GLOBALS] ([GLOBALS_PARAMETER], [GLOBALS_VALUE], [GLOBALS_DESCRIPTION], [_GLOBALS_MANDT]) VALUES (N'currency', N'USD', N'Reporting currency. Required', N'100')
INSERT [dbo].[AM_GLOBALS] ([GLOBALS_PARAMETER], [GLOBALS_VALUE], [GLOBALS_DESCRIPTION], [_GLOBALS_MANDT]) VALUES (N'date1', N'2021-01-01', N'Scope - date from. Required', N'100')
INSERT [dbo].[AM_GLOBALS] ([GLOBALS_PARAMETER], [GLOBALS_VALUE], [GLOBALS_DESCRIPTION], [_GLOBALS_MANDT]) VALUES (N'date2', N'2021-03-31', N'Scope - date to. Required', N'100')
INSERT [dbo].[AM_GLOBALS] ([GLOBALS_PARAMETER], [GLOBALS_VALUE], [GLOBALS_DESCRIPTION], [_GLOBALS_MANDT]) VALUES (N'dateformat', N'ymd', N'Date syntax format. Required', N'100')
INSERT [dbo].[AM_GLOBALS] ([GLOBALS_PARAMETER], [GLOBALS_VALUE], [GLOBALS_DESCRIPTION], [_GLOBALS_MANDT]) VALUES (N'downloaddate', N'2021-03-31', N'Date of download. Required', N'100')
INSERT [dbo].[AM_GLOBALS] ([GLOBALS_PARAMETER], [GLOBALS_VALUE], [GLOBALS_DESCRIPTION], [_GLOBALS_MANDT]) VALUES (N'exchangeratetype', N'M', N'Exchange rate type used (see table T001A) for determing the exchange rates', N'100')
INSERT [dbo].[AM_GLOBALS] ([GLOBALS_PARAMETER], [GLOBALS_VALUE], [GLOBALS_DESCRIPTION], [_GLOBALS_MANDT]) VALUES (N'LIMIT_RECORDS', N'0', N'Enter 0 to run on full data sets or 100 to limit to 100 lines', N'100')
INSERT [dbo].[AM_GLOBALS] ([GLOBALS_PARAMETER], [GLOBALS_VALUE], [GLOBALS_DESCRIPTION], [_GLOBALS_MANDT]) VALUES (N'language1', N'EN', N'Primary language. Required', N'100')
INSERT [dbo].[AM_GLOBALS] ([GLOBALS_PARAMETER], [GLOBALS_VALUE], [GLOBALS_DESCRIPTION], [_GLOBALS_MANDT]) VALUES (N'language2', N'E', N'Secondary languageq. Required', N'100')
INSERT [dbo].[AM_GLOBALS] ([GLOBALS_PARAMETER], [GLOBALS_VALUE], [GLOBALS_DESCRIPTION], [_GLOBALS_MANDT]) VALUES (N'first_import_path', N'H:\GPW\Small table\Small table\Small table\output\test\test', N'Raw data location. Required', N'100')
INSERT [dbo].[AM_GLOBALS] ([GLOBALS_PARAMETER], [GLOBALS_VALUE], [GLOBALS_DESCRIPTION], [_GLOBALS_MANDT]) VALUES (N'SAP_DDIC_version', N'SOLA_DD03L', N'(SAP46C SAP47 SAPECC50 SAPECC60). Version of SAP data dictionary. Required for staging data.', N'100')
INSERT [dbo].[AM_GLOBALS] ([GLOBALS_PARAMETER], [GLOBALS_VALUE], [GLOBALS_DESCRIPTION], [_GLOBALS_MANDT]) VALUES (N'year', N'2020', N'Scope - year. Required', N'100')
INSERT [dbo].[AM_GLOBALS] ([GLOBALS_PARAMETER], [GLOBALS_VALUE], [GLOBALS_DESCRIPTION], [_GLOBALS_MANDT]) VALUES (N'new GL', N'N', N'Y for new GL with FAGLFLEXT, N for Old GL with GLT0', N'100')
INSERT [dbo].[AM_GLOBALS] ([GLOBALS_PARAMETER], [GLOBALS_VALUE], [GLOBALS_DESCRIPTION], [_GLOBALS_MANDT]) VALUES (N'custom_currency_field', N'DMBE2', N' ', N'100')
INSERT [dbo].[AM_GLOBALS] ([GLOBALS_PARAMETER], [GLOBALS_VALUE], [GLOBALS_DESCRIPTION], [_GLOBALS_MANDT]) VALUES (N'ZV_TB_RRCTY', N'0', N'0 for new gl and * for old gl', N'100')
INSERT [dbo].[AM_GLOBALS] ([GLOBALS_PARAMETER], [GLOBALS_VALUE], [GLOBALS_DESCRIPTION], [_GLOBALS_MANDT]) VALUES (N'COPA_TABLE_NAME', N'A_CE1SOLA', N'INPUT COPA TABLE NAME TO THIS LINE', N'100')
INSERT [dbo].[AM_GLOBALS] ([GLOBALS_PARAMETER], [GLOBALS_VALUE], [GLOBALS_DESCRIPTION], [_GLOBALS_MANDT]) VALUES (N'ZV_TB_RLDNR', N'00', N'ledger type which is used in DV02', N'100')
INSERT [dbo].[AM_GLOBALS] ([GLOBALS_PARAMETER], [GLOBALS_VALUE], [GLOBALS_DESCRIPTION], [_GLOBALS_MANDT]) VALUES (N'next_import_path', N'H:\GPW\Small table\Small table\Small table\output\test\test', NULL, NULL)
GO
