USE [DIVA_SOLA_FY20Q4_INCREMENTAL]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[AM_VENDOR_EXCEPTION_LIST](
	[VEL_COMPANY_CODE] [nvarchar](1000) NULL,
	[VEL_SUPPLIER_NUM] [nvarchar](1000) NULL,
	[_VENDOR_EXCEPTIO] [nvarchar](3) NULL
) ON [PRIMARY]
GO
