USE [DIVA_GB00_FY23_24]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[AM_GLOBALS](
	[GLOBALS_PARAMETER] [nvarchar](50) NOT NULL,
	[GLOBALS_VALUE] [nvarchar](500) NULL,
	[GLOBALS_DESCRIPTION] [nvarchar](200) NULL,
	[ORD_NUMBER] [int] NULL
) ON [PRIMARY]
GO
INSERT [dbo].[AM_GLOBALS] ([GLOBALS_PARAMETER], [GLOBALS_VALUE], [GLOBALS_DESCRIPTION], [ORD_NUMBER]) VALUES (N'currency', N'USD', N'Reporting currency. Required', 0)
INSERT [dbo].[AM_GLOBALS] ([GLOBALS_PARAMETER], [GLOBALS_VALUE], [GLOBALS_DESCRIPTION], [ORD_NUMBER]) VALUES (N'custom_currency_field', N'DMBTR', N'Custom_currency', 0)
INSERT [dbo].[AM_GLOBALS] ([GLOBALS_PARAMETER], [GLOBALS_VALUE], [GLOBALS_DESCRIPTION], [ORD_NUMBER]) VALUES (N'date1', N'20230401', N'Scope - date from. Required', 0)
INSERT [dbo].[AM_GLOBALS] ([GLOBALS_PARAMETER], [GLOBALS_VALUE], [GLOBALS_DESCRIPTION], [ORD_NUMBER]) VALUES (N'date2', N'20250331', N'Scope - date to. Required', 0)
INSERT [dbo].[AM_GLOBALS] ([GLOBALS_PARAMETER], [GLOBALS_VALUE], [GLOBALS_DESCRIPTION], [ORD_NUMBER]) VALUES (N'dateformat', N'ymd', N'Date syntax format. Required', 0)
INSERT [dbo].[AM_GLOBALS] ([GLOBALS_PARAMETER], [GLOBALS_VALUE], [GLOBALS_DESCRIPTION], [ORD_NUMBER]) VALUES (N'downloaddate', N'20250305', N'Date of download. Required', 0)
INSERT [dbo].[AM_GLOBALS] ([GLOBALS_PARAMETER], [GLOBALS_VALUE], [GLOBALS_DESCRIPTION], [ORD_NUMBER]) VALUES (N'exchangeratetype', N'M', N'Exchange rate type used (see table T001A) for determing the exchange rates', 0)
INSERT [dbo].[AM_GLOBALS] ([GLOBALS_PARAMETER], [GLOBALS_VALUE], [GLOBALS_DESCRIPTION], [ORD_NUMBER]) VALUES (N'FISCAL_YEAR_FROM', N'2023', NULL, 0)
INSERT [dbo].[AM_GLOBALS] ([GLOBALS_PARAMETER], [GLOBALS_VALUE], [GLOBALS_DESCRIPTION], [ORD_NUMBER]) VALUES (N'FISCAL_YEAR_TO', N'2024', NULL, 0)
INSERT [dbo].[AM_GLOBALS] ([GLOBALS_PARAMETER], [GLOBALS_VALUE], [GLOBALS_DESCRIPTION], [ORD_NUMBER]) VALUES (N'id', N'SVNE', N'System name. Required', 0)
INSERT [dbo].[AM_GLOBALS] ([GLOBALS_PARAMETER], [GLOBALS_VALUE], [GLOBALS_DESCRIPTION], [ORD_NUMBER]) VALUES (N'language1', N'EN', N'Primary language. Required', 0)
INSERT [dbo].[AM_GLOBALS] ([GLOBALS_PARAMETER], [GLOBALS_VALUE], [GLOBALS_DESCRIPTION], [ORD_NUMBER]) VALUES (N'language2', N'E', N'Secondary languageq. Required', 0)
INSERT [dbo].[AM_GLOBALS] ([GLOBALS_PARAMETER], [GLOBALS_VALUE], [GLOBALS_DESCRIPTION], [ORD_NUMBER]) VALUES (N'LIMIT_RECORDS', N'0', N'Enter 0 to run on full data sets or 100 to limit to 100 lines', 0)
INSERT [dbo].[AM_GLOBALS] ([GLOBALS_PARAMETER], [GLOBALS_VALUE], [GLOBALS_DESCRIPTION], [ORD_NUMBER]) VALUES (N'New_GL', N'N', N'New SAP ledger in use. Required', 0)
INSERT [dbo].[AM_GLOBALS] ([GLOBALS_PARAMETER], [GLOBALS_VALUE], [GLOBALS_DESCRIPTION], [ORD_NUMBER]) VALUES (N'path', N'F:\DIVA_GB00_FY2324\NEW PO\PO\PO\output', N'Raw data location. Required', 0)
INSERT [dbo].[AM_GLOBALS] ([GLOBALS_PARAMETER], [GLOBALS_VALUE], [GLOBALS_DESCRIPTION], [ORD_NUMBER]) VALUES (N'SAP_DDIC_version', N'SAPECC60', N'(SAP46C, SAP47, SAPECC50, SAPECC60). Version of SAP data dictionary. Required for staging data. ', 0)
INSERT [dbo].[AM_GLOBALS] ([GLOBALS_PARAMETER], [GLOBALS_VALUE], [GLOBALS_DESCRIPTION], [ORD_NUMBER]) VALUES (N'ZV_ACDOCA_RLDNR', N'0L', N'Ledger in General Ledger Accounting', 0)
INSERT [dbo].[AM_GLOBALS] ([GLOBALS_PARAMETER], [GLOBALS_VALUE], [GLOBALS_DESCRIPTION], [ORD_NUMBER]) VALUES (N'ZV_CLIENT', N'888', N'Filter on Specific Client', 0)
INSERT [dbo].[AM_GLOBALS] ([GLOBALS_PARAMETER], [GLOBALS_VALUE], [GLOBALS_DESCRIPTION], [ORD_NUMBER]) VALUES (N'ZV_SYSTEM_VERSION', N'PARALELL', N'PARALELL or S4HANA', 0)
INSERT [dbo].[AM_GLOBALS] ([GLOBALS_PARAMETER], [GLOBALS_VALUE], [GLOBALS_DESCRIPTION], [ORD_NUMBER]) VALUES (N'ZV_TB_RRCTY', N'0', N'0L Legder', 0)
INSERT [dbo].[AM_GLOBALS] ([GLOBALS_PARAMETER], [GLOBALS_VALUE], [GLOBALS_DESCRIPTION], [ORD_NUMBER]) VALUES (N'COPA_TABLE_NAME', N'A_CE1AM00', N'INPUT COPA TABLE NAME TO THIS LINE', 0)
INSERT [dbo].[AM_GLOBALS] ([GLOBALS_PARAMETER], [GLOBALS_VALUE], [GLOBALS_DESCRIPTION], [ORD_NUMBER]) VALUES (N'ZV_EXCHANGE_RATE_TYPE', N'WWSD', N'', NULL)
INSERT [dbo].[AM_GLOBALS] ([GLOBALS_PARAMETER], [GLOBALS_VALUE], [GLOBALS_DESCRIPTION], [ORD_NUMBER]) VALUES (N'ZV_DATE', N'03-31', N'', NULL)
GO
