USE [DIVA_GB00_FY23_24]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[AM_GL_HIERARCHY](
	[GL_L1] [nvarchar](100) NULL,
	[GL_L2] [nvarchar](100) NULL,
	[GL_L3] [nvarchar](100) NULL,
	[GL_L4] [nvarchar](100) NULL,
	[GL_ACCT] [nvarchar](100) NULL,
	[GL_TXT] [nvarchar](100) NULL
) ON [PRIMARY]
GO
INSERT [dbo].[AM_GL_HIERARCHY] ([GL_L1], [GL_L2], [GL_L3], [GL_L4], [GL_ACCT], [GL_TXT]) VALUES (NULL, NULL, NULL, NULL, N'A013010', N'Trade notes receivable- Bill of Exchange- General')
INSERT [dbo].[AM_GL_HIERARCHY] ([GL_L1], [GL_L2], [GL_L3], [GL_L4], [GL_ACCT], [GL_TXT]) VALUES (NULL, NULL, NULL, NULL, N'A014010', N'Trade account receivable- General')
INSERT [dbo].[AM_GL_HIERARCHY] ([GL_L1], [GL_L2], [GL_L3], [GL_L4], [GL_ACCT], [GL_TXT]) VALUES (NULL, NULL, NULL, NULL, N'A014106', N'JPM DKK - Sony Europe BV - EUR-InClr')
INSERT [dbo].[AM_GL_HIERARCHY] ([GL_L1], [GL_L2], [GL_L3], [GL_L4], [GL_ACCT], [GL_TXT]) VALUES (NULL, NULL, NULL, NULL, N'A014134', N'Incmng Clring- SCSE INTESA BAM BA (RAS22)')
INSERT [dbo].[AM_GL_HIERARCHY] ([GL_L1], [GL_L2], [GL_L3], [GL_L4], [GL_ACCT], [GL_TXT]) VALUES (NULL, NULL, NULL, NULL, N'A014143', N'Incmng Clring- INTESA RSD SER (SCSE) NEW')
INSERT [dbo].[AM_GL_HIERARCHY] ([GL_L1], [GL_L2], [GL_L3], [GL_L4], [GL_ACCT], [GL_TXT]) VALUES (NULL, NULL, NULL, NULL, N'A014152', N'JPM SEK - Sony Europe BV - EUR-InClr')
INSERT [dbo].[AM_GL_HIERARCHY] ([GL_L1], [GL_L2], [GL_L3], [GL_L4], [GL_ACCT], [GL_TXT]) VALUES (NULL, NULL, NULL, NULL, N'A014172', N'Incmng Clring- CITI BANK SEU SWITZERLAND CHF')
INSERT [dbo].[AM_GL_HIERARCHY] ([GL_L1], [GL_L2], [GL_L3], [GL_L4], [GL_ACCT], [GL_TXT]) VALUES (NULL, NULL, NULL, NULL, N'A014176', N'Incmng Clring- CITI BANK SONY EUROPE AT EUR')
INSERT [dbo].[AM_GL_HIERARCHY] ([GL_L1], [GL_L2], [GL_L3], [GL_L4], [GL_ACCT], [GL_TXT]) VALUES (NULL, NULL, NULL, NULL, N'A014177', N'Incmng Clring- CITI BANK PSE EUR')
INSERT [dbo].[AM_GL_HIERARCHY] ([GL_L1], [GL_L2], [GL_L3], [GL_L4], [GL_ACCT], [GL_TXT]) VALUES (NULL, NULL, NULL, NULL, N'A014184', N'Incmng Clring- CITI BANK SES USD')
INSERT [dbo].[AM_GL_HIERARCHY] ([GL_L1], [GL_L2], [GL_L3], [GL_L4], [GL_ACCT], [GL_TXT]) VALUES (NULL, NULL, NULL, NULL, N'A014185', N'Incmng Clring- CITI BANK GERMANY EUR')
INSERT [dbo].[AM_GL_HIERARCHY] ([GL_L1], [GL_L2], [GL_L3], [GL_L4], [GL_ACCT], [GL_TXT]) VALUES (NULL, NULL, NULL, NULL, N'A014190', N'Incmng Clring- CITI BANK EUR ITALY')
INSERT [dbo].[AM_GL_HIERARCHY] ([GL_L1], [GL_L2], [GL_L3], [GL_L4], [GL_ACCT], [GL_TXT]) VALUES (NULL, NULL, NULL, NULL, N'A014191', N'Incmng Clring- CITI BANK EUR FRANCE')
INSERT [dbo].[AM_GL_HIERARCHY] ([GL_L1], [GL_L2], [GL_L3], [GL_L4], [GL_ACCT], [GL_TXT]) VALUES (NULL, NULL, NULL, NULL, N'A014196', N'Incmng Clring- CITI BANK EUR SPAIN')
INSERT [dbo].[AM_GL_HIERARCHY] ([GL_L1], [GL_L2], [GL_L3], [GL_L4], [GL_ACCT], [GL_TXT]) VALUES (NULL, NULL, NULL, NULL, N'A014199', N'Incmng Clring- CITI BANK PLN POLAND')
INSERT [dbo].[AM_GL_HIERARCHY] ([GL_L1], [GL_L2], [GL_L3], [GL_L4], [GL_ACCT], [GL_TXT]) VALUES (NULL, NULL, NULL, NULL, N'A014203', N'Incmng Clring- CITI BANK HUF HUNGARY')
INSERT [dbo].[AM_GL_HIERARCHY] ([GL_L1], [GL_L2], [GL_L3], [GL_L4], [GL_ACCT], [GL_TXT]) VALUES (NULL, NULL, NULL, NULL, N'A014204', N'Incmng Clring- CITI BANK CZK Czech')
INSERT [dbo].[AM_GL_HIERARCHY] ([GL_L1], [GL_L2], [GL_L3], [GL_L4], [GL_ACCT], [GL_TXT]) VALUES (NULL, NULL, NULL, NULL, N'A014206', N'Incmng Clring- CITI BANK EUR Slovakia')
INSERT [dbo].[AM_GL_HIERARCHY] ([GL_L1], [GL_L2], [GL_L3], [GL_L4], [GL_ACCT], [GL_TXT]) VALUES (NULL, NULL, NULL, NULL, N'A014207', N'Incmng Clring- CITI BANK RON ROMANIA')
INSERT [dbo].[AM_GL_HIERARCHY] ([GL_L1], [GL_L2], [GL_L3], [GL_L4], [GL_ACCT], [GL_TXT]) VALUES (NULL, NULL, NULL, NULL, N'A014212', N'Incmng Clring- CITI Belgium (EUR)')
INSERT [dbo].[AM_GL_HIERARCHY] ([GL_L1], [GL_L2], [GL_L3], [GL_L4], [GL_ACCT], [GL_TXT]) VALUES (NULL, NULL, NULL, NULL, N'A014214', N'Incmng Clring- CITI Amsterdam (EUR)')
INSERT [dbo].[AM_GL_HIERARCHY] ([GL_L1], [GL_L2], [GL_L3], [GL_L4], [GL_ACCT], [GL_TXT]) VALUES (NULL, NULL, NULL, NULL, N'A014215', N'Incmng Clring- CITI UK (GBP)')
INSERT [dbo].[AM_GL_HIERARCHY] ([GL_L1], [GL_L2], [GL_L3], [GL_L4], [GL_ACCT], [GL_TXT]) VALUES (NULL, NULL, NULL, NULL, N'A014216', N'Incmng Clring- CITI IRELAND (EUR)')
INSERT [dbo].[AM_GL_HIERARCHY] ([GL_L1], [GL_L2], [GL_L3], [GL_L4], [GL_ACCT], [GL_TXT]) VALUES (NULL, NULL, NULL, NULL, N'A014245', N'Incmng Clring- CITIBANK PAYROLL RON')
INSERT [dbo].[AM_GL_HIERARCHY] ([GL_L1], [GL_L2], [GL_L3], [GL_L4], [GL_ACCT], [GL_TXT]) VALUES (NULL, NULL, NULL, NULL, N'A014247', N'Incmng Clring- CITIBANK NL Payroll EUR')
INSERT [dbo].[AM_GL_HIERARCHY] ([GL_L1], [GL_L2], [GL_L3], [GL_L4], [GL_ACCT], [GL_TXT]) VALUES (NULL, NULL, NULL, NULL, N'A014248', N'Incmng Clring- CITIBANK SEK')
INSERT [dbo].[AM_GL_HIERARCHY] ([GL_L1], [GL_L2], [GL_L3], [GL_L4], [GL_ACCT], [GL_TXT]) VALUES (NULL, NULL, NULL, NULL, N'A014259', N'Citibank Norway(Tax)-SEU-NO3383011018540-NOK-InClr')
INSERT [dbo].[AM_GL_HIERARCHY] ([GL_L1], [GL_L2], [GL_L3], [GL_L4], [GL_ACCT], [GL_TXT]) VALUES (NULL, NULL, NULL, NULL, N'A014272', N'Incmng Clring- Citibank BGN')
INSERT [dbo].[AM_GL_HIERARCHY] ([GL_L1], [GL_L2], [GL_L3], [GL_L4], [GL_ACCT], [GL_TXT]) VALUES (NULL, NULL, NULL, NULL, N'A014274', N'Citibank Norway-SEU-NO1683011010698-NOK-InClr')
INSERT [dbo].[AM_GL_HIERARCHY] ([GL_L1], [GL_L2], [GL_L3], [GL_L4], [GL_ACCT], [GL_TXT]) VALUES (NULL, NULL, NULL, NULL, N'A014277', N'Citi Denmark-Payroll-DKK-InClr')
INSERT [dbo].[AM_GL_HIERARCHY] ([GL_L1], [GL_L2], [GL_L3], [GL_L4], [GL_ACCT], [GL_TXT]) VALUES (NULL, NULL, NULL, NULL, N'A014278', N'Citi - Sony Europe BV -EUR-InClr')
INSERT [dbo].[AM_GL_HIERARCHY] ([GL_L1], [GL_L2], [GL_L3], [GL_L4], [GL_ACCT], [GL_TXT]) VALUES (NULL, NULL, NULL, NULL, N'A014280', N'Citi Receivables - Sony Europe BV Chgs - EUR-InClr')
INSERT [dbo].[AM_GL_HIERARCHY] ([GL_L1], [GL_L2], [GL_L3], [GL_L4], [GL_ACCT], [GL_TXT]) VALUES (NULL, NULL, NULL, NULL, N'A014283', N'Citibank Sony Europe B.V. Portugal Local (Incoming')
INSERT [dbo].[AM_GL_HIERARCHY] ([GL_L1], [GL_L2], [GL_L3], [GL_L4], [GL_ACCT], [GL_TXT]) VALUES (NULL, NULL, NULL, NULL, N'A014300', N'Incoming Clearing- RAS ACCOUNT SEK')
INSERT [dbo].[AM_GL_HIERARCHY] ([GL_L1], [GL_L2], [GL_L3], [GL_L4], [GL_ACCT], [GL_TXT]) VALUES (NULL, NULL, NULL, NULL, N'A014302', N'Incoming Clearing- RAS ACCOUNT EUR')
INSERT [dbo].[AM_GL_HIERARCHY] ([GL_L1], [GL_L2], [GL_L3], [GL_L4], [GL_ACCT], [GL_TXT]) VALUES (NULL, NULL, NULL, NULL, N'A014303', N'Incoming Clearing- RAS ACCOUNT PLN')
INSERT [dbo].[AM_GL_HIERARCHY] ([GL_L1], [GL_L2], [GL_L3], [GL_L4], [GL_ACCT], [GL_TXT]) VALUES (NULL, NULL, NULL, NULL, N'A014305', N'Incoming Clearing- RAS ACCOUNT HUF')
INSERT [dbo].[AM_GL_HIERARCHY] ([GL_L1], [GL_L2], [GL_L3], [GL_L4], [GL_ACCT], [GL_TXT]) VALUES (NULL, NULL, NULL, NULL, N'A014306', N'Incoming Clearing- RAS ACCOUNT GBP')
INSERT [dbo].[AM_GL_HIERARCHY] ([GL_L1], [GL_L2], [GL_L3], [GL_L4], [GL_ACCT], [GL_TXT]) VALUES (NULL, NULL, NULL, NULL, N'A014311', N'Incoming Clearing- RAS ACCOUNT NOK')
INSERT [dbo].[AM_GL_HIERARCHY] ([GL_L1], [GL_L2], [GL_L3], [GL_L4], [GL_ACCT], [GL_TXT]) VALUES (NULL, NULL, NULL, NULL, N'A014312', N'Incoming Clearing- RAS ACCOUNT CZK')
INSERT [dbo].[AM_GL_HIERARCHY] ([GL_L1], [GL_L2], [GL_L3], [GL_L4], [GL_ACCT], [GL_TXT]) VALUES (NULL, NULL, NULL, NULL, N'A021010', N'Products- Merchandise & Finished goods- SAP main')
INSERT [dbo].[AM_GL_HIERARCHY] ([GL_L1], [GL_L2], [GL_L3], [GL_L4], [GL_ACCT], [GL_TXT]) VALUES (NULL, NULL, NULL, NULL, N'A021015', N'Products- Merchandise & FG- direct GL entry OIM')
INSERT [dbo].[AM_GL_HIERARCHY] ([GL_L1], [GL_L2], [GL_L3], [GL_L4], [GL_ACCT], [GL_TXT]) VALUES (NULL, NULL, NULL, NULL, N'A021060', N'Products- Merchandise & Finished goods- SAB104')
INSERT [dbo].[AM_GL_HIERARCHY] ([GL_L1], [GL_L2], [GL_L3], [GL_L4], [GL_ACCT], [GL_TXT]) VALUES (NULL, NULL, NULL, NULL, N'A024015', N'WIP- WBS required')
INSERT [dbo].[AM_GL_HIERARCHY] ([GL_L1], [GL_L2], [GL_L3], [GL_L4], [GL_ACCT], [GL_TXT]) VALUES (NULL, NULL, NULL, NULL, N'A024020', N'WIP- direct GL entry- system service')
INSERT [dbo].[AM_GL_HIERARCHY] ([GL_L1], [GL_L2], [GL_L3], [GL_L4], [GL_ACCT], [GL_TXT]) VALUES (NULL, NULL, NULL, NULL, N'A031040', N'Prepaid exps- Deferred Extended Warranty Exp')
INSERT [dbo].[AM_GL_HIERARCHY] ([GL_L1], [GL_L2], [GL_L3], [GL_L4], [GL_ACCT], [GL_TXT]) VALUES (NULL, NULL, NULL, NULL, N'A031050', N'Prepaid exps- Non income tax')
INSERT [dbo].[AM_GL_HIERARCHY] ([GL_L1], [GL_L2], [GL_L3], [GL_L4], [GL_ACCT], [GL_TXT]) VALUES (NULL, NULL, NULL, NULL, N'A032010', N'Other account receivable-current- General')
INSERT [dbo].[AM_GL_HIERARCHY] ([GL_L1], [GL_L2], [GL_L3], [GL_L4], [GL_ACCT], [GL_TXT]) VALUES (NULL, NULL, NULL, NULL, N'A032850', N'Other AR-current- direct GL entry- OIM')
INSERT [dbo].[AM_GL_HIERARCHY] ([GL_L1], [GL_L2], [GL_L3], [GL_L4], [GL_ACCT], [GL_TXT]) VALUES (NULL, NULL, NULL, NULL, N'A033010', N'Short term loan- General')
INSERT [dbo].[AM_GL_HIERARCHY] ([GL_L1], [GL_L2], [GL_L3], [GL_L4], [GL_ACCT], [GL_TXT]) VALUES (NULL, NULL, NULL, NULL, N'A034010', N'Adv paymts- General')
INSERT [dbo].[AM_GL_HIERARCHY] ([GL_L1], [GL_L2], [GL_L3], [GL_L4], [GL_ACCT], [GL_TXT]) VALUES (NULL, NULL, NULL, NULL, N'A035901', N'Expense to be recharged- Other2')
INSERT [dbo].[AM_GL_HIERARCHY] ([GL_L1], [GL_L2], [GL_L3], [GL_L4], [GL_ACCT], [GL_TXT]) VALUES (NULL, NULL, NULL, NULL, N'A038010', N'VAT-receivable on purchase- general')
INSERT [dbo].[AM_GL_HIERARCHY] ([GL_L1], [GL_L2], [GL_L3], [GL_L4], [GL_ACCT], [GL_TXT]) VALUES (NULL, NULL, NULL, NULL, N'A038020', N'VAT-receivable- on purchase- direct GL entry')
INSERT [dbo].[AM_GL_HIERARCHY] ([GL_L1], [GL_L2], [GL_L3], [GL_L4], [GL_ACCT], [GL_TXT]) VALUES (NULL, NULL, NULL, NULL, N'A038030', N'VAT-receivable- on purchase- FI interface')
INSERT [dbo].[AM_GL_HIERARCHY] ([GL_L1], [GL_L2], [GL_L3], [GL_L4], [GL_ACCT], [GL_TXT]) VALUES (NULL, NULL, NULL, NULL, N'A038050', N'VAT-receivable- Purch service VAT claim')
INSERT [dbo].[AM_GL_HIERARCHY] ([GL_L1], [GL_L2], [GL_L3], [GL_L4], [GL_ACCT], [GL_TXT]) VALUES (NULL, NULL, NULL, NULL, N'A038150', N'VAT-receivable (clearing) DE')
INSERT [dbo].[AM_GL_HIERARCHY] ([GL_L1], [GL_L2], [GL_L3], [GL_L4], [GL_ACCT], [GL_TXT]) VALUES (NULL, NULL, NULL, NULL, N'A038155', N'VAT-receivable (clearing) DE - OSS')
INSERT [dbo].[AM_GL_HIERARCHY] ([GL_L1], [GL_L2], [GL_L3], [GL_L4], [GL_ACCT], [GL_TXT]) VALUES (NULL, NULL, NULL, NULL, N'A038190', N'VAT-receivable (clearing) FI')
INSERT [dbo].[AM_GL_HIERARCHY] ([GL_L1], [GL_L2], [GL_L3], [GL_L4], [GL_ACCT], [GL_TXT]) VALUES (NULL, NULL, NULL, NULL, N'A038200', N'VAT-receivable (clearing) GB')
INSERT [dbo].[AM_GL_HIERARCHY] ([GL_L1], [GL_L2], [GL_L3], [GL_L4], [GL_ACCT], [GL_TXT]) VALUES (NULL, NULL, NULL, NULL, N'A038220', N'VAT-receivable (clearing) HU')
INSERT [dbo].[AM_GL_HIERARCHY] ([GL_L1], [GL_L2], [GL_L3], [GL_L4], [GL_ACCT], [GL_TXT]) VALUES (NULL, NULL, NULL, NULL, N'A038260', N'VAT-receivable (clearing) NL')
INSERT [dbo].[AM_GL_HIERARCHY] ([GL_L1], [GL_L2], [GL_L3], [GL_L4], [GL_ACCT], [GL_TXT]) VALUES (NULL, NULL, NULL, NULL, N'A038270', N'VAT-receivable (clearing) NO')
INSERT [dbo].[AM_GL_HIERARCHY] ([GL_L1], [GL_L2], [GL_L3], [GL_L4], [GL_ACCT], [GL_TXT]) VALUES (NULL, NULL, NULL, NULL, N'A038310', N'VAT-receivable (clearing) SE')
INSERT [dbo].[AM_GL_HIERARCHY] ([GL_L1], [GL_L2], [GL_L3], [GL_L4], [GL_ACCT], [GL_TXT]) VALUES (NULL, NULL, NULL, NULL, N'A114010', N'M&E- at cost- General')
INSERT [dbo].[AM_GL_HIERARCHY] ([GL_L1], [GL_L2], [GL_L3], [GL_L4], [GL_ACCT], [GL_TXT]) VALUES (NULL, NULL, NULL, NULL, N'A116010', N'Furniture & fixtures- at cost- General')
INSERT [dbo].[AM_GL_HIERARCHY] ([GL_L1], [GL_L2], [GL_L3], [GL_L4], [GL_ACCT], [GL_TXT]) VALUES (NULL, NULL, NULL, NULL, N'A117010', N'Vehicles- at cost- General')
INSERT [dbo].[AM_GL_HIERARCHY] ([GL_L1], [GL_L2], [GL_L3], [GL_L4], [GL_ACCT], [GL_TXT]) VALUES (NULL, NULL, NULL, NULL, N'A119200', N'Construction in Progress- Assets interim account')
INSERT [dbo].[AM_GL_HIERARCHY] ([GL_L1], [GL_L2], [GL_L3], [GL_L4], [GL_ACCT], [GL_TXT]) VALUES (NULL, NULL, NULL, NULL, N'A196001', N'Special GL transactions- Vendors noted items')
INSERT [dbo].[AM_GL_HIERARCHY] ([GL_L1], [GL_L2], [GL_L3], [GL_L4], [GL_ACCT], [GL_TXT]) VALUES (NULL, NULL, NULL, NULL, N'A212010', N'Trade AP- General')
INSERT [dbo].[AM_GL_HIERARCHY] ([GL_L1], [GL_L2], [GL_L3], [GL_L4], [GL_ACCT], [GL_TXT]) VALUES (NULL, NULL, NULL, NULL, N'A212100', N'Trade AP- invoice to be received- GRIR 1')
INSERT [dbo].[AM_GL_HIERARCHY] ([GL_L1], [GL_L2], [GL_L3], [GL_L4], [GL_ACCT], [GL_TXT]) VALUES (NULL, NULL, NULL, NULL, N'A212850', N'Trade AP- direct GL entry- OIM')
INSERT [dbo].[AM_GL_HIERARCHY] ([GL_L1], [GL_L2], [GL_L3], [GL_L4], [GL_ACCT], [GL_TXT]) VALUES (NULL, NULL, NULL, NULL, N'A215010', N'AP-non trade- General')
INSERT [dbo].[AM_GL_HIERARCHY] ([GL_L1], [GL_L2], [GL_L3], [GL_L4], [GL_ACCT], [GL_TXT]) VALUES (NULL, NULL, NULL, NULL, N'A215020', N'AP-non trade- Salaries and wages to be paid')
INSERT [dbo].[AM_GL_HIERARCHY] ([GL_L1], [GL_L2], [GL_L3], [GL_L4], [GL_ACCT], [GL_TXT]) VALUES (NULL, NULL, NULL, NULL, N'A215021', N'AP-non trade- Pension to be paid')
INSERT [dbo].[AM_GL_HIERARCHY] ([GL_L1], [GL_L2], [GL_L3], [GL_L4], [GL_ACCT], [GL_TXT]) VALUES (NULL, NULL, NULL, NULL, N'A215025', N'AP-Non trade - S&W Social Security tax')
INSERT [dbo].[AM_GL_HIERARCHY] ([GL_L1], [GL_L2], [GL_L3], [GL_L4], [GL_ACCT], [GL_TXT]) VALUES (NULL, NULL, NULL, NULL, N'A215040', N'AP-non trade- Other employee related costs')
INSERT [dbo].[AM_GL_HIERARCHY] ([GL_L1], [GL_L2], [GL_L3], [GL_L4], [GL_ACCT], [GL_TXT]) VALUES (NULL, NULL, NULL, NULL, N'A215070', N'AP-non trade- invoice to be received- GRIR')
INSERT [dbo].[AM_GL_HIERARCHY] ([GL_L1], [GL_L2], [GL_L3], [GL_L4], [GL_ACCT], [GL_TXT]) VALUES (NULL, NULL, NULL, NULL, N'A215071', N'AP-non trade- invoice to be received- GRIR SRM')
INSERT [dbo].[AM_GL_HIERARCHY] ([GL_L1], [GL_L2], [GL_L3], [GL_L4], [GL_ACCT], [GL_TXT]) VALUES (NULL, NULL, NULL, NULL, N'A215114', N'Outgng Clring- INTESA S.PAOLO EUR IT(RAS23)')
INSERT [dbo].[AM_GL_HIERARCHY] ([GL_L1], [GL_L2], [GL_L3], [GL_L4], [GL_ACCT], [GL_TXT]) VALUES (NULL, NULL, NULL, NULL, N'A215134', N'Outgng Clring- SCSE INTESA BAM BA (RAS22)')
INSERT [dbo].[AM_GL_HIERARCHY] ([GL_L1], [GL_L2], [GL_L3], [GL_L4], [GL_ACCT], [GL_TXT]) VALUES (NULL, NULL, NULL, NULL, N'A215143', N'Outgng Clring- INTESA RSD SER (SCSE) NEW')
INSERT [dbo].[AM_GL_HIERARCHY] ([GL_L1], [GL_L2], [GL_L3], [GL_L4], [GL_ACCT], [GL_TXT]) VALUES (NULL, NULL, NULL, NULL, N'A215172', N'Outgng Clring- CITI BANK SEU CH CHF')
INSERT [dbo].[AM_GL_HIERARCHY] ([GL_L1], [GL_L2], [GL_L3], [GL_L4], [GL_ACCT], [GL_TXT]) VALUES (NULL, NULL, NULL, NULL, N'A215176', N'Outgng Clring- CITI BANK SONY EUROPE AT EUR')
INSERT [dbo].[AM_GL_HIERARCHY] ([GL_L1], [GL_L2], [GL_L3], [GL_L4], [GL_ACCT], [GL_TXT]) VALUES (NULL, NULL, NULL, NULL, N'A215181', N'Outgng Clring- CITI BANK SES GBP')
INSERT [dbo].[AM_GL_HIERARCHY] ([GL_L1], [GL_L2], [GL_L3], [GL_L4], [GL_ACCT], [GL_TXT]) VALUES (NULL, NULL, NULL, NULL, N'A215185', N'Outgng Clring- CITI BANK GERMANY EUR')
INSERT [dbo].[AM_GL_HIERARCHY] ([GL_L1], [GL_L2], [GL_L3], [GL_L4], [GL_ACCT], [GL_TXT]) VALUES (NULL, NULL, NULL, NULL, N'A215186', N'Outgng Clring- CITI BANK SSS EUR')
INSERT [dbo].[AM_GL_HIERARCHY] ([GL_L1], [GL_L2], [GL_L3], [GL_L4], [GL_ACCT], [GL_TXT]) VALUES (NULL, NULL, NULL, NULL, N'A215190', N'Outgng Clring- CITI BANK EUR ITALY')
INSERT [dbo].[AM_GL_HIERARCHY] ([GL_L1], [GL_L2], [GL_L3], [GL_L4], [GL_ACCT], [GL_TXT]) VALUES (NULL, NULL, NULL, NULL, N'A215191', N'Outgng Clring- CITI BANK EUR FRANCE')
INSERT [dbo].[AM_GL_HIERARCHY] ([GL_L1], [GL_L2], [GL_L3], [GL_L4], [GL_ACCT], [GL_TXT]) VALUES (NULL, NULL, NULL, NULL, N'A215196', N'Outgng Clring- CITI BANK EUR SPAIN')
INSERT [dbo].[AM_GL_HIERARCHY] ([GL_L1], [GL_L2], [GL_L3], [GL_L4], [GL_ACCT], [GL_TXT]) VALUES (NULL, NULL, NULL, NULL, N'A215197', N'Outgng Clring- CITI BANK EUR PORTUGAL')
INSERT [dbo].[AM_GL_HIERARCHY] ([GL_L1], [GL_L2], [GL_L3], [GL_L4], [GL_ACCT], [GL_TXT]) VALUES (NULL, NULL, NULL, NULL, N'A215199', N'Outgng Clring- CITI BANK PLN POLAND')
INSERT [dbo].[AM_GL_HIERARCHY] ([GL_L1], [GL_L2], [GL_L3], [GL_L4], [GL_ACCT], [GL_TXT]) VALUES (NULL, NULL, NULL, NULL, N'A215212', N'Outgng Clring- CITI Belgium (EUR)')
INSERT [dbo].[AM_GL_HIERARCHY] ([GL_L1], [GL_L2], [GL_L3], [GL_L4], [GL_ACCT], [GL_TXT]) VALUES (NULL, NULL, NULL, NULL, N'A215214', N'Outgng Clring- CITI Amsterdam (EUR)')
INSERT [dbo].[AM_GL_HIERARCHY] ([GL_L1], [GL_L2], [GL_L3], [GL_L4], [GL_ACCT], [GL_TXT]) VALUES (NULL, NULL, NULL, NULL, N'A215215', N'Outgng Clring- CITI UK (GBP)')
INSERT [dbo].[AM_GL_HIERARCHY] ([GL_L1], [GL_L2], [GL_L3], [GL_L4], [GL_ACCT], [GL_TXT]) VALUES (NULL, NULL, NULL, NULL, N'A215216', N'Outgng Clring- CITI IRELAND (EUR)')
INSERT [dbo].[AM_GL_HIERARCHY] ([GL_L1], [GL_L2], [GL_L3], [GL_L4], [GL_ACCT], [GL_TXT]) VALUES (NULL, NULL, NULL, NULL, N'A215248', N'Outgng Clring- CITIBANK SEK')
INSERT [dbo].[AM_GL_HIERARCHY] ([GL_L1], [GL_L2], [GL_L3], [GL_L4], [GL_ACCT], [GL_TXT]) VALUES (NULL, NULL, NULL, NULL, N'A215272', N'Outgng Clring- Citibank BGN')
INSERT [dbo].[AM_GL_HIERARCHY] ([GL_L1], [GL_L2], [GL_L3], [GL_L4], [GL_ACCT], [GL_TXT]) VALUES (NULL, NULL, NULL, NULL, N'A215280', N'Citi Receivables - Sony Europe BV Chgs - EUR-OutCl')
INSERT [dbo].[AM_GL_HIERARCHY] ([GL_L1], [GL_L2], [GL_L3], [GL_L4], [GL_ACCT], [GL_TXT]) VALUES (NULL, NULL, NULL, NULL, N'A215300', N'Outgoing Clearing- RAS ACCOUNT SEK')
GO
INSERT [dbo].[AM_GL_HIERARCHY] ([GL_L1], [GL_L2], [GL_L3], [GL_L4], [GL_ACCT], [GL_TXT]) VALUES (NULL, NULL, NULL, NULL, N'A215302', N'Outgoing Clearing- RAS ACCOUNT EUR')
INSERT [dbo].[AM_GL_HIERARCHY] ([GL_L1], [GL_L2], [GL_L3], [GL_L4], [GL_ACCT], [GL_TXT]) VALUES (NULL, NULL, NULL, NULL, N'A215303', N'Outgoing Clearing- RAS ACCOUNT PLN')
INSERT [dbo].[AM_GL_HIERARCHY] ([GL_L1], [GL_L2], [GL_L3], [GL_L4], [GL_ACCT], [GL_TXT]) VALUES (NULL, NULL, NULL, NULL, N'A215304', N'Outgoing Clearing- RAS ACCOUNT RON')
INSERT [dbo].[AM_GL_HIERARCHY] ([GL_L1], [GL_L2], [GL_L3], [GL_L4], [GL_ACCT], [GL_TXT]) VALUES (NULL, NULL, NULL, NULL, N'A215305', N'Outgoing Clearing- RAS ACCOUNT HUF')
INSERT [dbo].[AM_GL_HIERARCHY] ([GL_L1], [GL_L2], [GL_L3], [GL_L4], [GL_ACCT], [GL_TXT]) VALUES (NULL, NULL, NULL, NULL, N'A215306', N'Outgoing Clearing- RAS ACCOUNT GBP')
INSERT [dbo].[AM_GL_HIERARCHY] ([GL_L1], [GL_L2], [GL_L3], [GL_L4], [GL_ACCT], [GL_TXT]) VALUES (NULL, NULL, NULL, NULL, N'A215307', N'Outgoing Clearing- RAS ACCOUNT USD')
INSERT [dbo].[AM_GL_HIERARCHY] ([GL_L1], [GL_L2], [GL_L3], [GL_L4], [GL_ACCT], [GL_TXT]) VALUES (NULL, NULL, NULL, NULL, N'A215308', N'Outgoing Clearing- RAS ACCOUNT DKK')
INSERT [dbo].[AM_GL_HIERARCHY] ([GL_L1], [GL_L2], [GL_L3], [GL_L4], [GL_ACCT], [GL_TXT]) VALUES (NULL, NULL, NULL, NULL, N'A215309', N'Outgoing Clearing- RAS ACCOUNT JPY')
INSERT [dbo].[AM_GL_HIERARCHY] ([GL_L1], [GL_L2], [GL_L3], [GL_L4], [GL_ACCT], [GL_TXT]) VALUES (NULL, NULL, NULL, NULL, N'A215310', N'Outgoing Clearing- RAS ACCOUNT CHF')
INSERT [dbo].[AM_GL_HIERARCHY] ([GL_L1], [GL_L2], [GL_L3], [GL_L4], [GL_ACCT], [GL_TXT]) VALUES (NULL, NULL, NULL, NULL, N'A215311', N'Outgoing Clearing- RAS ACCOUNT NOK')
INSERT [dbo].[AM_GL_HIERARCHY] ([GL_L1], [GL_L2], [GL_L3], [GL_L4], [GL_ACCT], [GL_TXT]) VALUES (NULL, NULL, NULL, NULL, N'A215312', N'Outgoing Clearing- RAS ACCOUNT CZK')
INSERT [dbo].[AM_GL_HIERARCHY] ([GL_L1], [GL_L2], [GL_L3], [GL_L4], [GL_ACCT], [GL_TXT]) VALUES (NULL, NULL, NULL, NULL, N'A215314', N'Outgoing Clearing- RAS ACCOUNT TRY')
INSERT [dbo].[AM_GL_HIERARCHY] ([GL_L1], [GL_L2], [GL_L3], [GL_L4], [GL_ACCT], [GL_TXT]) VALUES (NULL, NULL, NULL, NULL, N'A215400', N'Concur Global Pay')
INSERT [dbo].[AM_GL_HIERARCHY] ([GL_L1], [GL_L2], [GL_L3], [GL_L4], [GL_ACCT], [GL_TXT]) VALUES (NULL, NULL, NULL, NULL, N'A215850', N'Other AP-non trade- direct GL entry- OIM')
INSERT [dbo].[AM_GL_HIERARCHY] ([GL_L1], [GL_L2], [GL_L3], [GL_L4], [GL_ACCT], [GL_TXT]) VALUES (NULL, NULL, NULL, NULL, N'A216010', N'Accrd exps- Copyright levies')
INSERT [dbo].[AM_GL_HIERARCHY] ([GL_L1], [GL_L2], [GL_L3], [GL_L4], [GL_ACCT], [GL_TXT]) VALUES (NULL, NULL, NULL, NULL, N'A216020', N'Accrd exps- Packaging levies')
INSERT [dbo].[AM_GL_HIERARCHY] ([GL_L1], [GL_L2], [GL_L3], [GL_L4], [GL_ACCT], [GL_TXT]) VALUES (NULL, NULL, NULL, NULL, N'A216030', N'Accrd exps- Battery levies')
INSERT [dbo].[AM_GL_HIERARCHY] ([GL_L1], [GL_L2], [GL_L3], [GL_L4], [GL_ACCT], [GL_TXT]) VALUES (NULL, NULL, NULL, NULL, N'A216040', N'Accrd exps, Chemical Tax levies')
INSERT [dbo].[AM_GL_HIERARCHY] ([GL_L1], [GL_L2], [GL_L3], [GL_L4], [GL_ACCT], [GL_TXT]) VALUES (NULL, NULL, NULL, NULL, N'A216101', N'AE- SR- Co-op AD(MDF)- AAC')
INSERT [dbo].[AM_GL_HIERARCHY] ([GL_L1], [GL_L2], [GL_L3], [GL_L4], [GL_ACCT], [GL_TXT]) VALUES (NULL, NULL, NULL, NULL, N'A216102', N'AE- SR- Co-op AD(MDF)- Other #1')
INSERT [dbo].[AM_GL_HIERARCHY] ([GL_L1], [GL_L2], [GL_L3], [GL_L4], [GL_ACCT], [GL_TXT]) VALUES (NULL, NULL, NULL, NULL, N'A216134', N'AE- reduction- Spiff- TACT Channel')
INSERT [dbo].[AM_GL_HIERARCHY] ([GL_L1], [GL_L2], [GL_L3], [GL_L4], [GL_ACCT], [GL_TXT]) VALUES (NULL, NULL, NULL, NULL, N'A216136', N'AE- SR- Spiff- Other #1')
INSERT [dbo].[AM_GL_HIERARCHY] ([GL_L1], [GL_L2], [GL_L3], [GL_L4], [GL_ACCT], [GL_TXT]) VALUES (NULL, NULL, NULL, NULL, N'A216137', N'ACCRUED TACTICAL SALES OUT ALLOWANCES')
INSERT [dbo].[AM_GL_HIERARCHY] ([GL_L1], [GL_L2], [GL_L3], [GL_L4], [GL_ACCT], [GL_TXT]) VALUES (NULL, NULL, NULL, NULL, N'A216158', N'AE- SR- Vol Rebt- JBP value added reseller 2 tier')
INSERT [dbo].[AM_GL_HIERARCHY] ([GL_L1], [GL_L2], [GL_L3], [GL_L4], [GL_ACCT], [GL_TXT]) VALUES (NULL, NULL, NULL, NULL, N'A216159', N'AE- SR- Vol Rebate- JBP SERP')
INSERT [dbo].[AM_GL_HIERARCHY] ([GL_L1], [GL_L2], [GL_L3], [GL_L4], [GL_ACCT], [GL_TXT]) VALUES (NULL, NULL, NULL, NULL, N'A216164', N'AE- SR- Vol Rebate- Clearing accounts')
INSERT [dbo].[AM_GL_HIERARCHY] ([GL_L1], [GL_L2], [GL_L3], [GL_L4], [GL_ACCT], [GL_TXT]) VALUES (NULL, NULL, NULL, NULL, N'A216165', N'Accrd exps- Sales reduction- Volume Rebate- PSE')
INSERT [dbo].[AM_GL_HIERARCHY] ([GL_L1], [GL_L2], [GL_L3], [GL_L4], [GL_ACCT], [GL_TXT]) VALUES (NULL, NULL, NULL, NULL, N'A216230', N'Accrd exps- SR- Other manual price adj')
INSERT [dbo].[AM_GL_HIERARCHY] ([GL_L1], [GL_L2], [GL_L3], [GL_L4], [GL_ACCT], [GL_TXT]) VALUES (NULL, NULL, NULL, NULL, N'A216345', N'Accrd exps- Social security expense')
INSERT [dbo].[AM_GL_HIERARCHY] ([GL_L1], [GL_L2], [GL_L3], [GL_L4], [GL_ACCT], [GL_TXT]) VALUES (NULL, NULL, NULL, NULL, N'A216350', N'Accrd exps- Welfare expense')
INSERT [dbo].[AM_GL_HIERARCHY] ([GL_L1], [GL_L2], [GL_L3], [GL_L4], [GL_ACCT], [GL_TXT]) VALUES (NULL, NULL, NULL, NULL, N'A216410', N'Accrd exps- Reserve for royalty')
INSERT [dbo].[AM_GL_HIERARCHY] ([GL_L1], [GL_L2], [GL_L3], [GL_L4], [GL_ACCT], [GL_TXT]) VALUES (NULL, NULL, NULL, NULL, N'A216430', N'Accrd exps- WEEE directive')
INSERT [dbo].[AM_GL_HIERARCHY] ([GL_L1], [GL_L2], [GL_L3], [GL_L4], [GL_ACCT], [GL_TXT]) VALUES (NULL, NULL, NULL, NULL, N'A216440', N'Accrd exps- SGA freight')
INSERT [dbo].[AM_GL_HIERARCHY] ([GL_L1], [GL_L2], [GL_L3], [GL_L4], [GL_ACCT], [GL_TXT]) VALUES (NULL, NULL, NULL, NULL, N'A216450', N'Accrd exps- SGA storage')
INSERT [dbo].[AM_GL_HIERARCHY] ([GL_L1], [GL_L2], [GL_L3], [GL_L4], [GL_ACCT], [GL_TXT]) VALUES (NULL, NULL, NULL, NULL, N'A216460', N'Accrd exps- SGA sales commission- General')
INSERT [dbo].[AM_GL_HIERARCHY] ([GL_L1], [GL_L2], [GL_L3], [GL_L4], [GL_ACCT], [GL_TXT]) VALUES (NULL, NULL, NULL, NULL, N'A216461', N'Accrd exps- SGA sales commission- Int. sales force')
INSERT [dbo].[AM_GL_HIERARCHY] ([GL_L1], [GL_L2], [GL_L3], [GL_L4], [GL_ACCT], [GL_TXT]) VALUES (NULL, NULL, NULL, NULL, N'A216610', N'Liabilities for sales returns')
INSERT [dbo].[AM_GL_HIERARCHY] ([GL_L1], [GL_L2], [GL_L3], [GL_L4], [GL_ACCT], [GL_TXT]) VALUES (NULL, NULL, NULL, NULL, N'A216800', N'Accrd exps- COGS freight')
INSERT [dbo].[AM_GL_HIERARCHY] ([GL_L1], [GL_L2], [GL_L3], [GL_L4], [GL_ACCT], [GL_TXT]) VALUES (NULL, NULL, NULL, NULL, N'A216810', N'Accrd exps- COGS duty')
INSERT [dbo].[AM_GL_HIERARCHY] ([GL_L1], [GL_L2], [GL_L3], [GL_L4], [GL_ACCT], [GL_TXT]) VALUES (NULL, NULL, NULL, NULL, N'A216901', N'Accrd exps- Restructuring Accruals')
INSERT [dbo].[AM_GL_HIERARCHY] ([GL_L1], [GL_L2], [GL_L3], [GL_L4], [GL_ACCT], [GL_TXT]) VALUES (NULL, NULL, NULL, NULL, N'A216902', N'Accrd exps- Miscellaneous Inventory adjustments')
INSERT [dbo].[AM_GL_HIERARCHY] ([GL_L1], [GL_L2], [GL_L3], [GL_L4], [GL_ACCT], [GL_TXT]) VALUES (NULL, NULL, NULL, NULL, N'A216905', N'Accrued SGA - Lease liability accrued')
INSERT [dbo].[AM_GL_HIERARCHY] ([GL_L1], [GL_L2], [GL_L3], [GL_L4], [GL_ACCT], [GL_TXT]) VALUES (NULL, NULL, NULL, NULL, N'A216910', N'Accrd exps- Other- Bulk Invoice control account')
INSERT [dbo].[AM_GL_HIERARCHY] ([GL_L1], [GL_L2], [GL_L3], [GL_L4], [GL_ACCT], [GL_TXT]) VALUES (NULL, NULL, NULL, NULL, N'A216911', N'Accrd exps- Other- Bulk Invoice accrual account')
INSERT [dbo].[AM_GL_HIERARCHY] ([GL_L1], [GL_L2], [GL_L3], [GL_L4], [GL_ACCT], [GL_TXT]) VALUES (NULL, NULL, NULL, NULL, N'A220010', N'Tax payable on sales- General')
INSERT [dbo].[AM_GL_HIERARCHY] ([GL_L1], [GL_L2], [GL_L3], [GL_L4], [GL_ACCT], [GL_TXT]) VALUES (NULL, NULL, NULL, NULL, N'A231010', N'Income tax payable- National tax')
INSERT [dbo].[AM_GL_HIERARCHY] ([GL_L1], [GL_L2], [GL_L3], [GL_L4], [GL_ACCT], [GL_TXT]) VALUES (NULL, NULL, NULL, NULL, N'A231100', N'Income tax payable- Local tax')
INSERT [dbo].[AM_GL_HIERARCHY] ([GL_L1], [GL_L2], [GL_L3], [GL_L4], [GL_ACCT], [GL_TXT]) VALUES (NULL, NULL, NULL, NULL, N'A232030', N'Accrued other taxes- S&W Hol and Wel tax')
INSERT [dbo].[AM_GL_HIERARCHY] ([GL_L1], [GL_L2], [GL_L3], [GL_L4], [GL_ACCT], [GL_TXT]) VALUES (NULL, NULL, NULL, NULL, N'A232900', N'Accrued other taxes- Other1')
INSERT [dbo].[AM_GL_HIERARCHY] ([GL_L1], [GL_L2], [GL_L3], [GL_L4], [GL_ACCT], [GL_TXT]) VALUES (NULL, NULL, NULL, NULL, N'A273010', N'Other misc. CL- General')
INSERT [dbo].[AM_GL_HIERARCHY] ([GL_L1], [GL_L2], [GL_L3], [GL_L4], [GL_ACCT], [GL_TXT]) VALUES (NULL, NULL, NULL, NULL, N'A277020', N'Accrued pension exps- Reserve for other PRP')
INSERT [dbo].[AM_GL_HIERARCHY] ([GL_L1], [GL_L2], [GL_L3], [GL_L4], [GL_ACCT], [GL_TXT]) VALUES (NULL, NULL, NULL, NULL, N'A313020', N'Liability for DB&DC- Corporate pension fund(DB)')
INSERT [dbo].[AM_GL_HIERARCHY] ([GL_L1], [GL_L2], [GL_L3], [GL_L4], [GL_ACCT], [GL_TXT]) VALUES (NULL, NULL, NULL, NULL, N'A340040', N'Other non-curr liabilities- Severance')
INSERT [dbo].[AM_GL_HIERARCHY] ([GL_L1], [GL_L2], [GL_L3], [GL_L4], [GL_ACCT], [GL_TXT]) VALUES (NULL, NULL, NULL, NULL, N'A505010', N'COGS- Products')
INSERT [dbo].[AM_GL_HIERARCHY] ([GL_L1], [GL_L2], [GL_L3], [GL_L4], [GL_ACCT], [GL_TXT]) VALUES (NULL, NULL, NULL, NULL, N'A505030', N'COGS- Other')
INSERT [dbo].[AM_GL_HIERARCHY] ([GL_L1], [GL_L2], [GL_L3], [GL_L4], [GL_ACCT], [GL_TXT]) VALUES (NULL, NULL, NULL, NULL, N'A505060', N'COGS- Inbound Duties and other fees')
INSERT [dbo].[AM_GL_HIERARCHY] ([GL_L1], [GL_L2], [GL_L3], [GL_L4], [GL_ACCT], [GL_TXT]) VALUES (NULL, NULL, NULL, NULL, N'A505070', N'COGS- Inbound Freight- Finished goods (Ship)')
INSERT [dbo].[AM_GL_HIERARCHY] ([GL_L1], [GL_L2], [GL_L3], [GL_L4], [GL_ACCT], [GL_TXT]) VALUES (NULL, NULL, NULL, NULL, N'A505073', N'COGC- Inbound Freight- Materials & Parts (Land)')
INSERT [dbo].[AM_GL_HIERARCHY] ([GL_L1], [GL_L2], [GL_L3], [GL_L4], [GL_ACCT], [GL_TXT]) VALUES (NULL, NULL, NULL, NULL, N'A531400', N'NOE- FX Translation losses')
INSERT [dbo].[AM_GL_HIERARCHY] ([GL_L1], [GL_L2], [GL_L3], [GL_L4], [GL_ACCT], [GL_TXT]) VALUES (NULL, NULL, NULL, NULL, N'A531900', N'NOE- Other1')
INSERT [dbo].[AM_GL_HIERARCHY] ([GL_L1], [GL_L2], [GL_L3], [GL_L4], [GL_ACCT], [GL_TXT]) VALUES (NULL, NULL, NULL, NULL, N'A622620', N'Sales reduction- Other manual price adj')
INSERT [dbo].[AM_GL_HIERARCHY] ([GL_L1], [GL_L2], [GL_L3], [GL_L4], [GL_ACCT], [GL_TXT]) VALUES (NULL, NULL, NULL, NULL, N'A631300', N'NOR- FX Translation gain')
INSERT [dbo].[AM_GL_HIERARCHY] ([GL_L1], [GL_L2], [GL_L3], [GL_L4], [GL_ACCT], [GL_TXT]) VALUES (NULL, NULL, NULL, NULL, N'A631900', N'NOR- Other1')
INSERT [dbo].[AM_GL_HIERARCHY] ([GL_L1], [GL_L2], [GL_L3], [GL_L4], [GL_ACCT], [GL_TXT]) VALUES (NULL, NULL, NULL, NULL, N'A702010', N'S&W- Base salaries')
INSERT [dbo].[AM_GL_HIERARCHY] ([GL_L1], [GL_L2], [GL_L3], [GL_L4], [GL_ACCT], [GL_TXT]) VALUES (NULL, NULL, NULL, NULL, N'A702210', N'S&W- Termination Pay')
INSERT [dbo].[AM_GL_HIERARCHY] ([GL_L1], [GL_L2], [GL_L3], [GL_L4], [GL_ACCT], [GL_TXT]) VALUES (NULL, NULL, NULL, NULL, N'A702900', N'S&W- Other1')
INSERT [dbo].[AM_GL_HIERARCHY] ([GL_L1], [GL_L2], [GL_L3], [GL_L4], [GL_ACCT], [GL_TXT]) VALUES (NULL, NULL, NULL, NULL, N'A703010', N'Bonuses & allowance- General')
INSERT [dbo].[AM_GL_HIERARCHY] ([GL_L1], [GL_L2], [GL_L3], [GL_L4], [GL_ACCT], [GL_TXT]) VALUES (NULL, NULL, NULL, NULL, N'A704010', N'Retirement bnf exps- Prov for retirement bnfs?DB?')
INSERT [dbo].[AM_GL_HIERARCHY] ([GL_L1], [GL_L2], [GL_L3], [GL_L4], [GL_ACCT], [GL_TXT]) VALUES (NULL, NULL, NULL, NULL, N'A704200', N'Retirement benefit exps-DC plans')
INSERT [dbo].[AM_GL_HIERARCHY] ([GL_L1], [GL_L2], [GL_L3], [GL_L4], [GL_ACCT], [GL_TXT]) VALUES (NULL, NULL, NULL, NULL, N'A705050', N'Social security- LOCAL WELFARE CONTRIBUTIONS')
INSERT [dbo].[AM_GL_HIERARCHY] ([GL_L1], [GL_L2], [GL_L3], [GL_L4], [GL_ACCT], [GL_TXT]) VALUES (NULL, NULL, NULL, NULL, N'A705051', N'Social security- LOCAL WELFARE TAXES S&W')
INSERT [dbo].[AM_GL_HIERARCHY] ([GL_L1], [GL_L2], [GL_L3], [GL_L4], [GL_ACCT], [GL_TXT]) VALUES (NULL, NULL, NULL, NULL, N'A706010', N'Welfare exps- Private Healthcare Insurance')
INSERT [dbo].[AM_GL_HIERARCHY] ([GL_L1], [GL_L2], [GL_L3], [GL_L4], [GL_ACCT], [GL_TXT]) VALUES (NULL, NULL, NULL, NULL, N'A706020', N'Welfare exps- Meals')
INSERT [dbo].[AM_GL_HIERARCHY] ([GL_L1], [GL_L2], [GL_L3], [GL_L4], [GL_ACCT], [GL_TXT]) VALUES (NULL, NULL, NULL, NULL, N'A706030', N'Welfare exps- Housing benefits')
INSERT [dbo].[AM_GL_HIERARCHY] ([GL_L1], [GL_L2], [GL_L3], [GL_L4], [GL_ACCT], [GL_TXT]) VALUES (NULL, NULL, NULL, NULL, N'A706040', N'Welfare exps, Relocation')
INSERT [dbo].[AM_GL_HIERARCHY] ([GL_L1], [GL_L2], [GL_L3], [GL_L4], [GL_ACCT], [GL_TXT]) VALUES (NULL, NULL, NULL, NULL, N'A706400', N'Welfare expenses – Mobility')
INSERT [dbo].[AM_GL_HIERARCHY] ([GL_L1], [GL_L2], [GL_L3], [GL_L4], [GL_ACCT], [GL_TXT]) VALUES (NULL, NULL, NULL, NULL, N'A706900', N'Welfare - Misc Employee Benefits Welfare')
INSERT [dbo].[AM_GL_HIERARCHY] ([GL_L1], [GL_L2], [GL_L3], [GL_L4], [GL_ACCT], [GL_TXT]) VALUES (NULL, NULL, NULL, NULL, N'A706901', N'Welfare - Misc Employee Benefits Other')
INSERT [dbo].[AM_GL_HIERARCHY] ([GL_L1], [GL_L2], [GL_L3], [GL_L4], [GL_ACCT], [GL_TXT]) VALUES (NULL, NULL, NULL, NULL, N'A709010', N'Stock-based compensation- General')
INSERT [dbo].[AM_GL_HIERARCHY] ([GL_L1], [GL_L2], [GL_L3], [GL_L4], [GL_ACCT], [GL_TXT]) VALUES (NULL, NULL, NULL, NULL, N'A711020', N'Freight- Finished goods freightage(Air)')
INSERT [dbo].[AM_GL_HIERARCHY] ([GL_L1], [GL_L2], [GL_L3], [GL_L4], [GL_ACCT], [GL_TXT]) VALUES (NULL, NULL, NULL, NULL, N'A711030', N'Freight- Finished goods freightage(Land)')
INSERT [dbo].[AM_GL_HIERARCHY] ([GL_L1], [GL_L2], [GL_L3], [GL_L4], [GL_ACCT], [GL_TXT]) VALUES (NULL, NULL, NULL, NULL, N'A711100', N'Freight- Finished goods Outbound Freight Insurance')
INSERT [dbo].[AM_GL_HIERARCHY] ([GL_L1], [GL_L2], [GL_L3], [GL_L4], [GL_ACCT], [GL_TXT]) VALUES (NULL, NULL, NULL, NULL, N'A711900', N'Freight- Other1')
INSERT [dbo].[AM_GL_HIERARCHY] ([GL_L1], [GL_L2], [GL_L3], [GL_L4], [GL_ACCT], [GL_TXT]) VALUES (NULL, NULL, NULL, NULL, N'A712010', N'Equipment- tools & software expensed- E&T')
INSERT [dbo].[AM_GL_HIERARCHY] ([GL_L1], [GL_L2], [GL_L3], [GL_L4], [GL_ACCT], [GL_TXT]) VALUES (NULL, NULL, NULL, NULL, N'A712100', N'Equipment- tools & software expensed- Soft')
INSERT [dbo].[AM_GL_HIERARCHY] ([GL_L1], [GL_L2], [GL_L3], [GL_L4], [GL_ACCT], [GL_TXT]) VALUES (NULL, NULL, NULL, NULL, N'A714010', N'Utilities exps- Electrical power')
INSERT [dbo].[AM_GL_HIERARCHY] ([GL_L1], [GL_L2], [GL_L3], [GL_L4], [GL_ACCT], [GL_TXT]) VALUES (NULL, NULL, NULL, NULL, N'A714030', N'Utilities exps- Gas charges')
INSERT [dbo].[AM_GL_HIERARCHY] ([GL_L1], [GL_L2], [GL_L3], [GL_L4], [GL_ACCT], [GL_TXT]) VALUES (NULL, NULL, NULL, NULL, N'A714900', N'Utilities exps- Other1')
INSERT [dbo].[AM_GL_HIERARCHY] ([GL_L1], [GL_L2], [GL_L3], [GL_L4], [GL_ACCT], [GL_TXT]) VALUES (NULL, NULL, NULL, NULL, N'A722010', N'R&T exps- Recruiting expense')
INSERT [dbo].[AM_GL_HIERARCHY] ([GL_L1], [GL_L2], [GL_L3], [GL_L4], [GL_ACCT], [GL_TXT]) VALUES (NULL, NULL, NULL, NULL, N'A722020', N'R&T exps- Training exps')
INSERT [dbo].[AM_GL_HIERARCHY] ([GL_L1], [GL_L2], [GL_L3], [GL_L4], [GL_ACCT], [GL_TXT]) VALUES (NULL, NULL, NULL, NULL, N'A723010', N'Travelling & commutation- Fare')
INSERT [dbo].[AM_GL_HIERARCHY] ([GL_L1], [GL_L2], [GL_L3], [GL_L4], [GL_ACCT], [GL_TXT]) VALUES (NULL, NULL, NULL, NULL, N'A723010N', N'Travelling & commutation- Fare (Non deductible)')
INSERT [dbo].[AM_GL_HIERARCHY] ([GL_L1], [GL_L2], [GL_L3], [GL_L4], [GL_ACCT], [GL_TXT]) VALUES (NULL, NULL, NULL, NULL, N'A723020', N'Travelling & commutation- Accommodation')
INSERT [dbo].[AM_GL_HIERARCHY] ([GL_L1], [GL_L2], [GL_L3], [GL_L4], [GL_ACCT], [GL_TXT]) VALUES (NULL, NULL, NULL, NULL, N'A723020N', N'Travelling & commutation- Accommodation (ND)')
INSERT [dbo].[AM_GL_HIERARCHY] ([GL_L1], [GL_L2], [GL_L3], [GL_L4], [GL_ACCT], [GL_TXT]) VALUES (NULL, NULL, NULL, NULL, N'A723030', N'Travelling & commutation- vehicle running exp')
INSERT [dbo].[AM_GL_HIERARCHY] ([GL_L1], [GL_L2], [GL_L3], [GL_L4], [GL_ACCT], [GL_TXT]) VALUES (NULL, NULL, NULL, NULL, N'A723030N', N'Travelling & commutation- vehicle running exp(ND)')
INSERT [dbo].[AM_GL_HIERARCHY] ([GL_L1], [GL_L2], [GL_L3], [GL_L4], [GL_ACCT], [GL_TXT]) VALUES (NULL, NULL, NULL, NULL, N'A723900', N'Travelling & commutation- Other1')
INSERT [dbo].[AM_GL_HIERARCHY] ([GL_L1], [GL_L2], [GL_L3], [GL_L4], [GL_ACCT], [GL_TXT]) VALUES (NULL, NULL, NULL, NULL, N'A725010', N'Commu exps- Postal exps')
INSERT [dbo].[AM_GL_HIERARCHY] ([GL_L1], [GL_L2], [GL_L3], [GL_L4], [GL_ACCT], [GL_TXT]) VALUES (NULL, NULL, NULL, NULL, N'A725020', N'Commu exps- Network and Land phone')
INSERT [dbo].[AM_GL_HIERARCHY] ([GL_L1], [GL_L2], [GL_L3], [GL_L4], [GL_ACCT], [GL_TXT]) VALUES (NULL, NULL, NULL, NULL, N'A725030', N'Commu exps- Cell phone')
GO
INSERT [dbo].[AM_GL_HIERARCHY] ([GL_L1], [GL_L2], [GL_L3], [GL_L4], [GL_ACCT], [GL_TXT]) VALUES (NULL, NULL, NULL, NULL, N'A725900', N'Commu exps- Other1')
INSERT [dbo].[AM_GL_HIERARCHY] ([GL_L1], [GL_L2], [GL_L3], [GL_L4], [GL_ACCT], [GL_TXT]) VALUES (NULL, NULL, NULL, NULL, N'A726010', N'Meals and Entmt exps- Meal')
INSERT [dbo].[AM_GL_HIERARCHY] ([GL_L1], [GL_L2], [GL_L3], [GL_L4], [GL_ACCT], [GL_TXT]) VALUES (NULL, NULL, NULL, NULL, N'A726030', N'Meals and Entmt exps- Gift (Non deductable)')
INSERT [dbo].[AM_GL_HIERARCHY] ([GL_L1], [GL_L2], [GL_L3], [GL_L4], [GL_ACCT], [GL_TXT]) VALUES (NULL, NULL, NULL, NULL, N'A726200N', N'Meals and Entmt exps- Gift (Non deductible)')
INSERT [dbo].[AM_GL_HIERARCHY] ([GL_L1], [GL_L2], [GL_L3], [GL_L4], [GL_ACCT], [GL_TXT]) VALUES (NULL, NULL, NULL, NULL, N'A726300', N'Meals and Entmt exps- Entmt')
INSERT [dbo].[AM_GL_HIERARCHY] ([GL_L1], [GL_L2], [GL_L3], [GL_L4], [GL_ACCT], [GL_TXT]) VALUES (NULL, NULL, NULL, NULL, N'A726300N', N'Meals and Entmt exps- Entmt (ND)')
INSERT [dbo].[AM_GL_HIERARCHY] ([GL_L1], [GL_L2], [GL_L3], [GL_L4], [GL_ACCT], [GL_TXT]) VALUES (NULL, NULL, NULL, NULL, N'A726310N', N'Meals and Entmt exps- Entmt- government  (ND)')
INSERT [dbo].[AM_GL_HIERARCHY] ([GL_L1], [GL_L2], [GL_L3], [GL_L4], [GL_ACCT], [GL_TXT]) VALUES (NULL, NULL, NULL, NULL, N'A731010', N'Insurance exps- Fire premiums on tangible FA')
INSERT [dbo].[AM_GL_HIERARCHY] ([GL_L1], [GL_L2], [GL_L3], [GL_L4], [GL_ACCT], [GL_TXT]) VALUES (NULL, NULL, NULL, NULL, N'A731900', N'Insurance exps- Other1')
INSERT [dbo].[AM_GL_HIERARCHY] ([GL_L1], [GL_L2], [GL_L3], [GL_L4], [GL_ACCT], [GL_TXT]) VALUES (NULL, NULL, NULL, NULL, N'A731901', N'Insurance exps, Vehicles')
INSERT [dbo].[AM_GL_HIERARCHY] ([GL_L1], [GL_L2], [GL_L3], [GL_L4], [GL_ACCT], [GL_TXT]) VALUES (NULL, NULL, NULL, NULL, N'A731910', N'Insurance exps- Stock in transit/transport')
INSERT [dbo].[AM_GL_HIERARCHY] ([GL_L1], [GL_L2], [GL_L3], [GL_L4], [GL_ACCT], [GL_TXT]) VALUES (NULL, NULL, NULL, NULL, N'A732010', N'Repair&maintenance exps- M&Es')
INSERT [dbo].[AM_GL_HIERARCHY] ([GL_L1], [GL_L2], [GL_L3], [GL_L4], [GL_ACCT], [GL_TXT]) VALUES (NULL, NULL, NULL, NULL, N'A732020', N'Repair&maintenance exps- Bld/LI/struc')
INSERT [dbo].[AM_GL_HIERARCHY] ([GL_L1], [GL_L2], [GL_L3], [GL_L4], [GL_ACCT], [GL_TXT]) VALUES (NULL, NULL, NULL, NULL, N'A732030', N'Repair&maintenance exps- Vehicles')
INSERT [dbo].[AM_GL_HIERARCHY] ([GL_L1], [GL_L2], [GL_L3], [GL_L4], [GL_ACCT], [GL_TXT]) VALUES (NULL, NULL, NULL, NULL, N'A732100', N'Repair&maintenance exps- In-company cleaning fee')
INSERT [dbo].[AM_GL_HIERARCHY] ([GL_L1], [GL_L2], [GL_L3], [GL_L4], [GL_ACCT], [GL_TXT]) VALUES (NULL, NULL, NULL, NULL, N'A732120', N'Repair&maintenance exps- Waste disposal fee')
INSERT [dbo].[AM_GL_HIERARCHY] ([GL_L1], [GL_L2], [GL_L3], [GL_L4], [GL_ACCT], [GL_TXT]) VALUES (NULL, NULL, NULL, NULL, N'A732130', N'Repair&maintenance exps- Security consignment fee')
INSERT [dbo].[AM_GL_HIERARCHY] ([GL_L1], [GL_L2], [GL_L3], [GL_L4], [GL_ACCT], [GL_TXT]) VALUES (NULL, NULL, NULL, NULL, N'A732140', N'Repair&maintenance exps- Relocation & removal exps')
INSERT [dbo].[AM_GL_HIERARCHY] ([GL_L1], [GL_L2], [GL_L3], [GL_L4], [GL_ACCT], [GL_TXT]) VALUES (NULL, NULL, NULL, NULL, N'A732150', N'Repair&maintenance exps- IS H/W Maintenance')
INSERT [dbo].[AM_GL_HIERARCHY] ([GL_L1], [GL_L2], [GL_L3], [GL_L4], [GL_ACCT], [GL_TXT]) VALUES (NULL, NULL, NULL, NULL, N'A732160', N'Repair&maintenance exps- IS S/W Maintenance')
INSERT [dbo].[AM_GL_HIERARCHY] ([GL_L1], [GL_L2], [GL_L3], [GL_L4], [GL_ACCT], [GL_TXT]) VALUES (NULL, NULL, NULL, NULL, N'A732900', N'Repair&maintenance exps- Other1')
INSERT [dbo].[AM_GL_HIERARCHY] ([GL_L1], [GL_L2], [GL_L3], [GL_L4], [GL_ACCT], [GL_TXT]) VALUES (NULL, NULL, NULL, NULL, N'A734010', N'Allowance for doubtful debts- General')
INSERT [dbo].[AM_GL_HIERARCHY] ([GL_L1], [GL_L2], [GL_L3], [GL_L4], [GL_ACCT], [GL_TXT]) VALUES (NULL, NULL, NULL, NULL, N'A741010', N'Donation- General')
INSERT [dbo].[AM_GL_HIERARCHY] ([GL_L1], [GL_L2], [GL_L3], [GL_L4], [GL_ACCT], [GL_TXT]) VALUES (NULL, NULL, NULL, NULL, N'A742010', N'misc. tax- Consumption tax')
INSERT [dbo].[AM_GL_HIERARCHY] ([GL_L1], [GL_L2], [GL_L3], [GL_L4], [GL_ACCT], [GL_TXT]) VALUES (NULL, NULL, NULL, NULL, N'A742020', N'misc. tax- Property tax')
INSERT [dbo].[AM_GL_HIERARCHY] ([GL_L1], [GL_L2], [GL_L3], [GL_L4], [GL_ACCT], [GL_TXT]) VALUES (NULL, NULL, NULL, NULL, N'A742030', N'misc. tax- Customs duty tariff')
INSERT [dbo].[AM_GL_HIERARCHY] ([GL_L1], [GL_L2], [GL_L3], [GL_L4], [GL_ACCT], [GL_TXT]) VALUES (NULL, NULL, NULL, NULL, N'A743010', N'Storage- Finished goods storage fee')
INSERT [dbo].[AM_GL_HIERARCHY] ([GL_L1], [GL_L2], [GL_L3], [GL_L4], [GL_ACCT], [GL_TXT]) VALUES (NULL, NULL, NULL, NULL, N'A743900', N'Storage- Other1')
INSERT [dbo].[AM_GL_HIERARCHY] ([GL_L1], [GL_L2], [GL_L3], [GL_L4], [GL_ACCT], [GL_TXT]) VALUES (NULL, NULL, NULL, NULL, N'A744010', N'misc. exps- membership fee')
INSERT [dbo].[AM_GL_HIERARCHY] ([GL_L1], [GL_L2], [GL_L3], [GL_L4], [GL_ACCT], [GL_TXT]) VALUES (NULL, NULL, NULL, NULL, N'A744020', N'misc. exps- Books & magazines')
INSERT [dbo].[AM_GL_HIERARCHY] ([GL_L1], [GL_L2], [GL_L3], [GL_L4], [GL_ACCT], [GL_TXT]) VALUES (NULL, NULL, NULL, NULL, N'A744020N', N'misc. exps- Books & magazines (ND)')
INSERT [dbo].[AM_GL_HIERARCHY] ([GL_L1], [GL_L2], [GL_L3], [GL_L4], [GL_ACCT], [GL_TXT]) VALUES (NULL, NULL, NULL, NULL, N'A744050', N'misc. exps- Bank commissions')
INSERT [dbo].[AM_GL_HIERARCHY] ([GL_L1], [GL_L2], [GL_L3], [GL_L4], [GL_ACCT], [GL_TXT]) VALUES (NULL, NULL, NULL, NULL, N'A744060', N'misc. exps- Compensation for damage')
INSERT [dbo].[AM_GL_HIERARCHY] ([GL_L1], [GL_L2], [GL_L3], [GL_L4], [GL_ACCT], [GL_TXT]) VALUES (NULL, NULL, NULL, NULL, N'A744080', N'misc. exps- Contractual penalties')
INSERT [dbo].[AM_GL_HIERARCHY] ([GL_L1], [GL_L2], [GL_L3], [GL_L4], [GL_ACCT], [GL_TXT]) VALUES (NULL, NULL, NULL, NULL, N'A744900', N'misc. exps- Other1')
INSERT [dbo].[AM_GL_HIERARCHY] ([GL_L1], [GL_L2], [GL_L3], [GL_L4], [GL_ACCT], [GL_TXT]) VALUES (NULL, NULL, NULL, NULL, N'A744900N', N'misc. exps- Other1 (Non deductible)')
INSERT [dbo].[AM_GL_HIERARCHY] ([GL_L1], [GL_L2], [GL_L3], [GL_L4], [GL_ACCT], [GL_TXT]) VALUES (NULL, NULL, NULL, NULL, N'A745010', N'Rent exps- Computers')
INSERT [dbo].[AM_GL_HIERARCHY] ([GL_L1], [GL_L2], [GL_L3], [GL_L4], [GL_ACCT], [GL_TXT]) VALUES (NULL, NULL, NULL, NULL, N'A745030N', N'Rent exps- Company housings (Non deductible)')
INSERT [dbo].[AM_GL_HIERARCHY] ([GL_L1], [GL_L2], [GL_L3], [GL_L4], [GL_ACCT], [GL_TXT]) VALUES (NULL, NULL, NULL, NULL, N'A745050', N'Rent exps- Parking lot exps')
INSERT [dbo].[AM_GL_HIERARCHY] ([GL_L1], [GL_L2], [GL_L3], [GL_L4], [GL_ACCT], [GL_TXT]) VALUES (NULL, NULL, NULL, NULL, N'A745070', N'Rent exps- Warehouse exps')
INSERT [dbo].[AM_GL_HIERARCHY] ([GL_L1], [GL_L2], [GL_L3], [GL_L4], [GL_ACCT], [GL_TXT]) VALUES (NULL, NULL, NULL, NULL, N'A745080', N'Rent exps- Vehicles exps')
INSERT [dbo].[AM_GL_HIERARCHY] ([GL_L1], [GL_L2], [GL_L3], [GL_L4], [GL_ACCT], [GL_TXT]) VALUES (NULL, NULL, NULL, NULL, N'A745090', N'Rent exps- Office rent')
INSERT [dbo].[AM_GL_HIERARCHY] ([GL_L1], [GL_L2], [GL_L3], [GL_L4], [GL_ACCT], [GL_TXT]) VALUES (NULL, NULL, NULL, NULL, N'A745095', N'Rent Exps, Office rent (SysInt)')
INSERT [dbo].[AM_GL_HIERARCHY] ([GL_L1], [GL_L2], [GL_L3], [GL_L4], [GL_ACCT], [GL_TXT]) VALUES (NULL, NULL, NULL, NULL, N'A745900', N'Rent exps- Other1')
INSERT [dbo].[AM_GL_HIERARCHY] ([GL_L1], [GL_L2], [GL_L3], [GL_L4], [GL_ACCT], [GL_TXT]) VALUES (NULL, NULL, NULL, NULL, N'A748010', N'Prof service fee- CPA Audit fee')
INSERT [dbo].[AM_GL_HIERARCHY] ([GL_L1], [GL_L2], [GL_L3], [GL_L4], [GL_ACCT], [GL_TXT]) VALUES (NULL, NULL, NULL, NULL, N'A748020', N'Prof service fee- Temp staff service fee (agency)')
INSERT [dbo].[AM_GL_HIERARCHY] ([GL_L1], [GL_L2], [GL_L3], [GL_L4], [GL_ACCT], [GL_TXT]) VALUES (NULL, NULL, NULL, NULL, N'A748030', N'Prof service fee- Legal Services')
INSERT [dbo].[AM_GL_HIERARCHY] ([GL_L1], [GL_L2], [GL_L3], [GL_L4], [GL_ACCT], [GL_TXT]) VALUES (NULL, NULL, NULL, NULL, N'A748040', N'Prof service fee- IS consultant fees')
INSERT [dbo].[AM_GL_HIERARCHY] ([GL_L1], [GL_L2], [GL_L3], [GL_L4], [GL_ACCT], [GL_TXT]) VALUES (NULL, NULL, NULL, NULL, N'A748050', N'Prof service fee- Other consultant fees')
INSERT [dbo].[AM_GL_HIERARCHY] ([GL_L1], [GL_L2], [GL_L3], [GL_L4], [GL_ACCT], [GL_TXT]) VALUES (NULL, NULL, NULL, NULL, N'A748060', N'Prof service fee- Market research')
INSERT [dbo].[AM_GL_HIERARCHY] ([GL_L1], [GL_L2], [GL_L3], [GL_L4], [GL_ACCT], [GL_TXT]) VALUES (NULL, NULL, NULL, NULL, N'A748090', N'Prof service fee- Business Process Outsourcing')
INSERT [dbo].[AM_GL_HIERARCHY] ([GL_L1], [GL_L2], [GL_L3], [GL_L4], [GL_ACCT], [GL_TXT]) VALUES (NULL, NULL, NULL, NULL, N'A748900', N'Prof service fee- Other1')
INSERT [dbo].[AM_GL_HIERARCHY] ([GL_L1], [GL_L2], [GL_L3], [GL_L4], [GL_ACCT], [GL_TXT]) VALUES (NULL, NULL, NULL, NULL, N'A761010', N'Subcontract exps- General')
INSERT [dbo].[AM_GL_HIERARCHY] ([GL_L1], [GL_L2], [GL_L3], [GL_L4], [GL_ACCT], [GL_TXT]) VALUES (NULL, NULL, NULL, NULL, N'A767010', N'WEEE directive- General')
INSERT [dbo].[AM_GL_HIERARCHY] ([GL_L1], [GL_L2], [GL_L3], [GL_L4], [GL_ACCT], [GL_TXT]) VALUES (NULL, NULL, NULL, NULL, N'A771020', N'AD&Pro exps- Media expenses- Magazine')
INSERT [dbo].[AM_GL_HIERARCHY] ([GL_L1], [GL_L2], [GL_L3], [GL_L4], [GL_ACCT], [GL_TXT]) VALUES (NULL, NULL, NULL, NULL, N'A771040', N'AD&Pro exps- Media- Outdoor/Transit advertising')
INSERT [dbo].[AM_GL_HIERARCHY] ([GL_L1], [GL_L2], [GL_L3], [GL_L4], [GL_ACCT], [GL_TXT]) VALUES (NULL, NULL, NULL, NULL, N'A771050', N'AD&Pro exps- Media expenses- TV')
INSERT [dbo].[AM_GL_HIERARCHY] ([GL_L1], [GL_L2], [GL_L3], [GL_L4], [GL_ACCT], [GL_TXT]) VALUES (NULL, NULL, NULL, NULL, N'A771070', N'AD&Pro exps- Media- Internet (Search Engine Mkt)')
INSERT [dbo].[AM_GL_HIERARCHY] ([GL_L1], [GL_L2], [GL_L3], [GL_L4], [GL_ACCT], [GL_TXT]) VALUES (NULL, NULL, NULL, NULL, N'A771090', N'AD&Pro exps- Media expenses- Internet others')
INSERT [dbo].[AM_GL_HIERARCHY] ([GL_L1], [GL_L2], [GL_L3], [GL_L4], [GL_ACCT], [GL_TXT]) VALUES (NULL, NULL, NULL, NULL, N'A771100', N'AD&Pro exps- Contents Creation for Media')
INSERT [dbo].[AM_GL_HIERARCHY] ([GL_L1], [GL_L2], [GL_L3], [GL_L4], [GL_ACCT], [GL_TXT]) VALUES (NULL, NULL, NULL, NULL, N'A771110', N'AD&Pro exps- Sponsorship')
INSERT [dbo].[AM_GL_HIERARCHY] ([GL_L1], [GL_L2], [GL_L3], [GL_L4], [GL_ACCT], [GL_TXT]) VALUES (NULL, NULL, NULL, NULL, N'A771200', N'AD&Pro exps- Promoter expenses')
INSERT [dbo].[AM_GL_HIERARCHY] ([GL_L1], [GL_L2], [GL_L3], [GL_L4], [GL_ACCT], [GL_TXT]) VALUES (NULL, NULL, NULL, NULL, N'A771210', N'AD&Pro exps- Event&Exhibition')
INSERT [dbo].[AM_GL_HIERARCHY] ([GL_L1], [GL_L2], [GL_L3], [GL_L4], [GL_ACCT], [GL_TXT]) VALUES (NULL, NULL, NULL, NULL, N'A771220', N'AD&Pro exps- Others- Sample')
INSERT [dbo].[AM_GL_HIERARCHY] ([GL_L1], [GL_L2], [GL_L3], [GL_L4], [GL_ACCT], [GL_TXT]) VALUES (NULL, NULL, NULL, NULL, N'A771230N', N'AD&Pro exps- Others- Give Away (Non deductible)')
INSERT [dbo].[AM_GL_HIERARCHY] ([GL_L1], [GL_L2], [GL_L3], [GL_L4], [GL_ACCT], [GL_TXT]) VALUES (NULL, NULL, NULL, NULL, N'A771240', N'AD&Pro exps- Others- Dealer/Customer- Training')
INSERT [dbo].[AM_GL_HIERARCHY] ([GL_L1], [GL_L2], [GL_L3], [GL_L4], [GL_ACCT], [GL_TXT]) VALUES (NULL, NULL, NULL, NULL, N'A771300', N'AD&Pro exps- Shop front communication- POP')
INSERT [dbo].[AM_GL_HIERARCHY] ([GL_L1], [GL_L2], [GL_L3], [GL_L4], [GL_ACCT], [GL_TXT]) VALUES (NULL, NULL, NULL, NULL, N'A771310', N'AD&Pro exps- Shop front communication- Catalog')
INSERT [dbo].[AM_GL_HIERARCHY] ([GL_L1], [GL_L2], [GL_L3], [GL_L4], [GL_ACCT], [GL_TXT]) VALUES (NULL, NULL, NULL, NULL, N'A771320', N'AD&Pro exps- Shop front communication- Fixture')
INSERT [dbo].[AM_GL_HIERARCHY] ([GL_L1], [GL_L2], [GL_L3], [GL_L4], [GL_ACCT], [GL_TXT]) VALUES (NULL, NULL, NULL, NULL, N'A771900', N'AD&Pro exps- Other1')
INSERT [dbo].[AM_GL_HIERARCHY] ([GL_L1], [GL_L2], [GL_L3], [GL_L4], [GL_ACCT], [GL_TXT]) VALUES (NULL, NULL, NULL, NULL, N'A774010', N'Sales commission- General')
INSERT [dbo].[AM_GL_HIERARCHY] ([GL_L1], [GL_L2], [GL_L3], [GL_L4], [GL_ACCT], [GL_TXT]) VALUES (NULL, NULL, NULL, NULL, N'A774030', N'Sales commission-eCommerce')
INSERT [dbo].[AM_GL_HIERARCHY] ([GL_L1], [GL_L2], [GL_L3], [GL_L4], [GL_ACCT], [GL_TXT]) VALUES (NULL, NULL, NULL, NULL, N'A775010', N'Service- Inwarranty- exchange')
INSERT [dbo].[AM_GL_HIERARCHY] ([GL_L1], [GL_L2], [GL_L3], [GL_L4], [GL_ACCT], [GL_TXT]) VALUES (NULL, NULL, NULL, NULL, N'A775020', N'Service- Inwarranty- other')
INSERT [dbo].[AM_GL_HIERARCHY] ([GL_L1], [GL_L2], [GL_L3], [GL_L4], [GL_ACCT], [GL_TXT]) VALUES (NULL, NULL, NULL, NULL, N'A775100', N'Service- Outwarranty')
INSERT [dbo].[AM_GL_HIERARCHY] ([GL_L1], [GL_L2], [GL_L3], [GL_L4], [GL_ACCT], [GL_TXT]) VALUES (NULL, NULL, NULL, NULL, N'A775900', N'Service- Other1')
INSERT [dbo].[AM_GL_HIERARCHY] ([GL_L1], [GL_L2], [GL_L3], [GL_L4], [GL_ACCT], [GL_TXT]) VALUES (NULL, NULL, NULL, NULL, N'A777010', N'IPR fee- Patent Royalty Payment')
INSERT [dbo].[AM_GL_HIERARCHY] ([GL_L1], [GL_L2], [GL_L3], [GL_L4], [GL_ACCT], [GL_TXT]) VALUES (NULL, NULL, NULL, NULL, N'A778010', N'Copyright levies')
INSERT [dbo].[AM_GL_HIERARCHY] ([GL_L1], [GL_L2], [GL_L3], [GL_L4], [GL_ACCT], [GL_TXT]) VALUES (NULL, NULL, NULL, NULL, N'A778020', N'Packaging levies')
INSERT [dbo].[AM_GL_HIERARCHY] ([GL_L1], [GL_L2], [GL_L3], [GL_L4], [GL_ACCT], [GL_TXT]) VALUES (NULL, NULL, NULL, NULL, N'A778040', N'Levies Organic tax')
INSERT [dbo].[AM_GL_HIERARCHY] ([GL_L1], [GL_L2], [GL_L3], [GL_L4], [GL_ACCT], [GL_TXT]) VALUES (NULL, NULL, NULL, NULL, N'A780091', N'OGE/Gain relate to Lease contract modification')
INSERT [dbo].[AM_GL_HIERARCHY] ([GL_L1], [GL_L2], [GL_L3], [GL_L4], [GL_ACCT], [GL_TXT]) VALUES (NULL, NULL, NULL, NULL, N'A901000', N'Purchase merchandise')
INSERT [dbo].[AM_GL_HIERARCHY] ([GL_L1], [GL_L2], [GL_L3], [GL_L4], [GL_ACCT], [GL_TXT]) VALUES (NULL, NULL, NULL, NULL, N'A910000', N'Inventory end merchandise')
INSERT [dbo].[AM_GL_HIERARCHY] ([GL_L1], [GL_L2], [GL_L3], [GL_L4], [GL_ACCT], [GL_TXT]) VALUES (NULL, NULL, NULL, NULL, N'A920110', N'Intracompany- AP')
INSERT [dbo].[AM_GL_HIERARCHY] ([GL_L1], [GL_L2], [GL_L3], [GL_L4], [GL_ACCT], [GL_TXT]) VALUES (NULL, NULL, NULL, NULL, N'A923100', N'Interim account- GL')
INSERT [dbo].[AM_GL_HIERARCHY] ([GL_L1], [GL_L2], [GL_L3], [GL_L4], [GL_ACCT], [GL_TXT]) VALUES (NULL, NULL, NULL, NULL, N'A999930', N'Journal splitting Control Account')
INSERT [dbo].[AM_GL_HIERARCHY] ([GL_L1], [GL_L2], [GL_L3], [GL_L4], [GL_ACCT], [GL_TXT]) VALUES (NULL, NULL, NULL, NULL, N'A034040', N'Adv paymnts- SALES REDUCTIONS TACTICAL CASH BACK')
INSERT [dbo].[AM_GL_HIERARCHY] ([GL_L1], [GL_L2], [GL_L3], [GL_L4], [GL_ACCT], [GL_TXT]) VALUES (NULL, NULL, NULL, NULL, N'A711010', N'Freight- Finished goods freightage(Ship)')
GO
