USE [DIVA_GB00_FY23_24]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[AM_SCOPE](
	[SCOPE_MANDANT] [varchar](3) NOT NULL,
	[SCOPE_CMPNY_CODE] [varchar](20) NOT NULL,
	[SCOPE_BUSINESS_DMN_L1] [varchar](100) NULL,
	[SCOPE_BUSINESS_DMN_L2] [nvarchar](100) NULL,
	[SCOPE_SYSTEM] [varchar](20) NULL
) ON [PRIMARY]
GO
INSERT [dbo].[AM_SCOPE] ([SCOPE_MANDANT], [SCOPE_CMPNY_CODE], [SCOPE_BUSINESS_DMN_L1], [SCOPE_BUSINESS_DMN_L2], [SCOPE_SYSTEM]) VALUES (N'400', N'GB00', N'NA', N'Sony Europe B.V.', N'NA')
GO
