USE [DIVA_SIE_US_FY22]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[AM_AR_CLEAR_ACC](
	[ACCOUNT] [nvarchar](100) NULL,
	[GL TEXT] [nvarchar](1000) NULL,
	[GL_LONG TEXT] [nvarchar](1000) NULL,
	[CLASSIFICATION] [nvarchar](100) NULL
) ON [PRIMARY]
GO
INSERT [dbo].[AM_AR_CLEAR_ACC] ([ACCOUNT], [GL TEXT], [GL_LONG TEXT], [CLASSIFICATION]) VALUES (N'A014201', N'I/Clear Citi US70Con', N'Incoming Clearing - Citi - SIE LLC Concur Account', N'')
INSERT [dbo].[AM_AR_CLEAR_ACC] ([ACCOUNT], [GL TEXT], [GL_LONG TEXT], [CLASSIFICATION]) VALUES (N'A014210', N'I/Clear JPM US70 USD', N'Incoming Clearing - JPM - SIE LLC USD Main Account', N'')
INSERT [dbo].[AM_AR_CLEAR_ACC] ([ACCOUNT], [GL TEXT], [GL_LONG TEXT], [CLASSIFICATION]) VALUES (N'A014211', N'I/Clear JPM US70 USD', N'Incoming Clearing - JPM - SIE LLC USD HW Account', N'')
INSERT [dbo].[AM_AR_CLEAR_ACC] ([ACCOUNT], [GL TEXT], [GL_LONG TEXT], [CLASSIFICATION]) VALUES (N'A014212', N'I/Clear JPM US70 CAD', N'Incoming Clearing - JPM - SIE LLC CAD Account', N'')
INSERT [dbo].[AM_AR_CLEAR_ACC] ([ACCOUNT], [GL TEXT], [GL_LONG TEXT], [CLASSIFICATION]) VALUES (N'A014213', N'I/Clear JPM US70 EUR', N'Incoming Clearing - JPM - SIE LLC EUR Account', N'')
INSERT [dbo].[AM_AR_CLEAR_ACC] ([ACCOUNT], [GL TEXT], [GL_LONG TEXT], [CLASSIFICATION]) VALUES (N'A014214', N'I/Clear JPM US70 GBP', N'Incoming Clearing - JPM - SIE LLC GBP Account', N'')
INSERT [dbo].[AM_AR_CLEAR_ACC] ([ACCOUNT], [GL TEXT], [GL_LONG TEXT], [CLASSIFICATION]) VALUES (N'A014215', N'I/Clear JPM US70 JPY', N'Incoming Clearing - JPM - SIE LLC JPY Account', N'')
INSERT [dbo].[AM_AR_CLEAR_ACC] ([ACCOUNT], [GL TEXT], [GL_LONG TEXT], [CLASSIFICATION]) VALUES (N'A014217', N'I/Clear JPM US71 USD', N'Incoming Clearing - JPM - SIET USD Account', N'')
INSERT [dbo].[AM_AR_CLEAR_ACC] ([ACCOUNT], [GL TEXT], [GL_LONG TEXT], [CLASSIFICATION]) VALUES (N'A014218', N'I/Clear JPM US71 CAD', N'Incoming Clearing - JPM - SIET CAD Account', N'')
INSERT [dbo].[AM_AR_CLEAR_ACC] ([ACCOUNT], [GL TEXT], [GL_LONG TEXT], [CLASSIFICATION]) VALUES (N'A014307', N'I Clr-RAS USD', N'Incoming Clearing- RAS ACCOUNT USD', N'')
INSERT [dbo].[AM_AR_CLEAR_ACC] ([ACCOUNT], [GL TEXT], [GL_LONG TEXT], [CLASSIFICATION]) VALUES (N'A014309', N'I Clr-RAS JPY', N'Incoming Clearing- RAS ACCOUNT JPY', N'')
INSERT [dbo].[AM_AR_CLEAR_ACC] ([ACCOUNT], [GL TEXT], [GL_LONG TEXT], [CLASSIFICATION]) VALUES (N'A014850', N'T AR-D GL entry-OIM', N'Trade account receivable- direct GL entry- OIM', N'')
INSERT [dbo].[AM_AR_CLEAR_ACC] ([ACCOUNT], [GL TEXT], [GL_LONG TEXT], [CLASSIFICATION]) VALUES (N'A014856', N'Trade AR - Network', N'Trade AR - Network', N'')
INSERT [dbo].[AM_AR_CLEAR_ACC] ([ACCOUNT], [GL TEXT], [GL_LONG TEXT], [CLASSIFICATION]) VALUES (N'A021015', N'M&FG-D GL-OIM', N'Products- Merchandise & FG- direct GL entry OIM', N'')
INSERT [dbo].[AM_AR_CLEAR_ACC] ([ACCOUNT], [GL TEXT], [GL_LONG TEXT], [CLASSIFICATION]) VALUES (N'A021050', N'M&FG-Devaluation', N'Products- Merchandise & FG- Devaluation', N'')
INSERT [dbo].[AM_AR_CLEAR_ACC] ([ACCOUNT], [GL TEXT], [GL_LONG TEXT], [CLASSIFICATION]) VALUES (N'A021060', N'Inventory - GINI', N'Inventory - Goods Issued Not Invoiced', N'')
INSERT [dbo].[AM_AR_CLEAR_ACC] ([ACCOUNT], [GL TEXT], [GL_LONG TEXT], [CLASSIFICATION]) VALUES (N'A021110', N'Inventory - Freight', N'Inventory - Freight', N'')
INSERT [dbo].[AM_AR_CLEAR_ACC] ([ACCOUNT], [GL TEXT], [GL_LONG TEXT], [CLASSIFICATION]) VALUES (N'A031900', N'PE-Other1', N'Prepaid exps- Other1', N'')
INSERT [dbo].[AM_AR_CLEAR_ACC] ([ACCOUNT], [GL TEXT], [GL_LONG TEXT], [CLASSIFICATION]) VALUES (N'A032850', N'Other AR - D.GL OIM', N'Other AR - Current - Direct GL Entry - OIM', N'')
INSERT [dbo].[AM_AR_CLEAR_ACC] ([ACCOUNT], [GL TEXT], [GL_LONG TEXT], [CLASSIFICATION]) VALUES (N'A039020', N'All D.Debts - Dis', N'Allowance For Doubtful Debts - Dispute Claims', N'')
INSERT [dbo].[AM_AR_CLEAR_ACC] ([ACCOUNT], [GL TEXT], [GL_LONG TEXT], [CLASSIFICATION]) VALUES (N'A089010', N'OCA-Gen', N'Other Current Assets- Miscellaneous- General', N'')
INSERT [dbo].[AM_AR_CLEAR_ACC] ([ACCOUNT], [GL TEXT], [GL_LONG TEXT], [CLASSIFICATION]) VALUES (N'A119020', N'CIP-D GL entry', N'Construction in Progress- at cost- direct GL entry', N'')
INSERT [dbo].[AM_AR_CLEAR_ACC] ([ACCOUNT], [GL TEXT], [GL_LONG TEXT], [CLASSIFICATION]) VALUES (N'A212850', N'T AP-D GL entry- OIM', N'Trade AP- direct GL entry- OIM', N'')
INSERT [dbo].[AM_AR_CLEAR_ACC] ([ACCOUNT], [GL TEXT], [GL_LONG TEXT], [CLASSIFICATION]) VALUES (N'A215307', N'O Clr-RAS USD', N'Outgoing Clearing- RAS ACCOUNT USD', N'')
INSERT [dbo].[AM_AR_CLEAR_ACC] ([ACCOUNT], [GL TEXT], [GL_LONG TEXT], [CLASSIFICATION]) VALUES (N'A215400', N'Concur Global Pay', N'Concur Global Pay', N'')
INSERT [dbo].[AM_AR_CLEAR_ACC] ([ACCOUNT], [GL TEXT], [GL_LONG TEXT], [CLASSIFICATION]) VALUES (N'A215850', N'Oth AP NT D.GL OIM', N'Other AP - Non Trade - Direct GL Entry - OIM', N'')
INSERT [dbo].[AM_AR_CLEAR_ACC] ([ACCOUNT], [GL TEXT], [GL_LONG TEXT], [CLASSIFICATION]) VALUES (N'A216100', N'Accrd Exps Co Op Res', N'Accrd Exps - SR - Co - Op Reserve', N'')
INSERT [dbo].[AM_AR_CLEAR_ACC] ([ACCOUNT], [GL TEXT], [GL_LONG TEXT], [CLASSIFICATION]) VALUES (N'A216130', N'Accrd Exps -Merch', N'Accrd Exps - SR - Merch. Program Reserve', N'')
INSERT [dbo].[AM_AR_CLEAR_ACC] ([ACCOUNT], [GL TEXT], [GL_LONG TEXT], [CLASSIFICATION]) VALUES (N'A216230', N'Accrd Exps SS Reserv', N'Accrd Exps - Sales Special Reserve', N'')
INSERT [dbo].[AM_AR_CLEAR_ACC] ([ACCOUNT], [GL TEXT], [GL_LONG TEXT], [CLASSIFICATION]) VALUES (N'A216411', N'AE-Res TPIP royalty', N'Accrd Exps- TPIP Royalty', N'')
INSERT [dbo].[AM_AR_CLEAR_ACC] ([ACCOUNT], [GL TEXT], [GL_LONG TEXT], [CLASSIFICATION]) VALUES (N'A216610', N'Liab. For Sales Retu', N'Liabilities for sales returns', N'')
INSERT [dbo].[AM_AR_CLEAR_ACC] ([ACCOUNT], [GL TEXT], [GL_LONG TEXT], [CLASSIFICATION]) VALUES (N'A216853', N'AE sales comission', N'Accrd Exps - Integrator Commission', N'')
INSERT [dbo].[AM_AR_CLEAR_ACC] ([ACCOUNT], [GL TEXT], [GL_LONG TEXT], [CLASSIFICATION]) VALUES (N'A216901', N'AE-Other2', N'Accrd exps- Other2', N'')
INSERT [dbo].[AM_AR_CLEAR_ACC] ([ACCOUNT], [GL TEXT], [GL_LONG TEXT], [CLASSIFICATION]) VALUES (N'A220010', N'Tax-P on sales-Gen', N'Tax payable on sales- General', N'')
INSERT [dbo].[AM_AR_CLEAR_ACC] ([ACCOUNT], [GL TEXT], [GL_LONG TEXT], [CLASSIFICATION]) VALUES (N'A220020', N'Tax Pay On Sales D.G', N'Tax payable on sales- Dir- Other', N'')
INSERT [dbo].[AM_AR_CLEAR_ACC] ([ACCOUNT], [GL TEXT], [GL_LONG TEXT], [CLASSIFICATION]) VALUES (N'A226010', N'Def rev-Gen', N'Deferred revenue-current- General', N'')
INSERT [dbo].[AM_AR_CLEAR_ACC] ([ACCOUNT], [GL TEXT], [GL_LONG TEXT], [CLASSIFICATION]) VALUES (N'A226030', N'Def rev-Subscription', N'Def Rev-Subscription', N'')
INSERT [dbo].[AM_AR_CLEAR_ACC] ([ACCOUNT], [GL TEXT], [GL_LONG TEXT], [CLASSIFICATION]) VALUES (N'A226035', N'Def rev-Wallet', N'Deferred revenue-current- Wallet', N'')
INSERT [dbo].[AM_AR_CLEAR_ACC] ([ACCOUNT], [GL TEXT], [GL_LONG TEXT], [CLASSIFICATION]) VALUES (N'A226040', N'Def rev-Prepaid card', N'Deferred revenue-current- Prepaid card', N'')
INSERT [dbo].[AM_AR_CLEAR_ACC] ([ACCOUNT], [GL TEXT], [GL_LONG TEXT], [CLASSIFICATION]) VALUES (N'A226050', N'Def rev-Live prepaid', N'Def Rev-Prepaid Money cards LiveCard/ESD', N'')
INSERT [dbo].[AM_AR_CLEAR_ACC] ([ACCOUNT], [GL TEXT], [GL_LONG TEXT], [CLASSIFICATION]) VALUES (N'A226070', N'Def rev-Sub redeemed', N'Def Rev - Subscription redeemed', N'')
INSERT [dbo].[AM_AR_CLEAR_ACC] ([ACCOUNT], [GL TEXT], [GL_LONG TEXT], [CLASSIFICATION]) VALUES (N'A229010', N'Reserve for warranty', N'Reserve for warranty- General', N'')
INSERT [dbo].[AM_AR_CLEAR_ACC] ([ACCOUNT], [GL TEXT], [GL_LONG TEXT], [CLASSIFICATION]) VALUES (N'A232030', N'Accrd Exps - Tax EE', N'Accrd Exps - Tax EE & ER', N'')
INSERT [dbo].[AM_AR_CLEAR_ACC] ([ACCOUNT], [GL TEXT], [GL_LONG TEXT], [CLASSIFICATION]) VALUES (N'A273010', N'Other Misc. CL - Gen', N'Other misc. curr- General', N'')
INSERT [dbo].[AM_AR_CLEAR_ACC] ([ACCOUNT], [GL TEXT], [GL_LONG TEXT], [CLASSIFICATION]) VALUES (N'A273020', N'Other Misc. CL Custo', N'Other misc. curr- Deposits1', N'')
INSERT [dbo].[AM_AR_CLEAR_ACC] ([ACCOUNT], [GL TEXT], [GL_LONG TEXT], [CLASSIFICATION]) VALUES (N'A273060', N'Other Misc. CL - Wel', N'Other Misc. CL - Welfare', N'')
INSERT [dbo].[AM_AR_CLEAR_ACC] ([ACCOUNT], [GL TEXT], [GL_LONG TEXT], [CLASSIFICATION]) VALUES (N'A505010', N'COGS-Products', N'COGS- Products', N'')
INSERT [dbo].[AM_AR_CLEAR_ACC] ([ACCOUNT], [GL TEXT], [GL_LONG TEXT], [CLASSIFICATION]) VALUES (N'A505030', N'COGS-Other', N'COGS- Other', N'')
INSERT [dbo].[AM_AR_CLEAR_ACC] ([ACCOUNT], [GL TEXT], [GL_LONG TEXT], [CLASSIFICATION]) VALUES (N'A505070', N'Inb Freight-FG(Ship', N'COGS- Inbound Freight- Finished goods (Ship)', N'')
INSERT [dbo].[AM_AR_CLEAR_ACC] ([ACCOUNT], [GL TEXT], [GL_LONG TEXT], [CLASSIFICATION]) VALUES (N'A505110', N'Prov C Ret', N'Provision for COGS Returns', N'')
INSERT [dbo].[AM_AR_CLEAR_ACC] ([ACCOUNT], [GL TEXT], [GL_LONG TEXT], [CLASSIFICATION]) VALUES (N'A505300', N'COGS-Devaluation', N'COGS- Devaluation', N'')
INSERT [dbo].[AM_AR_CLEAR_ACC] ([ACCOUNT], [GL TEXT], [GL_LONG TEXT], [CLASSIFICATION]) VALUES (N'A505530', N'COGS-C card acceptan', N'COGS- transaction fees', N'')
INSERT [dbo].[AM_AR_CLEAR_ACC] ([ACCOUNT], [GL TEXT], [GL_LONG TEXT], [CLASSIFICATION]) VALUES (N'A531400', N'NOE-FX Trans losses', N'NOE- FX Translation losses', N'')
INSERT [dbo].[AM_AR_CLEAR_ACC] ([ACCOUNT], [GL TEXT], [GL_LONG TEXT], [CLASSIFICATION]) VALUES (N'A542300', N'Prov. Frgn Taxes, WH', N'Prov. For Foreign Taxes, WH', N'')
INSERT [dbo].[AM_AR_CLEAR_ACC] ([ACCOUNT], [GL TEXT], [GL_LONG TEXT], [CLASSIFICATION]) VALUES (N'A621010', N'Gross Sales-Products', N'Gross Sales- Products', N'')
INSERT [dbo].[AM_AR_CLEAR_ACC] ([ACCOUNT], [GL TEXT], [GL_LONG TEXT], [CLASSIFICATION]) VALUES (N'A621020', N'Ship Rev', N'Gross Sales Shipping Revenue', N'')
INSERT [dbo].[AM_AR_CLEAR_ACC] ([ACCOUNT], [GL TEXT], [GL_LONG TEXT], [CLASSIFICATION]) VALUES (N'A621091', N'Network Revenue 1', N'Gross Sales- FMA Store Sales', N'')
INSERT [dbo].[AM_AR_CLEAR_ACC] ([ACCOUNT], [GL TEXT], [GL_LONG TEXT], [CLASSIFICATION]) VALUES (N'A621092', N'Network Revenue 2', N'Gross Sales- Integrator Sales', N'')
INSERT [dbo].[AM_AR_CLEAR_ACC] ([ACCOUNT], [GL TEXT], [GL_LONG TEXT], [CLASSIFICATION]) VALUES (N'A621095', N'Network Revenue 5', N'Gross Sales- ESD', N'')
INSERT [dbo].[AM_AR_CLEAR_ACC] ([ACCOUNT], [GL TEXT], [GL_LONG TEXT], [CLASSIFICATION]) VALUES (N'A621098', N'Gross Sales- PSN mis', N'Gross Sales- PSN misc other', N'')
INSERT [dbo].[AM_AR_CLEAR_ACC] ([ACCOUNT], [GL TEXT], [GL_LONG TEXT], [CLASSIFICATION]) VALUES (N'A621900', N'Gross Sales-Other1', N'Gross Sales- Other1', N'')
INSERT [dbo].[AM_AR_CLEAR_ACC] ([ACCOUNT], [GL TEXT], [GL_LONG TEXT], [CLASSIFICATION]) VALUES (N'A622111', N'SR-OID 2', N'Sales reduction - Discount', N'')
INSERT [dbo].[AM_AR_CLEAR_ACC] ([ACCOUNT], [GL TEXT], [GL_LONG TEXT], [CLASSIFICATION]) VALUES (N'A622210', N'SR-Co-op AD(MDF) 1', N'Sales reduction  Co-op AD(Activity)', N'')
INSERT [dbo].[AM_AR_CLEAR_ACC] ([ACCOUNT], [GL TEXT], [GL_LONG TEXT], [CLASSIFICATION]) VALUES (N'A622620', N'SR-Chgbck/Wallet adj', N'Sales reduction - Chargebacks/Wallet adj', N'')
INSERT [dbo].[AM_AR_CLEAR_ACC] ([ACCOUNT], [GL TEXT], [GL_LONG TEXT], [CLASSIFICATION]) VALUES (N'A622650', N'PSN AR Clearing', N'PSN AR Clearing', N'')
INSERT [dbo].[AM_AR_CLEAR_ACC] ([ACCOUNT], [GL TEXT], [GL_LONG TEXT], [CLASSIFICATION]) VALUES (N'A631300', N'NOR-FX Trans gain', N'NOR- FX Translation gain', N'')
INSERT [dbo].[AM_AR_CLEAR_ACC] ([ACCOUNT], [GL TEXT], [GL_LONG TEXT], [CLASSIFICATION]) VALUES (N'A702010', N'S&W-Base salaries', N'S&W- Base salaries', N'')
INSERT [dbo].[AM_AR_CLEAR_ACC] ([ACCOUNT], [GL TEXT], [GL_LONG TEXT], [CLASSIFICATION]) VALUES (N'A702100', N'S&W-Temp employees', N'S&W- Temporary employees', N'')
INSERT [dbo].[AM_AR_CLEAR_ACC] ([ACCOUNT], [GL TEXT], [GL_LONG TEXT], [CLASSIFICATION]) VALUES (N'A702800', N'S&W-Outgo recharge', N'S&W- Outgoing recharge', N'')
INSERT [dbo].[AM_AR_CLEAR_ACC] ([ACCOUNT], [GL TEXT], [GL_LONG TEXT], [CLASSIFICATION]) VALUES (N'A703010', N'Bonuses-Gen', N'Bonuses & allowance- General', N'')
INSERT [dbo].[AM_AR_CLEAR_ACC] ([ACCOUNT], [GL TEXT], [GL_LONG TEXT], [CLASSIFICATION]) VALUES (N'A706900', N'Welfare exps-Other1', N'Welfare exps- Other1', N'')
INSERT [dbo].[AM_AR_CLEAR_ACC] ([ACCOUNT], [GL TEXT], [GL_LONG TEXT], [CLASSIFICATION]) VALUES (N'A711030', N'Freight-FG (Land)', N'Freight- Finished goods freightage(Land)', N'')
INSERT [dbo].[AM_AR_CLEAR_ACC] ([ACCOUNT], [GL TEXT], [GL_LONG TEXT], [CLASSIFICATION]) VALUES (N'A712010', N'E&T expensed', N'Equipment- tools & software expensed- E&T', N'')
INSERT [dbo].[AM_AR_CLEAR_ACC] ([ACCOUNT], [GL TEXT], [GL_LONG TEXT], [CLASSIFICATION]) VALUES (N'A714700', N'Util Exps, H/B (Var)', N'Utilities Exps, Hosting/Bandwidth (Var)', N'')
INSERT [dbo].[AM_AR_CLEAR_ACC] ([ACCOUNT], [GL TEXT], [GL_LONG TEXT], [CLASSIFICATION]) VALUES (N'A722020', N'Training exps', N'R&T exps- Training exps', N'')
INSERT [dbo].[AM_AR_CLEAR_ACC] ([ACCOUNT], [GL TEXT], [GL_LONG TEXT], [CLASSIFICATION]) VALUES (N'A723010', N'Fare', N'Travelling & commutation- Fare', N'')
INSERT [dbo].[AM_AR_CLEAR_ACC] ([ACCOUNT], [GL TEXT], [GL_LONG TEXT], [CLASSIFICATION]) VALUES (N'A723020', N'Accommodation', N'Travelling & commutation- Accommodation', N'')
INSERT [dbo].[AM_AR_CLEAR_ACC] ([ACCOUNT], [GL TEXT], [GL_LONG TEXT], [CLASSIFICATION]) VALUES (N'A723030', N'vehicle running exp', N'Travelling & commutation- vehicle running exp', N'')
INSERT [dbo].[AM_AR_CLEAR_ACC] ([ACCOUNT], [GL TEXT], [GL_LONG TEXT], [CLASSIFICATION]) VALUES (N'A723900', N'Trav&commut-Other1', N'Travelling & commutation- Other1', N'')
INSERT [dbo].[AM_AR_CLEAR_ACC] ([ACCOUNT], [GL TEXT], [GL_LONG TEXT], [CLASSIFICATION]) VALUES (N'A725010', N'Postal exps', N'Commu exps- Postal exps', N'')
INSERT [dbo].[AM_AR_CLEAR_ACC] ([ACCOUNT], [GL TEXT], [GL_LONG TEXT], [CLASSIFICATION]) VALUES (N'A726010', N'Meal', N'Meals and Entmt exps- Meal', N'')
INSERT [dbo].[AM_AR_CLEAR_ACC] ([ACCOUNT], [GL TEXT], [GL_LONG TEXT], [CLASSIFICATION]) VALUES (N'A744010', N'membership fee', N'misc. exps- membership fee', N'')
INSERT [dbo].[AM_AR_CLEAR_ACC] ([ACCOUNT], [GL TEXT], [GL_LONG TEXT], [CLASSIFICATION]) VALUES (N'A744020', N'Books & magazines', N'misc. exps- Books & magazines', N'')
INSERT [dbo].[AM_AR_CLEAR_ACC] ([ACCOUNT], [GL TEXT], [GL_LONG TEXT], [CLASSIFICATION]) VALUES (N'A744050', N'Bank commissions', N'misc. exps- Bank commissions', N'')
INSERT [dbo].[AM_AR_CLEAR_ACC] ([ACCOUNT], [GL TEXT], [GL_LONG TEXT], [CLASSIFICATION]) VALUES (N'A744800', N'Outgo recharge', N'misc. exps- Outgoing recharge', N'')
INSERT [dbo].[AM_AR_CLEAR_ACC] ([ACCOUNT], [GL TEXT], [GL_LONG TEXT], [CLASSIFICATION]) VALUES (N'A744801', N'Misc. exps-IT Alloca', N'Misc. Exps - IT Allocation', N'')
INSERT [dbo].[AM_AR_CLEAR_ACC] ([ACCOUNT], [GL TEXT], [GL_LONG TEXT], [CLASSIFICATION]) VALUES (N'A744900', N'misc. exps-Other1', N'misc. exps- Other1', N'')
INSERT [dbo].[AM_AR_CLEAR_ACC] ([ACCOUNT], [GL TEXT], [GL_LONG TEXT], [CLASSIFICATION]) VALUES (N'A745080', N'Vehicles exps', N'Rent exps- Vehicles exps', N'')
INSERT [dbo].[AM_AR_CLEAR_ACC] ([ACCOUNT], [GL TEXT], [GL_LONG TEXT], [CLASSIFICATION]) VALUES (N'A745090', N'Office rent', N'Rent exps- Office rent', N'')
INSERT [dbo].[AM_AR_CLEAR_ACC] ([ACCOUNT], [GL TEXT], [GL_LONG TEXT], [CLASSIFICATION]) VALUES (N'A748030', N'Legal Services', N'Prof service fee- Legal Services', N'')
INSERT [dbo].[AM_AR_CLEAR_ACC] ([ACCOUNT], [GL TEXT], [GL_LONG TEXT], [CLASSIFICATION]) VALUES (N'A748040', N'IS consultant fees', N'Prof service fee- IS consultant fees', N'')
INSERT [dbo].[AM_AR_CLEAR_ACC] ([ACCOUNT], [GL TEXT], [GL_LONG TEXT], [CLASSIFICATION]) VALUES (N'A765010', N'Ext 3rdParty Dev-Gen', N'External 3rd party Development - General', N'')
INSERT [dbo].[AM_AR_CLEAR_ACC] ([ACCOUNT], [GL TEXT], [GL_LONG TEXT], [CLASSIFICATION]) VALUES (N'A771110', N'Sponsorship', N'Mktg - Sponsorship', N'')
INSERT [dbo].[AM_AR_CLEAR_ACC] ([ACCOUNT], [GL TEXT], [GL_LONG TEXT], [CLASSIFICATION]) VALUES (N'A771330', N'Field Sales & Merch', N'Mktg - Field Sales & Merchandising', N'')
INSERT [dbo].[AM_AR_CLEAR_ACC] ([ACCOUNT], [GL TEXT], [GL_LONG TEXT], [CLASSIFICATION]) VALUES (N'A771900', N'Marketing Other', N'Mktg - Marketing Other', N'')
INSERT [dbo].[AM_AR_CLEAR_ACC] ([ACCOUNT], [GL TEXT], [GL_LONG TEXT], [CLASSIFICATION]) VALUES (N'A775020', N'Service-IW-other', N'Service- Inwarranty- other', N'')
INSERT [dbo].[AM_AR_CLEAR_ACC] ([ACCOUNT], [GL TEXT], [GL_LONG TEXT], [CLASSIFICATION]) VALUES (N'A775900', N'Service-Other1', N'Service- Other1', N'')
INSERT [dbo].[AM_AR_CLEAR_ACC] ([ACCOUNT], [GL TEXT], [GL_LONG TEXT], [CLASSIFICATION]) VALUES (N'A999930', N'JE splitting Control', N'Journal splitting Control Account', N'')
INSERT [dbo].[AM_AR_CLEAR_ACC] ([ACCOUNT], [GL TEXT], [GL_LONG TEXT], [CLASSIFICATION]) VALUES (N'A999996', N'AR OPEN ITEM CONVERS', N'Clearing account- AR OPEN ITEM CONVERSION', N'')
GO
