USE [DIVA_SIE_US_FY22]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[AM_AR_CLEARING](
	[ZF_ACCOUNTS] [varchar](max) NULL,
	[SKAT_TXT50] [nvarchar](52) NULL,
	[SKAT_TXT20] [nvarchar](22) NULL,
	[ZF_AR_CLEARING] [nchar](10) NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
INSERT [dbo].[AM_AR_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_CLEARING]) VALUES (N'A014201', N'Incoming Clearing - Citi - SIE LLC Concur Account', N'I/Clear Citi US70Con', N'X         ')
INSERT [dbo].[AM_AR_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_CLEARING]) VALUES (N'A014210', N'Incoming Clearing - JPM - SIE LLC USD Main Account', N'I/Clear JPM US70 USD', N'X         ')
INSERT [dbo].[AM_AR_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_CLEARING]) VALUES (N'A014211', N'Incoming Clearing - JPM - SIE LLC USD HW Account', N'I/Clear JPM US70 USD', N'X         ')
INSERT [dbo].[AM_AR_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_CLEARING]) VALUES (N'A014212', N'Incoming Clearing - JPM - SIE LLC CAD Account', N'I/Clear JPM US70 CAD', N'X         ')
INSERT [dbo].[AM_AR_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_CLEARING]) VALUES (N'A014213', N'Incoming Clearing - JPM - SIE LLC EUR Account', N'I/Clear JPM US70 EUR', N'X         ')
INSERT [dbo].[AM_AR_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_CLEARING]) VALUES (N'A014214', N'Incoming Clearing - JPM - SIE LLC GBP Account', N'I/Clear JPM US70 GBP', N'X         ')
INSERT [dbo].[AM_AR_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_CLEARING]) VALUES (N'A014215', N'Incoming Clearing - JPM - SIE LLC JPY Account', N'I/Clear JPM US70 JPY', N'X         ')
INSERT [dbo].[AM_AR_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_CLEARING]) VALUES (N'A014217', N'Incoming Clearing - JPM - SIET USD Account', N'I/Clear JPM US71 USD', N'X         ')
INSERT [dbo].[AM_AR_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_CLEARING]) VALUES (N'A014218', N'Incoming Clearing - JPM - SIET CAD Account', N'I/Clear JPM US71 CAD', N'X         ')
INSERT [dbo].[AM_AR_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_CLEARING]) VALUES (N'A014307', N'Incoming Clearing- RAS ACCOUNT USD', N'I Clr-RAS USD', N'X         ')
INSERT [dbo].[AM_AR_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_CLEARING]) VALUES (N'A014309', N'Incoming Clearing- RAS ACCOUNT JPY', N'I Clr-RAS JPY', N'X         ')
INSERT [dbo].[AM_AR_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_CLEARING]) VALUES (N'A014315', N'Incoming Clearing - RAS Account CAD', N'I/Clear RAS Acc CAD', N'X         ')
INSERT [dbo].[AM_AR_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_CLEARING]) VALUES (N'A622650', N'PSN AR Clearing', N'PSN AR Clearing', N'X         ')
INSERT [dbo].[AM_AR_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_CLEARING]) VALUES (N'A014850', N'Trade account receivable- direct GL entry- OIM', N'T AR-D GL entry-OIM', NULL)
INSERT [dbo].[AM_AR_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_CLEARING]) VALUES (N'A014856', N'Trade AR - Network', N'Trade AR - Network', NULL)
INSERT [dbo].[AM_AR_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_CLEARING]) VALUES (N'A021015', N'Products- Merchandise & FG- direct GL entry OIM', N'M&FG-D GL-OIM', NULL)
INSERT [dbo].[AM_AR_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_CLEARING]) VALUES (N'A021050', N'Products- Merchandise & FG- Devaluation', N'M&FG-Devaluation', NULL)
INSERT [dbo].[AM_AR_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_CLEARING]) VALUES (N'A021060', N'Inventory - Goods Issued Not Invoiced', N'Inventory - GINI', NULL)
INSERT [dbo].[AM_AR_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_CLEARING]) VALUES (N'A021110', N'Inventory - Freight', N'Inventory - Freight', NULL)
INSERT [dbo].[AM_AR_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_CLEARING]) VALUES (N'A031900', N'Prepaid exps- Other1', N'PE-Other1', NULL)
INSERT [dbo].[AM_AR_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_CLEARING]) VALUES (N'A032850', N'Other AR - Current - Direct GL Entry - OIM', N'Other AR - D.GL OIM', NULL)
INSERT [dbo].[AM_AR_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_CLEARING]) VALUES (N'A039020', N'Allowance For Doubtful Debts - Dispute Claims', N'All D.Debts - Dis', NULL)
INSERT [dbo].[AM_AR_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_CLEARING]) VALUES (N'A089010', N'Other Current Assets- Miscellaneous- General', N'OCA-Gen', NULL)
INSERT [dbo].[AM_AR_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_CLEARING]) VALUES (N'A119020', N'Construction in Progress- at cost- direct GL entry', N'CIP-D GL entry', NULL)
INSERT [dbo].[AM_AR_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_CLEARING]) VALUES (N'A212850', N'Trade AP- direct GL entry- OIM', N'T AP-D GL entry- OIM', NULL)
INSERT [dbo].[AM_AR_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_CLEARING]) VALUES (N'A215307', N'Outgoing Clearing- RAS ACCOUNT USD', N'O Clr-RAS USD', NULL)
INSERT [dbo].[AM_AR_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_CLEARING]) VALUES (N'A215400', N'Concur Global Pay', N'Concur Global Pay', NULL)
INSERT [dbo].[AM_AR_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_CLEARING]) VALUES (N'A215850', N'Other AP - Non Trade - Direct GL Entry - OIM', N'Oth AP NT D.GL OIM', NULL)
INSERT [dbo].[AM_AR_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_CLEARING]) VALUES (N'A216100', N'Accrd Exps - SR - Co - Op Reserve', N'Accrd Exps Co Op Res', NULL)
INSERT [dbo].[AM_AR_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_CLEARING]) VALUES (N'A216130', N'Accrd Exps - SR - Merch. Program Reserve', N'Accrd Exps -Merch', NULL)
INSERT [dbo].[AM_AR_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_CLEARING]) VALUES (N'A216230', N'Accrd Exps - Sales Special Reserve', N'Accrd Exps SS Reserv', NULL)
INSERT [dbo].[AM_AR_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_CLEARING]) VALUES (N'A216411', N'Accrd Exps- TPIP Royalty', N'AE-Res TPIP royalty', NULL)
INSERT [dbo].[AM_AR_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_CLEARING]) VALUES (N'A216610', N'Liabilities for sales returns', N'Liab. For Sales Retu', NULL)
INSERT [dbo].[AM_AR_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_CLEARING]) VALUES (N'A216853', N'Accrd Exps - Integrator Commission', N'AE sales comission', NULL)
INSERT [dbo].[AM_AR_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_CLEARING]) VALUES (N'A216901', N'Accrd exps- Other2', N'AE-Other2', NULL)
INSERT [dbo].[AM_AR_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_CLEARING]) VALUES (N'A220010', N'Tax payable on sales- General', N'Tax-P on sales-Gen', NULL)
INSERT [dbo].[AM_AR_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_CLEARING]) VALUES (N'A220020', N'Tax payable on sales- Dir- Other', N'Tax Pay On Sales D.G', NULL)
INSERT [dbo].[AM_AR_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_CLEARING]) VALUES (N'A226010', N'Deferred revenue-current- General', N'Def rev-Gen', NULL)
INSERT [dbo].[AM_AR_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_CLEARING]) VALUES (N'A226030', N'Def Rev-Subscription', N'Def rev-Subscription', NULL)
INSERT [dbo].[AM_AR_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_CLEARING]) VALUES (N'A226035', N'Deferred revenue-current- Wallet', N'Def rev-Wallet', NULL)
INSERT [dbo].[AM_AR_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_CLEARING]) VALUES (N'A226040', N'Deferred revenue-current- Prepaid card', N'Def rev-Prepaid card', NULL)
INSERT [dbo].[AM_AR_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_CLEARING]) VALUES (N'A226050', N'Def Rev-Prepaid Money cards LiveCard/ESD', N'Def rev-Live prepaid', NULL)
INSERT [dbo].[AM_AR_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_CLEARING]) VALUES (N'A226070', N'Def Rev - Subscription redeemed', N'Def rev-Sub redeemed', NULL)
INSERT [dbo].[AM_AR_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_CLEARING]) VALUES (N'A229010', N'Reserve for warranty- General', N'Reserve for warranty', NULL)
INSERT [dbo].[AM_AR_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_CLEARING]) VALUES (N'A232030', N'Accrd Exps - Tax EE & ER', N'Accrd Exps - Tax EE', NULL)
INSERT [dbo].[AM_AR_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_CLEARING]) VALUES (N'A273010', N'Other misc. curr- General', N'Other Misc. CL - Gen', NULL)
INSERT [dbo].[AM_AR_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_CLEARING]) VALUES (N'A273020', N'Other misc. curr- Deposits1', N'Other Misc. CL Custo', NULL)
INSERT [dbo].[AM_AR_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_CLEARING]) VALUES (N'A273060', N'Other Misc. CL - Welfare', N'Other Misc. CL - Wel', NULL)
INSERT [dbo].[AM_AR_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_CLEARING]) VALUES (N'A505010', N'COGS- Products', N'COGS-Products', NULL)
INSERT [dbo].[AM_AR_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_CLEARING]) VALUES (N'A505030', N'COGS- Other', N'COGS-Other', NULL)
INSERT [dbo].[AM_AR_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_CLEARING]) VALUES (N'A505070', N'COGS- Inbound Freight- Finished goods (Ship)', N'Inb Freight-FG(Ship', NULL)
INSERT [dbo].[AM_AR_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_CLEARING]) VALUES (N'A505110', N'Provision for COGS Returns', N'Prov C Ret', NULL)
INSERT [dbo].[AM_AR_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_CLEARING]) VALUES (N'A505300', N'COGS- Devaluation', N'COGS-Devaluation', NULL)
INSERT [dbo].[AM_AR_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_CLEARING]) VALUES (N'A505530', N'COGS- transaction fees', N'COGS-C card acceptan', NULL)
INSERT [dbo].[AM_AR_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_CLEARING]) VALUES (N'A531400', N'NOE- FX Translation losses', N'NOE-FX Trans losses', NULL)
INSERT [dbo].[AM_AR_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_CLEARING]) VALUES (N'A542300', N'Prov. For Foreign Taxes, WH', N'Prov. Frgn Taxes, WH', NULL)
INSERT [dbo].[AM_AR_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_CLEARING]) VALUES (N'A621010', N'Gross Sales- Products', N'Gross Sales-Products', NULL)
INSERT [dbo].[AM_AR_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_CLEARING]) VALUES (N'A621020', N'Gross Sales Shipping Revenue', N'Ship Rev', NULL)
INSERT [dbo].[AM_AR_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_CLEARING]) VALUES (N'A621091', N'Gross Sales- FMA Store Sales', N'Network Revenue 1', NULL)
INSERT [dbo].[AM_AR_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_CLEARING]) VALUES (N'A621092', N'Gross Sales- Integrator Sales', N'Network Revenue 2', NULL)
INSERT [dbo].[AM_AR_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_CLEARING]) VALUES (N'A621095', N'Gross Sales- ESD', N'Network Revenue 5', NULL)
INSERT [dbo].[AM_AR_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_CLEARING]) VALUES (N'A621098', N'Gross Sales- PSN misc other', N'Gross Sales- PSN mis', NULL)
INSERT [dbo].[AM_AR_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_CLEARING]) VALUES (N'A621900', N'Gross Sales- Other1', N'Gross Sales-Other1', NULL)
INSERT [dbo].[AM_AR_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_CLEARING]) VALUES (N'A622111', N'Sales reduction - Discount', N'SR-OID 2', NULL)
INSERT [dbo].[AM_AR_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_CLEARING]) VALUES (N'A622210', N'Sales reduction  Co-op AD(Activity)', N'SR-Co-op AD(MDF) 1', NULL)
INSERT [dbo].[AM_AR_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_CLEARING]) VALUES (N'A622620', N'Sales reduction - Chargebacks/Wallet adj', N'SR-Chgbck/Wallet adj', NULL)
INSERT [dbo].[AM_AR_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_CLEARING]) VALUES (N'A631300', N'NOR- FX Translation gain', N'NOR-FX Trans gain', NULL)
INSERT [dbo].[AM_AR_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_CLEARING]) VALUES (N'A702010', N'S&W- Base salaries', N'S&W-Base salaries', NULL)
INSERT [dbo].[AM_AR_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_CLEARING]) VALUES (N'A702100', N'S&W- Temporary employees', N'S&W-Temp employees', NULL)
INSERT [dbo].[AM_AR_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_CLEARING]) VALUES (N'A702800', N'S&W- Outgoing recharge', N'S&W-Outgo recharge', NULL)
INSERT [dbo].[AM_AR_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_CLEARING]) VALUES (N'A703010', N'Bonuses & allowance- General', N'Bonuses-Gen', NULL)
INSERT [dbo].[AM_AR_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_CLEARING]) VALUES (N'A706900', N'Welfare exps- Other1', N'Welfare exps-Other1', NULL)
INSERT [dbo].[AM_AR_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_CLEARING]) VALUES (N'A711030', N'Freight- Finished goods freightage(Land)', N'Freight-FG (Land)', NULL)
INSERT [dbo].[AM_AR_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_CLEARING]) VALUES (N'A712010', N'Equipment- tools & software expensed- E&T', N'E&T expensed', NULL)
INSERT [dbo].[AM_AR_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_CLEARING]) VALUES (N'A714700', N'Utilities Exps, Hosting/Bandwidth (Var)', N'Util Exps, H/B (Var)', NULL)
INSERT [dbo].[AM_AR_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_CLEARING]) VALUES (N'A722020', N'R&T exps- Training exps', N'Training exps', NULL)
INSERT [dbo].[AM_AR_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_CLEARING]) VALUES (N'A723010', N'Travelling & commutation- Fare', N'Fare', NULL)
INSERT [dbo].[AM_AR_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_CLEARING]) VALUES (N'A723020', N'Travelling & commutation- Accommodation', N'Accommodation', NULL)
INSERT [dbo].[AM_AR_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_CLEARING]) VALUES (N'A723030', N'Travelling & commutation- vehicle running exp', N'vehicle running exp', NULL)
INSERT [dbo].[AM_AR_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_CLEARING]) VALUES (N'A723900', N'Travelling & commutation- Other1', N'Trav&commut-Other1', NULL)
INSERT [dbo].[AM_AR_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_CLEARING]) VALUES (N'A725010', N'Commu exps- Postal exps', N'Postal exps', NULL)
INSERT [dbo].[AM_AR_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_CLEARING]) VALUES (N'A726010', N'Meals and Entmt exps- Meal', N'Meal', NULL)
INSERT [dbo].[AM_AR_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_CLEARING]) VALUES (N'A744010', N'misc. exps- membership fee', N'membership fee', NULL)
INSERT [dbo].[AM_AR_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_CLEARING]) VALUES (N'A744020', N'misc. exps- Books & magazines', N'Books & magazines', NULL)
INSERT [dbo].[AM_AR_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_CLEARING]) VALUES (N'A744050', N'misc. exps- Bank commissions', N'Bank commissions', NULL)
INSERT [dbo].[AM_AR_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_CLEARING]) VALUES (N'A744800', N'misc. exps- Outgoing recharge', N'Outgo recharge', NULL)
INSERT [dbo].[AM_AR_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_CLEARING]) VALUES (N'A744801', N'Misc. Exps - IT Allocation', N'Misc. exps-IT Alloca', NULL)
INSERT [dbo].[AM_AR_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_CLEARING]) VALUES (N'A744900', N'misc. exps- Other1', N'misc. exps-Other1', NULL)
INSERT [dbo].[AM_AR_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_CLEARING]) VALUES (N'A745080', N'Rent exps- Vehicles exps', N'Vehicles exps', NULL)
INSERT [dbo].[AM_AR_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_CLEARING]) VALUES (N'A745090', N'Rent exps- Office rent', N'Office rent', NULL)
INSERT [dbo].[AM_AR_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_CLEARING]) VALUES (N'A748030', N'Prof service fee- Legal Services', N'Legal Services', NULL)
INSERT [dbo].[AM_AR_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_CLEARING]) VALUES (N'A748040', N'Prof service fee- IS consultant fees', N'IS consultant fees', NULL)
INSERT [dbo].[AM_AR_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_CLEARING]) VALUES (N'A765010', N'External 3rd party Development - General', N'Ext 3rdParty Dev-Gen', NULL)
INSERT [dbo].[AM_AR_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_CLEARING]) VALUES (N'A771110', N'Mktg - Sponsorship', N'Sponsorship', NULL)
INSERT [dbo].[AM_AR_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_CLEARING]) VALUES (N'A771330', N'Mktg - Field Sales & Merchandising', N'Field Sales & Merch', NULL)
INSERT [dbo].[AM_AR_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_CLEARING]) VALUES (N'A771900', N'Mktg - Marketing Other', N'Marketing Other', NULL)
INSERT [dbo].[AM_AR_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_CLEARING]) VALUES (N'A775020', N'Service- Inwarranty- other', N'Service-IW-other', NULL)
INSERT [dbo].[AM_AR_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_CLEARING]) VALUES (N'A775900', N'Service- Other1', N'Service-Other1', NULL)
INSERT [dbo].[AM_AR_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_CLEARING]) VALUES (N'A999930', N'Journal splitting Control Account', N'JE splitting Control', NULL)
INSERT [dbo].[AM_AR_CLEARING] ([ZF_ACCOUNTS], [SKAT_TXT50], [SKAT_TXT20], [ZF_AR_CLEARING]) VALUES (N'A999996', N'Clearing account- AR OPEN ITEM CONVERSION', N'AR OPEN ITEM CONVERS', NULL)
GO
