USE [DIVA_SIE_US_FY22]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[AM_REGION_S4_MAPPING](
	[Country] [varchar](100) NULL,
	[Code] [varchar](10) NULL,
	[Region] [varchar](100) NULL
) ON [PRIMARY]
GO
INSERT [dbo].[AM_REGION_S4_MAPPING] ([Country], [Code], [Region]) VALUES (N'Afghanistan', N'AF', N'APAC')
INSERT [dbo].[AM_REGION_S4_MAPPING] ([Country], [Code], [Region]) VALUES (N'Albania', N'AL', N'EMEA')
INSERT [dbo].[AM_REGION_S4_MAPPING] ([Country], [Code], [Region]) VALUES (N'Algeria', N'DZ', N'EMEA')
INSERT [dbo].[AM_REGION_S4_MAPPING] ([Country], [Code], [Region]) VALUES (N'American Samoa', N'AS', N'APAC')
INSERT [dbo].[AM_REGION_S4_MAPPING] ([Country], [Code], [Region]) VALUES (N'Andorra', N'AD', N'EMEA')
INSERT [dbo].[AM_REGION_S4_MAPPING] ([Country], [Code], [Region]) VALUES (N'Angola', N'AO', N'EMEA')
INSERT [dbo].[AM_REGION_S4_MAPPING] ([Country], [Code], [Region]) VALUES (N'Anguilla', N'AI', N'LATAM')
INSERT [dbo].[AM_REGION_S4_MAPPING] ([Country], [Code], [Region]) VALUES (N'Antarctica', N'AQ', N'APAC')
INSERT [dbo].[AM_REGION_S4_MAPPING] ([Country], [Code], [Region]) VALUES (N'Antigua and Barbuda', N'AG', N'LATAM')
INSERT [dbo].[AM_REGION_S4_MAPPING] ([Country], [Code], [Region]) VALUES (N'Argentina', N'AR', N'LATAM')
INSERT [dbo].[AM_REGION_S4_MAPPING] ([Country], [Code], [Region]) VALUES (N'Armenia', N'AM', N'APAC')
INSERT [dbo].[AM_REGION_S4_MAPPING] ([Country], [Code], [Region]) VALUES (N'Aruba', N'AW', N'LATAM')
INSERT [dbo].[AM_REGION_S4_MAPPING] ([Country], [Code], [Region]) VALUES (N'Australia', N'AU', N'APAC')
INSERT [dbo].[AM_REGION_S4_MAPPING] ([Country], [Code], [Region]) VALUES (N'Austria', N'AT', N'EMEA')
INSERT [dbo].[AM_REGION_S4_MAPPING] ([Country], [Code], [Region]) VALUES (N'Azerbaijan', N'AZ', N'APAC')
INSERT [dbo].[AM_REGION_S4_MAPPING] ([Country], [Code], [Region]) VALUES (N'Bahamas (the)', N'BS', N'LATAM')
INSERT [dbo].[AM_REGION_S4_MAPPING] ([Country], [Code], [Region]) VALUES (N'Bahrain', N'BH', N'EMEA')
INSERT [dbo].[AM_REGION_S4_MAPPING] ([Country], [Code], [Region]) VALUES (N'Bangladesh', N'BD', N'APAC')
INSERT [dbo].[AM_REGION_S4_MAPPING] ([Country], [Code], [Region]) VALUES (N'Barbados', N'BB', N'LATAM')
INSERT [dbo].[AM_REGION_S4_MAPPING] ([Country], [Code], [Region]) VALUES (N'Belarus', N'BY', N'EMEA')
INSERT [dbo].[AM_REGION_S4_MAPPING] ([Country], [Code], [Region]) VALUES (N'Belgium', N'BE', N'EMEA')
INSERT [dbo].[AM_REGION_S4_MAPPING] ([Country], [Code], [Region]) VALUES (N'Belize', N'BZ', N'LATAM')
INSERT [dbo].[AM_REGION_S4_MAPPING] ([Country], [Code], [Region]) VALUES (N'Benin', N'BJ', N'EMEA')
INSERT [dbo].[AM_REGION_S4_MAPPING] ([Country], [Code], [Region]) VALUES (N'Bermuda', N'BM', N'NA')
INSERT [dbo].[AM_REGION_S4_MAPPING] ([Country], [Code], [Region]) VALUES (N'Bhutan', N'BT', N'APAC')
INSERT [dbo].[AM_REGION_S4_MAPPING] ([Country], [Code], [Region]) VALUES (N'Bolivia (Plurinational State of)', N'BO', N'LATAM')
INSERT [dbo].[AM_REGION_S4_MAPPING] ([Country], [Code], [Region]) VALUES (N'Bonaire, Sint Eustatius and Saba', N'BQ', N'NA')
INSERT [dbo].[AM_REGION_S4_MAPPING] ([Country], [Code], [Region]) VALUES (N'Bosnia and Herzegovina', N'BA', N'EMEA')
INSERT [dbo].[AM_REGION_S4_MAPPING] ([Country], [Code], [Region]) VALUES (N'Botswana', N'BW', N'EMEA')
INSERT [dbo].[AM_REGION_S4_MAPPING] ([Country], [Code], [Region]) VALUES (N'Bouvet Island', N'BV', N'EMEA')
INSERT [dbo].[AM_REGION_S4_MAPPING] ([Country], [Code], [Region]) VALUES (N'Brazil', N'BR', N'LATAM')
INSERT [dbo].[AM_REGION_S4_MAPPING] ([Country], [Code], [Region]) VALUES (N'British Indian Ocean Territory (the)', N'IO', N'APAC')
INSERT [dbo].[AM_REGION_S4_MAPPING] ([Country], [Code], [Region]) VALUES (N'Brunei Darussalam', N'BN', N'APAC')
INSERT [dbo].[AM_REGION_S4_MAPPING] ([Country], [Code], [Region]) VALUES (N'Bulgaria', N'BG', N'EMEA')
INSERT [dbo].[AM_REGION_S4_MAPPING] ([Country], [Code], [Region]) VALUES (N'Burkina Faso', N'BF', N'EMEA')
INSERT [dbo].[AM_REGION_S4_MAPPING] ([Country], [Code], [Region]) VALUES (N'Burundi', N'BI', N'EMEA')
INSERT [dbo].[AM_REGION_S4_MAPPING] ([Country], [Code], [Region]) VALUES (N'Cabo Verde', N'CV', N'EMEA')
INSERT [dbo].[AM_REGION_S4_MAPPING] ([Country], [Code], [Region]) VALUES (N'Cambodia', N'KH', N'APAC')
INSERT [dbo].[AM_REGION_S4_MAPPING] ([Country], [Code], [Region]) VALUES (N'Cameroon', N'CM', N'EMEA')
INSERT [dbo].[AM_REGION_S4_MAPPING] ([Country], [Code], [Region]) VALUES (N'Canada', N'CA', N'NA')
INSERT [dbo].[AM_REGION_S4_MAPPING] ([Country], [Code], [Region]) VALUES (N'Cayman Islands (the)', N'KY', N'LATAM')
INSERT [dbo].[AM_REGION_S4_MAPPING] ([Country], [Code], [Region]) VALUES (N'Central African Republic (the)', N'CF', N'EMEA')
INSERT [dbo].[AM_REGION_S4_MAPPING] ([Country], [Code], [Region]) VALUES (N'Chad', N'TD', N'EMEA')
INSERT [dbo].[AM_REGION_S4_MAPPING] ([Country], [Code], [Region]) VALUES (N'Chile', N'CL', N'LATAM')
INSERT [dbo].[AM_REGION_S4_MAPPING] ([Country], [Code], [Region]) VALUES (N'China', N'CN', N'APAC')
INSERT [dbo].[AM_REGION_S4_MAPPING] ([Country], [Code], [Region]) VALUES (N'Christmas Island', N'CX', N'APAC')
INSERT [dbo].[AM_REGION_S4_MAPPING] ([Country], [Code], [Region]) VALUES (N'Cocos (Keeling) Islands (the)', N'CC', N'APAC')
INSERT [dbo].[AM_REGION_S4_MAPPING] ([Country], [Code], [Region]) VALUES (N'Colombia', N'CO', N'LATAM')
INSERT [dbo].[AM_REGION_S4_MAPPING] ([Country], [Code], [Region]) VALUES (N'Comoros (the)', N'KM', N'APAC')
INSERT [dbo].[AM_REGION_S4_MAPPING] ([Country], [Code], [Region]) VALUES (N'Congo (the Democratic Republic of the)', N'CD', N'EMEA')
INSERT [dbo].[AM_REGION_S4_MAPPING] ([Country], [Code], [Region]) VALUES (N'Congo (the)', N'CG', N'EMEA')
INSERT [dbo].[AM_REGION_S4_MAPPING] ([Country], [Code], [Region]) VALUES (N'Cook Islands (the)', N'CK', N'APAC')
INSERT [dbo].[AM_REGION_S4_MAPPING] ([Country], [Code], [Region]) VALUES (N'Costa Rica', N'CR', N'LATAM')
INSERT [dbo].[AM_REGION_S4_MAPPING] ([Country], [Code], [Region]) VALUES (N'Croatia', N'HR', N'EMEA')
INSERT [dbo].[AM_REGION_S4_MAPPING] ([Country], [Code], [Region]) VALUES (N'Cuba', N'CU', N'LATAM')
INSERT [dbo].[AM_REGION_S4_MAPPING] ([Country], [Code], [Region]) VALUES (N'Curaçao', N'CW', N'NA')
INSERT [dbo].[AM_REGION_S4_MAPPING] ([Country], [Code], [Region]) VALUES (N'Cyprus', N'CY', N'EMEA')
INSERT [dbo].[AM_REGION_S4_MAPPING] ([Country], [Code], [Region]) VALUES (N'Czechia', N'CZ', N'EMEA')
INSERT [dbo].[AM_REGION_S4_MAPPING] ([Country], [Code], [Region]) VALUES (N'Côte d''Ivoire', N'CI', N'EMEA')
INSERT [dbo].[AM_REGION_S4_MAPPING] ([Country], [Code], [Region]) VALUES (N'Denmark', N'DK', N'EMEA')
INSERT [dbo].[AM_REGION_S4_MAPPING] ([Country], [Code], [Region]) VALUES (N'Djibouti', N'DJ', N'EMEA')
INSERT [dbo].[AM_REGION_S4_MAPPING] ([Country], [Code], [Region]) VALUES (N'Dominica', N'DM', N'LATAM')
INSERT [dbo].[AM_REGION_S4_MAPPING] ([Country], [Code], [Region]) VALUES (N'Dominican Republic (the)', N'DO', N'LATAM')
INSERT [dbo].[AM_REGION_S4_MAPPING] ([Country], [Code], [Region]) VALUES (N'Ecuador', N'EC', N'LATAM')
INSERT [dbo].[AM_REGION_S4_MAPPING] ([Country], [Code], [Region]) VALUES (N'Egypt', N'EG', N'EMEA')
INSERT [dbo].[AM_REGION_S4_MAPPING] ([Country], [Code], [Region]) VALUES (N'El Salvador', N'SV', N'LATAM')
INSERT [dbo].[AM_REGION_S4_MAPPING] ([Country], [Code], [Region]) VALUES (N'Equatorial Guinea', N'GQ', N'EMEA')
INSERT [dbo].[AM_REGION_S4_MAPPING] ([Country], [Code], [Region]) VALUES (N'Eritrea', N'ER', N'EMEA')
INSERT [dbo].[AM_REGION_S4_MAPPING] ([Country], [Code], [Region]) VALUES (N'Estonia', N'EE', N'EMEA')
INSERT [dbo].[AM_REGION_S4_MAPPING] ([Country], [Code], [Region]) VALUES (N'Eswatini', N'SZ', N'EMEA')
INSERT [dbo].[AM_REGION_S4_MAPPING] ([Country], [Code], [Region]) VALUES (N'Ethiopia', N'ET', N'EMEA')
INSERT [dbo].[AM_REGION_S4_MAPPING] ([Country], [Code], [Region]) VALUES (N'Falkland Islands (the) [Malvinas]', N'FK', N'EMEA')
INSERT [dbo].[AM_REGION_S4_MAPPING] ([Country], [Code], [Region]) VALUES (N'Faroe Islands (the)', N'FO', N'EMEA')
INSERT [dbo].[AM_REGION_S4_MAPPING] ([Country], [Code], [Region]) VALUES (N'Fiji', N'FJ', N'APAC')
INSERT [dbo].[AM_REGION_S4_MAPPING] ([Country], [Code], [Region]) VALUES (N'Finland', N'FI', N'EMEA')
INSERT [dbo].[AM_REGION_S4_MAPPING] ([Country], [Code], [Region]) VALUES (N'France', N'FR', N'EMEA')
INSERT [dbo].[AM_REGION_S4_MAPPING] ([Country], [Code], [Region]) VALUES (N'French Guiana', N'GF', N'LATAM')
INSERT [dbo].[AM_REGION_S4_MAPPING] ([Country], [Code], [Region]) VALUES (N'French Polynesia', N'PF', N'APAC')
INSERT [dbo].[AM_REGION_S4_MAPPING] ([Country], [Code], [Region]) VALUES (N'French Southern Territories (the)', N'TF', N'APAC')
INSERT [dbo].[AM_REGION_S4_MAPPING] ([Country], [Code], [Region]) VALUES (N'Gabon', N'GA', N'EMEA')
INSERT [dbo].[AM_REGION_S4_MAPPING] ([Country], [Code], [Region]) VALUES (N'Gambia (the)', N'GM', N'EMEA')
INSERT [dbo].[AM_REGION_S4_MAPPING] ([Country], [Code], [Region]) VALUES (N'Georgia', N'GE', N'EMEA')
INSERT [dbo].[AM_REGION_S4_MAPPING] ([Country], [Code], [Region]) VALUES (N'Germany', N'DE', N'EMEA')
INSERT [dbo].[AM_REGION_S4_MAPPING] ([Country], [Code], [Region]) VALUES (N'Ghana', N'GH', N'EMEA')
INSERT [dbo].[AM_REGION_S4_MAPPING] ([Country], [Code], [Region]) VALUES (N'Gibraltar', N'GI', N'EMEA')
INSERT [dbo].[AM_REGION_S4_MAPPING] ([Country], [Code], [Region]) VALUES (N'Greece', N'GR', N'EMEA')
INSERT [dbo].[AM_REGION_S4_MAPPING] ([Country], [Code], [Region]) VALUES (N'Greenland', N'GL', N'NA')
INSERT [dbo].[AM_REGION_S4_MAPPING] ([Country], [Code], [Region]) VALUES (N'Grenada', N'GD', N'LATAM')
INSERT [dbo].[AM_REGION_S4_MAPPING] ([Country], [Code], [Region]) VALUES (N'Guadeloupe', N'GP', N'LATAM')
INSERT [dbo].[AM_REGION_S4_MAPPING] ([Country], [Code], [Region]) VALUES (N'Guam', N'GU', N'APAC')
INSERT [dbo].[AM_REGION_S4_MAPPING] ([Country], [Code], [Region]) VALUES (N'Guatemala', N'GT', N'LATAM')
INSERT [dbo].[AM_REGION_S4_MAPPING] ([Country], [Code], [Region]) VALUES (N'Guernsey', N'GG', N'EMEA')
INSERT [dbo].[AM_REGION_S4_MAPPING] ([Country], [Code], [Region]) VALUES (N'Guinea', N'GN', N'EMEA')
INSERT [dbo].[AM_REGION_S4_MAPPING] ([Country], [Code], [Region]) VALUES (N'Guinea-Bissau', N'GW', N'EMEA')
INSERT [dbo].[AM_REGION_S4_MAPPING] ([Country], [Code], [Region]) VALUES (N'Guyana', N'GY', N'LATAM')
INSERT [dbo].[AM_REGION_S4_MAPPING] ([Country], [Code], [Region]) VALUES (N'Haiti', N'HT', N'LATAM')
INSERT [dbo].[AM_REGION_S4_MAPPING] ([Country], [Code], [Region]) VALUES (N'Heard Island and McDonald Islands', N'HM', N'APAC')
INSERT [dbo].[AM_REGION_S4_MAPPING] ([Country], [Code], [Region]) VALUES (N'Holy See (the)', N'VA', N'EMEA')
INSERT [dbo].[AM_REGION_S4_MAPPING] ([Country], [Code], [Region]) VALUES (N'Honduras', N'HN', N'LATAM')
INSERT [dbo].[AM_REGION_S4_MAPPING] ([Country], [Code], [Region]) VALUES (N'Hong Kong', N'HK', N'APAC')
GO
INSERT [dbo].[AM_REGION_S4_MAPPING] ([Country], [Code], [Region]) VALUES (N'Hungary', N'HU', N'EMEA')
INSERT [dbo].[AM_REGION_S4_MAPPING] ([Country], [Code], [Region]) VALUES (N'Iceland', N'IS', N'EMEA')
INSERT [dbo].[AM_REGION_S4_MAPPING] ([Country], [Code], [Region]) VALUES (N'India', N'IN', N'APAC')
INSERT [dbo].[AM_REGION_S4_MAPPING] ([Country], [Code], [Region]) VALUES (N'Indonesia', N'ID', N'APAC')
INSERT [dbo].[AM_REGION_S4_MAPPING] ([Country], [Code], [Region]) VALUES (N'Iran (Islamic Republic of)', N'IR', N'EMEA')
INSERT [dbo].[AM_REGION_S4_MAPPING] ([Country], [Code], [Region]) VALUES (N'Iraq', N'IQ', N'EMEA')
INSERT [dbo].[AM_REGION_S4_MAPPING] ([Country], [Code], [Region]) VALUES (N'Ireland', N'IE', N'EMEA')
INSERT [dbo].[AM_REGION_S4_MAPPING] ([Country], [Code], [Region]) VALUES (N'Isle of Man', N'IM', N'EMEA')
INSERT [dbo].[AM_REGION_S4_MAPPING] ([Country], [Code], [Region]) VALUES (N'Israel', N'IL', N'EMEA')
INSERT [dbo].[AM_REGION_S4_MAPPING] ([Country], [Code], [Region]) VALUES (N'Italy', N'IT', N'EMEA')
INSERT [dbo].[AM_REGION_S4_MAPPING] ([Country], [Code], [Region]) VALUES (N'Jamaica', N'JM', N'LATAM')
INSERT [dbo].[AM_REGION_S4_MAPPING] ([Country], [Code], [Region]) VALUES (N'Japan', N'JP', N'APAC')
INSERT [dbo].[AM_REGION_S4_MAPPING] ([Country], [Code], [Region]) VALUES (N'Jersey', N'JE', N'EMEA')
INSERT [dbo].[AM_REGION_S4_MAPPING] ([Country], [Code], [Region]) VALUES (N'Jordan', N'JO', N'EMEA')
INSERT [dbo].[AM_REGION_S4_MAPPING] ([Country], [Code], [Region]) VALUES (N'Kazakhstan', N'KZ', N'EMEA')
INSERT [dbo].[AM_REGION_S4_MAPPING] ([Country], [Code], [Region]) VALUES (N'Kenya', N'KE', N'EMEA')
INSERT [dbo].[AM_REGION_S4_MAPPING] ([Country], [Code], [Region]) VALUES (N'Kiribati', N'KI', N'EMEA')
INSERT [dbo].[AM_REGION_S4_MAPPING] ([Country], [Code], [Region]) VALUES (N'Korea (the Democratic People''s Republic of)', N'KP', N'APAC')
INSERT [dbo].[AM_REGION_S4_MAPPING] ([Country], [Code], [Region]) VALUES (N'Korea (the Republic of)', N'KR', N'APAC')
INSERT [dbo].[AM_REGION_S4_MAPPING] ([Country], [Code], [Region]) VALUES (N'Kuwait', N'KW', N'EMEA')
INSERT [dbo].[AM_REGION_S4_MAPPING] ([Country], [Code], [Region]) VALUES (N'Kyrgyzstan', N'KG', N'EMEA')
INSERT [dbo].[AM_REGION_S4_MAPPING] ([Country], [Code], [Region]) VALUES (N'Lao People''s Democratic Republic (the)', N'LA', N'APAC')
INSERT [dbo].[AM_REGION_S4_MAPPING] ([Country], [Code], [Region]) VALUES (N'Latvia', N'LV', N'EMEA')
INSERT [dbo].[AM_REGION_S4_MAPPING] ([Country], [Code], [Region]) VALUES (N'Lebanon', N'LB', N'EMEA')
INSERT [dbo].[AM_REGION_S4_MAPPING] ([Country], [Code], [Region]) VALUES (N'Lesotho', N'LS', N'EMEA')
INSERT [dbo].[AM_REGION_S4_MAPPING] ([Country], [Code], [Region]) VALUES (N'Liberia', N'LR', N'EMEA')
INSERT [dbo].[AM_REGION_S4_MAPPING] ([Country], [Code], [Region]) VALUES (N'Libya', N'LY', N'EMEA')
INSERT [dbo].[AM_REGION_S4_MAPPING] ([Country], [Code], [Region]) VALUES (N'Liechtenstein', N'LI', N'EMEA')
INSERT [dbo].[AM_REGION_S4_MAPPING] ([Country], [Code], [Region]) VALUES (N'Lithuania', N'LT', N'EMEA')
INSERT [dbo].[AM_REGION_S4_MAPPING] ([Country], [Code], [Region]) VALUES (N'Luxembourg', N'LU', N'EMEA')
INSERT [dbo].[AM_REGION_S4_MAPPING] ([Country], [Code], [Region]) VALUES (N'Macao', N'MO', N'APAC')
INSERT [dbo].[AM_REGION_S4_MAPPING] ([Country], [Code], [Region]) VALUES (N'Madagascar', N'MG', N'EMEA')
INSERT [dbo].[AM_REGION_S4_MAPPING] ([Country], [Code], [Region]) VALUES (N'Malawi', N'MW', N'EMEA')
INSERT [dbo].[AM_REGION_S4_MAPPING] ([Country], [Code], [Region]) VALUES (N'Malaysia', N'MY', N'APAC')
INSERT [dbo].[AM_REGION_S4_MAPPING] ([Country], [Code], [Region]) VALUES (N'Maldives', N'MV', N'APAC')
INSERT [dbo].[AM_REGION_S4_MAPPING] ([Country], [Code], [Region]) VALUES (N'Mali', N'ML', N'EMEA')
INSERT [dbo].[AM_REGION_S4_MAPPING] ([Country], [Code], [Region]) VALUES (N'Malta', N'MT', N'EMEA')
INSERT [dbo].[AM_REGION_S4_MAPPING] ([Country], [Code], [Region]) VALUES (N'Marshall Islands (the)', N'MH', N'APAC')
INSERT [dbo].[AM_REGION_S4_MAPPING] ([Country], [Code], [Region]) VALUES (N'Martinique', N'MQ', N'LATAM')
INSERT [dbo].[AM_REGION_S4_MAPPING] ([Country], [Code], [Region]) VALUES (N'Mauritania', N'MR', N'EMEA')
INSERT [dbo].[AM_REGION_S4_MAPPING] ([Country], [Code], [Region]) VALUES (N'Mauritius', N'MU', N'EMEA')
INSERT [dbo].[AM_REGION_S4_MAPPING] ([Country], [Code], [Region]) VALUES (N'Mayotte', N'YT', N'EMEA')
INSERT [dbo].[AM_REGION_S4_MAPPING] ([Country], [Code], [Region]) VALUES (N'Mexico', N'MX', N'LATAM')
INSERT [dbo].[AM_REGION_S4_MAPPING] ([Country], [Code], [Region]) VALUES (N'Micronesia (Federated States of)', N'FM', N'APAC')
INSERT [dbo].[AM_REGION_S4_MAPPING] ([Country], [Code], [Region]) VALUES (N'Moldova (the Republic of)', N'MD', N'EMEA')
INSERT [dbo].[AM_REGION_S4_MAPPING] ([Country], [Code], [Region]) VALUES (N'Monaco', N'MC', N'EMEA')
INSERT [dbo].[AM_REGION_S4_MAPPING] ([Country], [Code], [Region]) VALUES (N'Mongolia', N'MN', N'APAC')
INSERT [dbo].[AM_REGION_S4_MAPPING] ([Country], [Code], [Region]) VALUES (N'Montenegro', N'ME', N'EMEA')
INSERT [dbo].[AM_REGION_S4_MAPPING] ([Country], [Code], [Region]) VALUES (N'Montserrat', N'MS', N'EMEA')
INSERT [dbo].[AM_REGION_S4_MAPPING] ([Country], [Code], [Region]) VALUES (N'Morocco', N'MA', N'EMEA')
INSERT [dbo].[AM_REGION_S4_MAPPING] ([Country], [Code], [Region]) VALUES (N'Mozambique', N'MZ', N'EMEA')
INSERT [dbo].[AM_REGION_S4_MAPPING] ([Country], [Code], [Region]) VALUES (N'Myanmar', N'MM', N'APAC')
INSERT [dbo].[AM_REGION_S4_MAPPING] ([Country], [Code], [Region]) VALUES (N'Namibia', N'NA', N'EMEA')
INSERT [dbo].[AM_REGION_S4_MAPPING] ([Country], [Code], [Region]) VALUES (N'Nauru', N'NR', N'APAC')
INSERT [dbo].[AM_REGION_S4_MAPPING] ([Country], [Code], [Region]) VALUES (N'Nepal', N'NP', N'APAC')
INSERT [dbo].[AM_REGION_S4_MAPPING] ([Country], [Code], [Region]) VALUES (N'Netherlands (the)', N'NL', N'EMEA')
INSERT [dbo].[AM_REGION_S4_MAPPING] ([Country], [Code], [Region]) VALUES (N'New Caledonia', N'NC', N'APAC')
INSERT [dbo].[AM_REGION_S4_MAPPING] ([Country], [Code], [Region]) VALUES (N'New Zealand', N'NZ', N'APAC')
INSERT [dbo].[AM_REGION_S4_MAPPING] ([Country], [Code], [Region]) VALUES (N'Nicaragua', N'NI', N'LATAM')
INSERT [dbo].[AM_REGION_S4_MAPPING] ([Country], [Code], [Region]) VALUES (N'Niger (the)', N'NE', N'EMEA')
INSERT [dbo].[AM_REGION_S4_MAPPING] ([Country], [Code], [Region]) VALUES (N'Nigeria', N'NG', N'EMEA')
INSERT [dbo].[AM_REGION_S4_MAPPING] ([Country], [Code], [Region]) VALUES (N'Niue', N'NU', N'APAC')
INSERT [dbo].[AM_REGION_S4_MAPPING] ([Country], [Code], [Region]) VALUES (N'Norfolk Island', N'NF', N'APAC')
INSERT [dbo].[AM_REGION_S4_MAPPING] ([Country], [Code], [Region]) VALUES (N'Northern Mariana Islands (the)', N'MP', N'APAC')
INSERT [dbo].[AM_REGION_S4_MAPPING] ([Country], [Code], [Region]) VALUES (N'Norway', N'NO', N'EMEA')
INSERT [dbo].[AM_REGION_S4_MAPPING] ([Country], [Code], [Region]) VALUES (N'Oman', N'OM', N'EMEA')
INSERT [dbo].[AM_REGION_S4_MAPPING] ([Country], [Code], [Region]) VALUES (N'Pakistan', N'PK', N'EMEA')
INSERT [dbo].[AM_REGION_S4_MAPPING] ([Country], [Code], [Region]) VALUES (N'Palau', N'PW', N'APAC')
INSERT [dbo].[AM_REGION_S4_MAPPING] ([Country], [Code], [Region]) VALUES (N'Palestine, State of', N'PS', N'EMEA')
INSERT [dbo].[AM_REGION_S4_MAPPING] ([Country], [Code], [Region]) VALUES (N'Panama', N'PA', N'LATAM')
INSERT [dbo].[AM_REGION_S4_MAPPING] ([Country], [Code], [Region]) VALUES (N'Papua New Guinea', N'PG', N'APAC')
INSERT [dbo].[AM_REGION_S4_MAPPING] ([Country], [Code], [Region]) VALUES (N'Paraguay', N'PY', N'LATAM')
INSERT [dbo].[AM_REGION_S4_MAPPING] ([Country], [Code], [Region]) VALUES (N'Peru', N'PE', N'LATAM')
INSERT [dbo].[AM_REGION_S4_MAPPING] ([Country], [Code], [Region]) VALUES (N'Philippines (the)', N'PH', N'APAC')
INSERT [dbo].[AM_REGION_S4_MAPPING] ([Country], [Code], [Region]) VALUES (N'Pitcairn', N'PN', N'APAC')
INSERT [dbo].[AM_REGION_S4_MAPPING] ([Country], [Code], [Region]) VALUES (N'Poland', N'PL', N'EMEA')
INSERT [dbo].[AM_REGION_S4_MAPPING] ([Country], [Code], [Region]) VALUES (N'Portugal', N'PT', N'EMEA')
INSERT [dbo].[AM_REGION_S4_MAPPING] ([Country], [Code], [Region]) VALUES (N'Puerto Rico', N'PR', N'LATAM')
INSERT [dbo].[AM_REGION_S4_MAPPING] ([Country], [Code], [Region]) VALUES (N'Qatar', N'QA', N'EMEA')
INSERT [dbo].[AM_REGION_S4_MAPPING] ([Country], [Code], [Region]) VALUES (N'Republic of North Macedonia', N'MK', N'EMEA')
INSERT [dbo].[AM_REGION_S4_MAPPING] ([Country], [Code], [Region]) VALUES (N'Romania', N'RO', N'EMEA')
INSERT [dbo].[AM_REGION_S4_MAPPING] ([Country], [Code], [Region]) VALUES (N'Russian Federation (the)', N'RU', N'EMEA')
INSERT [dbo].[AM_REGION_S4_MAPPING] ([Country], [Code], [Region]) VALUES (N'Rwanda', N'RW', N'EMEA')
INSERT [dbo].[AM_REGION_S4_MAPPING] ([Country], [Code], [Region]) VALUES (N'Réunion', N'RE', N'APAC')
INSERT [dbo].[AM_REGION_S4_MAPPING] ([Country], [Code], [Region]) VALUES (N'Saint Barthélemy', N'BL', N'EMEA')
INSERT [dbo].[AM_REGION_S4_MAPPING] ([Country], [Code], [Region]) VALUES (N'Saint Helena, Ascension and Tristan da Cunha', N'SH', N'EMEA')
INSERT [dbo].[AM_REGION_S4_MAPPING] ([Country], [Code], [Region]) VALUES (N'Saint Kitts and Nevis', N'KN', N'NA')
INSERT [dbo].[AM_REGION_S4_MAPPING] ([Country], [Code], [Region]) VALUES (N'Saint Lucia', N'LC', N'NA')
INSERT [dbo].[AM_REGION_S4_MAPPING] ([Country], [Code], [Region]) VALUES (N'Saint Martin (French part)', N'MF', N'NA')
INSERT [dbo].[AM_REGION_S4_MAPPING] ([Country], [Code], [Region]) VALUES (N'Saint Pierre and Miquelon', N'PM', N'NA')
INSERT [dbo].[AM_REGION_S4_MAPPING] ([Country], [Code], [Region]) VALUES (N'Saint Vincent and the Grenadines', N'VC', N'NA')
INSERT [dbo].[AM_REGION_S4_MAPPING] ([Country], [Code], [Region]) VALUES (N'Samoa', N'WS', N'APAC')
INSERT [dbo].[AM_REGION_S4_MAPPING] ([Country], [Code], [Region]) VALUES (N'San Marino', N'SM', N'EMEA')
INSERT [dbo].[AM_REGION_S4_MAPPING] ([Country], [Code], [Region]) VALUES (N'Sao Tome and Principe', N'ST', N'EMEA')
INSERT [dbo].[AM_REGION_S4_MAPPING] ([Country], [Code], [Region]) VALUES (N'Saudi Arabia', N'SA', N'EMEA')
INSERT [dbo].[AM_REGION_S4_MAPPING] ([Country], [Code], [Region]) VALUES (N'Senegal', N'SN', N'EMEA')
INSERT [dbo].[AM_REGION_S4_MAPPING] ([Country], [Code], [Region]) VALUES (N'Serbia', N'RS', N'EMEA')
INSERT [dbo].[AM_REGION_S4_MAPPING] ([Country], [Code], [Region]) VALUES (N'Seychelles', N'SC', N'APAC')
INSERT [dbo].[AM_REGION_S4_MAPPING] ([Country], [Code], [Region]) VALUES (N'Sierra Leone', N'SL', N'EMEA')
INSERT [dbo].[AM_REGION_S4_MAPPING] ([Country], [Code], [Region]) VALUES (N'Singapore', N'SG', N'APAC')
GO
INSERT [dbo].[AM_REGION_S4_MAPPING] ([Country], [Code], [Region]) VALUES (N'Sint Maarten (Dutch part)', N'SX', N'NA')
INSERT [dbo].[AM_REGION_S4_MAPPING] ([Country], [Code], [Region]) VALUES (N'Slovakia', N'SK', N'EMEA')
INSERT [dbo].[AM_REGION_S4_MAPPING] ([Country], [Code], [Region]) VALUES (N'Slovenia', N'SI', N'EMEA')
INSERT [dbo].[AM_REGION_S4_MAPPING] ([Country], [Code], [Region]) VALUES (N'Solomon Islands', N'SB', N'APAC')
INSERT [dbo].[AM_REGION_S4_MAPPING] ([Country], [Code], [Region]) VALUES (N'Somalia', N'SO', N'EMEA')
INSERT [dbo].[AM_REGION_S4_MAPPING] ([Country], [Code], [Region]) VALUES (N'South Africa', N'ZA', N'EMEA')
INSERT [dbo].[AM_REGION_S4_MAPPING] ([Country], [Code], [Region]) VALUES (N'South Georgia and the South Sandwich Islands', N'GS', N'LATAM')
INSERT [dbo].[AM_REGION_S4_MAPPING] ([Country], [Code], [Region]) VALUES (N'South Sudan', N'SS', N'EMEA')
INSERT [dbo].[AM_REGION_S4_MAPPING] ([Country], [Code], [Region]) VALUES (N'Spain', N'ES', N'EMEA')
INSERT [dbo].[AM_REGION_S4_MAPPING] ([Country], [Code], [Region]) VALUES (N'Sri Lanka', N'LK', N'APAC')
INSERT [dbo].[AM_REGION_S4_MAPPING] ([Country], [Code], [Region]) VALUES (N'Sudan (the)', N'SD', N'EMEA')
INSERT [dbo].[AM_REGION_S4_MAPPING] ([Country], [Code], [Region]) VALUES (N'Suriname', N'SR', N'LATAM')
INSERT [dbo].[AM_REGION_S4_MAPPING] ([Country], [Code], [Region]) VALUES (N'Svalbard and Jan Mayen', N'SJ', N'EMEA')
INSERT [dbo].[AM_REGION_S4_MAPPING] ([Country], [Code], [Region]) VALUES (N'Sweden', N'SE', N'EMEA')
INSERT [dbo].[AM_REGION_S4_MAPPING] ([Country], [Code], [Region]) VALUES (N'Switzerland', N'CH', N'EMEA')
INSERT [dbo].[AM_REGION_S4_MAPPING] ([Country], [Code], [Region]) VALUES (N'Syrian Arab Republic', N'SY', N'EMEA')
INSERT [dbo].[AM_REGION_S4_MAPPING] ([Country], [Code], [Region]) VALUES (N'Taiwan (Province of China)', N'TW', N'APAC')
INSERT [dbo].[AM_REGION_S4_MAPPING] ([Country], [Code], [Region]) VALUES (N'Tajikistan', N'TJ', N'EMEA')
INSERT [dbo].[AM_REGION_S4_MAPPING] ([Country], [Code], [Region]) VALUES (N'Tanzania, United Republic of', N'TZ', N'EMEA')
INSERT [dbo].[AM_REGION_S4_MAPPING] ([Country], [Code], [Region]) VALUES (N'Thailand', N'TH', N'APAC')
INSERT [dbo].[AM_REGION_S4_MAPPING] ([Country], [Code], [Region]) VALUES (N'Timor-Leste', N'TL', N'APAC')
INSERT [dbo].[AM_REGION_S4_MAPPING] ([Country], [Code], [Region]) VALUES (N'Togo', N'TG', N'EMEA')
INSERT [dbo].[AM_REGION_S4_MAPPING] ([Country], [Code], [Region]) VALUES (N'Tokelau', N'TK', N'APAC')
INSERT [dbo].[AM_REGION_S4_MAPPING] ([Country], [Code], [Region]) VALUES (N'Tonga', N'TO', N'APAC')
INSERT [dbo].[AM_REGION_S4_MAPPING] ([Country], [Code], [Region]) VALUES (N'Trinidad and Tobago', N'TT', N'NA')
INSERT [dbo].[AM_REGION_S4_MAPPING] ([Country], [Code], [Region]) VALUES (N'Tunisia', N'TN', N'EMEA')
INSERT [dbo].[AM_REGION_S4_MAPPING] ([Country], [Code], [Region]) VALUES (N'Turkey', N'TR', N'EMEA')
INSERT [dbo].[AM_REGION_S4_MAPPING] ([Country], [Code], [Region]) VALUES (N'Turkmenistan', N'TM', N'EMEA')
INSERT [dbo].[AM_REGION_S4_MAPPING] ([Country], [Code], [Region]) VALUES (N'Turks and Caicos Islands (the)', N'TC', N'NA')
INSERT [dbo].[AM_REGION_S4_MAPPING] ([Country], [Code], [Region]) VALUES (N'Tuvalu', N'TV', N'APAC')
INSERT [dbo].[AM_REGION_S4_MAPPING] ([Country], [Code], [Region]) VALUES (N'Uganda', N'UG', N'EMEA')
INSERT [dbo].[AM_REGION_S4_MAPPING] ([Country], [Code], [Region]) VALUES (N'Ukraine', N'UA', N'EMEA')
INSERT [dbo].[AM_REGION_S4_MAPPING] ([Country], [Code], [Region]) VALUES (N'United Arab Emirates (the)', N'AE', N'EMEA')
INSERT [dbo].[AM_REGION_S4_MAPPING] ([Country], [Code], [Region]) VALUES (N'United Kingdom of Great Britain and Northern Ireland (the)', N'GB', N'EMEA')
INSERT [dbo].[AM_REGION_S4_MAPPING] ([Country], [Code], [Region]) VALUES (N'United States Minor Outlying Islands (the)', N'UM', N'APAC')
INSERT [dbo].[AM_REGION_S4_MAPPING] ([Country], [Code], [Region]) VALUES (N'United States of America (the)', N'US', N'NA')
INSERT [dbo].[AM_REGION_S4_MAPPING] ([Country], [Code], [Region]) VALUES (N'Uruguay', N'UY', N'LATAM')
INSERT [dbo].[AM_REGION_S4_MAPPING] ([Country], [Code], [Region]) VALUES (N'Uzbekistan', N'UZ', N'APAC')
INSERT [dbo].[AM_REGION_S4_MAPPING] ([Country], [Code], [Region]) VALUES (N'Vanuatu', N'VU', N'APAC')
INSERT [dbo].[AM_REGION_S4_MAPPING] ([Country], [Code], [Region]) VALUES (N'Venezuela (Bolivarian Republic of)', N'VE', N'LATAM')
INSERT [dbo].[AM_REGION_S4_MAPPING] ([Country], [Code], [Region]) VALUES (N'Viet Nam', N'VN', N'APAC')
INSERT [dbo].[AM_REGION_S4_MAPPING] ([Country], [Code], [Region]) VALUES (N'Virgin Islands (British)', N'VG', N'NA')
INSERT [dbo].[AM_REGION_S4_MAPPING] ([Country], [Code], [Region]) VALUES (N'Virgin Islands (U.S.)', N'VI', N'NA')
INSERT [dbo].[AM_REGION_S4_MAPPING] ([Country], [Code], [Region]) VALUES (N'Wallis and Futuna', N'WF', N'APAC')
INSERT [dbo].[AM_REGION_S4_MAPPING] ([Country], [Code], [Region]) VALUES (N'Western Sahara', N'EH', N'EMEA')
INSERT [dbo].[AM_REGION_S4_MAPPING] ([Country], [Code], [Region]) VALUES (N'Yemen', N'YE', N'EMEA')
INSERT [dbo].[AM_REGION_S4_MAPPING] ([Country], [Code], [Region]) VALUES (N'Zambia', N'ZM', N'EMEA')
INSERT [dbo].[AM_REGION_S4_MAPPING] ([Country], [Code], [Region]) VALUES (N'Zimbabwe', N'ZW', N'EMEA')
INSERT [dbo].[AM_REGION_S4_MAPPING] ([Country], [Code], [Region]) VALUES (N'Åland Islands', N'AX', N'EMEA')
GO
