USE [DIVA_SIE_US_FY22]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[AM_OTHER_ACCOUTS](
	[SKAT_SAKNR] [nvarchar](12) NULL
) ON [PRIMARY]
GO
INSERT [dbo].[AM_OTHER_ACCOUTS] ([SKAT_SAKNR]) VALUES (N'A226010')
INSERT [dbo].[AM_OTHER_ACCOUTS] ([SKAT_SAKNR]) VALUES (N'A226035')
INSERT [dbo].[AM_OTHER_ACCOUTS] ([SKAT_SAKNR]) VALUES (N'A226040')
INSERT [dbo].[AM_OTHER_ACCOUTS] ([SKAT_SAKNR]) VALUES (N'A226050')
INSERT [dbo].[AM_OTHER_ACCOUTS] ([SKAT_SAKNR]) VALUES (N'A226070')
INSERT [dbo].[AM_OTHER_ACCOUTS] ([SKAT_SAKNR]) VALUES (N'A995010')
INSERT [dbo].[AM_OTHER_ACCOUTS] ([SKAT_SAKNR]) VALUES (N'A999000')
INSERT [dbo].[AM_OTHER_ACCOUTS] ([SKAT_SAKNR]) VALUES (N'A999010')
INSERT [dbo].[AM_OTHER_ACCOUTS] ([SKAT_SAKNR]) VALUES (N'A999200')
INSERT [dbo].[AM_OTHER_ACCOUTS] ([SKAT_SAKNR]) VALUES (N'A999400')
INSERT [dbo].[AM_OTHER_ACCOUTS] ([SKAT_SAKNR]) VALUES (N'A999405')
INSERT [dbo].[AM_OTHER_ACCOUTS] ([SKAT_SAKNR]) VALUES (N'A999410')
INSERT [dbo].[AM_OTHER_ACCOUTS] ([SKAT_SAKNR]) VALUES (N'A999900')
INSERT [dbo].[AM_OTHER_ACCOUTS] ([SKAT_SAKNR]) VALUES (N'A999910')
INSERT [dbo].[AM_OTHER_ACCOUTS] ([SKAT_SAKNR]) VALUES (N'A999920')
INSERT [dbo].[AM_OTHER_ACCOUTS] ([SKAT_SAKNR]) VALUES (N'A999930')
INSERT [dbo].[AM_OTHER_ACCOUTS] ([SKAT_SAKNR]) VALUES (N'A999990')
INSERT [dbo].[AM_OTHER_ACCOUTS] ([SKAT_SAKNR]) VALUES (N'A999994')
INSERT [dbo].[AM_OTHER_ACCOUTS] ([SKAT_SAKNR]) VALUES (N'A999995')
INSERT [dbo].[AM_OTHER_ACCOUTS] ([SKAT_SAKNR]) VALUES (N'A999996')
INSERT [dbo].[AM_OTHER_ACCOUTS] ([SKAT_SAKNR]) VALUES (N'A999997')
INSERT [dbo].[AM_OTHER_ACCOUTS] ([SKAT_SAKNR]) VALUES (N'A999998')
INSERT [dbo].[AM_OTHER_ACCOUTS] ([SKAT_SAKNR]) VALUES (N'A999999')
GO
