USE [DIVA_SIE_US_FY22]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[AM_COMPANY_CODE](
	[COMPANY_CODE] [varchar](20) NOT NULL,
	[BUKRS_MAPPING] [varchar](20) NOT NULL
) ON [PRIMARY]
GO
INSERT [dbo].[AM_COMPANY_CODE] ([COMPANY_CODE], [BUKRS_MAPPING]) VALUES (N'US70', N'US70')
INSERT [dbo].[AM_COMPANY_CODE] ([COMPANY_CODE], [BUKRS_MAPPING]) VALUES (N'US71', N'US71')
GO
