USE [DIVA_SIE_US_FY22]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[AM_GL_BANK_ACC](
	[GL_BANK_ACC_MANDT] [nvarchar](5) NULL,
	[GL_BANK_ACC_BUKRS] [nvarchar](6) NULL,
	[GL_BANK_ACC_HKONT] [nvarchar](12) NULL,
	[GL_BANK_TEXT1] [varchar](1) NOT NULL
) ON [PRIMARY]
GO
INSERT [dbo].[AM_GL_BANK_ACC] ([GL_BANK_ACC_MANDT], [GL_BANK_ACC_BUKRS], [GL_BANK_ACC_HKONT], [GL_BANK_TEXT1]) VALUES (N'100', N'US70', N'A012200', N'')
INSERT [dbo].[AM_GL_BANK_ACC] ([GL_BANK_ACC_MANDT], [GL_BANK_ACC_BUKRS], [GL_BANK_ACC_HKONT], [GL_BANK_TEXT1]) VALUES (N'100', N'US70', N'A012201', N'')
INSERT [dbo].[AM_GL_BANK_ACC] ([GL_BANK_ACC_MANDT], [GL_BANK_ACC_BUKRS], [GL_BANK_ACC_HKONT], [GL_BANK_TEXT1]) VALUES (N'100', N'US70', N'A012210', N'')
INSERT [dbo].[AM_GL_BANK_ACC] ([GL_BANK_ACC_MANDT], [GL_BANK_ACC_BUKRS], [GL_BANK_ACC_HKONT], [GL_BANK_TEXT1]) VALUES (N'100', N'US70', N'A012211', N'')
INSERT [dbo].[AM_GL_BANK_ACC] ([GL_BANK_ACC_MANDT], [GL_BANK_ACC_BUKRS], [GL_BANK_ACC_HKONT], [GL_BANK_TEXT1]) VALUES (N'100', N'US70', N'A012212', N'')
INSERT [dbo].[AM_GL_BANK_ACC] ([GL_BANK_ACC_MANDT], [GL_BANK_ACC_BUKRS], [GL_BANK_ACC_HKONT], [GL_BANK_TEXT1]) VALUES (N'100', N'US70', N'A012213', N'')
INSERT [dbo].[AM_GL_BANK_ACC] ([GL_BANK_ACC_MANDT], [GL_BANK_ACC_BUKRS], [GL_BANK_ACC_HKONT], [GL_BANK_TEXT1]) VALUES (N'100', N'US70', N'A012214', N'')
INSERT [dbo].[AM_GL_BANK_ACC] ([GL_BANK_ACC_MANDT], [GL_BANK_ACC_BUKRS], [GL_BANK_ACC_HKONT], [GL_BANK_TEXT1]) VALUES (N'100', N'US70', N'A012215', N'')
INSERT [dbo].[AM_GL_BANK_ACC] ([GL_BANK_ACC_MANDT], [GL_BANK_ACC_BUKRS], [GL_BANK_ACC_HKONT], [GL_BANK_TEXT1]) VALUES (N'100', N'US70', N'A012216', N'')
INSERT [dbo].[AM_GL_BANK_ACC] ([GL_BANK_ACC_MANDT], [GL_BANK_ACC_BUKRS], [GL_BANK_ACC_HKONT], [GL_BANK_TEXT1]) VALUES (N'100', N'US70', N'A012300', N'')
INSERT [dbo].[AM_GL_BANK_ACC] ([GL_BANK_ACC_MANDT], [GL_BANK_ACC_BUKRS], [GL_BANK_ACC_HKONT], [GL_BANK_TEXT1]) VALUES (N'100', N'US70', N'A012302', N'')
INSERT [dbo].[AM_GL_BANK_ACC] ([GL_BANK_ACC_MANDT], [GL_BANK_ACC_BUKRS], [GL_BANK_ACC_HKONT], [GL_BANK_TEXT1]) VALUES (N'100', N'US70', N'A012306', N'')
INSERT [dbo].[AM_GL_BANK_ACC] ([GL_BANK_ACC_MANDT], [GL_BANK_ACC_BUKRS], [GL_BANK_ACC_HKONT], [GL_BANK_TEXT1]) VALUES (N'100', N'US70', N'A012307', N'')
INSERT [dbo].[AM_GL_BANK_ACC] ([GL_BANK_ACC_MANDT], [GL_BANK_ACC_BUKRS], [GL_BANK_ACC_HKONT], [GL_BANK_TEXT1]) VALUES (N'100', N'US70', N'A012308', N'')
INSERT [dbo].[AM_GL_BANK_ACC] ([GL_BANK_ACC_MANDT], [GL_BANK_ACC_BUKRS], [GL_BANK_ACC_HKONT], [GL_BANK_TEXT1]) VALUES (N'100', N'US70', N'A012309', N'')
INSERT [dbo].[AM_GL_BANK_ACC] ([GL_BANK_ACC_MANDT], [GL_BANK_ACC_BUKRS], [GL_BANK_ACC_HKONT], [GL_BANK_TEXT1]) VALUES (N'100', N'US70', N'A012311', N'')
INSERT [dbo].[AM_GL_BANK_ACC] ([GL_BANK_ACC_MANDT], [GL_BANK_ACC_BUKRS], [GL_BANK_ACC_HKONT], [GL_BANK_TEXT1]) VALUES (N'100', N'US70', N'A012314', N'')
INSERT [dbo].[AM_GL_BANK_ACC] ([GL_BANK_ACC_MANDT], [GL_BANK_ACC_BUKRS], [GL_BANK_ACC_HKONT], [GL_BANK_TEXT1]) VALUES (N'100', N'US70', N'A012315', N'')
INSERT [dbo].[AM_GL_BANK_ACC] ([GL_BANK_ACC_MANDT], [GL_BANK_ACC_BUKRS], [GL_BANK_ACC_HKONT], [GL_BANK_TEXT1]) VALUES (N'100', N'US70', N'A012316', N'')
INSERT [dbo].[AM_GL_BANK_ACC] ([GL_BANK_ACC_MANDT], [GL_BANK_ACC_BUKRS], [GL_BANK_ACC_HKONT], [GL_BANK_TEXT1]) VALUES (N'100', N'US70', N'A012318', N'')
INSERT [dbo].[AM_GL_BANK_ACC] ([GL_BANK_ACC_MANDT], [GL_BANK_ACC_BUKRS], [GL_BANK_ACC_HKONT], [GL_BANK_TEXT1]) VALUES (N'100', N'US70', N'A012319', N'')
INSERT [dbo].[AM_GL_BANK_ACC] ([GL_BANK_ACC_MANDT], [GL_BANK_ACC_BUKRS], [GL_BANK_ACC_HKONT], [GL_BANK_TEXT1]) VALUES (N'100', N'US70', N'A012320', N'')
INSERT [dbo].[AM_GL_BANK_ACC] ([GL_BANK_ACC_MANDT], [GL_BANK_ACC_BUKRS], [GL_BANK_ACC_HKONT], [GL_BANK_TEXT1]) VALUES (N'100', N'US71', N'A012217', N'')
INSERT [dbo].[AM_GL_BANK_ACC] ([GL_BANK_ACC_MANDT], [GL_BANK_ACC_BUKRS], [GL_BANK_ACC_HKONT], [GL_BANK_TEXT1]) VALUES (N'100', N'US71', N'A012218', N'')
INSERT [dbo].[AM_GL_BANK_ACC] ([GL_BANK_ACC_MANDT], [GL_BANK_ACC_BUKRS], [GL_BANK_ACC_HKONT], [GL_BANK_TEXT1]) VALUES (N'100', N'US71', N'A012307', N'')
INSERT [dbo].[AM_GL_BANK_ACC] ([GL_BANK_ACC_MANDT], [GL_BANK_ACC_BUKRS], [GL_BANK_ACC_HKONT], [GL_BANK_TEXT1]) VALUES (N'100', N'US71', N'A012315', N'')
GO
